web/js/ctrl/MailViewModel.js
This is in refrence to:
https://tutanota.uservoice.com/forums/237921-general/suggestions/8025057-re-re-re-re-re
=> Add function to parse old subject lines on replys and prevent duplicate Re: prefixes

web/js/ctrl/lang/en.js
Just corrected a couple of sentences which didn't quite make sense.
=> Corrections to English language welcome message.

src/api/common/TutanotaConstants.js, src/api/worker/EventBusClient.js, src/api/worker/facades/LoginFacade.js, src/api/worker/facades/UserManagementFacade.js, src/settings/AddGroupDialog.js, src/settings/GroupViewer.js, test/api/worker/search/IndexUtilsTest.js, test/api/worker/search/IndexerTest.js
=> Prevent loading of entityeventbatches for team (now mailinglist) groups

src/api/worker/search/IndexerCore.js, src/misc/ClientConstants.js, src/misc/ClientDetector.js, test/client/common/ClientDetectorTest.js
=> added palemoon to needsMicrotaskHack and browsertype

src/api/worker/search/Indexer.js, src/api/worker/search/IndexerCore.js, src/api/worker/search/MailIndexer.js
recreate index if groupdata was not found
mitigates #707
=> turn off data storage if the indexer fails to initialize

src/api/worker/facades/MailFacade.js
Thanks to the details video steps from our users:
- Add file to the draft, save draft
- Re-open draft, remove previous attachment, add another one
- Try to save, get an error
The code assumed that anything which is not `DataFile` is `TutanotaFile` which is not the case.
=> Fix removing and adding attachment on mobile, fix #952

app-android/app/src/main/java/de/tutao/tutanota/Utils.java
=> [android] Fallback to URI when picking file and name is absent

src/contacts/ContactEditor.js
=> Fix infinite fields in contact editor, fix #1074

src/app.js, src/misc/LanguageViewModel.js, src/settings/AddDomainDialog.js
Replaces all uservoice links with newer FAQ URLs
=> fix: removes uservoice links

src/api/worker/EventBusClient.js
In certain cases when connection is unstable more than a single websocket connection is created:
`this._socket = new WebSocket(url)`
`tryReconnect` was called unconditionally with every `onOnline` event and it caused a race-condition. This PR fixes this behavior by closing all deferred reconnects before opening a new one.
=> Fixed websocket race-condition on unstable connection

src/calendar/CalendarEventDialog.js, src/gui/base/DatePicker.js, src/settings/ContactFormViewer.js, src/settings/WhitelabelSettingsViewer.js
A much more elaborate fix that avoids polluting the date picker with specifics of the model.
Requires changes to modules (White label/Contact form) that I cannot properly test in my configuration.
=> Fix #1455, respect week start preference in calendar date picker.

src/mail/MailViewer.js
Transforms strings temporarily to upper when comparing them.
(Fixes #1519)
=> Fix #1519: Make reply check case-insensitive

src/contacts/ContactViewer.js
=> Check if birthday is defined when showing contact

flow/api/types.js, flow/electron.js, src/desktop/ApplicationWindow.js, src/desktop/IPC.js, src/desktop/preload.js, src/gui/base/SearchInPageOverlay.js, src/native/NativeWrapperCommands.js, test/client/desktop/ApplicationWindowTest.js, test/client/desktop/IPCTest.js
add explicit blur & focus for search overlay when it is the only result
enable enter to select next result and backspace to select the previous one
=> [desktop] fix #1775 & #1280

app-android/app/src/main/java/de/tutao/tutanota/push/TutanotaNotificationsHandler.java
Before FileNotFound would be thrown on any 4xx status code.
=> [android] Fix recognizing status codes when downloading notifications

flow/electron.js, src/desktop/DesktopMain.js, src/desktop/DesktopNotifier.js, src/desktop/DesktopTray.js, test/client/desktop/DesktopNotifierTest.js
add badge & bounce to mac os dock icon
=> [desktop] fix #1754

src/calendar/CalendarImporter.js, src/calendar/CalendarParser.js, test/client/calendar/CalendarImporterTest.js, test/client/calendar/CalendarParsertest.js
- Handle import with nonsense end time
- Add type to exported all-day times
=> Calendar import/export compatibility improvements

package-lock.json, package.json
this gives us a few accessibility improvements (related to VoiceOver and some aria tags) on mac and fixes for some rare crashes.
=> [desktop] update electron to 8.2.0

src/login/SecondFactorHandler.js
fix #1792
This happens because we receive generic U2fError instead of timeout
error (seems like u2f has its own timeout). Now we will only show the
error dialog if the waiting dialog is still visible. We would like to
cancel u2f request but it doesn't seem to be possible.
Hopefully we can improve this after we migrate to WebAuthn.
=> Fix receiving u2f error after login was accepted

src/settings/EditAliasesFormN.js
fix #1988
`sort()` sorts array in place and we've been modifying global groupInfo
instance.
=> Fix updating groupInfo because of the aliases order

src/api/common/utils/ArrayUtils.js, test/api/common/ArrayUtilsTest.js
fix #1956
insertIntoSortedArray couldn't handle the case where the last element
was equal but the first one was the one to be replaced
=> Fix replacing calendar events, 

src/settings/ContactFormEditor.js
fix #1977
Progress dialog tried to restore the focus to the element which had it
before the dialog but focus was already grabbed by the new dialog.
This moves opening of the contact form after the progress dialog so that
they are not open at the same time. Multiple modal dialogs do not play
well together and we should avoid it as much as possible.
=> Fix losing focus after opening contact form editor

src/mail/MailViewer.js
=> Add copy action to recipient dropdowns

src/gui/base/RecipientButton.js
=> Fix printing of addresses in expanded view

src/gui/base/BubbleTextField.js
=> Fix editor bubbles

README.md
There is no reason to provide a http link anymore ;)
=> Use http"s" for roadmap link in README.md

src/mail/MailViewer.js
=> Improvements for mail viewer actions

buildSrc/Builder.js, flow/api/types.js, src/api/main/EventController.js, src/api/main/WorkerClient.js, src/api/worker/EventBusClient.js, src/api/worker/WorkerImpl.js, src/api/worker/crypto/lib/murmurhash3_32.js, src/api/worker/facades/MailFacade.js, src/mail/MailModel.js, test/api/worker/facades/MailFacadeTest.js
See commit messages
fix #2035
fix #2086
=> Fix IE bugs

doc/BUILDING.md
A small change, looks like the URL may have accidentally been left out
=> Minor update to BUILDING.md

src/gui/base/ViewSlider.js
=> Implement back swipe gesture from the edge of the screen, close #626

src/calendar/CalendarView.js
=> Fix switching to the next month in calendar when date's 31st

src/desktop/DesktopDownloadManager.js, test/client/desktop/DesktopDownloadManagerTest.js
resolving the downloadNative promise after the stream was explicitly
closed should prevent any EBUSY errors from cropping up when the user
chose 'open attachment' and the client tries to open the file right
after the download.
=> properly close file after native download attempt, fix #2113

dist.js, make.js
=> use full os.hostname for local restUrl in dist & make script

src/mail/Exporter.js
=> export attachments with correct Content-Type header, fixes #2192

src/api/worker/facades/MailFacade.js
=> Fix error when opening email with errors

src/mail/MailUtils.js, src/mail/MailViewer.js
=> Move mails to spam folder after reporting spam/phishing, close #2158

src/calendar/CalendarImporter.js, test/client/calendar/CalendarImporterTest.js
=> Fix time in exported all-day events

src/settings/emaildomain/AddEmailAddressesPage.js
prevetns double click of next button on that page
closes #2201
=> automatically add alias with next button (AddEmailAddressesPage)

src/gui/main-styles.js, src/subscription/SignOrderProcessingAgreementDialog.js
=> hide printed order process agreement in background when printing

src/gui/base/Modal.js, src/gui/nav/DrawerMenu.js, src/misc/KeyManager.js
Add the F1-Help icon for free users and change the support button to be a dropdown for premium ones.
fix #580
=> Add the icon to open F1-Help (fix #580) 

doc/HACKING.md
=> correct typo in HACKING.md

src/desktop/ApplicationWindow.js, test/client/desktop/ApplicationWindowTest.js
=> [desktop] set spellchecker default to off

buildSrc/electron-package-json-template.js
=> [desktop] disable update download requests with multiple byte ranges

src/native/NativeWrapperCommands.js
=> fix mailEditor in native, fixes #2221

src/api/worker/search/Indexer.js
=> Use EntityRestCache for indexer

src/contacts/ContactView.js
=> Import contacts one by one

src/api/worker/EventBusClient.js, src/gui/base/Header.js
=> Fix mobile action bar

src/gui/base/DatePicker.js
=> Fix mobile date picker selecting invalid date in some zones

src/settings/EditNotificationEmailDialog.js
=> Custom email notification editor fix

src/calendar/CalendarEventViewModel.js
=> fixes deleting calendar event with external confidential recipient without password

src/search/SearchBar.js
=> fixes #2335

src/api/worker/facades/CalendarFacade.js, src/calendar/CalendarModel.js, src/search/SearchBar.js
=> Optimize loading of quick search results

src/search/SearchView.js
forgot to call show on the returned dialog, #2176
=> fix open mail editor from search view

src/mail/MailViewer.js
=> disable forward (shortcut and button) for external users

src/calendar/CalendarView.js, src/misc/DeviceConfig.js
Remember hidden calendars per device with local storage
=> Remember calendar visibility

src/settings/EditSecondFactorsForm.js
=> hides recovery code dialog when setting 2fa for other users

package-lock.json, package.json
contains fix for CVE-2020-15999
fix #2395
=> [desktop] update to electron 10.1.5

src/calendar/CalendarView.js
=> handle not-found-error when deleting calendar

src/api/common/TutanotaConstants.js, src/api/worker/rest/RestClient.js
=> limit request size sent by client

app-android/app/src/main/java/de/tutao/tutanota/MainActivity.java, app-android/app/src/main/java/de/tutao/tutanota/data/UserInfoDao.java, app-android/app/src/main/java/de/tutao/tutanota/push/PushNotificationService.java, app-android/app/src/main/java/de/tutao/tutanota/push/ResponseCodes.java, app-android/app/src/main/java/de/tutao/tutanota/push/SseClient.java, app-android/app/src/main/java/de/tutao/tutanota/push/SseStorage.java, app-android/app/src/main/java/de/tutao/tutanota/push/TutanotaNotificationsHandler.java, app-ios/tutanota/Sources/Alarms/TUTAlarmNotification.h, app-ios/tutanota/Sources/Alarms/TUTAlarmNotification.m, app-ios/tutanota/Sources/TUTAlarmManager.h, app-ios/tutanota/Sources/TUTAlarmManager.m, app-ios/tutanota/Sources/Utils/TUTUserPreferenceFacade.h, app-ios/tutanota/Sources/Utils/TUTUserPreferenceFacade.m, src/desktop/sse/DesktopAlarmScheduler.js, src/desktop/sse/DesktopSseClient.js, test/client/desktop/sse/DesktopSseClientTest.js
=> Pass single user when opening SSE connection

src/contacts/ContactViewer.js, src/mail/MailEditorN.js, src/mail/MailUtils.js, src/mail/MailViewer.js
=> append signature to body when creating editor from mailto url

src/calendar/CalendarEventEditDialog.js, src/gui/base/ExpanderN.js, src/login/LoginView.js, src/mail/MailEditorN.js
=> Fix login with saved when loginWith is passed, replace expander

test/api/crypto/CryptoFacadeTest.js
related to #2402
cherry-pick'ed from entity-update-lookahead branch
The fix is to set ourselves as the leader
=> Fix CryptoFacadeTest

src/mail/MailView.js, src/mail/MailViewer.js, src/search/SearchResultDetailsViewer.js
=> load instances of a mail sequentially

app-android/app/src/main/java/de/tutao/tutanota/NetworkUtils.java, app-ios/tutanota/Sources/TUTAlarmManager.m, app-ios/tutanota/Sources/TUTAppDelegate.m, app-ios/tutanota/Sources/Utils/TUTUtils.h, app-ios/tutanota/Sources/Utils/TUTUtils.m
=> App model version

app-android/app/build.gradle
Also update build tools because the old version was already ignored
close #2415
=> [android] Target SDK 29

src/gui/base/ButtonN.js, src/login/LoginView.js
fix #2424
The app buttons were triggering form submit, call preventDefault to stop this. Also switched them over to use ButtonN since i was there
=> Don't login when clicking on app button on login screen

app-android/app/src/main/java/de/tutao/tutanota/FileOpenException.java, app-android/app/src/main/java/de/tutao/tutanota/FileUtil.java
fix #2415
Instead of relying on writing to the Downloads folder we add files to
the Downloads MediaStore collection. System also makes sure to rename
the file if it's a duplicate.
=> [android] Fix downloading attachments on Android 10

dist.js, flow/electron.js, src/desktop/sse/DesktopSseClient.js
After some requests MissedNotification download was getting stuck after
the TCP handshake. Adding some event listeners seems to help. This
looks like a bug in Node.js.
=> [desktop] Work around network issues w/ MissedNotification

src/contacts/MultiContactViewer.js, src/mail/MultiMailViewer.js, src/search/MultiSearchViewer.js
This fixes #2443 as well as fixing the button positions for selecting multiple contacts.
=> Fix button alignment for MultiMailViewer, MultiContactView, MultiSearchViewer (fixes #2443)

app-android/app/src/main/AndroidManifest.xml
This PR makes the app resizeable on Android Desktops and should fix #2167
**PS:** If you're going to merge this: would you be so kind and add the [`hacktoberfest-accepted`](https://hacktoberfest.digitalocean.com/hacktoberfest-update) label to this PR? Thank you in advance!
=> make app resizeable

src/search/SearchBar.js
A bit like the shortcuts, maybe we want to generalize this, if we do
manual key handling in other places as well
fix #2553
=> Refactor and add special key handling for search

src/misc/KeyManager.js
change children from "right" to "left"
closes #2543
=> fix close button being on wrong side, fix #2543

src/mail/MailViewer.js
=> Deactivate header/reply/forward shortcut for draft

src/settings/EditAliasesFormN.js
=> Check for remaining alias creation allowed when creating new alias

app-android/app/src/main/AndroidManifest.xml
=> [android] Opt-out from sending metrics to google

src/gui/base/List.js
=> Ignore missing dom elements in list

src/misc/ErrorHandlerImpl.js
=> Send feedback reports to a specific mailbox

app-android/app/src/main/java/de/tutao/tutanota/FileUtil.java, app-android/app/src/main/java/de/tutao/tutanota/Native.java, app-android/app/src/main/java/de/tutao/tutanota/push/LocalNotificationsFacade.java, app-android/app/src/main/res/drawable/ic_download.xml, app-android/app/src/main/res/values/strings.xml
=> [android] Show notification when file download is finished

src/search/SearchBar.js
=> Fix search button focus

src/api/worker/facades/CalendarFacade.js
=> Reduce calendar import concurrency with large calendar and many alarms

src/mail/SendMailModel.js
=> Fix new draft decision

src/native/NativeWrapperCommands.js
=> Fix sharing on android

src/settings/AppearanceSettingsViewer.js
=> Fix language dropdown sorting

src/contacts/ContactView.js
Adds back button handling to the contacts view:
* Switch back to the Contact list if a contact is selected
* Abort multi selection if active
fix #2590
=> Handle device back button in contacts view

src/subscription/giftcards/GiftCardUtils.js
=> Show gift card print button only when not on app

src/gui/base/Expander.js
otherwise they will be included in the tab sequence
We have to delay removal so that they can still do their shrink and fade out which is why it's tracked separately from attrs.expanded and done on a timeout
=> remove expander's children when hidden

src/gui/base/Expander.js, src/mail/MailViewer.js
this slipped by me in some changes i made in the last release, sorry!
=> fix show more button in email attachments, fix #2651

src/api/main/SignupForm.js, test/api/main/SignupFormTest.js
=> Accept more captcha formats

flow/CommonFlowDeclares.js, src/api/common/utils/Utils.js, src/gui/base/Dialog.js, src/gui/base/DialogHeaderBar.js, src/subscription/PaymentDataDialog.js, src/subscription/PaymentMethodInput.js
had to do add some laziness to the dialog since the result of showActionDialog is somewhat self contained
=> Don't show cancel option once a user has linked paypal details

src/login/LoginViewController.js, src/misc/ErrorHandlerImpl.js, src/subscription/SubscriptionUtils.js
=> Redirect to storage upgrade when reaching limit

src/mail/view/MailGuiUtils.js
=> Check mail delete dialog return before deleting

buildSrc/RollupDebugConfig.js
to prevent it from generating synthetic module
=> add crypto to commonjs-plugin ignore

src/api/common/TutanotaConstants.js, src/subscription/InvoiceAndPaymentDataPage.js, src/translations/de.js, src/translations/de_sie.js, src/translations/en.js
=> More informative error on throttled cc verification

src/subscription/SubscriptionViewer.js
=> Remove duplicate extensions section in subscription settings

src/api/common/utils/PromiseUtils.js, src/api/worker/crypto/InstanceMapper.js, test/api/common/PromiseUtilTest.js
Bluebird is not used in desktop code anymore but InstanceMapper still
used Promise.map from Bluebird. This commit replaces Promise.map with
our own sequential implementation.
fix #2707
=> Reimplement Promise.map, fix alarms on desktop

src/gui/main-styles.js
=> [admin] fix url tooltip not showing up in admin mode

doc/BUILDING.md
Needed after migration to rollup
fix #2739
=> Update node version in building instructions

buildSrc/Builder.js, dist.js, libs/s.js, package-lock.json, package.json, src/polyfill.js
Polyfills were not properly transpiled and this prevented older
WebViews from loading the app. With this change it shows outdated
message for Chrome 44 but not for 39.
=> Fix loading client on older browsers, fix #2732

buildSrc/Builder.js, dist.js, src/app.js, src/desktop/DesktopLog.js, src/desktop/DesktopMonkeyPatch.js
=> Fix desktop log

src/desktop/ElectronUpdater.js, src/polyfill.js, test/client/desktop/ElectronUpdaterTest.js
=> Improve desktop update experience

src/ApplicationPaths.js, src/app.js, src/serviceworker/sw.js
So that app.js and serviceworker can share instead of duplicating, close #2343
=> Split application paths into separate file

src/subscription/SwitchSubscriptionDialogModel.js
=> make PriceService requests sequentially in switch subscription dialog

src/misc/FormatValidator.js, src/subscription/PaymentMethodInput.js, test/client/common/FormatterTest.js
Implementation of the Luhn algorithm, so we can save users from sending mistyped credit card numbers to the server, as they could accidentally get themselves blocked
=> client side validation of credit card numbers

src/mail/view/MailListView.js, src/mail/view/MailView.js
=> change modifier for export drag and drop

src/mail/view/EventBanner.js
=> allow free users to quick reply to event invites

src/subscription/PaymentMethodInput.js
=> Check CVC length on payment data updat

app-android/app/src/main/java/de/tutao/tutanota/MainActivity.java, app-android/app/src/main/java/de/tutao/tutanota/Native.java, app-ios/tutanota/Sources/TUTAlarmManager.h, app-ios/tutanota/Sources/TUTAlarmManager.m, app-ios/tutanota/Sources/TUTViewController.m, doc/notifications.md, flow/api/types.js, src/api/common/WorkerProtocol.js, src/api/worker/crypto/InstanceMapper.js, src/api/worker/facades/CalendarFacade.js, src/desktop/DesktopMain.js, src/desktop/IPC.js, src/native/main/PushServiceApp.js, test/api/crypto/CryptoFacadeTest.js, test/client/desktop/IPCTest.js
=> Schedule alarms locally for new device

src/gui/editor/HtmlEditor.js
=> Remove unnecessary border in HtmlEditor

src/calendar/export/CalendarImporter.js, src/calendar/export/CalendarParser.js, test/client/calendar/CalendarImporterTest.js
=> Allow calendar event attendees without PARTSTAT

package-lock.json, package.json
=> Update Electron to 11.2.3

src/search/view/MultiSearchViewer.js
=> Download all mail contents sequentially from MultiSearchViewer

package-lock.json, package.json
=> use new oxmsg build

src/mail/export/Exporter.js, src/mail/view/MailViewer.js, src/mail/view/MultiMailViewer.js, src/search/view/MultiSearchViewer.js
=> Don't create zip file when exporting a single mail

src/mail/model/MailUtils.js
=> enable drag and drop export for all users

src/mail/export/Exporter.js, src/mail/view/MailViewer.js, src/mail/view/MultiMailViewer.js, src/search/view/MultiSearchViewer.js
=> show progress dialog when exporting from search viewer

src/desktop/Socketeer.js
Server was closed before we would get an error so we would assign it
to null and never restart. We are using the local reference instead now.
=> Fix retrying to start socket server

src/mail/editor/MailEditorViewModel.js
=> save contactModel in MailEditorRecipientField

src/mail/view/EventBanner.js
=> show progress dialog when confirming calendar event invites

src/calendar/CalendarEventViewModel.js, src/calendar/CalendarUtils.js
=> only have the organizer increase calendar event sequence number

src/api/main/WorkerClient.js, src/api/worker/facades/CustomerFacade.js, src/settings/emaildomain/VerifyOwnershipPage.js
=> Make domain verification tokens per domain

src/api/main/EntropyCollector.js, src/api/worker/crypto/Randomizer.js, src/desktop/CryptoFns.js, src/desktop/DesktopCryptoFacade.js, src/desktop/DeviceKeyProviderImpl.js
Randomizer was not seeded so config migration was failing.
fix #2911
=> [desktop] Fix generating device key

src/api/worker/search/EventQueue.js, src/mail/model/MailUtils.js, src/mail/view/MailViewer.js, test/api/worker/search/EventQueueTest.js
=> Fix ProgrammingError for create-create entity updates

src/calendar/export/CalendarImporter.js
fix #2325
This may be difficult to test, because we'll have to find a way to get into this invalid state with an undefined alarm trigger
=> fix exporting calendar with invalid alarm triggers

src/subscription/SubscriptionSelector.js, src/subscription/UpgradeSubscriptionPage.js
=> fix highlighting of boxes in SubscriptionSelector

src/contacts/view/ContactView.js, src/contacts/view/MultiContactViewer.js
=> make _contactList nullable and check that it is defined in ContactView

src/subscription/PaymentViewer.js
=> fix changing payment method with no existing postings

src/mail/model/MailModel.js, src/mail/view/MailView.js
=> fix unhandled PreconditionFailedError when moving mails

src/desktop/integration/DesktopIntegratorLinux.js, test/client/desktop/integration/DesktopIntegratorTest.js
=> Fix deactivating desktop integration

src/gui/base/Dropdown.js
=> Fix dropdown not closing when selection is made

src/support/FaqModel.js
=> fix faq search in support dialog

src/calendar/view/EventPreviewView.js
=> Fix attendee status

src/knowledgebase/model/KnowledgeBaseModel.js, src/templates/model/TemplatePopupModel.js
=> remove usage of Array.prototype.flat

package-lock.json, package.json
=> Update Electron to 11.4.4

src/settings/EditSignatureDialog.js, src/translations/en.js
=> show confirmation dialog before setting large signature

src/login/LoginViewController.js, src/misc/ErrorHandlerImpl.js, src/misc/SubscriptionDialogs.js, src/subscription/StorageCapacityOptionsDialog.js, src/subscription/SubscriptionViewer.js
=> show storage buy options when warning for limits

src/contacts/model/ContactModel.js
=> load contact suggestions in one request per listId

app-android/app/src/main/java/de/tutao/tutanota/push/TutanotaNotificationsHandler.java, app-ios/tutanota/Sources/TUTAlarmManager.m, src/desktop/sse/DesktopSseClient.js
=> Native suspension

src/mail/view/MailViewer.js
=> Enable contrast fix in dark mode if background-color present

src/calendar/view/CalendarEventEditDialog.js
=> do not allow updates of read-only calendar events

src/calendar/view/EventPreviewView.js, src/gui/main-styles.js
=> show scrollbar for overflowing event descriptions on mobile

src/gui/ScrollSelectList.js, src/gui/base/BubbleTextField.js, src/gui/base/GuiUtils.js, src/knowledgebase/view/KnowledgeBaseDialogContent.js, src/misc/RecipientInfoBubbleHandler.js, src/sharing/view/GroupSharingDialog.js
=> limit number of suggestions in BubbleTextField suggestions dropdown, fix scrolling

src/mail/editor/MailEditor.js
=> fix flickering language selector animation in MailEditor

src/gui/base/TextFieldN.js, src/settings/PasswordForm.js, src/settings/SetDomainCertificateDialog.js, src/subscription/SignupForm.js
=> Fix signup UI

buildSrc/Builder.js, buildSrc/DesktopBuilder.js, buildSrc/RollupConfig.js, buildSrc/RollupDebugConfig.js, src/desktop/DesktopMain.js, src/desktop/IPC.js, src/desktop/integration/DesktopIntegrator.js, src/desktop/integration/DesktopIntegratorDarwin.js, src/desktop/integration/DesktopIntegratorLinux.js, src/desktop/integration/DesktopIntegratorWin32.js, test/client/desktop/integration/DesktopIntegratorTest.js, test/client/desktop/sse/DesktopSseClientTest.js
=> fix DesktopSseClient and DesktopIntegrator tests

app-android/app/src/main/java/de/tutao/tutanota/push/TutanotaNotificationsHandler.java, app-ios/tutanota/Sources/TUTAlarmManager.m, src/desktop/sse/DesktopSseClient.js, test/api/TestUtils.js, test/client/desktop/sse/DesktopSseClientTest.js
Fix #2858 by handling both HTTP codes
=> Fix native suspension

src/mail/view/MailListView.js
=> Use trash icon when swiping to delete

src/support/FaqModel.js
Also refactor method to use async/await
fix #3074
=> Load images in FAQ

src/api/common/utils/DateUtils.js, src/calendar/date/CalendarUtils.js
=> Limit event iterations, check that date is valid

src/gui/editor/Editor.js
=> Add dir="auto" to every paragraph in Editor

src/api/common/TutanotaConstants.js, src/api/worker/facades/UserManagementFacade.js
=> Do not call MembershipService when not needed

.gitignore, buildSrc/DesktopBuilder.js, buildSrc/electron-package-json-template.js, buildSrc/installerSigner.js, buildSrc/winsigner.cjs, dist.js
to create these signatures, run the dist script with the environment
variable DEBUG_SIGN set to a directory containing a self-signed code
signing cert file test.p12
close #2918
=> add possibility to use self-signed cert for desktop update signatures

src/misc/ContactSuggestion.js
=> improve appearance of contact suggestions with long text

src/mail/view/MailViewer.js
oncreate was not called when switch between cached mails.
fix #3113
=> Fix line-height not being updated in mail viewer

dist.js
=> add documentation for dist.js DEBUG_SIGN env variable

src/desktop/DesktopCryptoFacade.js, src/desktop/config/DesktopConfig.js
=> [desktop] Handle encryption errors for config

src/contacts/ContactEditor.js
=> show shared password field for new contact editor

src/gui/base/BubbleTextField.js
The problem is that the "More" button and the progress icon have a different height and the progress spinner was alternating with the more button especially when the bubble input field reaches the second line. The fix sets the height of the spinner to the default button height and also reserve some fixed space for the progress icon to not replace the more button.
=> Reserve space for progress icon in bubble input field, fixes #3157

buildSrc/BuildServer.js, buildSrc/BuildServerClient.js, buildSrc/BuildServerFactory.js, buildSrc/BuildServerStarter.js, buildSrc/Builder.js, buildSrc/README.MD, make.js, package-lock.json, test/TestBuilder.js, test/test.js
Once this is on master, we will have to make minor adjustments to the Makefile of admin client upon updating the tutanota dependency there.
=> Refactor build

dist.js
Only import desktop signature dependencies if needed for actually building desktop Apps. Also some cleanup in `dist.js`.
See https://gitlab.com/jowlo/fdroiddata/-/jobs/1323442792 for a successful build.
fix #3154
=> Remove desktop build dependencies for F-Droid

src/mail/view/MailView.js, src/misc/KeyManager.js
fixes #3008
Function used for removing shortcuts would not remove some shortcuts due to invalid index.
=> Fix duplicate shortcuts, Fix shortcuts not being removed

src/contacts/ContactEditor.js
=> generate keys for contact fields when creating a new contact

src/gui/base/ButtonN.js
=> Right align dropdown icon

buildSrc/RollupConfig.js, src/api/common/TutanotaConstants.js, src/api/common/utils/ArrayUtils.js, src/gui/base/Dialog.js, src/gui/base/RichTextToolbar.js, src/gui/main-styles.js, src/mail/editor/SendMailModel.js, src/mail/press/PressReleaseEditor.js, src/mail/view/MailView.js
We needed a more proper way to send out press releases, and have decided to build in a feature in the client that will be disabled without a specific feature type
=> add press release editor

src/mail/view/MailViewer.js
we also no longer save the result of m.trust because it is bad to store Vnodes
fix #3209
=> redraw after sanitizing and setting mail body

.flowconfig, buildSrc/RollupConfig.js, src/desktop/DesktopFileExport.js
=> Fix resolving oxmsg from admin client

src/calendar/model/CalendarModel.js
=> Do not load alarms in web pert of desktop

src/subscription/SignupForm.js
=> Switch text box label when disabled during signup

package-lock.json, package.json
=> Update Electron to 11.4.10

src/settings/ContactFormViewer.js
=> disable title field in contact form viewer

src/mail/view/MailViewer.js
=> Don't offer to trust sender when mail auth fails

src/api/common/TutanotaConstants.js, src/api/common/error/OutOfSyncError.js, src/api/common/utils/DateUtils.js, src/api/common/utils/Utils.js, src/api/main/WorkerClient.js, src/api/worker/EventBusClient.js, src/api/worker/rest/EntityRestClient.js, src/api/worker/rest/RestClient.js, src/api/worker/search/Indexer.js, src/api/worker/search/MailIndexer.js, src/misc/IndexerDebugLogger.js, src/settings/AboutDialog.js, test/api/TestUtils.js, test/api/common/IndexerDebugLoggerTest.js, test/api/common/PromiseUtilTest.js, test/api/common/WorkerTest.js, test/api/rest/RestClientTest.js, test/api/worker/search/IndexerTest.js, test/client/desktop/IPCTest.js
=> Better detect when indexer goes out of sync

src/api/worker/search/Indexer.js, test/api/worker/search/IndexerTest.js
=> fix indexer out of sync bug + solve failing browser test

app-android/app/src/main/java/de/tutao/tutanota/MainActivity.java, buildSrc/Builder.js, dist.js, src/app.js
* Fix the status/navigation bars being set to the wrong colour based on the background of the app
* Fix white screen being shown for users who have an old webview
fix #3299 #3302
=> android bugfixes for 3.85.3

app-android/app/src/main/java/de/tutao/tutanota/MainActivity.java, app-android/app/src/main/java/de/tutao/tutanota/Utils.java, app-android/app/src/test/java/de/tutao/tutanota/UtilsTest.java, app-ios/tutanota.xcodeproj/project.pbxproj, app-ios/tutanota/Sources/TUTViewController.m, app-ios/tutanota/Sources/ThemeManager.swift, app-ios/tutanota/Sources/Utils/UIColor+utils.swift, app-ios/tutanotaTests/UIColorExtensionsTest.swift, src/gui/animation/Animations.js, src/gui/base/Color.js, src/settings/EditCustomColorsDialog.js, test/client/gui/ColorTest.js
=> Handle 3 digit color codes in custom theme for native

doc/HACKING.md
Minor improvements on the HACKING.md doc for online viewing.
Also fix wrong `fdroid-fix-deps.js` reference (was missing `js` part).
=> Improve hacking doc

app-ios/tutanota/Sources/Alarms/TUTAlarmNotification.m, app-ios/tutanota/Sources/Keychain/TUTKeychainManager.m, app-ios/tutanota/Sources/TUTAlarmManager.m, app-ios/tutanota/Sources/TUTViewController.m
Few fixes which address #3331 and hopefully #3010 as well. Please read complete commit message for the first commit.
=> Fixes for iOS alarms

src/login/contactform/ContactFormRequestDialog.js
=> don't trim spaces in contact form subject field

src/api/worker/facades/MailFacade.js
Mostly a reversion of a previous refactoring that introduced the bug, which wasn't totally necessary anyway
fix #3310
=> fix attachments duplication

src/subscription/PaymentViewer.js
=> expose credit invoices to the client

src/gui/base/DropdownN.js, src/gui/nav/DrawerMenu.js, src/misc/KeyManager.js
=> prevent the help dialog from showing the support dropdown shortcuts

src/mail/view/MailViewer.js
=> fix rendering of info banner buttons

buildSrc/RollupConfig.js, flow/libs.js, package-lock.json, package.json, src/gui/base/DropDownSelectorN.js, src/gui/base/DropdownN.js, src/gui/base/InfoBanner.js, src/gui/base/NotificationOverlay.js, src/gui/base/WizardDialogN.js, src/mail/view/MailFolderRow.js, src/mail/view/MailViewer.js, src/settings/GroupViewer.js, src/settings/SetDomainCertificateDialog.js, src/settings/UserViewer.js, src/settings/WhitelabelChildViewer.js, src/settings/emaildomain/AddDomainWizard.js, src/settings/emaildomain/EnterDomainPage.js, src/settings/whitelabel/WhitelabelGermanLanguageFileSettings.js, src/settings/whitelabel/WhitelabelRegistrationSettings.js, src/settings/whitelabel/WhitelabelSettingsViewer.js, src/subscription/UpgradeSubscriptionWizard.js, src/subscription/giftcards/RedeemGiftCardWizard.js
=> Fix Flow typing for Mithril

src/contacts/view/ContactListView.js, src/contacts/view/ContactView.js, src/gui/ListColumnWrapper.js, src/gui/base/DropDownSelectorN.js, src/gui/base/TextFieldN.js
=> Move contact sort selector to list header

src/api/common/utils/ArrayUtils.js, src/api/worker/EventBusClient.js, src/calendar/view/CalendarView.js, test/api/common/ArrayUtilsTest.js
This PR fixes scenario from #2619.
I think it might still break if there are some unprocessed events for the group and we reconnect in the middle but I imagine that it is fairly rare.
=> Fix handling membership loss

src/misc/U2fClient.js
=> Fix async waiting on u2f key

src/api/main/WorkerClient.js, src/api/worker/facades/MailFacade.js, src/api/worker/facades/ReceipientKeyDataUtils.js, src/api/worker/facades/ShareFacade.js, src/sharing/model/GroupSharingModel.js
=> fix error when sharing calendars and templates

src/RootView.js, src/gui/base/Overlay.js, src/gui/base/SnackBar.js, src/gui/builtinThemes.js, src/gui/theme.js
resolves #3063
This should only be merged when #3015 is ready, because otherwise it would not be used and thus not testable.
=> Create new SnackBar component

src/calendar/date/CalendarUpdateDistributor.js
=> fixes multiple files in calendar event

src/templates/model/TemplatePopupModel.js
Wasn't able to reproduce it but this should fix it?
fix #3408
=> initialize groupInstances in TemplatePopupModel.js ctor

buildSrc/Builder.js, make.js, packages/tutanota-build-server/README.md, packages/tutanota-build-server/src/BuildServer.js, packages/tutanota-build-server/src/Watchers.js
=> Flow is not executed repeatedly in watch mode

buildSrc/DesktopBuilder.js, buildSrc/compileKeytar.js, package-lock.json, package.json
the keytar build doesn't depend on runtime or
version anymore since it switched
from node headers to N-API.
close #3467
=> update keytar to v7.7.0

src/mail/editor/SendMailModel.js
=> fix error handling when updating draft

src/misc/U2fClient.js
=> fix u2f error handling in U2fClient

src/login/contactform/ContactFormRequestDialog.js, src/mail/editor/MailEditor.js, src/mail/editor/SendMailModel.js, src/mail/model/MailUtils.js
=> fix too large attachments in mailto link

app-android/app/src/main/java/de/tutao/tutanota/Native.java, app-ios/tutanota/Sources/TUTViewController.m, src/desktop/IPC.js
=> update native colors when saved theme definitions change

src/calendar/export/CalendarParser.js
=> Accept leading whitespace in ics dates

Jenkinsfile, buildSrc/Builder.js, packages/tutanota-build-server/src/BuildServer.js
=> Small build improvements

src/calendar/view/CalendarEventEditDialog.js, src/calendar/view/MultiDayCalendarView.js, src/gui/TimePicker.js
=> Calendar UI fixes

src/calendar/date/CalendarEventViewModel.js, src/calendar/view/CalendarEventEditDialog.js, src/gui/date/DatePicker.js, src/gui/date/DatePickerDialog.js, src/misc/DateParser.js, src/search/view/SearchView.js, src/settings/ContactFormViewer.js, src/settings/EditOutOfOfficeNotificationDialog.js, src/settings/EditOutOfOfficeNotificationDialogModel.js
=> Fix date picker rendering in calendar event edit dialog

src/calendar/view/CalendarView.js, src/calendar/view/CalendarViewModel.js
=> Fix creation of extra Private calendars

Ios.Jenkinsfile, app-ios/fastlane/Fastfile
=> CI improvements for ios

flow/mithril.js, packages/tutanota-utils/test/ArrayUtilsTest.js, src/app.js, src/misc/LoginUtils.js, src/subscription/SignupForm.js, src/subscription/UpgradeConfirmPage.js, src/subscription/UpgradeSubscriptionWizard.js, src/subscription/giftcards/PurchaseGiftCardDialog.js, src/subscription/giftcards/RedeemGiftCardWizard.js
=> Get token from url hash when going to signup page

src/app.js, src/login/LoginListener.js
=> Automatically select credential method

android.js, app-android/app/src/main/java/de/tutao/tutanota/MainActivity.java, app-android/app/src/main/java/de/tutao/tutanota/Native.java, app-ios/tutanota/Sources/TUTViewController.m, buildSrc/DevBuild.js, make.js, src/api/main/WorkerClient.js, src/app.js, src/desktop/ApplicationWindow.js, src/desktop/IPC.js, src/login/LoginListener.js, src/misc/credentials/CredentialsProviderFactory.js, src/native/common/NativeWrapper.js, src/settings/LoginSettingsViewer.js, test/client/desktop/ApplicationWindowTest.js, test/client/desktop/IPCTest.js
=> Fix opening mailbox from notification on android

src/app.js
=> Fix migration to keychain auth

app-ios/tutanota.xcodeproj/project.pbxproj, app-ios/tutanota/Sources/Files/FileFacade.swift, app-ios/tutanota/Sources/Keychain/KeyGeneratorSecureEnclave.swift, app-ios/tutanota/Sources/Keychain/KeychainManager.swift, app-ios/tutanota/Sources/Utils/SyncCompletion.swift, src/api/worker/facades/FileFacade.js, src/gui/dialogs/SelectCredentialsEncryptionModeDialog.js, src/misc/credentials/CredentialsProvider.js, src/native/common/FileApp.js
=> Keychain fixes

src/gui/TimePicker.js
=> [mobile] always give 24hr time to timepicker

app-ios/tutanota/Sources/Files/FileFacade.swift
=> [ios] read http response headers case-insensitively

app-ios/tutanota/Sources/ViewController.swift
Some code was lost during the conversion to swift I took this from the old TUTViewController.m 
fix #3680
=> [ios] handle webview navigation

flow/dompurify.js, libs/luxon.js, libs/purify.js, libs/s.js, package.json, src/misc/HtmlSanitizer.js, src/subscription/giftcards/GiftCardUtils.js, test/client/common/HtmlSanitizerTest.js
=> Fix gift card QR code

src/gui/main-styles.js
=> fix email headers formatting

src/desktop/integration/DesktopIntegratorLinux.js
complete GenericName and Keywords entries in share/applications/tutanota-desktop.desktop file
=> more metadata in application desktop file

src/gui/ThemeController.js, src/gui/base/Logo.js, src/gui/builtinThemes.js
~~Also collect theme related code together for organisation~~
~~All the changes are just imports + 4 files were moved~~
Undid the organizational changes to reduce conflicts with changes to whitelabel theme editor
close #3546
=> Moved Logo.js out of icons subdirectory

src/sharing/GroupSharingUtils.js
=> Fix calendar invitation notification message

src/gui/date/DatePickerDialog.js
End date picker should use dateTo_label
closes #3686
=> Fix date picker labels

flow/electron.js, package-lock.json, package.json, src/desktop/DesktopDownloadManager.js
=> Update Electron to 15

Android.Jenkinsfile, Ios.Jenkinsfile
=> [build] Don't bail in jenkins when createGithubReleasePage fails

src/api/main/NativeInterfaceFactory.js, src/app.js, src/native/main/NativeInterfaceMain.js
=> [android] fix opening notifications when app is not already running

src/calendar/view/CalendarMonthView.js
=> fix missing circle in CalendarMonthView for current day

src/mail/view/MailViewer.js
When displaying a mail we download and sanitize the mail. Until this is ready we show a progress spinner in the main body view of the email.
We also show the spinner while only sanitizing already downloaded data. This delays the rendering of the progress spinner by 300ms to reduce the flickering when skipping through mails at a quick rate.
fix #3120
=> Delay progress spinner rendering

src/gui/ThemeController.js, src/gui/builtinThemes.js, src/gui/theme.js, src/settings/AboutDialog.js
=> Always show tutanota logo in about dialog

src/api/worker/rest/EntityRestCache.js, test/api/rest/EntityRestCacheTest.js
=> fix caching loaded single entities

app-android/app/src/main/java/de/tutao/tutanota/Native.java, src/api/common/WorkerProxy.js, src/api/main/WorkerClient.js, src/api/worker/WorkerImpl.js
fix #3753
See full commit messages for details.
=> Fix native bridge issues

src/mail/view/MailViewer.ts
fix #3769
Also fix some botched formatting while we're at it.
=> Fix attachments 

src/desktop/DesktopMain.ts, src/desktop/DesktopUtils.ts, src/desktop/IPC.ts, test/client/desktop/IPCTest.ts
fix #3752
Note: it's completely untested, need to try all scenarios first
=> [desktop/win32] Fix registering mailto on Windows as non-admin user

buildSrc/RollupConfig.js, libs/libs.d.ts, package-lock.json, package.json, src/settings/EditSecondFactorDialog.ts, src/subscription/giftcards/GiftCardUtils.ts
=> Fix totp qrcode QR-code

src/api/common/TutanotaConstants.ts, src/settings/emaildomain/AddDomainWizard.ts
=> Fix DNS records names

src/settings/IdentifierListViewer.ts, src/settings/MailSettingsViewer.ts
=> Fix push identifier list

src/mail/view/MailViewer.ts
=> Fix download all for attachments

src/desktop/DesktopDownloadManager.ts, src/desktop/DesktopNetworkClient.ts, test/client/desktop/DesktopDownloadManagerTest.ts, test/client/nodemocker.ts
=> [desktop] Fix opening attachments, fix suspension handling

src/desktop/DesktopUtils.ts
=> [desktop/windows] write registry scripts into the tmp directory

package-lock.json, package.json, src/desktop/sse/SecretStorage.ts
fixes missing cancellation in keytar #3733
with this, the user will get an error box "Can't access secret storage" with a reference to the secret storage FAQ if they cancel the keychain unlock.
=> [desktop/linux] propagate keytar cancellation from KeytarSecretStorage

src/desktop/DesktopMain.ts, src/desktop/DeviceKeyProviderImpl.ts, src/desktop/IPC.ts, src/desktop/KeyStoreFacadeImpl.ts, src/desktop/config/DesktopConfig.ts, src/desktop/config/migrations/DesktopConfigMigrator.ts, src/desktop/config/migrations/migration-0003.ts, src/desktop/credentials/DektopCredentialsEncryption.ts, src/desktop/credentials/ElectronCredentialsEncryption.ts, src/desktop/sse/DesktopAlarmStorage.ts, src/desktop/sse/SecretStorage.ts, src/misc/credentials/CredentialsProviderFactory.ts, src/settings/LoginSettingsViewer.ts, test/api/TestUtils.ts, test/client/Suite.ts, test/client/desktop/DeviceKeyProviderTest.ts, test/client/desktop/IPCTest.ts, test/client/desktop/KeyStoreFacadeTest.ts, test/client/desktop/config/migrations/DesktopConfigMigratorTest.ts, test/client/desktop/credentials/DesktopCredentialsEncryptionTest.ts, test/client/desktop/credentials/ElectronCredentialsEncryptionTest.ts, test/client/desktop/integration/DesktopIntegratorTest.ts, test/client/desktop/sse/DesktopAlarmStorageTest.ts
=> [desktop] encrypt credentials

package-lock.json, package.json
see https://github.com/electron/electron/releases/tag/v16.0.0
close #3858
=> Update Electron to 16.0.8

package-lock.json, package.json, src/desktop/KeyStoreFacadeImpl.ts, test/client/desktop/KeyStoreFacadeTest.ts
=> Fix desktop cred encryption

src/misc/ErrorHandler.ts
=> Fix error handler import delay

src/api/worker/facades/DeviceEncryptionFacade.ts, src/desktop/sse/SecretStorage.ts, src/misc/credentials/NativeCredentialsEncryption.ts, test/client/misc/credentials/NativeCredentialsEncryptionTest.ts
See commit messages for full explanation
fix #3875
=> Fix saving credentials key

src/contacts/model/ContactUtils.ts, test/client/contact/ContactUtilsTest.ts
=> use leap year as default to format birthday without year

src/login/LoginViewModel.ts, test/client/login/LoginViewModelTest.ts
Better solution would be a more robust state representation but this
would be a big refactoring and it doesn't seem like it's needed badly.
fix #3846
=> Fix login page breaking after using empty fields

src/calendar/date/CalendarUtils.ts, src/gui/date/DatePicker.ts, src/gui/date/DatePickerDialog.ts
=> Mobile date picker fixes

src/subscription/BuyDialog.ts
Business feature was not taken into account while calculating the
difference.
fix #3922
=> Fix calculating per-user price w/ Business feature

src/desktop/WebDialog.ts, src/desktop/preload-webdialog.js, src/global.d.ts, src/native/main/WebauthnNativeBridge.ts, src/serviceworker/ServiceWorkerClient.ts
fix #3914
also fix #2178 webauthn dialog's non-responsiveness due to initialisation timing
draft because we still don't handle cancelled errors when the webauthn dialog is closed
=> Webauthn fixes

packages/tutanota-utils/lib/ArrayUtils.ts, packages/tutanota-utils/lib/index.ts, packages/tutanota-utils/test/ArrayUtilsTest.ts, src/api/common/utils/EntityUtils.ts, src/api/worker/rest/EntityRestCache.ts, src/misc/2fa/webauthn/WebauthnClient.ts, src/settings/UserListView.ts, test/api/rest/EntityRestCacheTest.ts
=> Fix entity rest cache loadRange

buildSrc/Builder.js, buildSrc/LaunchHtml.js, buildSrc/RollupDebugConfig.js, buildSrc/RollupUtils.js, buildSrc/buildUtils.js, buildSrc/electron-package-json-template.js, buildSrc/nativeLibraryProvider.js, buildSrc/nativeLibraryRollupPlugin.js, package-lock.json, package.json, packages/tutanota-build-server/package.json, src/api/main/MainLocator.ts, src/desktop/WebDialog.ts, test/TestBuilder.js
Close tutao/private-issues#12
Same branch for admin client
=> Admin webauth

src/api/common/error/DeviceStorageUnavailableError.ts, src/desktop/DesktopMain.ts, src/desktop/DesktopUtils.ts, src/desktop/KeyStoreFacadeImpl.ts, src/gui/dialogs/SelectCredentialsEncryptionModeDialog.ts, src/login/LoginViewModel.ts, src/misc/credentials/CredentialsProvider.ts, test/client/desktop/KeyStoreFacadeTest.ts, test/client/login/LoginViewModelTest.ts, test/client/misc/credentials/CredentialsProviderTest.ts
=> Wrap key retrieval errors other than CancelledError in DeviceStorageUnavailableError

src/gui/SidebarSection.ts
=> Fix long sidebar title not fitting into its column

src/subscription/BuyDialog.ts
there are three events the buy dialog must handle
* price increase ("buy")
* price decrease("order")
* price stays the same ("accept")
the action was aborted in the third case because the buy dialog was only
ever shown in the first two.
fix #3949, fix #3946
=> handle subscription changes without price changes properly

src/calendar/export/CalendarParser.ts, test/client/calendar/CalendarParserTest.ts
events conforming to https://tools.ietf.org/html/rfc5545 must have
an end time that is larger than the start time.
Some applications seem to export "reminder" like events with identical
start and end times.
we can safely provide some functionality anyway by assuming a legal
endTime if the event is otherwise okay.
illegal all-day events (ie events that only specify a start day,
but no time) will be converted to an all-day event with a duration of
one day.
illegal events that are not all-day will be converted to a duration of
1 second for the following reasons:
* duration is rendered as eg 2022-03-15 17:00 to 2022-03-15 17:00
* the duration has the minimal chance to overlap the end of day which
would cause the event to be rendered over 2 days
* we don't lose alarms by importing an event …
=> allow import of events with illegal end time

src/contacts/view/ContactViewer.ts
=> make contact comments selectable

src/gui/base/RichTextToolbar.ts, src/gui/editor/Editor.ts, src/gui/editor/HtmlEditor.ts, src/mail/editor/MailEditor.ts
the visible surface of the mail editor was smaller than the actual DOM element. this fix forces the squire editor to fill the whole dialog.
a tiny cleanup refactoring was also undertaken
fix #3896
with thanks to @Mxchaeltrxn for the original PR
=> Always focus the editor when clicking on the mail editor dialog

src/file/FileController.ts, src/global.d.ts
Contains a bugfix (more of a workaround) + a cleanup, see commit messages
fix #3983
=> fix firefox pdf attachments bug

src/mail/view/MailViewer.ts
=> Fix download action in MailViewer

src/mail/view/MailViewer.ts, src/mail/view/MailViewerViewModel.ts
=> Fix mailviewer devbugs

src/gui/base/Dialog.ts, src/mail/view/MailView.ts, src/settings/AddInboxRuleDialog.ts, src/settings/AddSpamRuleDialog.ts, src/settings/GroupViewer.ts, src/settings/MailSettingsViewer.ts, src/settings/UserViewer.ts
=> Do not close editor dialogs if a ConnectionError occurs, fix #4025

src/api/entities/storage/ModelInfo.ts, src/api/entities/storage/TypeModels.js, src/api/entities/tutanota/tutanotaModelInfo.ts
=> model changes for server issue 958

.github/workflows/release.yml, Android.Jenkinsfile, Desktop.Jenkinsfile, Ios.Jenkinsfile, buildSrc/releaseNotes.js
A simplified release notes body is generated for the iOS notes, and it is then saved to a file for fastlane to read it from.
fix #4062
=> Generate release notes for iOS, 

app-android/app/src/main/java/de/tutao/tutanota/FileUtil.java, app-ios/tutanota/Sources/Files/FileFacade.swift, src/api/common/utils/Utils.ts, src/mail/editor/MailEditor.ts
due to TCP buffering we don't actually get to know when our data was
written to the network.
this may cause us to copy a file to the TCP buffer and immediately start
waiting on a server response.
on slow connections, this trips the 15s HTTP read timeout.
removing the timeout and relying on the OS to tell us if the connection
breaks should help with this.
for this, we convert all SocketExceptions into ConnectionErrors.
There's still sort of a timeout because the server will stop listening
after 10 (?) minutes to prevent slow loris.
also add a redraw on the minimized mail editor so we see a change in
status immediately
#4035
=> [android] improve slow attachment uploads by removing read timeout

android.js, buildSrc/fetchDictionaries.js, buildSrc/nativeLibraryProvider.js, buildSrc/prepareMobileBuild.js, buildSrc/releaseNotes.js, buildSrc/signDesktopClients.js, bump-version.js, desktop.js, make.js, package-lock.json, package.json, packages/tutanota-build-server/src/BuildServerStarter.ts, webapp.js
=> [maintenance] update commander to v9

src/api/common/error/LoginIncompleteError.ts, src/api/common/utils/Utils.ts, src/api/worker/facades/UserFacade.ts, src/contacts/model/ContactModel.ts, src/gui/base/BubbleTextField.ts, src/mail/editor/MailEditor.ts, src/mail/editor/MailEditorViewModel.ts, src/mail/view/MailViewer.ts, src/misc/ErrorHandlerImpl.ts, src/misc/RecipientInfoBubbleHandler.ts
This PR introduces LoginIncompleteError that is thrown when update operations fail due to offline (and therefore incomplete) login (see individual commit messages). Close #4078
=> Offline update operations 4078

src/gui/FolderColumnView.ts
=> remove extra div from FolderColumnView when there's no button

src/api/common/utils/ErrorCheckUtils.ts, src/api/worker/crypto/CryptoFacade.ts, src/api/worker/facades/BlobFacade.ts, src/api/worker/facades/CalendarFacade.ts, src/api/worker/facades/LoginFacade.ts, src/api/worker/facades/UserFacade.ts, src/api/worker/rest/EntityRestClient.ts, src/api/worker/rest/ServiceExecutor.ts, src/file/FileController.ts, src/gui/base/Dialog.ts, src/gui/base/List.ts, src/mail/editor/MailEditor.ts, src/mail/editor/MailEditorViewModel.ts, src/mail/view/MailListView.ts, src/mail/view/MailView.ts, src/mail/view/MailViewerViewModel.ts, src/misc/ErrorHandlerImpl.ts, src/offline/LoadingState.ts, src/settings/AddInboxRuleDialog.ts, src/settings/AddSpamRuleDialog.ts, test/tests/api/worker/facades/BlobFacadeTest.ts, test/tests/api/worker/rest/EntityRestClientMock.ts, test/tests/api/worker/rest/EntityRestClientTest.ts, test/tests/api/worker/rest/ServiceExecutorTest.ts
=> Fix errors during incomplete login

src/subscription/SwitchSubscriptionDialog.ts
=> fix not awaiting Dialog for downgrade cancellation

app-android/app/src/main/java/de/tutao/tutanota/credentials/CredentialsEncryptionFromAPI30.java
=> [android] Fix keystore after Android upgrade

src/mail/view/MailView.ts, src/mail/view/MultiMailViewer.ts
=> Fix mail view list

Android.Jenkinsfile, Ios.Jenkinsfile, app-android/app/build.gradle, app-ios/tutanota/Info.plist, package-lock.json, package.json, packages/tutanota-crypto/package.json, packages/tutanota-test-utils/package.json, packages/tutanota-usagetests/package.json, packages/tutanota-utils/package.json
close #3933
With this PR, when running the pipeline for either android or ios, the test and production builds will both be done. The production app will then be published to the respective app store but not released. 
Once testing is completed, the only thing that then needs to be done is to go to the app store and submit for review/publish.
=> Streamline mobile release

src/calendar/view/CalendarAgendaView.ts
=> Calendar Agenda: fix all-day event with location bug

.gitignore, src/desktop/DesktopWindowManager.ts, src/desktop/config/migrations/DesktopConfigMigrator.ts, src/desktop/config/migrations/migration-0007.ts, test/tests/desktop/config/migrations/DesktopConfigMigratorTest.ts
=> increase default window size of desktop client to three-column width

app-ios/tutanota.xcodeproj/project.pbxproj, app-ios/tutanota/Sources/Alarms/AlarmManager.swift, app-ios/tutanota/Sources/AppDelegate.swift, app-ios/tutanota/Sources/Contacts/ContactsSource.swift, app-ios/tutanota/Sources/Crypto/CryptoFacade.swift, app-ios/tutanota/Sources/Files/BlobUtil.swift, app-ios/tutanota/Sources/Files/FileChooser.swift, app-ios/tutanota/Sources/Files/FileFacade.swift, app-ios/tutanota/Sources/Files/FileViewer.swift, app-ios/tutanota/Sources/Keychain/CredentialsEncryption.swift, app-ios/tutanota/Sources/Remote/WebViewBridge.swift
=> Swift async

src/api/worker/facades/BlobFacade.ts
=> retry with another node in case of internal server error

src/file/FileController.ts
=> Add isLegacyFile to FileController

src/gui/MailRecipientsTextField.ts, src/gui/RecipientsSearchDropDown.ts, src/gui/base/BubbleTextField.ts, src/gui/base/Dialog.ts, src/gui/base/buttons/FolderColumnHeaderButton.ts, src/gui/dialogs/ShortcutDialog.ts, src/gui/dialogs/SpellcheckLanguageDialog.ts, src/login/LoginForm.ts, src/mail/view/MailReportDialog.ts, src/misc/ErrorReporter.ts, src/search/view/SearchView.ts, src/settings/AddUserDialog.ts, src/settings/EditOutOfOfficeNotificationDialog.ts, src/settings/GlobalSettingsViewer.ts, src/settings/IdentifierListViewer.ts, src/settings/TemplateDetailsViewer.ts, src/settings/TemplateEditor.ts, src/settings/WhitelabelChildViewer.ts, src/subscription/DeleteAccountDialog.ts, src/subscription/SubscriptionViewer.ts, src/support/SupportDialog.ts
=> Fix attrs bugs

src/desktop/db/OfflineDb.ts, test/tests/desktop/db/OfflineDbTest.ts
=> Add ON CONFLICT REPLACE for ranges

src/login/contactform/ContactFormRequestDialog.ts, src/settings/EditAliasesFormN.ts, src/settings/emaildomain/AddEmailAddressesPage.ts, src/settings/whitelabel/WhitelabelCustomMetaTagsSettings.ts, src/settings/whitelabel/WhitelabelImprintAndPrivacySettings.ts, src/sharing/view/GroupSharingDialog.ts, src/subscription/Captcha.ts, src/subscription/SignupForm.ts, src/subscription/UpgradeSubscriptionPage.ts, test/tests/subscription/SignupFormTest.ts
=> Fix captcha

src/gui/base/Dialog.ts, src/settings/GlobalSettingsViewer.ts
also generally fixed the dropdown selection dialog
=> fix custom domain catch all selection

src/gui/base/GuiUtils.ts, src/subscription/InvoiceDataInput.ts
I also cleaned up the component, but didn't convert it because it has a `HtmlEditor` inside
fix #4258
=> fix VAT ID input

src/api/worker/facades/BlobFacade.ts, test/tests/api/worker/facades/BlobFacadeTest.ts
server issue 1127
Test notes can also be found on the server issue.
=> retry blobservice GET with another node in case of notfound server error

doc/BUILDING.md
It is nice to show that explicitly as an option. Please correct me if I am wrong about this,
but I did notice android APKs get published as an Asset along with the source code.
=> Add GitHub releases as an option

package-lock.json, package.json, src/api/entities/accounting/TypeModels.js, src/api/entities/base/TypeModels.js, src/api/entities/gossip/TypeModels.js, src/api/entities/monitor/TypeModels.js, src/api/entities/storage/TypeModels.js, src/api/entities/sys/TypeModels.js, src/api/entities/tutanota/TypeModels.js, src/native/common/InterWindowEventBus.ts, test/tests/api/worker/crypto/CryptoFacadeTest.ts, test/tests/login/LoginViewModelTest.ts
=> Update Typescript to 4.7

src/desktop/DesktopUtils.ts
=> provide tmp dir for each user

src/api/worker/WorkerLocator.ts, src/app.ts, src/desktop/config/ConfigKeys.ts, src/offline/CachePostLoginAction.ts, src/settings/DesktopSettingsViewer.ts, src/settings/MailSettingsViewer.ts, src/settings/OfflineStorageSettings.ts
=> Enable offline always

src/calendar/date/CalendarUpdateDistributor.ts
=> Remove logo to fix white background for calendar event emails

src/api/worker/rest/CustomCacheHandler.ts, src/api/worker/rest/EntityRestCache.ts, test/tests/api/worker/rest/CustomCacheHandlerTest.ts, test/tests/api/worker/rest/EntityRestCacheTest.ts
https://github.com/tutao/tutanota/issues/4262
=> Cache fixes

src/login/ExternalLoginView.ts
Now when the external user logs out and they have saved credentials, the login view shows just a button to login, rather than an empty login form
fix #4185
=> Use saved credentials for external login view after logout

src/mail/view/MailViewer.ts
=> replace inline images when using retry button in mailviewer

app-ios/tutanota/Sources/Files/IosFileFacade.swift, app-ios/tutanota/Sources/Keychain/KeyGeneratorSecureEnclave.swift, app-ios/tutanota/Sources/Keychain/KeychainManager.swift, app-ios/tutanota/Sources/ViewController.swift
We could not reproduce it and it might be a problem on Apple's side.
fix #3763
=> Fix ios cred error

app-android/app/proguard-rules.pro
=> [android] Add shrinker rules for kotlinx.serialization

app-android/app/src/main/java/de/tutao/tutanota/alarms/AlarmModel.kt, app-android/app/src/main/java/de/tutao/tutanota/alarms/AlarmNotificationEntity.kt, app-android/app/src/main/java/de/tutao/tutanota/alarms/EncryptedRepeatRule.kt
=> [android] account for nullable endValue in EncryptedRepeatRule

src/misc/RecipientsSearchModel.ts
=> Resolve recipients lazily from search dropdown

buildSrc/installerSigner.js, package-lock.json, package.json
=> [ci] upgrade js-yaml to v4.1.0

src/calendar/view/CalendarEventPopup.ts, src/gui/ThemeController.ts, src/gui/editor/HtmlEditor.ts, src/gui/styles.ts, src/gui/theme.ts, src/knowledgebase/view/KnowledgeBaseEntryView.ts, src/login/contactform/ContactFormView.ts, src/mail/editor/MailEditor.ts, src/mail/export/Bundler.ts, src/mail/press/PressReleaseEditor.ts, src/mail/signature/Signature.ts, src/mail/view/MailViewer.ts, src/mail/view/MailViewerViewModel.ts, src/misc/HtmlSanitizer.ts, src/settings/EditNotificationEmailDialog.ts, src/settings/EditSecondFactorDialog.ts, src/sharing/GroupSharingUtils.ts, src/subscription/TermsAndConditions.ts, src/subscription/giftcards/GiftCardUtils.ts, src/support/FaqModel.ts, test/tests/gui/ThemeControllerTest.ts, test/tests/mail/MailUtilsSignatureTest.ts, test/tests/mail/export/BundlerTest.ts, test/tests/misc/HtmlSanitizerTest.ts
=> Render mail body in shadow dom

src/desktop/DesktopUtils.ts, test/tests/Suite.ts, test/tests/desktop/DesktopUtilsTest.ts
=> [desktop] make deleteTutanotaTempDir handle multiple tmp subdirs

src/mail/view/MailViewer.ts
styles applied through classes set on our usual mailbody root
don't reach into the shadow root, so we wrap the sanitized mail body
in another div with these classes.
fix #4365
=> move mail-body classes into the shadow dom

src/mail/view/MailViewer.ts
touch and click handlers were attached to the wrong element
outside of shadow dom. Even when listener is set to the wrapper inside
the shadow dom event.target turns into pumpkin (shadow dom parent)
after the event loop. We handle both double tap and links by cancelling
real click events and then re-dispatching them after timeout (when we
are sure that it isn't a double-click). We changed how we dispatch it
because we don't have access to the original shadowed anchor element
anymore. Instead we just create a disposable anchor tag and to dispatch
the click event.
fix #4372
=> fix link handling in mail viewer

src/mail/view/MailViewer.ts
=> Fix setting correct attributes on synthetic anchor tag

src/misc/LanguageViewModel.ts
=> [maintenance] update privacy policy link

src/misc/passwords/PasswordGeneratorDialog.ts
=> fix not resolving translation keys in PasswordGeneratorDialog

src/gui/editor/HtmlEditor.ts, src/subscription/SubscriptionViewer.ts
=> Gui bugs 4391

src/desktop/net/ProtocolProxy.ts
We have a case for closing ephemeral sessions via beacon request and
there we have to use Blob. This seems to be the only place where we
do upload request with blob. It was not handled before (we assumed that
we have a buffer).
Now we handle both blob and bytes.
close #4398
=> [desktop] fix ProtocolProxy not handling blob uploads

src/settings/SelectMailAddressForm.ts
verifyMailAddress() was not checking whether the state is up-to-date
when switching off loading state. This is a consequence of a loose
state representation. Because of that users would see "invalid" state:
"busy" would be turned off before the actual result would show up for
the new email address.
Ideally this should be re-written as a proper state machine and
extracted into a ViewModel or similar.
fix #4403
=> Fix SelectMailAddressForm showing invalid state for a short time

app-android/app/src/main/java/de/tutao/tutanota/RemoteBridge.kt
=> [android] handle error response from native-to-web requests

android.js, app-android/app/src/main/java/de/tutao/tutanota/AndroidNativeCryptoFacade.kt, app-android/app/src/main/java/de/tutao/tutanota/MainActivity.kt, app-android/app/src/main/java/de/tutao/tutanota/push/PushNotificationService.kt, app-ios/tutanota/Sources/ViewController.swift, src/desktop/ApplicationWindow.ts, src/desktop/DesktopMain.ts, src/desktop/DesktopWindowManager.ts, src/desktop/config/ConfigKeys.ts
=> Migrate old origin localstorage

Android.Jenkinsfile, Desktop.Jenkinsfile, SqlcipherAndroid.Jenkinsfile, app-android/app/build.gradle, app-android/app/proguard-rules.pro, buildSrc/DesktopBuilder.js, buildSrc/electron-package-json-template.js, buildSrc/nativeLibraryProvider.js, jenkins-lib/util.groovy
* add new jenkinsfile for building loadable sqlcipher aar
* use it as a dependency if it's in the app-android/libs dir
close #4294
=> [android/ci] build and use android-database-sqlcipher

buildSrc/LaunchHtml.js, src/app.ts
close https://github.com/tutao/tutanota/issues/4346
=> Ignore chrome eval errors 4346

src/mail/editor/MailEditor.ts, src/mail/editor/SendMailModel.ts, src/native/main/WebCommonNativeFacade.ts
We want mailto and sharing to automatically save even if the user made no additional changes.
Fixes #4440
=> Make emails made with mailto and share w/ Android save as a draft

src/gui/base/RichTextToolbar.ts
=> re-add missing link button to the editor toolbar

src/gui/base/TextField.ts
=> change cursor on textfield labels to I-beam

src/mail/view/MailViewer.ts
=> Suppress keydown events if typing into form in mail body

src/settings/AddGroupDialog.ts, src/settings/AddUserDialog.ts, src/settings/EditAliasesFormN.ts, src/subscription/SignupForm.ts
Closes #4226 and closes #4244
Test notes are on #4226
=> Don't allow empty email addresses on signup/alias creation

src/settings/AddUserDialog.ts
=> Fix not being able to type space in new user field

src/mail/view/MailViewer.ts, src/mail/view/MailViewerViewModel.ts
=> Save all being shown should not count inline images

src/file/FileControllerNative.ts
=> Fix misleading error if cancelling attachment download

src/settings/GlobalSettingsViewer.ts
Adds refresh button and also reattempts loading audit log on expand if it did not load previously due to connection error
Closes #4172
=> Better UX for audit log on connection fail

src/settings/WhitelabelChildViewer.ts
=> Fix activated state label being inverted

app-ios/tutanota/Sources/CustomSchemeHandlers.swift, app-ios/tutanota/Sources/Files/IosFileFacade.swift, app-ios/tutanota/Sources/ViewController.swift, src/api/worker/WorkerLocator.ts, src/api/worker/facades/MailFacade.ts, test/tests/api/worker/facades/MailFacadeTest.ts
see  commit messages for details
fix #4476
fix #4361
=> fix ios attachment uploads

src/misc/TranslationKey.ts, src/settings/LoginSettingsViewer.ts, src/translations/de.ts, src/translations/de_sie.ts, src/translations/en.ts
a translations update is necessary when merging this
close #4307
=> show device encryption mode selector even when there are no saved credentials

buildSrc/releaseNotes.js
removing them is especially bothersome for ios releases.
=> [ci] don't render empty release note sections

src/calendar/view/CalendarEventEditDialog.ts, src/gui/base/TextField.ts, src/mail/editor/MailEditor.ts
fix #578
Co-authored-by: @nif-tutao
=> add button to toggle password visibility to mail editor

src/mail/view/MailView.ts
We already have a function in MailUtils for marking an array of emails as unread or read, so it makes more sense to use this function for this.
This function also checks the status of the emails before sending a request, thus we do not need to send unnecessary requests such as requesting an already read email be marked as read.
Fixes #4455
=> Have MailView use MailUtils for modifying the unread flag

src/desktop/net/ProtocolProxy.ts
we're getting errors that print only as "?" when passed to console,
this is an attempt to get a little more info.
#4504
=> add more logging to ProtocolProxy

src/RootView.ts, src/calendar/view/CalendarAgendaView.ts, src/calendar/view/CalendarMonthView.ts, src/calendar/view/MultiDayCalendarView.ts, src/contacts/view/ContactListView.ts, src/gui/HtmlUtils.ts, src/gui/ListColumnWrapper.ts, src/gui/base/Dialog.ts, src/gui/base/Dropdown.ts, src/gui/base/Label.ts, src/gui/base/Overlay.ts, src/gui/base/SnackBar.ts, src/gui/base/TextDisplayArea.ts, src/gui/base/TextField.ts, src/gui/base/ViewColumn.ts, src/gui/editor/HtmlEditor.ts, src/gui/main-styles.ts, src/gui/nav/ViewSlider.ts, src/mail/view/MailListView.ts, src/mail/view/MailViewer.ts, src/mail/view/MinimizedMailEditorOverlay.ts, src/settings/DummyTemplateListView.ts, src/settings/GroupListView.ts, src/settings/KnowledgeBaseListView.ts, src/settings/SettingsView.ts, src/settings/TemplateListView.ts, src/settings/UserListView.ts, src/settings/contactform/ContactFormListView.ts, src/support/SupportDialog.ts
* respect notches
* removed some old css hacks
=> mobile layout improvements

src/gui/editor/Editor.ts
Passing null to setFontFace will remove the font-face attribute in the editor. Therefore, if we do this for turning off preformatted text, it will remove the preformatted text.
Before, we were setting to sans-serif which is generally a different font than the default font for the editor.
Fixes #4103
=> Fix turning off preformatted text applying a different style than default in the editor

src/calendar/date/CalendarEventViewModel.ts, src/mail/editor/MailEditor.ts, src/mail/editor/SendMailModel.ts
=> Fix readding external guest not restoring password field

app-android/app/src/main/java/de/tutao/tutanota/offline/AndroidSqlCipherFacade.kt, packages/tutanota-utils/lib/Utils.ts, src/api/common/error/OfflineDbClosedError.ts, src/api/common/utils/Utils.ts, src/desktop/DesktopSqlCipher.ts, src/desktop/db/PerWindowSqlCipherFacade.ts, src/misc/ErrorHandlerImpl.ts
see commit messages
fix https://github.com/tutao/tutanota/issues/4527
=> Fix recovering sessions after offline

SqlcipherAndroid.Jenkinsfile, app-android/app/src/main/java/de/tutao/tutanota/offline/AndroidSqlCipherFacade.kt
=> Fix SQLite error on Android

src/mail/view/MailViewer.ts
=> Fix mail body issue

src/mail/view/MailViewerViewModel.ts, src/misc/ErrorReporter.ts
=> Fix issues with broken mail bodies

packages/tutanota-utils/lib/ArrayUtils.ts, packages/tutanota-utils/lib/index.ts, src/api/main/EventController.ts, src/api/worker/search/Indexer.ts, src/contacts/view/ContactView.ts, src/gui/base/List.ts, src/mail/model/MailModel.ts, src/mail/view/MailListView.ts, src/mail/view/MailViewerViewModel.ts, src/settings/EditNotificationEmailDialog.ts, src/settings/emaildomain/VerifyOwnershipPage.ts, src/subscription/giftcards/PurchaseGiftCardDialog.ts, test/tests/gui/base/ListTest.ts
=> fix wrong unread counter not being fixed

src/misc/ErrorHandlerImpl.ts
=> Fix recovering expired sessions when there's no offline

src/api/entities/gossip/ModelInfo.ts
=> model changes for version information status page

src/subscription/InvoiceAndPaymentDataPage.ts, src/subscription/InvoiceDataInput.ts, src/subscription/SwitchToBusinessInvoiceDataDialog.ts
=> Remove the invoice field on signup for private subs, #4602

src/mail/view/MailViewerHeader.ts
=> fix more recipient indicator in MailViewerHeader wrapping to two lines

src/api/worker/offline/OfflineStorage.ts, src/api/worker/rest/EphemeralCacheStorage.ts, src/sharing/view/GroupSharingDialog.ts, test/tests/api/worker/rest/EntityRestCacheTest.ts
=> Update lost group ranges 4707

src/gui/base/InfoBanner.ts
=> Fix margins for mail offline banner

src/mail/view/MailViewerHeader.ts
=> Fix invalid margins for banners in MailViewer

src/api/worker/facades/BlobFacade.ts
=> retry uploading of blobs in case of a disk failure

src/gui/base/List.ts, src/misc/TranslationKey.ts, src/translations/de.ts, src/translations/de_sie.ts, src/translations/en.ts
The "Connection lost." message is also removed since it was confusing
fix #4663
=> Rename "Try again" button to "Load more" (shown while offline)

packages/tutanota-usagetests/lib/model/Stage.ts, packages/tutanota-usagetests/lib/model/UsageTest.ts, packages/tutanota-usagetests/test/Suite.ts, src/api/entities/usage/ModelInfo.ts, src/api/entities/usage/TypeModels.js, src/api/entities/usage/TypeRefs.ts, src/api/main/MainLocator.ts, src/misc/TranslationKey.ts, src/misc/UsageTestModel.ts, src/misc/news/NewsDialog.ts, src/misc/news/items/RecoveryCodeNews.ts, src/settings/RecoverCodeDialog.ts, src/subscription/UpgradeSubscriptionPage.ts, src/translations/en.ts, test/tests/misc/UsageTestModelTest.ts
=> Recovery code news item, repeatable stages, recovery code usage test

src/misc/TranslationKey.ts, src/subscription/UpgradeConfirmPage.ts, src/translations/de.ts, src/translations/de_sie.ts, src/translations/en.ts
=> Remove recovery code from signup wizard, #4609

src/misc/news/items/RecoveryCodeNews.ts
Authored by ivk@tutao.de
fix #4768
=> Fix dynamic import in recovery code news

package-lock.json, package.json
close #4780
https://github.com/electron/electron/releases/tag/v19.1.6
https://github.com/electron/electron/releases/tag/v19.1.7
https://github.com/electron/electron/releases/tag/v19.1.8
=> Bump electron to 19.1.8

src/settings/mailaddress/MailAddressTable.ts
=> Fix non-admins being able to change sender name for disabled aliases

src/settings/mailaddress/MailAddressTable.ts
=> Prefill name in sender name dialog if nothing was set

app-android/app/build.gradle, app-android/app/src/main/AndroidManifest.xml, app-android/app/src/main/java/de/tutao/tutanota/MainActivity.kt, app-android/app/src/main/java/de/tutao/tutanota/alarms/SystemAlarmFacade.kt, app-android/app/src/main/java/de/tutao/tutanota/push/BootBroadcastReceiver.kt, app-android/app/src/main/java/de/tutao/tutanota/push/LocalNotificationsFacade.kt, app-android/app/src/main/java/de/tutao/tutanota/push/PushNotificationService.kt, app-android/app/src/main/java/de/tutao/tutanota/push/SseClient.kt, app-android/app/src/main/res/xml/data_extraction_rules.xml
=> [android] Target API 31

src/misc/news/NewsList.ts
=> Use ColumnEmptyMessageBox to indicate no news, #4747

src/misc/UsageTestModel.ts
=> Load usage test assignments immediately on opt-in

app-android/app/src/main/java/de/tutao/tutanota/AndroidFileFacade.kt, app-android/app/src/main/java/de/tutao/tutanota/push/LocalNotificationsFacade.kt, app-android/app/src/main/java/de/tutao/tutanota/push/PushNotificationService.kt
=> [android] Fix version check for creating notification channels

src/api/worker/facades/UserManagementFacade.ts, src/mail/model/MailModel.ts
Multiple clients can cause a race so we need to handle it gracefully.
fix #4800
same branch for tutadb
=> Handle an error when MailboxProperties already exists

app-ios/tutanota.xcodeproj/project.pbxproj, app-ios/tutanota.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, app-ios/tutanota/Sources/Remote/IosCommonSystemFacade.swift, app-ios/tutanota/Sources/Remote/RemoteBridge.swift
=> Remote bridge concurrency

src/settings/PasswordForm.ts, src/subscription/SignupForm.ts
=> Implement password strength usage test

packages/tutanota-usagetests/lib/model/UsageTest.ts, src/misc/UsageTestModel.ts, src/subscription/InvoiceAndPaymentDataPage.ts, src/subscription/InvoiceDataInput.ts, src/subscription/PaymentMethodInput.ts
=> Paypal usage test, credit card usage test

src/mail/view/MailViewer.ts, src/mail/view/MailViewerViewModel.ts, src/misc/HtmlSanitizer.ts
=> Change content blocking status of mail only after sanitization finished,

src/settings/login/secondfactor/SecondFactorEditDialog.ts
=> fix for webauthn error in SecondFactorEditDialog.

src/calendar/date/CalendarUtils.ts, src/calendar/view/CalendarDayEventsView.ts, src/calendar/view/CalendarMonthView.ts, src/calendar/view/MultiDayCalendarView.ts, src/gui/base/PageView.ts, src/misc/ClientDetector.ts
=> Calendar fixes

src/misc/news/items/RecoveryCodeNews.ts
=> Hide print button in RecoveryCodeNews on mobile

packages/tutanota-usagetests/lib/model/Stage.ts, packages/tutanota-usagetests/test/Suite.ts, src/settings/SelectMailAddressForm.ts, src/subscription/SignupForm.ts
=> Unavailable emails usage test

src/api/worker/search/Indexer.ts, src/api/worker/search/MailIndexer.ts, src/api/worker/search/SearchTypes.ts, src/search/SearchBar.ts, src/search/model/SearchModel.ts, src/search/view/SearchView.ts
=> 4311 fix search results not shown

src/native/main/WebCommonNativeFacade.ts
we're already getting a UserError with the correct message, just need to show it.
rethrowing the error to make the native side clean up.
close #4833
=> [ios] show message box if shared attachment size exceeds limit

buildSrc/electron-package-json-template.js
=> sign dlls for the windows apps

app-android/app/src/main/java/de/tutao/tutanota/MainActivity.kt, app-android/app/src/main/java/de/tutao/tutanota/RemoteBridge.kt
the error message may contain personal data, so we're not logging the entire error but try to extract the name of the underlying error.
close #4874
=> [android] catch error after failing to create mail editor from native.

src/mail/model/MailModel.ts
=> Do not load subfolder lists

app-ios/tutanota.xcodeproj/project.pbxproj, app-ios/tutanota/Sources/Crypto/TUTSubKeys.h, app-ios/tutanota/Sources/Crypto/TUTSubKeys.m, app-ios/tutanota/Sources/Files/FileChooser.swift, app-ios/tutanota/Sources/Utils/Swiftier.h, app-ios/tutanota/include/RsaFacade.h, app-ios/tutanota/include/TutaoAes128Facade.h, app-ios/tutanota/include/TutaoEncodingConverter.h, app-ios/tutanotaTests/CompatibilityTest.m, app-ios/tutanotaTests/TUTLogTest.m, app-ios/tutanotaTests/UIColorExtensionsTest.swift, src/settings/AboutDialog.ts
=> [maintenance] update copyright notices

app-ios/tutanota/Sources/Sharing/SharingStorage.swift
Directories have public.file-url as attachment type just like regular files. When trying to share a directory we use NSFileCoordinator that temporarily creates a zip file which we then copy to the shared storage.
fix #4834
=> fix sharing of folders on iOS

app-android/app/src/main/java/de/tutao/tutanota/AndroidFileFacade.kt, app-android/app/src/main/java/de/tutao/tutanota/AndroidNativeCryptoFacade.kt, src/desktop/DesktopNativeCryptoFacade.ts, src/desktop/net/DesktopDownloadManager.ts, test/tests/desktop/DesktopCryptoFacadeTest.ts
=> Fix native download override 4961

src/misc/ErrorHandler.ts
=> fix trying to log the stack of an undefined error

package-lock.json, package.json
Fix powershell failing command by updating electron-updater version
fix #4884
=> Update electron-updater version

src/gui/base/Expander.ts
1. Expander children wouldn't be removed until the next redraw which is not only bad for accessibility but was also influencing sizing because of the overflow
2. Expander would never clip the children anymore which we need at least for the animation but also for correct sizing when we are animating. We still need overflow sometimes so we enabled clipping only for the collapsed state.
fix #4835
=> Fix expander issues

src/calendar/view/CalendarView.ts
=> make week view header spanning a new year more clear

src/gui/HtmlUtils.ts, src/gui/base/Dropdown.ts, src/gui/base/Expander.ts, src/gui/base/Modal.ts, src/gui/base/Overlay.ts, src/gui/main-styles.ts, src/login/LoginView.ts
close #4429
Co-authored-by: wrd <wrd@tutao.de>
=> remove unneeded code related to IE11

src/gui/main-styles.ts
=> Replace instances of word-break: break-word with new, recommended style

src/gui/base/RichTextToolbar.ts
=> fix monospace tooltip not being resolved

src/RootView.ts
Previously a redraw was made after every touch or key event, setting the correct css class. Apparently redrawing breaks the button behaviour. A comment in a previous commit stated:
// It is important to not redraw at this point because click event may be lost otherwise and saved login button would not be // actually pressed. It's unclear why but preventing redraw (this way or
setting listener manually) helps.
// It's also useless to redraw for this click handler because we just want to add a global style definition.
Now the initial navigationType is still used, and then css classes are removed and added to the root element on events without requiring a redraw.
fix #4869
Co-authored-by: Willow <charlag@tutanota.com>
=> fix buggy list of notifications on ios

src/gui/base/DropDownSelector.ts, src/gui/base/TextField.ts, src/search/view/SearchView.ts
Update how TextField generates its top class
fix #5020
=> Update how TextField generates its top class

src/file/FileController.ts, src/file/FileControllerBrowser.ts
=> fix - opening/ downloading a file in browser does not work

src/api/common/mail/CommonMailUtils.ts, src/api/common/mail/FolderSystem.ts, src/api/main/MainLocator.ts, src/app.ts, src/login/ExternalLoginView.ts, src/mail/model/InboxRuleHandler.ts, src/mail/model/MailModel.ts, src/mail/view/MailGuiUtils.ts, src/mail/view/MailListView.ts, src/mail/view/MailView.ts, src/mail/view/MailViewerViewModel.ts, src/native/main/OpenMailboxHandler.ts, src/native/main/WebMobileFacade.ts, src/settings/AddInboxRuleDialog.ts
One issue with external mailbox was that the header was not given the new attributes it needs. We've converted ExternalLoginView to a proper component to help with that.
Another issue was assuming that all system folders exist for all mailboxes. We've introduced another helper to reduce the boilerplate, but we should be careful about using it.
fix #5031
=> External mailbox fixes

src/settings/ImportUsersViewer.ts
User import dialog was acknowledging that the worker side computes the progress in its own way in the comment but was ignoring that.
This commit changes it so that we use the progress from the worker again.
fix #5030
=> Fix user import progress

src/api/common/Logger.ts, src/misc/ErrorHandlerImpl.ts, src/misc/ErrorReporter.ts, src/misc/TranslationKey.ts, src/settings/AboutDialog.ts, src/translations/de.ts, src/translations/de_sie.ts, src/translations/en.ts
=> make it possible to attach log files to error reports

src/misc/ErrorHandlerImpl.ts
=> Fix error handler always ignoring errors

schemas/sys.json, schemas/tutanota.json, src/api/entities/sys/ModelInfo.ts, src/api/entities/sys/TypeModels.js, src/api/entities/sys/TypeRefs.ts, src/api/entities/tutanota/ModelInfo.ts, src/api/entities/tutanota/TypeModels.js, src/api/entities/tutanota/TypeRefs.ts, src/api/worker/crypto/CryptoFacade.ts, src/api/worker/offline/OfflineStorageMigrator.ts, src/api/worker/offline/StandardMigrations.ts, src/api/worker/offline/migrations/sys-v83.ts, test/tests/api/worker/crypto/CryptoFacadeTest.ts
see server issue 1313 and 1345
=> allow migration of legacy mails to MailDetails

src/calendar/view/CalendarViewModel.ts
=> Only process updates for calendar group in CalendarViewModel, fix #4977

src/gui/base/TextField.ts, src/login/LoginForm.ts, src/login/LoginView.ts
=> Fix prepopulate mail signup 4630

src/mail/view/MailView.ts
=> Correctly handle "Clear Folder" for custom subfolders

src/mail/view/EventBanner.ts
fix mixed case addresses preventing rendering of event response buttons
close #5079
=> Unbork events

make.js, src/desktop/net/ProtocolProxy.ts
=> Terminate json

src/api/worker/offline/OfflineStorage.ts
until now, we don't really know from the stack traces which part of the app fails to write its values to the storage.
#4958
=> add some more logging to cborg encode errors

doc/events.md, src/api/worker/rest/DefaultEntityRestCache.ts, test/tests/api/worker/rest/EntityRestCacheTest.ts
=> Delete MailDetailsBlob if Mail is deleted

src/api/common/utils/EntityUtils.ts, src/mail/model/MailUtils.ts, src/mail/view/MailGuiUtils.ts, src/mail/view/MailView.ts, src/mail/view/MobileMailActionBar.ts, src/mail/view/MultiMailViewer.ts, src/search/view/MultiSearchViewer.ts, src/search/view/SearchListView.ts, src/search/view/SearchView.ts
=> Fix shortcuts in SearchView

src/api/worker/facades/LoginFacade.ts, src/mail/view/MailViewerViewModel.ts
fix https://github.com/tutao/tutanota/issues/5122
fix https://github.com/tutao/tutanota/issues/5123
=> Fix offline issues

src/calendar/view/CalendarView.ts
=> fix wrong operator binding when deciding on date to use for new event

src/mail/view/MailView.ts, src/search/view/MultiSearchViewer.ts
=> fix wrong this binding in MultiSearchViewer action bar

src/api/common/utils/CommonCalendarUtils.ts, src/calendar/date/CalendarEventViewModel.ts, src/calendar/date/CalendarUtils.ts, src/calendar/model/CalendarModel.ts, src/mail/view/EventBanner.ts
=> make attendee check after reply button click on event case-insensitive

src/calendar/date/CalendarInvites.ts, src/mail/editor/SendMailModel.ts, src/mail/model/MailModel.ts, src/mail/model/MailUtils.ts, src/mail/view/MailGuiUtils.ts, src/mail/view/MailListView.ts, src/mail/view/MailView.ts, src/mail/view/MailViewer.ts, src/mail/view/MailViewerUtils.ts, src/mail/view/MailViewerViewModel.ts, src/search/view/SearchResultDetailsViewer.ts
Mail list that we use can either not exist anymore or just be plain invalid.
Now we handle such cases.
fix #5149
=> Fix assuming that the mail list is always there

src/mail/view/MailViewerViewModel.ts
Check that the entity event is an update event before updating the mail.
fix #5156
=> fix 404 error when deleting an email

src/contacts/ContactEditor.ts
=> Lock contact edit 
