tutao/tutanota

web/js/crypto/SecureRandom.js

Note this might cause the "SecureRandom does not have random numbers." exception to be thrown.
I think this is only currently used for generating RSA private keys. You might want to force everyone to generate new ones. I haven't tested, but I think it's rare that someone will generate a bad RSA key.

Fixed repeated random numbers

---

README.md

There is no web directory when first cloning the repository on the master branch.  You must checkout the release branch first.

correct out-of-order steps in instructions

---

src/gui/base/RichTextToolbar.js

If you hover on the "Ordered list" button in Formatting tools, a tooltip for "Unordered list" will appear. This simple commit fixes this typo.

Fixed "Ordered list" button title

---

src/gui/base/Dropdown.js
src/gui/base/DropdownN.js

Type fields in dropdowns are not automatically focused for mobile devices
Fixes #955

Add conditional for mobile in dropdown show

---

src/calendar/CalendarUtils.js
test/client/calendar/CalendarUtilsTest.js

This commit improves calendar time parsing to permit use of lower-case characters and periods in the am/pm indicators in TimePicker. It also allows omission of the colon separating hours and minutes, and the addition of spaces between the minutes and am/pm indicator. This mimics some of the behavior in other popular calendars. For example 13:14, 1314, 1:14pm, 114pm, 1:14 p.m., and 1:14 PM are all now equivalent. This can now handle the formats produced by most locales (it cannot handle some languages with non-Latin characters).
The timeStringFromParts() function has been modified to append a space and lower case "am" or "pm" when appropriate.
I added tests to the CalendarUtilsTest to verify these changes.

Address #1408, improve readability of am/pm in TimePicker. Make parseTime() more flexible and test new behavior.

---

src/contacts/ContactListView.js
src/contacts/ContactUtils.js
src/mail/MailEditor.js
src/search/SearchBarOverlay.js

Uses company name if if first and last name missing. Updates the search and sorting displays accordingly.

Fix #1511, use company name as fallback in contact list

---

buildSrc/electron-package-json-template.js
buildSrc/fix-old-uuid.nsh

Because of the change in the electron-builder the registry key format
has been changed. In certain situations there may be a registry entry
without an uninstaller file and the uninstall process failed.

Fix windows installer failing because of wrong registry key, fix #1686

---

src/calendar/CalendarModel.js

Without a default, `addDaysForRecurringEvent` will loop infinitely. This causes the application to hard crash.

Add default case to incrementByRepeatPeriod

---

src/mail/MailViewer.js

This adds a menu item in the drop down menu when viewing an email that will display the email headers. This allows users on mobile to view headers, and provides an alternative for desktop and browser users (instead of using the keyboard shortcut)

Add menu item to show headers in the dropdown menu

---

app-android/app/src/main/java/de/tutao/tutanota/Native.java
app-android/app/src/main/java/de/tutao/tutanota/alarms/AlarmNotificationsManager.java
app-android/app/src/main/java/de/tutao/tutanota/push/TutanotaNotificationsHandler.java
src/api/worker/EventBusClient.js
src/api/worker/facades/LoginFacade.js
src/api/worker/search/Indexer.js
src/api/worker/search/IndexerCore.js
src/app.js
src/calendar/CalendarAgendaView.js
src/calendar/CalendarDayEventsView.js
src/calendar/CalendarDayView.js
src/calendar/CalendarEventDialog.js
src/calendar/CalendarImporter.js
src/calendar/CalendarModel.js
src/calendar/CalendarMonthView.js
src/calendar/CalendarUtils.js
src/calendar/CalendarView.js
src/calendar/CalendarWeekView.js
src/calendar/ContinuingCalendarEventBubble.js
src/misc/WindowFacade.js
test/client/calendar/CalendarImporterTest.js
test/client/calendar/CalendarModelTest.js

For repeating events we remember time zone in which event was created
to have stable iterations across time zones. Unfortunately, this does
not work with all-day events which are supposed to be in the viewer's
time zone. When there's a daylight shift in creator's time zone viewer
may have day shifted by one. This commit makes calculation use viewer's
time zone for all-day events.
It also introduces some changes for extracting times of all-day events
to make them work with passed time zone. This is necessary for tests
and might also be helpful if we introduce "timezone override" in the
future.
Some functions from DateUtils had to be duplicated in CalendarUtils to
make them timezone-aware. We cannot make this change in DateUtils
because we don't depend on Luxon in the worker.

Fix recurring all-day events from another timezone, fix #1809

---

src/search/SearchView.js

Regression after 152846866da7c6e0d849ae454d86939c034075a8
We changed mailboxDetails stream to not have default value until it's
loaded and we don't create search view filters until it's initialized.

Do not expect search filters to exist too early, fix #1790

---

src/mail/MailEditor.js
src/mail/MailUtils.js

In case of inserting lines before/after the image we've been removing
attachment when we shouldn't have (Squire would insert it back right
away).
Another case is removing the attachment itself. We've been not removing
corresponding image element.

Fix falsely removing/not removing attachments for inline image, fix #1515

---

app-android/app/src/main/java/de/tutao/tutanota/push/PushNotificationService.java
app-android/app/src/main/java/de/tutao/tutanota/push/SseClient.java

This happened when background service was started when device is
offline. We give up on rescheduling in two cases: on too many attempts
or when being offline. We only dismissed notification in the first case
before.

[android] Fix stuck connection notification

---

flow/electron.js
src/desktop/ApplicationWindow.js
test/client/desktop/ApplicationWindowTest.js

register shortcuts on did-finish-load event to retain them after F5 reload

[desktop] fix #1828

---

flow/electron.js
src/desktop/DesktopMain.js
src/desktop/integration/DesktopIntegratorLinux.js

- Linux: add a call to `update-desktop-database` after integration when using GNOME. close #1864
- MacOs: handle mailto link events received before app.isReady. close #1877

[desktop] improve mailto handling

---

src/translations/en.js

In the context of creating a Spam rule, and in conjunction with its opposite 'Always Spam', 'Not Spam' seems more gramatically correct than 'No spam'.

Improved whitelist action translation for English language

---

app-android/app/src/main/res/values-v26/styles.xml

We cannot change navbar buttons color before API 26 but we changed
navbar color starting from API 23 because of the styles resource (we
defined it there so that system shows the right navbar color for splash
screen). This commit removes navbar color from values-v23 and defines
another style resource for API 26.

[android] Do not accidentally color navbar before API 26

---

src/desktop/ApplicationWindow.js
src/desktop/DesktopDownloadManager.js
src/desktop/IPC.js
src/file/FileController.js
test/client/desktop/DesktopDownloadManagerTest.js

electron doesn't allow us to delay asking for the path if using the 'will-download' handler.
switching over to the app logic so the blobl is already downloaded when we ask for the save path
close #1886

[desktop] handle file downloads like in the apps

---

src/mail/MailEditor.js
src/settings/EditAliasesFormN.js

This commit resolves #1844
Sections:
- User Settings > Email > Email aliases > Show email aliases
- User management > User > Email aliases > Show email aliases
- Emails > New email > Show > Sender

Sort aliases alphabetically in settings and mail editor

---

package-lock.json
package.json
src/api/main/UserController.js
test/client/desktop/DesktopUtilsTest.js

This PR is for upgrading the version of Flow from 0.77.0 to 0.80.0. No code changes were necessary, except 
1. `path` in `test/client/desktop/DesktopUtilsTest.js` had to be cast to `any` in order to edit the `sep` property--otherwise Flow complains about `sep` not being a writeable property of `path`. 
2. Flow complained that the there was a missing type annotation for the Promise returned by `deleteSessionSync()`, so the function's return type had to be annotated.

Upgrading Flow version to 0.81.0

---

buildSrc/electron-package-json-template.js
src/desktop/DesktopWindowManager.js
src/desktop/ElectronUpdater.js
test/client/desktop/ElectronUpdaterTest.js

electron-updater currently does not correctly update system-wide windows
installs on app-quit because of missing admin rights.
manually calling autoUpdater.quitAndInstall seems to correctly trigger
the UAC dialog.
To test in local network, first reproduce the problem in the following way on the master branch:
* serve `build/desktop/` directory on the local network under some url
* add the line `sign=false` to `buildSrc/electron-package-json-template.js` before the return statement
* also change `build.publish.url` from `targetUrl` to the url the build directory is served under
* build client with `node dist -w` or `node dist -we` for subsequent tries
* install client on windows machine, selecting system-wide installation.
* increment version number in `build/desktop/latest.yml`
* start …

[desktop] manually install update on quit, close #1413

---

src/gui/base/Dropdown.js

fix #1949
We invoke "show" on each resize. When field is focused and keyboard is
opened Android resizes the screen and we've been grabbing focus to the
button again.
DropdownN doesn't listen for resizes yet.

Fix filtering dropdowns on Android

---

src/calendar/CalendarView.js
src/contacts/ContactView.js
src/contacts/ContactViewer.js
src/gui/base/Button.js
src/gui/base/ButtonN.js
src/gui/base/Checkbox.js
src/gui/base/CheckboxN.js
src/gui/base/Expander.js
src/gui/base/ExpanderN.js
src/gui/base/Header.js
src/gui/base/NavButtonN.js
src/mail/MailView.js
src/mail/MailViewer.js
src/search/SearchBar.js
src/search/SearchView.js
src/settings/MailSettingsViewer.js

fix #1700
Shortcuts were duplicated because `onbeforeremove()` mithril hook is only
called when element loses its parent. If the parent is removed, hook
is not called for children. This made us miss some of the
`keyManager.unregisterShortcuts()` calls and also some of the
`removeFlash()` calls.
`onremove()` on the other hand is called each time element is removed
from the DOM (whether via parent or directly) and that's what we need
in most cases.

Fix duplicated shortcuts

---

src/login/LoginView.js

fix #1953
Before we had key handler and it tried to submit form even if it was
not visible. Now the form is submitted by `onsubmit` event which is
triggered on enter key. Without `keyManager` consuming this event buttons
receive `onkeydown` event and properly simulate click.

Fix pressing enter for selecting saved credentials

---

src/subscription/BuyOptionBox.js
src/subscription/SubscriptionSelector.js

Change the column order of the sign-up and upgrade dialog only when one-column layout is shown (e.g. mobile).

Change the column order of the subscription selector. Fix #1902

---

buildSrc/DesktopBuilder.js
buildSrc/electron-package-json-template.js
dist.js
doc/BUILDING.md
make.js
src/desktop/ElectronUpdater.js
src/desktop/config/DesktopConfigHandler.js
src/desktop/config/migrations/DesktopConfigMigrator.js
src/desktop/config/migrations/migration-0001.js
src/settings/DesktopSettingsViewer.js
test/client/desktop/ElectronUpdaterTest.js
test/client/desktop/config/migrations/DesktopConfigMigratorTest.js

adds some options to the dist.js build script:
--unpacked
disables the building of installers (dir target for all platforms)
--out-dir \<outDir\>
move the built installers (or dirs) into the path outDir after building.
Defaults to build/desktop and build/desktop-test
--custom-release
disable autoUpdate in the release target by not including an update url.
disable building of the test client.

[desktop] add builds w/o auto-updates and unpacked builds, close #1857

---

flow/electron.js
src/desktop/ApplicationWindow.js
src/desktop/DesktopWindowManager.js
test/client/desktop/ApplicationWindowTest.js
test/client/desktop/DesktopWindowManagerTest.js

this fix will clear the dock icon badge on mac when **any**
window is focused (including newly created), in addition to
the "activate" callback that's already on the app object
(see DesktopMain.js).

[desktop] clear dock badge on each window focus, close #1971

---

flow/api/types.js
flow/electron.js
src/desktop/ApplicationWindow.js
src/desktop/DesktopContextMenu.js
src/desktop/DesktopWindowManager.js
src/desktop/IPC.js
src/desktop/Socketeer.js
src/desktop/preload.js
src/gui/main-styles.js
test/client/desktop/ApplicationWindowTest.js
test/client/desktop/DesktopWindowManagerTest.js

also close #1620 since the new ipc api is essentially what we're doing, only not fully bidirectional.

[desktop] reduce API surface of preload script after it has run

---

src/desktop/DesktopMain.js
src/desktop/DesktopUtils.js
src/desktop/ElectronUpdater.js
test/client/desktop/ElectronUpdaterTest.js

- users will now be notified of an update failure after the 5th error
- update checks now implement random exponential backoff
- different versions of the app can now steal the single instance lock
from each other, terminating the already running instance

[desktop] improve update error handling and single instance lock, #2032

---

src/api/common/TutanotaConstants.js
src/calendar/CalendarUtils.js
src/settings/AppearanceSettingsViewer.js

- add the ability to display calendar with Saturday being the first day of the week
- rename firstDayOfWeekFromSundayOffset to firstDayOfWeekFromOffset for clarity as Saturday can be an offset
- add Saturday as an option in the Appearance Settings
- add comment to clarify how names of the days are generated

Add Saturday to week start options - Fix #1941

---

src/settings/MailSettingsViewer.js

Tested:
1. Send an email using the default sender X from Tutanota account A to Tutanota account B
2. Verify in account B that it was received and showing the correct default address X of account A
3. Change the default sender of account A now in "Settings/Email/Sending addresses/Default sender" to email address Y
4. Send a 2nd email using the new default sender Y from account A to account B
5. Verify in account B that the email was received and is showing the new default address Y of acccount A

Sort default sender list alphabetically - fix tutao/tutanota#2017

---

src/login/SecondFactorHandler.js

fix #1792
We fixed this issue before for Firefox in 0edfcf3 but turns out that
Firefox and Chrome return different error codes on timeout: Firefox 1
(OTHER_ERROR), Chrome 4 (DEVICE_INELIGIBLE) and neither is really
correct as it should be 5 (TIMEOUT). This commit also silences
DEVICE_INELIGIBLE if the dialog is already hidden.

Fix late U2F error dialog shown after login was accepted

---

src/desktop/DesktopMain.js
src/desktop/DesktopMonkeyPatch.js
src/desktop/DesktopUtils.js
src/desktop/sse/DesktopSseClient.js

will write the desktop logs to
app.getPath('userData')+'/logs/' + tutanota_desktop.log
on quit, renaming any old logfile to tutanota_desktop_old.log

[desktop] write logs to disk on process exit, close #2061

---

src/mail/MailViewer.js

Looks like this argument is redundant now. It's only ever called with `false`, so it can safely be removed and the code can be simplified slightly

Remove redundant argument in actionButtons

---

src/desktop/DesktopUtils.js
test/client/desktop/DesktopUtilsTest.js

checks each attachment file name against a number of regexes, preventing
saving of files with names that
* contain illegal characters (unicode control characters, <>?/\ )
* have trailing periods on windows
* are reserved on the current platform (CON, CON.txt, .., .)
invalid characters are replaced with underscores while reserved names
are treated as if the file with the reserved name already exists in the
target directory, adding a suffix number: CON.txt -> CON-1.txt

[desktop] prevent saving of attachments with invalid names, close #2063

---

src/gui/base/ViewSlider.js

When two columns are visible and the second one is focused, the didn't
check for drawer gesture correctly

Fix back gesture when two columns are visible, fix #626

---

src/desktop/ApplicationWindow.js
src/desktop/DesktopContextMenu.js
src/desktop/DesktopWindowManager.js
test/client/Suite.js
test/client/desktop/ApplicationWindowTest.js
test/client/desktop/DesktopContextMenuTest.js

BrowserWindow arg to the handler will be undefined if no window is open.
Since context menu actions make no sense without context, the click
handlers should noop in this case.

let context menu click noop if webContents is unavailable, fix #2112

---

src/calendar/CalendarMonthView.js
src/calendar/CalendarWeekView.js

Provides a fix for issue #1780

Only display week number if the week is configured to begin on Monday, fix #1780

---

src/desktop/ApplicationWindow.js
src/desktop/preload.js
test/client/desktop/ApplicationWindowTest.js

There seems to be an issue that prevents the wheel listener that's set in the initial execution of the preload script from receiving WheelEvents that were not dispatched manually.
If the listener is attached after the web app has initialized, the problem doesn't occur.
fix #2165

[desktop] use 'wheel' event instead of window.onmousewheel

---

app-android/app/src/main/java/de/tutao/tutanota/MainActivity.java

fix #2247
Toast on bg thread was causing exception. We shouldn't even show it
there because files without text is a normal case e.g. when only photo
is sent from a gallery app.

[android] Fix sharing

---

src/api/worker/SuspensionHandler.js
src/calendar/CalendarUpdateDistributor.js
src/mail/MailEditorN.js
src/mail/MailEditorViewModel.js
src/mail/MailView.js
src/mail/MailViewer.js
src/mail/SendMailModel.js
src/misc/ErrorHandlerImpl.js
src/settings/AboutDialog.js
test/api/worker/SuspensionHandlerTest.js

When resolving deferred requests in the suspension handler, errors still need to be handled internally even if theyre being caught by the original caller, because Promise.each waits for them to be resolved and will error out otherwise. For example, there are cases like when loading UserGroupRoot where the call to load expects the possibility of a NotFoundError, but the SuspensionHandler itself was still throwing an unhandled exception

Handle exceptions when resolving deferred promises in suspension handler

---

src/serviceworker/sw.js

Init function was not invoked when env was not present and we never
actually set the env. It happened in a4a6caa when only one half of
the condition was inverted.
fix #2383

Fix activating service worker

---

src/gui/base/Editor.js

https://html.spec.whatwg.org/multipage/interaction.html#sequential-focus-navigation
If a focusable area is omitted from the sequential
focus navigation order of its Document, then it is
unreachable via sequential focus navigation.
fix #2394
fix #2380

add tabindex 0 to editor component

---

src/api/common/utils/MapUtils.js
src/api/worker/search/IndexUtils.js
src/calendar/CalendarEventViewModel.js
test/client/calendar/CalendarEventViewModelTest.js

We pick the default sender from the inviteModel to use as the default organizer when inviting guests, and allow setting organizer by "inviting" yourself

Calendar invite organizer fixes

---

src/api/main/UserController.js

`navigator.sendBeacon` sets `Content-Type: text/plain` if passed a
string. Using `Blob` it uses the blobs type for the header (see
https://codereview.chromium.org/996143002 for chromium and
https://stackoverflow.com/questions/40523469/navigator-sendbeacon-to-pass-header-information)
Should help for some blocked content types returning `415` errors, fixes #2391
* Make sure you are using HTTPS, Beacons are disabled for HTTP
* Login to the client without saving a session. Sessions are not closed for saved credentials
* To get a log of the beacon on closing a tab in firefox go to `about:networking` -> Logging and set the logging modules to `timestamp,nsHttp:3` to log the http headers.

Set Beacon content type header

---

src/mail/SendMailModel.js

Fixes #2379. It was probably a typo, since there was code for restoring the sender address. It just didn't set it since the parameter key used was "sender" instead of the expected "senderMailAddress" thus it defaulted to the default address.

Restore the address properly (fixes #2379)

---

src/gui/base/BubbleTextField.js
src/gui/base/TextField.js
src/gui/base/TextFieldN.js
src/misc/KeyManager.js

This fixes #2427 by using onkeypress instead of onkeydown, which lets us intercept keys while knowing the actual value of the character being inserted.
I tested this by changing my system's keyboard layout to one that doesn't have the U.S. comma key code correspond to a comma.

Handle commas for BubbleTextField (fixes #2427)

---

src/settings/EditSecondFactorsForm.js

On whitelabel domain not only remove the link to 2fa but also 'more info' line
fixes #2448

Remove 'More info' line if on whitelabel domain

---

src/settings/EditAliasesFormN.js

This fixes #1919 by navigating to the subscriptions folder and bringing up alias options.

Redirect to buying aliases when OK is selected (fixes #1919)

---

src/gui/base/TextFieldN.js

This is not needed anymore with current mithril, from our observation.

Remove workaround for password field on older mithril

---

src/settings/LoginSettingsViewer.js
src/settings/SettingsView.js

When refreshing from the settings view, we try to get the UserController in some of the component view functions after we've logged out, leading to a failed assertNotNull, so we now check if there is a UserController to be gotten before trying to get it
close #2403

Add isUserLoggedIn check before calls to getUserController

---

src/api/Env.js
src/mail/MailEditorN.js

Fixes #2423 by changing the listener to do nothing but still trigger if the tab is closed when on browser, allowing the user the option to not close the tab if they are unsure without closing the editor regardless of their choice.

Don't close the mail editor if tab is not closed (fix #2423)

---

src/mail/MailViewer.js

This resolves #1710 by ignoring "inherit" color properties when we're using a dark theme and need to check if we need a light background, instead.
Before:
After:

Ignore "inherit" color when determining if white background is needed (fixes #1710)

---

.vscode/extensions.json
.vscode/settings.json

When the project repository is opened up in VSCode, a bunch of `flow` errors start showing up as seen in the following screenshot:
This PR fixes these errors by doing two things:
1. Recommend installing a VSCode specific [extension](https://marketplace.visualstudio.com/items?itemName=flowtype.flow-for-vscode) that supports Flow typings throw an [`extensions.json`](https://code.visualstudio.com/docs/editor/extension-gallery#_workspace-recommended-extensions) file.
2. Disable JavaScript validation as mentioned on the official [`flowtype` README](https://github.com/flowtype/flow-for-vscode#setup) by adding a `settings.json` file.
Please note that these additions are specific to VSCode only and should not interfere with other editors.

fix: VSCode flow errors

---

src/calendar/CalendarEventPopup.js

Adds `E` to edit and `Delete` to delete a calendar event from the popup.
Fixes #2552

Add calendar event popup shortcuts

---

src/api/common/Logger.js

Easy way out. We loose the logs about the whole object, but should be
lighter than c1ea9f94bf.
fix #2184
see https://github.com/tutao/tutanota/issues/2562#issuecomment-753990738_

Do not produce error when logging cyclic objects

---

src/search/SearchBar.js

Prevents from expanding the search bar again after closing when changing views (E-Mail, Calendar, Contacts)
closes #2534

Unset search bars lastQuery on close

---

src/mail/SendMailModel.js

When editing a draft in trash or spam folder and saving changes, save it as new draft in the drafts folder instead of just saving in trash/spam.
fix #2535

Create new drafts when editing trash/spam

---

src/RootView.js

somehow doing "onmousedown = null" didn't disable the onmousedown code, added a bool check to fix
closes #2486

fix "disabling outline" being console logged infinitely, fix #2486

---

src/gui/main-styles.js

this was broken by a change i'd made earlier to not print the folder column in the mobile layout. Reminder to try to be more specific with css classes fixes #2478

Fix printing of email sender and recipients

---

src/misc/ClientDetector.js
test/client/common/ClientDetectorTest.js

see #2069, close #1861
This should be a safe change as date formatting didn't properly work
with Chrome 55 anyway (see #1861) which was breaking the app.
This is a first step of requiring modern browser versions.

Bump minimum Chrome version to 56

---

src/contacts/VCardImporter.js
test/client/contact/VCardImporterTest.js

RFC-compliant vcards do not contain `CHARSET` parameter at all anymore.
Charset can only be set via MIME type on the vcard itself, see https://tools.ietf.org/html/rfc6350#section-3.1 and this errata https://www.rfc-editor.org/errata/eid3199 which removes the `CHARSET` reference. Apparently, there is some confusion and i don't know if this RFC is respected anyways.
We should still support, but in case no charset is given i think it will be sensible to assume standard compliance.
Also adds a test case based on #2572 
fix #2572

Assume UTF-8 charset for vcard imports

---

src/api/common/utils/FileUtils.js
src/desktop/DesktopUtils.js
src/desktop/PathUtils.js
src/file/FileController.js

fix #2637
`legalizeFilenames` is in `/src/desktop/PathUtils`, is that going to be a problem for dependencies?

Use legalizeFilename to preserve duplicate files

---

resources/scripts/after-install.sh

The systemctl command is named quite misunderstandably, the man page is
clearer:
try-reload-or-restart PATTERN...
Reload one or more units if they support it. If not, stop and then
start them instead. *This does nothing if the units are not running.*

Do not try to reload tutadb service if not running

---

buildSrc/Builder.js
buildSrc/electron-package-json-template.js
flow/api/types.js
flow/electron.js
flow/libs.js
package-lock.json
src/app.js
src/desktop/ApplicationWindow.js
src/desktop/DesktopWindowManager.js
src/desktop/IPC.js
src/desktop/Socketeer.js
src/desktop/electron-localshortcut/LocalShortcut.js
src/desktop/preload.js
src/gui/SearchInPageOverlay.js
src/misc/WindowFacade.js
src/native/common/NativeWrapper.js
src/native/main/NativeWrapperCommands.js
test/client/desktop/ApplicationWindowTest.js
test/client/desktop/IPCTest.js

The preload script required some access to the window object of the renderer
thread to implement browser functionality that's missing in a BrowserWindow.
This prevented use of the contextI isolation option.
This commit moves that functionality from the preload script to either the main
thread or the web app so we can enable context isolation.
* mouse wheel zoom was moved to the main thread, listening to the new
zoom-changed event on WebContents (ApplicationWindow.js)
* url reveal on hover was split into a main part listening on update-target-url
on WebContent (ApplicationWindow.js) and a new NativeWrapperCommand to fill in
the url element
* the fix for MacOS navigation history when trying to navigate a text box with
cmd+arrows moved to WindowFacade.js
* the SearchPageOverlay now fixes the …

[desktop] enable context isolation for all BrowserWindows

---

src/desktop/ApplicationWindow.js
src/desktop/IPC.js
src/desktop/preload.js
src/native/common/NativeWrapper.js
test/client/desktop/ApplicationWindowTest.js
test/client/desktop/IPCTest.js

remove the need to stringify message objects for passing
through IPC and the executeJavaScript() call for
the main->renderer direction.
electron is taking care of the context isolation
fix #2712

[desktop] pass js objects over IPC instead of strings

---

package-lock.json
package.json
src/desktop/DesktopUtils.js

the changes to oxmsg include:
- add CLSID to exported .msg files so that outlook knows how to handle them
- changes to the public api to which i have adapted

update oxmsg version and adapt to changes, close #2727

---

src/api/common/utils/BirthdayUtils.js
src/contacts/VCardImporter.js
src/contacts/model/ContactUtils.js
src/contacts/view/ContactViewer.js

Incorrect birthdays are now silently not imported. Surprisingly, not
handling the exception broke the whole UI.
The vcard importer probably needs a rewrite as real parser.
fix #2708

Handle birthday parse exceptions

---

src/gui/base/TextFieldN.js

fixes #2776
I decided not to check if injectionsLeft actually renders a child or children for moving the label out of the base position, because it would make the code more complicated (different types) and for injectionsLeft of TextFieldN is only used in the out of office notification dialog.
The old-style text field component has not been updated.

move textfield label if injectionsLeft is defined

---

src/desktop/DesktopDownloadManager.js
src/desktop/DesktopFileExport.js
src/desktop/DesktopMain.js
src/desktop/DesktopUtils.js
src/desktop/IPC.js
src/login/LoginViewController.js
test/client/desktop/DesktopDownloadManagerTest.js

We do it at startup because on windows we won't receive before-quit, will-quit or quit events when the user shuts down or logs out without quitting the app first.
this commit also has some consolidation of tmp dir usage and minor tidying up
close #2770

clear up temporary directory on startup and quit

---

src/api/worker/search/EventQueue.js
test/api/worker/search/EventQueueTest.js

In case of DELETE we have been removing all the batches between it and
previous DELETE/MOVE. We did not add the new DELETE because the old
one should be enough. However those operations inbetween can still be
"latest for entity", even if they are empty and since we don't add a
new DELETE to the queue we wouldn't operate latest entry in the map.
This commit sets previous batch as the latest one instead of the
removed batch
fix #2648

Fix "batch does not have events for" error

---

src/api/worker/search/EventQueue.js
test/api/worker/search/EventQueueTest.js

96b4ed7 introduced a fix for the DELETE-CREATE-DELETE-CREATE case in
EventQueue optimization. However it used the wrong index to set
lastOperationForEntity. This commit sets it only when we have to and
with the right index.
fix #2648

Fix DELETE-CREATE combo in EventQueue again

---

src/api/worker/search/SearchFacade.js

_reduceToUniqueElementIds step already performs deduplication for
search but we have only merged results afterwards.
Now we pass actual existing results to the function so that they get
properly deduplicated and merged.
fix #2243

Prevent duplicate contact suggestion

---

src/desktop/DesktopWindowManager.js

WebContentsEvent.sender.id and BrowswerWindow.id can be different. This fix uses an electron API method to get the correct window for the WebContentsEvent.

get correct browser window id from WebContentsEvent, fixes #2766

---

flow/electron.js
src/desktop/ElectronUpdater.js
test/client/desktop/ElectronUpdaterTest.js

This commit does two things:
- it re-enables wizard for auto-update on Windows. We need it to
successfully update system-wide.
- it disables update-on-quit behavior on Windows because wizard in
that case in unexpected.
fix #1413

[desktop] Fix updating system-wide Windows installation

---

src/mail/view/MailView.js

See the comment at https://mithril.js.org/route.html#routeresolveronmatch about `m.route.get()` not being set yet during the `onmatch` call.
fix #2840

Fix opening mailto links for dist builds

---

src/misc/U2fClient.js

the iframe used for u2f fails to load properly in electron, which
messed up the delivery of IPC message responses.
fix #2766

[desktop] prevent desktop client from testing u2f support

---

src/calendar/view/CalendarEventPopup.js
src/calendar/view/CalendarView.js

fix #2824
Upon the first calendar event popup being opened, if the html sanitizer had not already been loaded at some point during the session, then it's loading would not be done before the first view call of the event preview. Since the dropdown size is based on the size of the inner html, it would mismatched because we had yet to sanitize the description and insert it in the popup

Preload HtmlSanitizer and pass it into CalendarEventPopup

---

src/api/common/utils/Utils.js
src/calendar/view/CalendarEventPopup.js
src/calendar/view/EventPreviewView.js
src/gui/base/Modal.js
src/mail/export/Exporter.js

This pull request does things:
- Stops modal components from having backgroundClick called on them when they were the target of the click, so that the calendar event view popup can be clicked on without it going away.
- Make the text in the calendar event popup selectable, and make the location field clickable
in regards to the location field, if the field looks like a link then we will treat it as a link, otherwise it will link to OpenStreetMap. The URL detection could be improved maybe. I have a regex that's a bit more conservative about detecting possible URLs, but it seems like using inbuilt URL handling should be a safe bet here

Improve functionality of CalendarEventPopup

---

src/calendar/CalendarEventViewModel.js
src/calendar/CalendarUtils.js
src/calendar/view/CalendarEventPopup.js
test/client/calendar/CalendarUtilsTest.js

fix #2741
Outlook has special format for links and it is removed by our
sanitizer. We try to find such places and replace them with proper
HTML.

Fix broken links for invites from Outlook

---

src/desktop/ApplicationWindow.js
src/desktop/PathUtils.js
test/client/desktop/ApplicationWindowTest.js
test/client/desktop/PathUtilsTest.js

the function is used to produce a url (that can be extended with query parameters) to the desktop start file instead of a file path.
fix #2791

[desktop] use node.js url.pathToFileURL

---

src/api/common/TutanotaConstants.js
src/settings/CheckDomainDnsStatusDialog.js
src/settings/DomainDnsStatus.js
src/settings/emaildomain/AddDomainWizard.js
src/settings/emaildomain/VerifyDnsRecordsPage.js
src/translations/en.js

After a discussion with @jowlo we decided not to make the change on the server but on the client. I also did some refactoring to have a single view for DNS records now.
fixes #2820 and fixes #2877

use single view for DNS records, display dot at the end of CNAME and MX record values

---

src/calendar/view/CalendarDayEventsView.js

fix #2847
We use clientWidth instead of scrollWidth of the columns, because scrollWidth includes overflow, meaning that its the max of either the width of the column or of it's widest element, meaning the bubbles wouldn't be able to become narrower

fix horizontal overflow of event bubbles in week view

---

src/search/SearchBar.js

Fix #2933 
First commit:
SearchBar forces another search when it thinks that the indexing
finished however it was not checking whether the indexing failed. So if
the indexing failed somewhere in the middle it would retry again and
again.
Second commit:
We have not been unsubscribing from locator.search.indexState so it
would hold a reference to the old searchBar when it's not rendered.

Fix looping index

---

src/calendar/export/CalendarImporter.js

fix #2910
We also have to remove double quotes as they are not allowed inside of param-value type properties

Wrap event attendee names in double quotes when exporting calendars

---

src/gui/base/DropdownN.js
src/gui/base/GuiUtils.js
src/mail/view/MailGuiUtils.js
src/mail/view/MailViewer.js

fix #2925
Also, change the positioning handling for the dropdown, so that it appears underneath the mouse, rather than below the image element
Also also, rename DropDownChildAttrs to DropdownChildAttrs for consistency's sake

Add option to just download inline images on long press

---

src/calendar/view/EventPreviewView.js

fix #2899
long titles will now be wrapped, long locations are cut off with ellipsis (as they were before). Also included is adding noopener and noreferrer to the location link

fix overflowing event title and location

---

src/mail/editor/MailEditor.js

Add <kbd>Ctrl</kbd>+<kbd>Enter</kbd> as a shortcut to send mails while in the mail editor view
See [reddit](https://www.reddit.com/r/tutanota/comments/n62p81/feature_request_shortcut_to_send_current_email/) or common expectations (like here on github)

Add ctrl-enter as send shortcut

---

src/mail/editor/MailEditor.js
src/templates/view/TemplatePopup.js

For now we will not have templates enable in the apps. We may choose to add it later but it would require further changes to/an alternate version of the template popup as it is not suited for mobile

Disable template popup in mobile

---

src/calendar/view/CalendarEventEditDialog.js
src/gui/base/BubbleTextField.js
src/gui/base/Expander.js
src/mail/editor/MailEditor.js
src/mail/editor/MailEditorViewModel.js
src/sharing/view/GroupSharingDialog.js

resolves #2949
I decided to make the suggestions dropdown with position `absolute` so that it does not move around when scrolling (as it would the case with `fixed`). I decided not to put position 'relative' to the parent element, i.e. the BubbleTextField for the following reason:
In some use cases there is an ancestor element with overflow set to `hidden` which means the dropdown would not be shown. However, we avoid this problem by putting position `relative` on a parent of the overflow-hidden element.

show suggestions for bubble text field in overlay dropdown

---

src/app.js
src/calendar/CalendarUpdateDistributor.js
src/gui/styles.js
src/gui/theme.js
src/login/LoginView.js
src/login/LoginViewController.js
src/misc/DeviceConfig.js
src/settings/AppearanceSettingsViewer.js
src/settings/EditCustomColorsDialog.js
src/settings/whitelabel/WhitelabelSettingsViewer.js

We were managing themes via top level functions that operate on globals, which was confusing and error prone. Now we have a single point of access
We keep the global theme singleton for convenience
fix #3030

Create global theme management singleton

---

src/calendar/CalendarUpdateDistributor.js
src/calendar/export/CalendarParser.js
src/mail/editor/SendMailModel.js
test/client/calendar/CalendarEventViewModelTest.js

closes  #2975
I decided to ignore incorrectly formatted attendee and organizer mail addresses during calendar imports because we already ignore certain attendees and organizers when importing calendars. The alternative to allow invalid addresses would mean that we would have to check for validity of each address in many places and omission to do so might lead to more bugs.
Also, this PR fixes RecipientsNotFoundError handling of non-existing tutanota addresses in calendar events. It is now possible to delete such events or remove the incorrect addresses from the list of attendees. However, sending out updates for such events will still show an error dialog that mentions the invalid attendee addresses. So in this case the user has to manually cleanup by deleting the respective addresses (or …

validate mail addresses during event import and handle RecipientsNotFoundError for calendar events

---

src/calendar/view/EventPreviewView.js
src/gui/main-styles.js

We now will show up to two lines of text for the title, and any more will be scrollable.
Also, disable horizontal scrolling for the description field and use `word-wrap: break-word` instead. 
fix #2899

fix display of large event names in preview

---

Jenkinsfile
buildSrc/Builder.js
buildSrc/DesktopBuilder.js
buildSrc/RollupConfig.js
buildSrc/RollupPlugins.js
buildSrc/compileKeytar.js
buildSrc/electron-package-json-template.js
package-lock.json
package.json

Make sure to also run each built artifact. If something is wrong with keytar, there should be an error message right on startup of the app. 
closes #2582

Build keytar on our own

---

flow/electron.js
src/desktop/ApplicationWindow.js
src/desktop/DesktopDownloadManager.js
src/desktop/DesktopUtils.js
src/desktop/DesktopWindowManager.js
src/desktop/IPC.js
src/desktop/config/DesktopConfig.js
test/client/desktop/ApplicationWindowTest.js

add override of electrons' per-url zoom factor retention
electron started to exhibit chromiums' zoom factor retention
which is saved in electron.app.getPath('userData')/Preferences
* %APPDATA%/tutanota-desktop/Preferences on win32
* ~/.config/tutanota-desktop/Preferences on linux
* ~/Library/Application Support/tutanota-desktop/Preferences on darwin
this conflicts with our own zoom handling logic.
it is saved per url and at different times apparently depending
on things like whether a window is open at the time of shutdown
or not.
this commit overrides this behaviour by maintaining the current
zoom factor in the window manager and resetting it whenever
any WebContents navigated.
also reduces the step size of scale adjustment from 10% to 5%.
fix #2917, #2317

add override of electrons' per-url zoom factor retention

---

src/gui/base/ViewSlider.js
src/mail/view/MailView.js
src/mail/view/MailViewer.js
src/search/view/SearchResultDetailsViewer.js

This avoids big frame losses by separating re-layouts. ViewSlider
animations trigger layout and showing/scaling mail body does too.

Defer rendering mail body until viewSlider animation is over.

---

src/mail/editor/MailEditorViewModel.js
src/native/common/FileApp.js

Promise.prototype.map() was replaced by Array.prototype.map() and was
not type-checked.
fix #3138

Fix attaching files on mobile

---

flow/core_missing.js
src/api/common/utils/Utils.js
src/misc/ClientDetector.js
src/misc/DeviceConfig.js
src/serviceworker/ServiceWorkerClient.js

We handle SecurityErrors when trying to register the ServiceWorker, as these can be thrown when specific browser settings are enabled
fix #3107

Handle SecurityError when using ServiceWorker and localStorage

---

src/misc/ClientDetector.js

If `dom.storage.enabled` is set to false in `about:config` then localStorage will be `null` rather than `undefined`
fix #3122

allow loading client when localStorage was disabled in about:config

---

src/mail/editor/MailEditor.js

This will now focus the editor whenever you toggle the formatting
toolbar, even if the editor wasn't already focused. This is
most likely what you want 9 times out of 10 anyway.
fix #3036

Don't focus subject bar when toggling formatting toolbar

---

.github/workflows/test.yml
buildSrc/BuildServer.js
buildSrc/DesktopBuilder.js
dist.js
package-lock.json
package.json
test/client/calendar/CalendarEventViewModelTest.js

- pin electron-builder to v22.11.4 because of incompatibilities with node 16 https://github.com/electron-userland/electron-builder/issues/5668
- use fs.rm instead of fs.rmdir because of deprecation
- fetch prebuild keytar if cross-platform build is detected
close #3196

[desktop] fix cross-platform build failures

---

src/mail/view/MailGuiUtils.js

`filter` returns an empty array, which is truthy, so the old implementation just returned a clone of the original array.

Fix attachments of response #3252

---

dist.js

We already generate the translation chunks as "translation-xx-xxxxx.js", so we don't have to then append "translation" to the front. When generating `sw.js` we tell it to add the file beginning with "translation-en" to it's list of files to cache, which doesn't exist because all of the translation files begin with "translation-translation"
fix #3268

[build] don't prepend "translation" to translation chunks

---

src/api/worker/search/EventQueue.js

We "move" the CustomerInfo between the free and premium CustomerInfo lists in the SwitchAccountTypeService. Therefore the event queue must be able to handle the case that the customer info has been updated after being moved
fix #3248

Designate CustomerInfo as a movable entity type

---

src/gui/base/Dialog.js
src/mail/view/MailGuiUtils.js

Until now we hard code the enter key to trigger confirmation in a confirmation dialog regardless of which button is selected. Sometimes this isn't ideal as you don't want it to be too easy to do dangerous operations, so I've added functionality that can opt in to disable it. I would also be for just disabling it always
fix #3200

don't permanently delete mail when hitting enter key

---

flow/libs.js
src/app.js
src/calendar/view/CalendarMonthView.js
src/contacts/ContactAggregateEditor.js
src/gui/base/BubbleTextField.js
src/gui/base/Dialog.js
src/gui/base/Header.js
src/gui/base/MultiSelectionBar.js
src/gui/base/NotificationOverlay.js
src/gui/base/Overlay.js
src/gui/base/ViewColumn.js
src/gui/base/ViewSlider.js
src/gui/base/ViewSliderN.js
src/gui/date/DatePicker.js
src/gui/dialogs/ShortcutDialog.js
src/login/LoginViewController.js
src/mail/view/MailListView.js
src/misc/KeyManager.js
src/search/SearchBar.js
src/serviceworker/ServiceWorkerClient.js
src/settings/SettingsView.js
src/sharing/view/GroupSharingDialog.js
src/subscription/BuyOptionBox.js
src/subscription/SubscriptionUtils.js
src/subscription/SwitchSubscriptionDialog.js
src/subscription/UpgradeSubscriptionPage.js
src/support/SupportDialog.js

makes sure that lifecycle methods on mithril component classes don't return promises to make issues like #3225 less likely
lifecycle methods passed to m on plain objects are not checked yet

remove old Component type, separate f1 help gui from keymanager

---

src/desktop/DesktopWindowManager.js
src/settings/DesktopSettingsViewer.js

electron handles spellchecking through native apis on mac, so we don't need to any configuration of our own
fix #3251

don't handle spellchecking on mac ourselves

---

src/gui/date/DatePicker.js
src/gui/date/DatePickerDialog.js

fix #3110
If one of the date fields was empty we were showing "unlimited", but it would actually be interpreted as "whatever it already is" now we only show "unlimited" when the user actually has indexed their entire mailbox

show current index date when field is empty in DatePickerDialog

---

app-ios/tutanota/Sources/Files/TUTFileUtil.m
app-ios/tutanota/Sources/TUTAlarmManager.m

We call `TUTUserPreferenceFacade.storeAlarms` in a loop, which calls `NSJSONSerialization.dataWithJSONObject`, which for some reason isn't releasing everything it allocates.
So we now only call `storeAlarms` once after scheduling/unscheduling all the new notifications.
also it goes way more faster now
fix #3363

[ios] fix memory leak when scheduling alarms

---

src/api/common/RecipientInfo.js
src/api/main/WorkerClient.js
src/api/worker/facades/MailFacade.js
src/login/contactform/ContactFormRequestDialog.js
src/mail/editor/SendMailModel.js
src/mail/model/MailUtils.js
src/misc/ErrorHandlerImpl.js

This turned out to be fairly large. We pass RecipientInfos, which may have Promises inside of them, over the worker boundary. This is no good, but for some reason worked when we had bluebird, but not anymore
This commit also contains some refactorings to use async/await
fix #3399

don't send promises over the worker saving/updating/sending drafts

---

src/api/worker/EventBusClient.js

Check for socket in _close() was broken with Flow update (it was
checking if socket is a function which is never the case). This code is
not needed because the function is stubbed in tests anyway.
fix #3411

Fix reconnecting websocket

---

src/desktop/ApplicationWindow.js
src/desktop/IPC.js
src/gui/SearchInPageOverlay.js
src/native/main/NativeWrapperCommands.js

* handle CancelledError as an expected error
* log other rejections
* return null in any rejection case and for no results instead of mock result object
* 
close #3362

[desktop] properly handle findInPage rejections

---

src/api/common/utils/Utils.js
src/api/main/LoginController.js
src/api/main/UserController.js
src/gui/base/GuiUtils.js
src/gui/base/InfoBanner.js
src/login/LoginViewController.js
src/mail/view/MailViewer.js
src/settings/DesktopSettingsViewer.js
src/settings/EditSecondFactorsForm.js
src/settings/LoginSettingsViewer.js
src/settings/SettingsExpander.js

fix #3150
This makes sure that the logged in user is either not in whitelabel mode or a global admin before displaying most `tutanota.com` links.
Another improvement would be disabling the FAQ search completely, since all those will come from our domain. This would make #3182 unnecessary.

remove tutanota links for non-admin whitelabel users

---

flow/electron.js
package-lock.json
package.json
src/desktop/ApplicationWindow.js
test/client/desktop/ApplicationWindowTest.js

The only breaking change in 12 and 13 which affects us is that
new-window event is deprecated. I also copied some missing type
definitions for Electron.
Close #3348

Update Electron to 13.3.0

---

src/gui/ScrollSelectList.js
src/templates/model/TemplatePopupModel.js
src/templates/view/TemplatePopup.js

use element.scrollIntoView function instead of manual positioning, fix scrolling after filtering templates, fixes #3229

fix scrolling in template list after filtering

---

src/api/common/utils/ArrayUtils.js
src/gui/base/List.js
src/search/SearchBar.js
src/search/model/SearchModel.js
src/search/view/SearchListView.js
src/search/view/SearchView.js

if we try to search again for the exact same query, then we will just return the promise from the previous search query.
Will need to be confirmed that this is the right way to go by someone who groks the search implementation
fix #1972

fix search list duplication

---

src/api/common/Logger.js
src/api/common/utils/ArrayUtils.js
src/desktop/DesktopMonkeyPatch.js
src/desktop/DeviceKeyProviderImpl.js
src/desktop/config/ConfigFile.js
src/desktop/config/DesktopConfig.js
src/desktop/sse/DesktopSseClient.js
test/api/common/ArrayUtilsTest.js
test/client/Suite.js
test/client/desktop/config/ConfigFileTest.js
test/client/desktop/sse/DesktopAlarmSchedulerTest.js
test/client/desktop/sse/DesktopSseClientTest.js

main changes:
* DesktopDeviceKeyProvider should only get the key once, otherwise it might generate more than one key in a sequence and leave different parts of the app with different device keys. #3295 
* writes and reads to the config file are sequenced now to prevent race condition from corrupting it.
this can be readily reproduced by creating several alarms, checking that they are written to conf.json and then deleting one of the events from the calendar. the file is likely to contain invalid json. #3295 #3316

[desktop] improve handling of local config

---

src/gui/ThemeController.js
src/login/LoginListener.js
src/misc/WhitelabelCustomizations.js
src/settings/whitelabel/WhitelabelSettingsViewer.js

We incorrectly assumed that whitelabel config has the full custom theme.
It is not the case anymore.
fix #3638

Fix saving the custom theme to the storage

---

src/desktop/DesktopMain.js
src/desktop/DesktopWindowManager.js
src/desktop/DeviceKeyProviderImpl.js
src/desktop/sse/DesktopAlarmScheduler.js
src/desktop/sse/DesktopAlarmStorage.js
src/desktop/sse/DesktopSseClient.js
test/client/desktop/sse/DesktopAlarmSchedulerTest.js
test/client/desktop/sse/DesktopAlarmStorageTest.js
test/client/desktop/sse/DesktopSseClientTest.js

The alarmscheduler of the desktop client should try to decrypt alarmnotifications until there are no keys left it could use before throwing an error.
if it does throw, there's something wrong with the locally stored sseinfo, alarmnotifications or pushIdentifierSessionKeys and we should clear them, essentially returning to the state of a new device and redownloading alarms.
It will never use alarmNotifications that are partially unable to be decrypted ("_errors" key gets set by the InstanceMapper).

Catch corrupt deviceidentifier 3295

---

src/desktop/ApplicationWindow.js
src/desktop/DesktopWindowManager.js

normal zoom changes update the zoom factor maintained by the windowmanager
Ctrl+0 didn't, so the window manager would reset the zoom to the saved,
now outdated value on did-navigate events.
this commit globally changes the zoom on all windows and updates the saved
value when Ctrl+0 is pressed.
fix #3717

[desktop] make sure currentBounds is updated on Ctrl+0

---

src/mail/view/MailViewer.js

*  the mail's `/settings/invoice` href is interpreted as an
absolute path, the root of which is `https://mail.tutanota.com/`
in browsers (correct) and the file system root in
electron (wrong).
* changing it to a relative path, e.g. `../../settings/invoice`
would _theoretically_ work, but relies on the link being displayed
in the correct location relative to the settings page.
Practically, any link navigation in the desktop clients that's
pointing to the file system is prevented by us, because we don't
want the shell to open/execute random files from links that got sent by mail.
* the `file:///C:/settings/invoice` link is generated from the mail's
`/settings/invoice` href by electron before dispatching the onclick event.
this commit allows for relative navigation from Tutanota Team
mails …

[desktop] handle relative settings URLs in windows

---

buildSrc/windows-installer.nsh
flow/electron.js
src/desktop/DesktopUtils.js
src/desktop/integration/RegistryScriptGenerator.js
src/desktop/reg-templater.js
test/client/Suite.js
test/client/desktop/integration/RegistryScriptGeneratorTest.js

* a per-user install should only write into HKEY_CURRENT_USER so other users
can't select an app that's not installed for them as default mail app
* the app now opens the settings page after registering as a mail handler so
the user can select it
#3574

[desktop] update registry entries for windows, depend on install mode

---

src/search/view/MultiSearchViewer.ts

`this._searchListView` was used before being assigned
fix #3784

Fix opening search

---

src/desktop/DesktopUtils.ts
src/desktop/reg-templater.ts
src/settings/DesktopSettingsViewer.ts

close #3574
Also clean up the code a bit, remove unused code, do not attempt to
register on Linux as it doesn't work.
Still need to test on Windows

Only register mailto handler on Windows for current user

---

src/misc/2fa/webauthn/WebauthnClient.ts
src/polyfill.ts

cborg needs BigInt to work properly. We could load cborg dynamically
only if we know that it will work but we do not want to introduce
another chunk just for it. So instead we allow loading it but we will
not use it for webauthn.
Also removes Uint8Array.prototype.slice polyfill as it exists pretty
much everywhere
fix #3830

Fix loading without BigInt

---

package-lock.json
package.json

I compared two versions, there are not so many changes:
https://github.com/digitalbazaar/forge/compare/0.10.0...v1.2.0
However, I noticed that it is pretty big and we need only a little part of it. I think we might be able to easily replace it with SubtleCrypto APIs built into Node: https://nodejs.org/api/webcrypto.html
All we need to do is decode PEM and verify signature (like in this example: https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/importKey#pkcs_8_import).
Or we can say that we provide raw key data when building the app and then we don't even need to parse it.
close #3771

Update node-forge to 1.2.0

---

packages/tutanota-utils/lib/PromiseUtils.ts
src/misc/ErrorHandler.ts

The first time throttled import would be called it would wait forever
because passing negative number to delay() would just never complete
(as setTimeout would never fire either).
fix #3834

Fix logging out not working on the first try

---

Jenkinsfile

Jenkins warns about this line in the build info pages.
https://www.jenkins.io/doc/pipeline/steps/credentials-binding/

[ci] don't use double quotes for environment variable interpolation

---

src/calendar/view/CalendarMonthView.ts

fix #3624
Some CSS classes were only being applied on desktop. This seems to somehow have been a fix for some issue in the past, but upon removing it, i dont see anything wrong, so whatever it was is probably gone now anyway

fix alignment of current day indicator on mobile,

---

src/misc/DateParser.ts

`DateParser._cleanUpAndSplit` removes any characters
that cannot be dealt with, such as the char 'a'.
This results in an empty date part if a date of the form
"a/4/12", for example, is entered by a user.
`_cleanUpAndSplit` would then remove the part containing only 'a'
(zero-length) and the date would be interpreted as
month/day or day/month, depending on locale, which
resulted in unexpected dates being saved.
Instead, we cut off dates that have more than three
parts and do not remove zero-length parts, which
fixes the test failure mentioned in the issue.

Change date parsing to not remove empty date parts, fix #3782

---

src/contacts/model/ContactUtils.ts
test/client/contact/ContactUtilsTest.ts

The workaround was done to fix #414, but it failed to consider leap
years. As a result, birthdays of contacts on Feb. 29 were displayed
as Mar. 1.
The aforementioned bug does not appear to be present in recent
Chrome versions.
fix #3684

Remove buggy workaround for old Chrome versions

---

Desktop.Jenkinsfile
Webapp.Jenkinsfile
buildSrc/createGithubReleasePage.js
buildSrc/publish.js
package-lock.json
package.json

This commit enables building the webapp and the desktop clients separately
Now it is possible to get a test webapp client running even if the desktop builds are failing
We will have to make sure that flatpak is still building properly as this commit introduces
a new git tag, `tutanota-desktop-release-$version`
We should look into creating a meta-pipeline that can run all build pipelines together, to ease part of the release process a bit

[build] Split webapp and desktop builds in Jenkins

---

src/api/common/utils/Utils.ts

fix #3939
WebauthnError was crossing two IPC boundaries but was not deserialized
correctly. Unfortunately we match be the class and not by the error
name.

Fix deserialization of WebauthnError

---

app-android/app/build.gradle

Newer IOUtils requires Android 9 or at least some APIs from it and
Android 6 and 7 do not have it without some kind of polyfills.
It would manifest as constant crashes for background process and
crashes when downloading files.
We need to either move away from io-commons or introduce some sort of
de-sugaring/polyfill.
fix #3962

[android] Fix crash caused by IOUtils update on old systems

---

packages/tutanota-test-utils/lib/TestUtils.ts
packages/tutanota-test-utils/lib/index.ts
packages/tutanota-test-utils/package.json
test/client/desktop/DesktopCryptoFacadeTest.ts
test/client/mail/SendMailModelTest.ts
types/ospec.d.ts

Rather than doing anything fancy with extending `o` (I looked into it), I opted to just create a function that looks and behaves the same was as `verify`, but it _secretly_ makes an assertion with ospec

[test-utils] Add utility to count testdouble's `verify` as ospec assertions

---

src/desktop/WebDialog.ts
src/misc/2fa/SecondFactorAuthView.ts

remove rounded corners from WebDialog window on MacOs
the rounded corners seem to take up some space from inside the window
this caused the alignment of the content to be different than expected
fix https://github.com/tutao/tutanota/issues/3950
Also included:
some people miss the primary button on the dialog,
making it stand out more could help. centered primary buttons on the
bottom of dialogs are atypical for us anyway.
also centers the "lost account access" link because it looks strange
next to the red button when right-aligned

[desktop] Fix macos webdialog

---

src/gui/base/List.ts
src/mail/view/MailView.ts
src/mail/view/MailViewer.ts
src/mail/view/MailViewerViewModel.ts
src/mail/view/MultiMailViewer.ts
types/globals.d.ts

There are two commits, the first is the basic bugfix, the second is an improvement in the UI, so that the dropdown doesn't open at the opposite side of the window to where the user would already be looking
We may choose to leave the second commit out for now, to avoid increasing the testing load
fix #4006

Fix move mails shortcut in mailviewer

---

src/mail/view/MailViewer.ts
src/mail/view/MailViewerViewModel.ts

The from/to/cc/bcc/replyTo fields weren't being updated when switching between mails, because they were still being rendered in the constructor of the MailViewer, so now we just render them in `view`
This commit keeps the behaviour where the show more section will stay open when you switch mails, which deviates from the behaviour on production but seems less janky
fix #4015

Fix "show more" section in mailviewer

---

src/mail/view/MailView.ts
src/mail/view/MailViewer.ts
src/mail/view/MailViewerViewModel.ts

Page up/Page down/Home/End buttons were not working
It was another case of the MailViewer outlasting it's ViewModel, so references to it's DOM element in the ViewModel were being lost.
We need to be mindful of cases like this, especially when doing these refactorings.
Now scrolling of the MailViewer is handled entirely within the MailViewer itself (registering shortcuts and doing the scrolling).
for bonus points, you can now use these keys to scroll in the search view, since the shortcuts are no longer being setup by the MailView.
fix #4018

Fix MailViewer scrolling keys

---

src/calendar/date/CalendarUpdateDistributor.ts
src/gui/base/ViewSlider.ts
src/mail/editor/MailEditor.ts
src/mail/editor/SendMailModel.ts
src/mail/view/MailView.ts
src/mail/view/MailViewer.ts
src/mail/view/MailViewerViewModel.ts
src/search/view/SearchResultDetailsViewer.ts
test/client/mail/SendMailModelTest.ts

Inline images are no longer stored or passed as a promise because it is
not necessary: we redraw before we finish loading.
Clarified animation delays for:
1. Rendering mail body in single column layout
2. Spinner when switching between mails
Moved mail body and inline image processing back into mail viewer
because of lifecycle differences:
1. When switching between mails, mailViewer stays but viewModel is
replaced
2. When switching between app sections, mailViewer is recreated but
viewModel stays
handleAnchorClick is moved back to viewer because it makes more sense
in GUI-related code
replaceInlineImages is back into MailViewer because it is coupled
tightly to mailBody and works on HTML.
closes #4031

Fix bugs with MailViewer

---

src/gui/base/List.ts

With the new loading state for offline error we have been missing a
check in `loadMoreIfNecessary()` so the list loading would be triggering
continuously while scrolling near the retry button. It was especially
prominent on iOS where there is an overscroll effect and UI updates
seem to take longer.
Simply adding a check to `loadMoreIfNecessary()` is not enough as it
was also used for retry itself. Instead, we introduce another function
which doesn't check for position and only works in the correct state.
fix #4032

Fix trying to load list while offline

---

packages/tutanota-utils/lib/LazyLoaded.ts
packages/tutanota-utils/test/LazyLoadedTest.ts
packages/tutanota-utils/test/Suite.ts

previously, a LazyLoaded instance would reject forever once the loader
rejected because the rejected promise was cached. fixed by inserting a
catch that deletes the cached promise before rethrowing
the error.
also add LazyLoaded test suite.
fix #3995

[desktop/linux] retry on next LazyLoaded.getAsync when load rejected

---

src/desktop/ipc/DesktopInterWindowEventSender.ts
src/desktop/ipc/IInterWindowEventBus.ts
src/login/LoginListener.ts
src/misc/credentials/CredentialsProvider.ts
src/native/common/InterWindowEventBus.ts

The interwindow event bus would send it's messages off and forget about them. When deleting credentials though it's only safe to delete the offline database once the other windows have finished closing their database connections, which means we need to know when they have completed. now the interwindoweventbus will not resolve until all of it's listeners have also resolved
fix #4108

wait for other windows to finish logging out before deleting database

---

libs/s.js
src/misc/ErrorHandlerImpl.ts

All links on git.io will stop redirecting after April 29, 2022.
- https://github.blog/changelog/2022-04-25-git-io-deprecation/

chore: remove git.io

---

src/calendar/view/CalendarAgendaView.ts

Make the Calendar Agenda View Title easier to understand, by displaying startDate in DateWithWeekday format
Addresses: #3564 
* This makes the day easier to understand, providing some context
* Removed the month comparison and dispaly dateWithWeekday even when startDate month and endDate month are equal
* Previously the displayed Date format was: `4 Wed - Tue, May 17, 2022`, now it is `Wed, May 4 - Tue, May 17, 2022`

(#3564) Make the Calendar Agenda View Title easier to understand, by displaying startDate in DateWithWeekday format

---

src/api/worker/facades/LoginFacade.ts
test/tests/api/worker/facades/LoginFacadeTest.ts

The problem occurred because before offline login we didn't use the
cache for the login process so user's GroupInfo was likely not cached as
it is not downloaded that often after login.
Now there's a temporary workaround that just falls back to the sync
login.
Also, after e3fc4135be9e8b855fb876ccb88476f39b2f04f6 websocket would not
connect in async login because it would think that there's already
previous login (because of the partial login), so it would try to
reconnect instead which didn't work because we started in the
terminated state.
Now it checks for full login and always uses connect().
fix #4150

Fix logging in after upgrading from 3.96.3, fix websocket

---

src/settings/OfflineStorageSettings.ts
src/subscription/SwitchSubscriptionDialog.ts

if a previously premium user downgrades, they will still keep their time
range as they had configured it. This is being handled in
`clearExcludedData` but in the settings
it was still showing what was stored in localStorage.
fix https://github.com/tutao/tutanota/issues/4159
also improve readability of SwitchSubscriptionDialog

always show default offline time range for free users

---

buildSrc/LaunchHtml.js

It was generating broken html files for the browser tests because the type attribute was not being generated correctly. It didn't show up in production because we don't specify type

[build] fix launch html

---

Webapp.Jenkinsfile

the missing line caused the step of pushing release notes in the Publish stage to fail
with `No such property: VERSION for class: groovy.lang.Binding`

[build] add VERSION env var to Webapp.Jenkinsfile

---

src/gui/Header.ts

these are arbitrary and can't be relied upon to leave enough space.
fix #4178

hide offline indicator on mobile if there is an injected view

---

src/misc/ErrorHandlerImpl.ts

With offline login we've added handling for closed session after going
online. The code path is the same as for expired sessions. For offline
we've added code which re-saves the credentials after new session is
created. This shouldn't happen for ephemeral sessions (when they expire)
because we don't store them but this check was missing.
fix #4193

Fix handling for expired sessions

---

src/api/worker/facades/LoginFacade.ts
src/api/worker/search/ContactIndexer.ts
src/api/worker/search/Indexer.ts
test/tests/api/worker/search/ContactIndexerTest.ts
test/tests/api/worker/search/IndexerTest.ts

When the indexer is initialized on login it previously only downloaded
contacts if they have never been indexed before. Now we additionally
download (and therefore cache) them if we have a new offline db.
Note: When logging in offline the contact list will now always be
available but suggestions still don't work as we can only initialize
index db once we have a usergroupkey.
close #4134

Make sure contacts are always available in offline mode,

---

packages/tutanota-utils/lib/TypeRef.ts
packages/tutanota-utils/lib/index.ts
src/api/common/EntityClient.ts
src/api/common/EntityFunctions.ts
src/api/common/utils/CommonCalendarUtils.ts
src/api/common/utils/EntityUtils.ts
src/api/worker/WorkerLocator.ts
src/api/worker/offline/OfflineStorage.ts
src/api/worker/rest/CacheStorageProxy.ts
src/api/worker/rest/CustomCacheHandler.ts
src/api/worker/rest/EntityRestCache.ts
src/api/worker/rest/EphemeralCacheStorage.ts
src/api/worker/search/MailIndexer.ts
src/app.ts
src/calendar/date/CalendarUtils.ts
src/offline/CachePostLoginAction.ts
test/tests/Suite.ts
test/tests/api/worker/offline/OfflineStorageTest.ts
test/tests/api/worker/rest/CustomCacheHandlerTest.ts
test/tests/api/worker/rest/EntityRestCacheTest.ts

enables caching of calendar events and retrieves all calendars and
events on successful full login when offline storage is enabled
for the initial loading:
* the offline cache is available after partial login, but we can only
fill it after full login.
* most of the work is available on the main thread already:
* calendarModel.loadCalendarInfos
* progress tracking
* we don't care about the return values of the loading.
this makes a post login action a good place for the initial loading of
calendars.
for the caching of CalendarEvents:
* CalendarEvents have CustomIds that depend on the start time,
but are not sortable and therefore were incompatible with the
EntityRestCache range caching logic.
* converting their Ids clientside to sortable b64ext of the GeneratedIds
is problematic because …

make all calendars available offline

---

src/gui/MailRecipientsTextField.ts
src/gui/base/BubbleTextField.ts

We are passing in the same search model to all three recipient fields. perhaps better would have been to create a different model for each field but i think that is overkill.
instead we just only show the dropdown iff the field is focussed
I also fixed a bug in which the selected search entry wouldn't be updated when the dropdown shrinks, and tabbing away would cause a failed non-null assertion
fix #4232

don't triplicate the recipient search dropdown in mail editor.

---

src/gui/MailRecipientsTextField.ts
src/misc/TranslationKey.ts
src/translations/de.ts
src/translations/de_sie.ts
src/translations/en.ts

i botched the handling when I split up the input handler. now when a list of recipients is given, invalid ones are filtered out and displayed in an error message
a new translation key was added so we should pull translations from phrase
#4101
#4240

improve handling of invalid pasted recipients

---

app-ios/tutanota.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
app-ios/tutanota/Sources/Remote/WebViewBridge.swift
src/native/main/NativeInterfaceMain.ts

We've been accidentally using unix sleep() method instead
of pausing the task which was stopping one whole thread of
the executor.
fix #4241

[iOS] Fix app getting stuck after reload

---

src/gui/MailRecipientsTextField.ts

fixed the cause, but also removed the assert not null because it's a bit severe, better that
nothing should happen in the case that no suggestion is selected
fix #4246

fix assert not null in mail editor recipient field

---

buildSrc/RollupConfig.js
buildSrc/buildWebapp.js

The chunking check aborted the build on the first problem that is found.
This is fine for small changes, but for bigger ones the
check-fix-check-fix cycle can get annoying.
The check is also only mandatory in CI now, which is slow anyway. This means
the tradeoff between fast and complete feedback falls squarely on the
side of completeness, giving the developer the chance to fix all
problems before even re-running the check locally.
With this commit, the check plugin aggregates the errors and outputs
them all at the same time after the check is finished before throwing.

improve the reporting of chunking problems

---

src/gui/base/List.ts

when offline with only a partial mail list cached, sometimes the connection lost indicator does not get rendered, even though it should. there was a race between `loadMoreIfNecessary` reading the value of `visibleElementsHeight` and `_createVirtualRows` writing to it. if it was read before it was written, then `loadMoreIfNecessary` would not try to load more from the server and would therefore not receive a connection lost error:
what should happen
- `loadMore` calls `loadAndAppendAnotherChunk`, which only returns a partial list
- `loadMore` then calls `loadMoreIfNecessary`, which tries to load the rest of the list, but gets an offline error
- because of the offline error, we show the connection lost indicator
what happens instead:
- `loadMore` is called
- `loadMore` calls …

fix missing connection list indicator

---

src/api/common/Env.ts
src/api/common/TutanotaConstants.ts
src/api/main/MainLocator.ts
src/gui/main-styles.ts
src/misc/WindowFacade.ts
src/native/main/NativeInterfaceFactory.ts
src/native/main/NativeInterfaceMain.ts

isDesktop() excludes the admin client, which leads to the ctrl+f search
overlay not being able to use the locator.searchTextFacade operations.

[admin] create a searchTextFacade for the admin client web process

---

src/api/worker/WorkerLocator.ts
src/api/worker/offline/OfflineStorage.ts
src/api/worker/rest/CacheStorageProxy.ts
src/api/worker/rest/EntityRestCache.ts
src/api/worker/rest/EphemeralCacheStorage.ts
src/api/worker/search/MailIndexer.ts
src/offline/CachePostLoginAction.ts
test/tests/api/worker/rest/EntityRestCacheTest.ts

* the worker thread needs to create an entity rest cache
* the cache needs a storage impl (ephemeral or offlineDB)
* the ephemeral cache doesn't support customId types, but the oDB does
via custom handlers.
* because the custom handlers were initialized separately from the
storage, we had an inconsistency where an ephemeral cache was created
with the custom handlers for the oDB, which led to loadRange requests
always returning empty event lists unless events were added after
login. This affected all non-persistent sessions in desktop clients.
moving the custom handler selection into the storage impl makes this
this mixup impossible.
fix #4339

fix invisible calendar events in desktop client non-persistent sessions

---

src/api/common/DataFile.ts
src/api/common/utils/FileUtils.ts
src/mail/editor/MailEditorViewModel.ts

pre-saving, a draft on the desktop client contains DataFile Attachments,
after saving they are TutanotaFiles.
The _downloadAttachment function of the MailEditorViewModel treated
these differently.
fix #4359

[desktop] make MailEditorViewModel download DataFiles and TutanotaFiles

---

src/desktop/tray/DesktopTray.ts

Was observable on Windows. We set electron.app.on("ready") too late,
after the app was ready. The handler would not fire and we wouldn't
create the tray.
Co-authored-by: nig <nig@tutao.de>
fix #4337

[desktop] Fix tray

---

src/mail/editor/MailEditor.ts
src/mail/editor/SendMailModel.ts

This adds a check for hasMailChanged() when the mail dialog is minimized, such as when closed.
The change to SendMailModel.ts is because drafts opened that have senders (such as a reply) are set as changed after the code below would have set it to unchanged. I'm not sure if there is a better way to handle this.
Also would it make sense to check if the mail was created as a reply and save anyway?
If merged, this closes #3580

Do not save a draft if message is unchanged

---

src/api/common/error/OfflineDbClosedError.ts
src/api/common/utils/Utils.ts
src/api/worker/offline/OfflineStorage.ts
src/desktop/db/OfflineDbFacade.ts
src/misc/ErrorHandlerImpl.ts

when the saved credentials have a session that expired (ie deleted from
other device) we detect this and reset the session. this includes
closing the websocket asynchronously and closing the offline DB.
the app may try to write to the db after closing it and before closing
the websocket, which normally would not be allowed, but is fine to
ignore in this state since we're going to recreate the session anyway.
close #4401

[desktop] ignore closed db error when in expired session recovery mode

---

src/misc/2fa/webauthn/BrowserWebauthn.ts

after the changes to the asset loading, the android client started
attempting u2f challenges because the domain matches the registered
keys.
this commit disables u2f in BrowserWebAuthn when used in apps until u2f
is properly supported.
this also fixes the misleading message
"security key is not registered for this domain" that would be shown to
mobile users, it's just "accept login from another client" now.
close #4426

[android/ios] explicitly disable u2f for mobile apps

---

app-android/app/src/main/java/de/tutao/tutanota/MainActivity.kt

On old androids, webkit's MimeTypeMap would return null for
some extensions used in our assets (ie .js).
since we proxy the requests for assets, we set the mimetype
manually with mimetypemap, which doesn't sit well with the
WebView if the mimetype is null (refuses to load it as executable).
Because of that worker would never be initialized (it loads polyfill.js
dynamically). For users it would look like the request is stuck.
close #4453

[android] add some values to the MimeTypeMap

---

src/settings/AboutDialog.ts

The copyright year in the About window should reflect the current year.
Fixes #4450

Update the copyright year to 2022

---

src/subscription/SwitchSubscriptionDialog.ts

Creating a new subscription has each option with a height of 270px, thus changing subscriptions should have the same height.
While this does mean there is some extra whitespace due to not having the monthly/yearly selection, having it be consistent is preferable, and it allows the Free plan to have enough room without being cut off.
Fixes #4163

Make switch subscription options' height match upgrade options

---

src/subscription/BuyDialog.ts

Prevent that the original date object can be accidentally edited directly when using this function.
For example, ConfirmSubscriptionView's view() function should not update the period end date directly when incrementing by 1.
Fixes #4196

Make BuyDialog.periodEndDate return a copy of the date

---

src/misc/ClientConstants.ts
src/misc/ClientDetector.ts
test/tests/misc/ClientDetectorTest.ts

According to our support policy, PaleMoon is an unsupported,
it-may-work-or-not user agent and should be classified as
BrowserType.Other.
close #4407

[cleanup] remove PaleMoon from BrowserTypes

---

src/desktop/DesktopWindowManager.ts

this is required to be able to use the crypto.subtle module in the web
app.

[desktop] pass "secure: true" to registerSchemeAsPrivileged

---

src/contacts/VCardExporter.ts
src/contacts/model/ContactUtils.ts
src/contacts/view/ContactViewer.ts
test/tests/contacts/ContactMergeUtilsTest.ts
test/tests/contacts/VCardExporterTest.ts

You accept both vanity URLs and full URLs for the default social media IDs. However, when a vanity URL is used, i.e. `TutanotaTeam` instead of `https://www.twitter.com/TutanotaTeam`, Tutanota currently doesn't populate it as a URL for the vCard export.
There should be consistency with how the URLs appear on the web client vs the vCard export. So for example if the web client will allow `TutanotaTeam` as a Twitter handle and convert it to a URL, then in the export I'd expect to see the same URL that the client produces.
The URL is malformed as the `:` should not be escaped.
> URL:http://example.org/restaurant.french/~chezchic.html
> 
> — https://datatracker.ietf.org/doc/html/rfc6350#section-6.7.8
Before the export looked like: `URL:https\://www.twitter.com/SethFalco`
Now it'll look …

fix: export full contact urls instead of vanity urls

---

src/gui/base/InfoBanner.ts

InfoBanner's styling should be able to handle long words. For example, you may receive an email with a long technical sender containing words or sequences of characters that cannot be broken up nicely, and we do not want to have this overflow.
Fixes #3910

Fix technical sender in info banner overflowing

---

src/settings/WhitelabelChildViewer.ts

On commit 9d5e2f6fb4bc14a5cc0f7b1a74a606b32cd56e16, the visual status of whitelabel children was corrected, but the actual effects of the button were broken, as it was written with the inverted functionality (thus deactivating activates and vice versa).
This commit fixes this issue by now having it send a deactivation date on deactivation as expected.
Fixes #4462

Fix deactivating a whitelabel date not sending a date

---

src/mail/editor/MailEditor.ts

We want to prevent that, when sending emails, emails are unexpectedly sent to recipients that the sender is unaware of.
Therefore, when opening a mail editor with pre-set CC/BCC recipients such as when clicking on a mailto link or opening a draft, we want the CC/BCC fields to be expanded automatically to indicate to the user that there are more recipients.
Fixes #3844

MailEditor should show CC/BCC if initialized with either

---

app-ios/tutanota/Sources/CustomSchemeHandlers.swift

some mails contain relative URLs in image tags or CSS, which is not nice
that's why, from now on, we check requests, twice.
#4487

[ios] don't crash on unknown asset requests

---

src/settings/AddSpamRuleDialog.ts

Make the field options in spam rules in line with the text used for inbox rules (e.g. From -> From/Sender). Also do not use hardcoded "CC"/"BCC" labels here.
Fixes #3350

Have spam rules field options use inbox rules text

---

src/login/recover/TakeOverDeletedAddressDialog.ts
src/subscription/UpgradeSubscriptionWizard.ts

When credentials are stored and the user cancels:
- the dialog for signing up a new account
- the dialog for taking over an account due to inactivity
- the dialog for having lost access to an account
the desired behavior should be that the user is not logged back into the
previously saved account.
To ensure this the parameters for redirecting to the login page have been
changed to not log the user in automatically after cancelling the mentioned
dialogs.
fixes #2549
Co-authored-by: @nif-tutao

Fix unwanted autologin when cancelling dialogs on login screen

---

src/subscription/InvoiceAndPaymentDataPage.ts
src/subscription/UpgradeSubscriptionWizard.ts

Specify an enabled function for InvoiceAndPaymentDataPage's attrs so that its page button is displayed when appropriate.
When signing up for a new account, do not display it if the the user either did not select Free or they are on the first page (and thus we may not be certain if they want to select a paid plan).
We want to check this in particular for signup, as upgrading from free to paid will, of course, always have an invoice page. And changing from paid to another plan does not have an invoice page to begin with.
Fixes #3100

Have invoice page number not display on first page of signup

---

src/mail/view/MailView.ts
src/mail/view/MailViewer.ts
src/mail/view/MailViewerViewModel.ts
src/search/view/SearchResultDetailsViewer.ts

fix the flicker when the unread state is changed:
Instead of recreating the view model we just update the mail in the existing one. This introduced the issue that the existing mail body would not be updated so we have to manually call `loadAll`, and also re-call `replaceInlineImages` hence the funky business with streams
fix the flickering when `contrastFixNeeded` is true: this is also fixed by not recreating the viewModel
fix the rendering of a new mailbody:
Mithril was reusing the dom element when switching from rendering a mail body to rendering the progress spinner. Because of the shadow dom, the old content was remaining. I opted to add keys to the different elements to force mithril to re-render it completely.
fix #4309

fix mailbody issues

---

src/gui/editor/HtmlEditor.ts

We do not want the editor to have an 'active' border when focused if it is disabled, as it may signal to the user that the editor can be edited in this state. The view call should check if the editor is now disabled before drawing a border.
Fixes #3935

Make HtmlEditor not show a border if disabled

---

src/mail/view/MailViewer.ts

When printing an email, the year should be included in the timestamp as printing is generally done for archival.
Fixes #1300

Show the date with the year when printing

---

src/desktop/ApplicationWindow.ts
src/desktop/WebDialog.ts
src/desktop/ipc/CentralIpcHandler.ts
src/desktop/ipc/ElectronWebContentsTransport.ts
src/desktop/ipc/RemoteBridge.ts

sometimes, the window is gone before we get to destroy the bridge.
This gives a TypeError: object has been destroyed.
In other cases, we try to send messages to already destroyed
webContents, giving TypeErrors because webContents.fromId returns
undefined.
To prevent this
* we add a listener to the destroy event of the webContents
* don't use ids for referencing the webContents, instead pass the
content itself around to be able to check isDestroyed()
fix https://github.com/tutao/tutanota/issues/4467

[desktop/mac] make destroying ipc more robust with destroyed webcontents

---

src/gui/editor/Editor.ts
src/settings/EditSignatureDialog.ts

There was an issue where the signature preview could be edited unless it is disabled later by changing the preview, so this change disables it when it is initialized if needed.
Squire also handled pasting before our code could handle it. Luckily, Squire has a willPaste event which can be used to suppress paste events, so this change utilizes this and removes the "not working currently" comment.
Fixes #2690

Fix signature preview being writable

---

src/gui/base/TextField.ts
src/login/LoginForm.ts

On a non-mobile device, we should automatically focus on email address so that the email can immediately be typed once on the login page.
Fixes #2810

LoginForm should have email automatically focused if not on mobile

---

src/api/main/UserController.ts

When the browser tab is closed we try to delete ephemeral session
using Beacon but while assembling the URL for CloseSessionService we
interpolated the whole object instead of a service name so the
URL had `[object Object]` in it.
fix #4523

Fix automatically closing ephemeral sessions with a beacon

---

src/api/worker/facades/BlobFacade.ts
src/desktop/CryptoFns.ts
src/desktop/DesktopFileFacade.ts
src/desktop/DesktopNativeCryptoFacade.ts
src/desktop/net/DesktopDownloadManager.ts
src/desktop/net/DesktopNetworkClient.ts
src/file/FileControllerNative.ts
test/tests/desktop/DesktopCryptoFacadeTest.ts
test/tests/desktop/net/DesktopDownloadManagerTest.ts

For reasons described in 6f4600f we started uploading
DataFile's via native. It was also changed in desktop but
we never actually implemented the desktop part.
With this change we fix multiple issues to make uploading blobs
work again on desktop:
- change writeDataFile() to not ask for path but instead write to a
temp directory for unencrypted files, like on other platforms,
and adjust the code accordingly
- implement aesEncryptFile(), splitFile() and upload(), needed for
blobs
fix #4529

[desktop] Upload blobs via native

---

src/contacts/view/ContactViewer.ts
src/gui/base/Overlay.ts
src/misc/WindowFacade.ts
src/settings/SettingsView.ts

Cover more views in the simplest way (e.g. scroll bar is in the wrong
position) and handle specific screen rotation scenario.
fix #4531

Fix more cases of wrong insets

---

src/api/main/LoginController.ts
src/api/main/LoginListener.ts
src/api/worker/offline/OfflineStorage.ts
src/api/worker/rest/CacheStorageProxy.ts
src/api/worker/rest/DefaultEntityRestCache.ts
src/api/worker/rest/EphemeralCacheStorage.ts
src/gui/base/OfflineIndicatorViewModel.ts
src/login/PostLoginActions.ts

The first issue is attempting to get last update time in OfflineIndicatorViewModel. It was trying to wait for partial login but unfortunately temporary login is also partial login.
We didn't want to just return null in this case as it might get interpreted incorrectly and instead we returned a sum type with the exact case and ignore uninitialized storage in this case.
The other issue was with LoginController and LoginListener not properly resetting themselves on logout (e.g. after temporary login) and giving incorrect results.
The third issue was with PostLoginActions initializing MailModel for temporary login. If a real login into another account is attempted afterwards it would lead to more errors.
To fully solve the problem we should rethink how temporary login affects the rest of the …

Fix issues with temporary login

---

src/RootView.ts
src/app.ts
src/gui/BaseTopLevelView.ts
src/gui/Header.ts
src/login/LoginView.ts
src/mail/view/MailViewer.ts
src/misc/RouteChange.ts
src/search/SearchBar.ts

Double login could occur if LoginView would start the normal login process and then the URL would change (e.g. when native part would change trigger login with specific account). In this case a second LoginView would be constructed and would start the login on its own. Normally this shouldn't happen but for LoginView we specifically opted into not caching it to not accidentally hold to credentials any longer than necessary.
To prevent this issue we should not create LoginView manually but let mithril do it. This is a bit tricky as LoginView needs some info passed into it. We ended up rewriting LoginView as a proper component and creating a new RouteResolver implementation that can work with this type of views.
fix #4554
fix https://github.com/tutao/tutanota/issues/4570
also see the same …

Fix double login in specific cases

---

src/mail/view/MailViewerViewModel.ts
src/search/view/SearchResultDetailsViewer.ts

The bug was caused by not taking into account email id and trying to reuse the same ViewModel as before.
We added the condition to the SearchViewDetailsViewer and also added an assertion to the MailViewerViewModel itself.
Fix #4561

Fix updating mail details in search view

---

app-ios/tutanota/Sources/Contacts/ContactsSource.swift
src/misc/RecipientsSearchModel.ts

Two issues:
- RecipientsSearchModel.ts was not clearing "loading" promise on error so if an error occurred at least once all the subsequent searches would just reject with the same error.
- ContactsSource.swift was not doing the right thing after conversion to async/await. The requestAccess() function has really odd interface where originally it's callback would return both boolean and error and in the old callback-based code we only checked the boolean. Now that we use an async() version it just throws. We fix it by catching it.
fix #4555

Fix errors when denying contact permission on iOS

---

src/mail/editor/MailEditor.ts

Added condition to check what label should be used.
fixes #3254

Wrong label on confidential button in the mail editor

---

src/api/worker/facades/MailFacade.ts
test/tests/api/worker/CompressionCompatibilityTestData.json
test/tests/api/worker/CompressionTest.ts

enable mail body compression

---

src/api/worker/rest/EntityRestClient.ts
test/tests/api/worker/rest/EntityRestClientTest.ts

Part of tutadb issue 1125.
Browser, iOS and one desktop platform

Support arbitrary URLs in EntityRestClient

---

src/mail/view/MailListView.ts

The check for dragging mails was assuming we will use selected mails when we only drag the mail under cursor.
fix #4614

Remove erroneous check when dragging mails

---

src/settings/GlobalSettingsViewer.ts

There isn't really any reason the client can't show this for free users as it appears to be fully functional on free accounts and may be useful to note when a password was changed for example.
Fixes #4539

Enable audit log for free accounts

---

src/subscription/UpgradeSubscriptionPage.ts

Usage tests were being loaded into UpgradeSubscriptionPage at the end of oncreate(), which is too late.
Loading them before selectFree can be called (i.e., in goToNextPageWithPreselectedSubscription) fixes this.
fixes #4605

Ensure subscription selection ping being sent when coming from website

---

src/login/PostLoginActions.ts
src/misc/UsageTestModel.ts
src/subscription/UpgradeSubscriptionWizard.ts
test/tests/misc/UsageTestModelTest.ts

This is because the current impl. was
causing bugs in PostLoginActions.onPartialLoginSuccess(). 
This method is also called on registering an account so 
that the storage behavior was set to persist (although the 
user is not quite logged in) and thus the ephemeral tests 
were no longer accessible for the signup dropouts or 
payment usage tests.

Remove usage test TTL behavior

---

src/settings/GlobalSettingsViewer.ts

Free users cannot have sub-accounts, thus showing
the section with the global opt-out makes no sense.
closes #4634

Only show global usage test section to premium accounts, #4634

---

src/gui/main-styles.ts

some HTML mails are displayed in front of the box shadow of the action bar / bottom navigation in the single-column layout
setting the z-index to the same as the header (2) prevents that
close #4635

fix bottom navigation sometimes not having a shadow

---

src/subscription/TermsAndConditions.ts

the privacy policy json files moved from tutanota.com/privacy-entries/ to tutanota.com/privacy-policy-entries/, which was not updated in TermsAndConditions.ts
close #4644

fix wrong privacy policy link in apps

---

src/gui/base/WizardDialog.ts
src/subscription/UpgradeSubscriptionPage.ts
src/subscription/UpgradeSubscriptionWizard.ts

Requires differentiating between subscriptions
during signup and upgrades when logged in to the client.
closes #4632

Do not measure signups for upgrades in the client, #4632

---

src/api/worker/offline/OfflineStorageMigrator.ts

There were multiple issues:
- if the database is old enough we would try to run other migrations first which wouldn't work because the db structure is not there yet
- if the db is not new we would never write the version for offline migration and would never run it because `undefined < 1` is always false.
fix #4696

Fix running ownerGroup migration

---

src/api/main/MainLocator.ts

CalendarModel receives a function to get alarm scheduler async and lazily. It doesn't cache it internally and would request a new one each time. When it would try to unschedule the alarms it wouldn't find anything about existing timeout ids.
We make sure to cache the scheduler in MainLocator so there will be one instance only.
fix #4676

Fix unscheduling alarms in web version

---

package-lock.json
package.json

better-sqlite would crash when opening a database, sometimes with apparent segfault, sometimes with dlopen failure
"could not find procedure"
when this breaks after an electron or compiler update check these places:
* binding.gyp of better-sqlite
* rebuild openssl

fix better-sqlite on windows

---

src/api/worker/facades/LoginFacade.ts

e.g. when we try to log in offline without a populated db. Before we only reset the cache on auth errors but since we reset the offline db users will be missing the offline cache and would run into the offline error without appropriate handling.
fix #4706

Fix resetting the login state after some errors during login

---

src/api/worker/offline/OfflineStorage.ts
src/api/worker/rest/DefaultEntityRestCache.ts
src/api/worker/rest/EphemeralCacheStorage.ts
test/tests/api/worker/rest/EntityRestCacheTest.ts

We are doing this to not accidentally try to download the event batches that we don't need.
fix #4714

Cleanup lastUpdateBatchIdPerGroup when losing a membership

---

src/native/main/WebMobileFacade.ts

The system back button on Android leads from the detail search view
in one of the settings back to MailView, when it should take you back
to the settings overview. For example for user management.
Therefore the order of the if statements in WebMobileFacade.ts has been
changed to check at an earlier stage whether it is possible to
focus the previous column. This only applies if the main column is not
the focused one. So we can eventually return to the main column.
Furthermore singleColumnLayout is a prerequisite because in the
multi-column layout it is not necessary to return to the previous column
since all columns are already visible.
also fix #4621 and fix #4649
fix #4656

Fix the misbehavior of the Android system back button in the settings

---

src/login/PostLoginActions.ts

On slow connections, the news indicator was not being rendered until user interaction. This is because at the end of PostLoginActions.fullLoginAsyncActions(), the view was not being redrawn, and NewsModel.loadNewsIds() was not being awaited.
fixes #4732

Fix news indicator sometimes not being rendered, #4732

---

packages/tutanota-usagetests/lib/model/UsageTest.ts
src/misc/UsageTestModel.ts

We now catch BadRequestErrors and handle
usage test stages not being registered
in case a usage test is misconfigured.
This is so misconfigured tests never affect
user experience, but it also means that we need to test usage test implementations extra diligently
and make sure they are configured correctly.
Otherwise, we might silently run a misconfigured test for a while and miss pings.
fixes #4736

Catch misconfigured usage test errors, #4736

---

app-android/app/src/main/java/de/tutao/tutanota/MainActivity.kt
app-android/app/src/main/java/de/tutao/tutanota/push/PushNotificationService.kt

We need to move the startForeground call to the onStartCommand method so that it will be called everytime we start the
PushNotificationService. Furthermore, we should not create the notification channels multiple times while the
app is running.
fix #1654

move startForeground call to onStartCommand method

---

app-android/app/src/main/java/de/tutao/tutanota/push/LooperThread.kt
app-android/app/src/main/java/de/tutao/tutanota/push/PushNotificationService.kt
app-android/app/src/main/java/de/tutao/tutanota/push/SseClient.kt

* The #1654 issue was caused by called startForeground at the wrong moment (`onCreate` instead of `onStartCommand`). It should have been relevant for boot only
* We have not been tracking the state properly and we could have been calling `startForeground()` multiple times. It was mitigated by us calling `removeBackgroundServiceNotification` after every message
* `scheduleJobFinish()` was creating the thread but it was never started meaning that `jobFinished()` would never be actually called
* `SSEClient` would call `onConnectionEstablished` multiple times
fix #1654

Fix few issues with PushNotificationService, fix #1654

---

app-android/app/src/main/java/de/tutao/tutanota/MainActivity.kt
app-android/app/src/main/java/de/tutao/tutanota/Utils.kt

We can exclude the bottom left screen region on android from the system gestures, so that the user can open the drawer menu with a swipe on the device even if system (back) gestures are enabled.

Exclude bottom left screen region on android from system gestures

---

src/misc/LoginUtils.ts

before, it just awaited the async import and dismiss the progress, but there's still other async work going on.
#4770

await loadSignupWizard to keep the progress dialog until it's ready

---

src/gui/main-styles.ts
src/subscription/BuyOptionBox.ts

avoids usage of the deprecated "word-break": "break-word" css directive. instead, "word-break": "normal"
and "overflow-wrap": "break-word" are used as suggested on mdn
close #4773

break feature list items

---

src/subscription/EmailAliasOptionsDialog.ts
src/subscription/StorageCapacityOptionsDialog.ts

adjusted to the size of the boxes on the website.
they appear in a dialog and are allowed to wrap, so this should be fine.
fix #4771

make alias and storage buy boxes bigger

---

packages/tutanota-usagetests/lib/model/UsageTestController.ts
src/misc/news/items/RecoveryCodeNews.ts

Caching it lead to us using the ObsoleteTest instance if we opted in because the RecoveryCodeNews' constructor was not being called again.
fixes #4784

Don't cache test instance in recovery code news

---

src/gui/main-styles.ts
src/misc/news/NewsList.ts

make news item take the dialog bg color

---

src/calendar/view/CalendarEventPopup.ts

WebMobileFacade#handlebackPress calls the modals onClose method, which was not implemented so far by the CalendarEventPopup modal.
fix #4809

fix CalendarEventPopup not closing when using android system back button

---

src/calendar/view/CalendarEventPopup.ts
src/gui/base/Modal.ts
src/gui/nav/ViewSlider.ts
src/misc/WindowFacade.ts

if the view slider has a previous (further left) column that's not a foreground column it can focus, it will do so and signal the window facade that the back button event has been handled.
otherwise, if the focused column is a foreground column, it will focus the next column to the right and signal the handled event. this has the effect of closing the drawer menu in our application.
fix #4731
Co-authored-by: nok <nok@tutao.de>

give ViewSlider the ability to handle browser history events

---

src/gui/MailRecipientsTextField.ts
src/gui/RecipientsSearchDropDown.ts
src/gui/base/Expander.ts

the suggestion dropdown is an absolutely positioned element,
these get positioned relative to the next positioned ancestor.
The MailRecipientsTextField did not come with its own
positioned element, so positioning of the dropdown depends
on the environment it's displayed in.
this commit adds a position: relative wrapper around the dropdown
also removes overflow: hidden from Expander since it's cutting off the
dropdown and doesn't seem to do anything in any browser (the issue
mentioned in https://github.com/tutao/tutanota/commit/f9796135229c588b4c5b7e0d6c3a6019f354028c was visible in the
new mailviewer header expander, but it's currently not anymore even
without the overflow: hidden)
fix #4725

Obscured recipients field 

---

src/misc/UsageTestModel.ts
test/tests/misc/UsageTestModelTest.ts

We always wait for the previous ping
to complete before attempting to send
the next one.

Make usage test ping sending more robust

---

src/login/recover/RecoverLoginDialog.ts

"type" was missing in the email field for the account recovery. By adding the value "Email" android phones won't autocorrect input anymore.
fix #3849

fix disable autocorrect in email field in recovery dialog

---

src/calendar/view/CalendarEventEditDialog.ts
src/gui/base/Dialog.ts
src/gui/base/TextField.ts
src/login/ExternalLoginView.ts
src/login/LoginForm.ts
src/login/contactform/ContactFormRequestDialog.ts
src/login/recover/RecoverLoginDialog.ts
src/login/recover/TakeOverDeletedAddressDialog.ts
src/mail/editor/MailEditor.ts
src/misc/2fa/SecondFactorAuthView.ts
src/settings/PasswordForm.ts
src/settings/login/secondfactor/SecondFactorEditDialog.ts
src/settings/mailaddress/AddAliasDialog.ts
src/subscription/DeleteAccountDialog.ts
src/termination/TerminationForm.ts

androids example autofill app needs the "autocomplete" field in an input field to offer autofill. The value of the autocomplete field is an instruction how this field should be handled.
There are other possible "autocomplete" values like "new-password" which can be used as well. Wherever TextField is created, the "autocomplete" field will now be filled with the appropriate value, if reasonable.
#4499

Add "autocomplete" to login input fields to better support autofill

---

src/login/contactform/ContactFormRequestDialog.ts

This commit simply removes an obsolete comment. The comment was written during migration from Button to ButtonN, but after this migration was performed ButtonN was renamed to Button. Furthermore, the in the comment mentioned round corners have since been removed from the Button.
close #4254

closes old button in ContactFormRequestDialog

---

Desktop.Jenkinsfile
app-android/app/build.gradle
app-ios/tutanota/Info.plist
package-lock.json
package.json
packages/licc/package.json
packages/tutanota-crypto/package.json
packages/tutanota-test-utils/package.json
packages/tutanota-usagetests/package.json
packages/tutanota-utils/package.json
src/settings/SelectMailAddressForm.ts
src/settings/SelectMailAddressFormWithSuggestions.ts
src/subscription/SignupForm.ts

it's not necessary for selecting a new mail address
since the address is new
the popup also obscures some suggestion UI
autocomplete = "new-password" is more reliable than
autocomplete = "off" since some browsers will still
ask to save the entered credentials and then
autocomplete anyway later (this can happen with
multiple accounts)
close https://github.com/tutao/tutanota/issues/4871
also contains the changes between 3.106.1 and 3.106.2

stop autocomplete on new mail address fields

---

src/gui/MailRecipientsTextField.ts

When no recipient from the suggestions is explicitly selected, none of the suggestions should be put to the recipient field. But currently when closing the recipient suggestion dropdown by for example clicking somewhere else the onBlur method is called and the current highlighted suggestion gets selected.
Still the input needs to be resolved, even if the dropdown is closed. This is for example necessary for external mail addresses.
fix #4831

fix mail address is selected when closing mail recipient suggestion

---

src/mail/view/MailViewerViewModel.ts

We've been caching suspicious status and not updating it on when the mail was updated. The state is actually redundant as we overwrite the phishing status on mail directly as soon as we check for phishing so the issue resolved itself after we removed it.
fix #4606

Fix mail phishing banner not being updated

---

app-ios/tutanota/Sources/Offline/IosSqlCipherFade.swift

It seems like the reason for the crash in 4836 is concurrent access to the db pointer. When we run into the outdated credentials we close the db and it can happen while another operation is running. The crash was happening when get() would check that db is open and copy the db handle, the db would be closed in the meantime and then get() would fail when it would try to use the db. The only way to prevent this is to make all db usage serial and we achieve this by using actor. This probably impacts the performance because there can be no more concurrent calls but we believe that the impact is minimal in practice.
fix #4836

[ios] Fix offline-related crash

---

src/desktop/ApplicationWindow.ts
src/desktop/DesktopErrorHandler.ts
src/misc/TranslationKey.ts
src/translations/de.ts
src/translations/de_sie.ts
src/translations/en.ts
test/tests/desktop/ApplicationWindowTest.ts

mac will throw an error when openExternal can't find an application to open the link. this can happen with custom protocols.
we now show a nice error message if this happens.
close #4952

[macos] fix uncaught error when clicking invalid links in mail

---

src/misc/ErrorHandlerImpl.ts

turns out that what shouldn't have changed changed after all. we had hundreds of reports of this in the last week.

ignore systemjs error with shortened URL

---

src/calendar/view/CalendarView.ts
src/contacts/view/ContactView.ts
src/gui/BaseTopLevelView.ts
src/mail/view/MailView.ts
src/search/view/SearchView.ts
src/settings/SettingsView.ts

With old view resolver updateUrl() would always be called before the view() method. With new view resolver and BaseTopLevelView this has changed and it would be called afterwards. When this got changed CalendarView would update it's state too late and would once redraw with the old state.
This commit reverts to the previous behavior so that we have a chance to set the state depending on the URL before we re-render.
fix #4998

Fix when onNewUrl() is called

---

src/desktop/net/DesktopDownloadManager.ts
test/tests/desktop/net/DesktopDownloadManagerTest.ts

on windows, we need to call close() to release the file handle and be able to open the joined file with other apps (or re-download the file)
fix #4946

[desktop/win] fix joinFiles not closing the output stream

---

src/api/common/TutanotaConstants.ts
src/desktop/ApplicationWindow.ts
src/desktop/tray/NonMacTray.ts
test/tests/desktop/ApplicationWindowTest.ts

* add Ctrl + Shift + Q for linux and window to quit app
* on mac, Cmd + Q still quits the app as before
* add the shortcut to the F1 menu for all platforms
fix #3378

[desktop] fix quit shortcut not working

---

src/mail/view/MailListView.ts
src/mail/view/MailView.ts

After changing MailView to be a proper component we've introduced a cache to hold on to some state. Unfortunately we had to hold the whole MailListView in the cache because of how it is written. This was not done properly because we create it only once and would hold on to the first instance of MailView (which was used at creation time). If we switch to another view and back we need to get a new MailView instance.
We fixed it by updating the MailView reference together with lifecycle.
A proper solution would mean not requiring MailView in there and not holding on to the whole MailListView in the cache.'
fix #5026

Fix navigation in Mail view, fix view caching issue

---

packages/tutanota-utils/lib/SortedArray.ts
packages/tutanota-utils/test/SortedArrayTest.ts
src/knowledgebase/model/KnowledgeBaseModel.ts
src/templates/model/TemplatePopupModel.ts

Constructors were not type-safe before and would fail with some TS configurations.

Fix types for SortedArray

---

packages/tutanota-crypto/test/bootstrap.ts
src/desktop/ApplicationWindow.ts
test/tests/desktop/ApplicationWindowTest.ts

if the window is actually being closed is still up for negotiation when "close" is emitted. "closed" is emitted after the window is gone, so that's when we're sure the db is not used anymore.
fix #5029

close offlineDB when the closed event is emitted, not before

---

app-android/app/build.gradle
app-ios/tutanota/Info.plist
buildSrc/DesktopBuilder.js
buildSrc/DevBuild.js
buildSrc/electron-package-json-template.js
package-lock.json
package.json
packages/licc/package.json
packages/tutanota-crypto/package.json
packages/tutanota-test-utils/package.json
packages/tutanota-usagetests/package.json
packages/tutanota-utils/package.json

5.3.0 couldn't handle windows machines with a restricted powershell 6.0.0 fixed that, but the alpha that's currently available does not work on linux because it's opening the child process wrong.

[desktop] use a nonbroken electron-updater version on each platform

---

src/api/worker/offline/OfflineStorage.ts
src/api/worker/offline/OfflineStorageMigrator.ts
test/tests/api/worker/offline/OfflineStorageMigratorTest.ts

DB downgrade check was not implemented properly where it would determine runtime version based on migrations. We run into a situation where we had multiple model versions with no migrations which made the check think that we are downgrading every time. Switching it to using modelInfo fixed the issue.
Another issue was not running migrations (and non populating metadata) after DB re-creation. We've added the code to run the migrator on the re-created database and handling for the old invalid state.
fix #5044

Fix offline DB being deleted every time

---

src/calendar/view/CalendarView.ts

we'll now use today as the current date instead of whatever date would currently be shown in the other views.
fix #4253

fix agenda view creating new event dialog with wrong date

---

src/api/entities/storage/ModelInfo.ts
src/api/entities/storage/TypeModels.js
src/api/entities/storage/TypeRefs.ts
src/api/worker/facades/BlobAccessTokenFacade.ts
src/api/worker/rest/EntityRestClient.ts
test/tests/api/worker/facades/BlobAccessTokenFacadeTest.ts

Requesting a read token no longer needs archiveDataType for archives you own, so do not do this for MailDetailsBlob since each recipient owns their own copy.
Also, if we add more blob element types, we should not assume that it will be a MailDetails blob. This value will be ignored anyway in these cases.
tutadb#1294

Make ArchiveDataType not required for reading blobs via EntityRestClient

---

src/api/entities/sys/ModelInfo.ts
src/api/entities/sys/Services.ts
src/api/entities/sys/TypeModels.js
src/api/entities/sys/TypeRefs.ts
src/api/entities/tutanota/ModelInfo.ts
src/api/entities/tutanota/TypeModels.js
src/settings/DomainDnsStatus.ts
src/settings/emaildomain/VerifyDnsRecordsPage.ts

Add customer ID as an optional field for support to assist with custom domain troubleshooting.
tutadb#1299

Allow checking arbitrary domain records

---

src/api/common/MailWrapper.ts

`isDetailsDraft()` would compare against the `null` strictly while in some cases the field would just not be set (probably from cbor). It would later proceed to try and use it in OfflineStorage#deleteMailList() which would throw an assertion error.
We fixed the check to match both.
Ideally we should also update the generated types to account for that.
fix #5108

Fix uncaught error because of invalid isDetailsDraft() check

---

src/api/worker/facades/LoginFacade.ts
src/login/PostLoginActions.ts
src/mail/model/MailModel.ts
src/mail/view/MailView.ts

Login state is tracked differently for worker and page sides of the app. When `LoginFacade` (worker) thinks that the partial login is done `LoginController` (page) can still fail, mostly due to `MailModel#init()` being part of the login process.
We suspect that the issue happened due to page login failing. On the next try we would try to log in again even though the login is already done from the worker's perspective.
We had two main options: either aborting worker login when page login (including `PostLoginActions`) fails or taking `MailModel#init()` out of the login process. We went with the latter because most of the code was already written with the assumption that `MailModel` is initialized asynchronously. This has an added benefit of letting user into the app faster. Later we can …

Fix getting into invalid login state

---

src/mail/view/MailListView.ts

The bug was introduced with the async check for the subfolders of trash and spam. To display the banner above the list we wrap both the list and the header in ListColumnWrapper but before we would only render the list inside the wrapper if we wanted to show the banner. With the async folder check the value of showingSpamOrTrash changes at an arbitrary moment of time and the list would be deleted and created at some moment of time as well. Some timing issue of re-creating the list would cause it to miss the state change for loading.
We worked around the issue by always rendering the wrapper which makes the DOM structure more stable and avoids re-creating the list. A better fix would also include changes to the List to make it more robust.
fix #5081

Fix trash, spam & subfolders getting stuck in the loading state

---

src/search/view/MultiSearchViewer.ts

The offset was previously created to keep the SearchView action buttons aligned with the MultiSearchViewer action buttons.
fix #5045

fix remove the offset at the top of action buttons

---

src/mail/editor/SendMailModel.ts

all of our accounts and aliases are case-insensitive (lowercased), so we should make sure that we're not sending mail with mixed-case senders.
The acute problem fixed by this is the following:
* create an event with at least one mixed-case internal address attendee, maybe from a contact (it's saved to the event as-is)
* try to reply to that invite from the attendees account ->  we're using the address from the event as a sender
* error out when sending the reply because there's no group that has the mixed-case address assigned
#5125

fix SendMailModel allowing mixed-case sender addresses

---

src/gui/base/CounterBadge.ts
src/mail/view/MailFolderRow.ts

The margin actually appeared for every CounterBadge, like unread counter, news item counter, minimized draft counter. Only in the case of the unread email counter the margin is needed. That's why I moved it from the component and wrapped the CounterBadge in case of the news badge in an extra div with the accurate margin.
fix #5160

fix the unnecessary margin at the right of the news badge

---

src/mail/model/MailUtils.ts
src/settings/MailSettingsViewer.ts
src/settings/mailaddress/MailAddressTableModel.ts
src/translations/de.ts
src/translations/de_sie.ts
src/translations/en.ts

* remove name setting from mail settings (it's still available in and only relevant to user management)
* show sender name along the default sender address in mail settings (only in the selected value field, where it will wrap. the dropdown still only shows the available sender addresses)
* improve wording of the default sender hint
* show in descending priority based on availability
*  the currently selected default sender address 
* the user's primary address
* "Mailbox"
above the folder column
close #5080

improve settings for account name and default sender

---

app-android/app/build.gradle
app-ios/tutanota/Info.plist
buildSrc/electron-package-json-template.js
package-lock.json
package.json
packages/licc/package.json
packages/tutanota-crypto/package.json
packages/tutanota-test-utils/package.json
packages/tutanota-usagetests/package.json
packages/tutanota-utils/package.json

we can't use this version on MacOS because electron-builder does not manage to install it.
fix c184f8919d952cfa5441ba27ebc5dd4225717655

revert electron-updater update

---

src/gui/base/DropDownSelector.ts

Especially in the settings the dropdown relies on event propagation of the IconButton. In DropDownSelector the IconButton's click action is set to noOp, while only the click on the whole view of the settings element is handled.
fix #5181

fix dropdowns in settings are not expandable by using the expand button

---

src/login/contactform/ContactFormRequestDialog.ts

`this` was not correctly bound. That's why the subject was not updated as well as the notification mail address -> also fixes that no notification emails are sent.
fix #5197

fix to send the subject with the contact form

---

buildSrc/DevBuild.js
buildSrc/buildPackages.js
buildSrc/packageBuilderFunctions.js
package.json
test/TestBuilder.js

Building packages is a part of most build invocations. Our old approach during dev builds was to
1. Invoke npm once to run build-packages
2. Invoke npm per each package to run tsc.
Unfortunately, npm is very slow. Additionally, the old approach was leading to tsc re-checking some packages multiple times because of dependencies between them. This would only worsen with time.
In our new approach we
1. invoke tsc only once
2. try to avoid invoking npm as much as possible
Unfortunately there is still one case where we invoke npx because we can't be sure that the location of node_modules/.bin is stable as we are sometimes used as a package. Without this we could reduce the time even further.

[build] Make building packages faster

---

src/api/worker/facades/BlobAccessTokenFacade.ts
test/tests/api/worker/facades/BlobAccessTokenFacadeTest.ts

Simple fixes that should alleviate the problem.
does not close but is related to #5153

Fix BlobAccessToken expiration check

---

src/mail/view/ConversationViewer.ts

The issue exists because we show floating subject on top of a normal subject even when we wouldn't have to. Ideally we should fix that issue but as an easy workaround we can make the floating subject selectable.
fix #5211

Make subject always selectable in ConversationViewer

---

src/desktop/DesktopMain.ts

electron changed from node 16+ to node 18+ with version 23+
node 17+ changed the default order of returned ipv4 and ipv6 addresses during dns lookup, which causes problems with some users.
this changes it back to the previous default.
fix #5295

[desktop] fix not being able to reach server in some networks with e23+

---

src/api/common/utils/EntityUtils.ts
src/calendar/date/CalendarEventViewModel.ts
src/calendar/model/CalendarModel.ts
test/tests/api/common/utils/EntityUtilsTest.ts

The issue happened because we had a new code path for creating event: when adding an exclusion we copy most of the event. However, clone() also copies some hidden technical fields. When we encrypt the instance we will pick them up and use them instead of encrypting the whole instance again. We cannot do that when we have a new session key.
To fix this we now remove all the technical fields from the instance before encrypting it.
fix #5317

Fix incorrectly copying event when adding exclusions

---

app-android/app/build.gradle
app-android/app/schemas/de.tutao.tutanota.data.AppDatabase/1.json
app-android/app/schemas/de.tutao.tutanota.data.AppDatabase/2.json
app-android/app/src/androidTest/java/de/tutao/tutanota/MigrationTest.kt
app-android/app/src/main/java/de/tutao/tutanota/alarms/AlarmNotificationsManager.kt
app-android/app/src/main/java/de/tutao/tutanota/alarms/EncryptedRepeatRule.kt
app-android/app/src/main/java/de/tutao/tutanota/data/AppDatabase.kt
app-android/app/src/main/java/de/tutao/tutanota/generated_ipc/NativePushFacade.kt
app-android/app/src/main/java/de/tutao/tutanota/generated_ipc/NativePushFacadeReceiveDispatcher.kt
app-android/app/src/main/java/de/tutao/tutanota/push/AndroidNativePushFacade.kt
app-ios/tutanota.xcodeproj/project.pbxproj
app-ios/tutanota/Sources/Alarms/AlarmManager.swift
app-ios/tutanota/Sources/Alarms/IosNativePushFacade.swift
app-ios/tutanota/Sources/GeneratedIpc/NativePushFacade.swift
app-ios/tutanota/Sources/GeneratedIpc/NativePushFacadeReceiveDispatcher.swift
app-ios/tutanota/Sources/Push/NotificationsHandler.swift
app-ios/tutanota/Sources/Utils/Utils.swift
ipc-schema/facades/NativePushFacade.json
packages/licc/package.json
src/api/worker/facades/lazy/CalendarFacade.ts
src/desktop/sse/DesktopAlarmStorage.ts
src/desktop/sse/DesktopNativePushFacade.ts
src/misc/DeviceConfig.ts
src/native/common/generatedipc/NativePushFacade.ts
src/native/common/generatedipc/NativePushFacadeReceiveDispatcher.ts
src/native/common/generatedipc/NativePushFacadeSendDispatcher.ts
src/native/main/NativePushServiceApp.ts
test/tests/misc/DeviceConfigTest.ts

it's possible for us to have stored old alarm notifications that don't contain exclusions that have been added by newer client (backported).
we're now unscheduling all alarms, deleting the stored alarms and do a complete re-download to get at the exclusions we missed after we log in.
we also added some migrations so new clients can deal with the old notifications.
fix #5319

properly migrate persisted alarm notification on all platforms

---

src/templates/view/TemplateShortcutListener.ts

the new squire changed the way cursor change events are reported to the editor, so we need to update the TemplateShortcutListener.
fix #5332

fix # + <tab> not bringing up the template popup

---

src/misc/WindowFacade.ts

* windowfacade.init() depends on login
* window facade registered the resize handler in init
* therefore, if logins is slow, styles might miss early resize events
fix #5349

register window size event handler in Windowfacade ctor instead of init

---

src/calendar/view/CalendarView.ts

the viewslider is now closed in the same way as for the navigation buttons
fix #5263

fix that the side menu is not closed when clicking today in calendar

---

src/settings/MailSettingsViewer.ts

the default sender should be updated on every redraw (whenever the view function is called) since it can be changed in other places in the background
fix #5321

fix, the displayed default sender is not updated when disabling alias

---

githooks/pre-commit
package.json

we may have to test that this works on MacOs and make changes to it so the `/dev/null` redirects redirect to `nul` on windows.

[ci] add .githooks/ with pre-commit formatting

---

src/subscription/BuyOptionBox.ts

The info button should align with the first line in the features list.
tutadb#1482

center info icons

---

src/settings/emaildomain/AddEmailAddressesPage.ts
src/settings/mailaddress/AddAliasDialog.ts
src/settings/mailaddress/MailAddressTableModel.ts
src/subscription/PriceUtils.ts

If the user books more aliases than any plan allows, we do not want to misinform the user that they can upgrade. So, we query the server and check if any available plans have more aliases than what the user has booked.
tutadb#1476

Inform the user upon reaching maximum alias count

---

src/settings/GlobalSettingsViewer.ts
src/subscription/DeleteAccountDialog.ts
src/subscription/SubscriptionViewer.ts

this makes delete account available for free users in the ios app which do not see the "plan" settings
includes a minor refactor and improvement to the DeleteAccountDialog.ts because the ios app immediately crashes after deleting the account when it receives the event for the group deletion.

move delete account from the "plan" settings to the "general" settings

---

src/api/worker/offline/migrations/sys-v86.ts

fix offline database migration for new pricing

---

src/api/common/TutanotaConstants.ts
src/subscription/SubscriptionSelector.ts

We want value plans to be highlighted to direct the focus of the user to them. Store the plans in a list for better understandability.
Currently, this applies to Revolutionary and Advanced which should both be highlighted for personal and business customers, respectively.
tutadb#1506

Refactor highlighted signup plans to list, add Advanced

---

src/gui/AttachmentBubble.ts
src/gui/base/Button.ts

we can remove the right padding on the static right text in the bubble if we use a comma.
this enables us to have no difference between the unsplit name in the expanded bubble and the split name in the collapsed bubble for short names that do not get ellipsed.
since the space right of the ellipsis is added by the browser, we're
unable to remove it easily.
fixes dee136a0c13c5be60188c5d2ba83c487bce4e060
Screencast before: 
[Screencast from 02.06.2023 13:40:29.webm](https://github.com/tutao/tutanota/assets/29049728/3edb3365-6b94-4e3a-99fb-fa22e3cd248c)
Screencast after:
[Screencast from 02.06.2023 13:42:27.webm](https://github.com/tutao/tutanota/assets/29049728/db83336e-8b5e-4978-ae8d-9103748cbd1a)

improve display of short file names in attachment bubble

---

src/mail/view/MailView.ts

MailView was scheduling another redraw on every render my chaining redraw after a promise. This redraw is anyway unnecessary as redraw would anyway be triggered in MailViewModel.
fix #5586
fix #5547

Fix constant redraw loop

---

src/contacts/view/ContactView.ts
src/contacts/view/ContactViewer.ts
src/gui/DesktopToolbars.ts
src/gui/base/List.ts
src/gui/main-styles.ts
src/mail/view/ConversationViewer.ts
src/search/view/SearchView.ts

No browsers support overlay scrollbars anymore and only some support `scrollbar-gutter` property.
To get a stable layout we force the containers that we expect to scroll to always reserve the space for the scrollbar and we try to match it in the toolbar.
fix #5595

Fix layout bugs caused by scrollbars

---

src/subscription/SwitchSubscriptionDialog.ts
src/subscription/SwitchSubscriptionDialogModel.ts
src/translations/de.ts
src/translations/de_sie.ts
src/translations/en.ts
test/tests/subscription/SwitchSubscriptionDialogModelTest.ts

New personal plans do not have multiple users enabled, but we want users to switch anyway.
As such, if the user is expected to keep having multiple users, they should see "per user".
This will happen if they have multiple users already booked prior to switching.
Also actually make SwitchSubscriptionDialogModelTest a test.
tutadb#1505

Show per-user if the user is expected to have multiple users enabled

---

src/subscription/SwitchSubscriptionDialogModel.ts

Some legacy plans aren't just Premium (0) as far as PlanType goes.
tutadb#1505

Include all legacy plans when determining multiuser support on switch

---

src/misc/RouteChange.ts

when moving a lot of mail or applying entity events, the new mail list tends to re-route to the same path over and over again. throttleRoute now ignores such calls and only actually calls m.route if the arguments are different from the last ones and the route did not change in some other way.
we should consolidate our custom routing logic at some point to make sure all parts of the app play by the same rules.
fix #5651

fix excessive route changes with mass mail operations

---

src/app.ts
src/serviceworker/sw.ts

Service worker has been throwing out the hash part of the URL when redirecting. Most browsers preseve the has on redirects but not Safari.
After changing that we needed to make sure that our redirect system does not result in double hashes concatenated into the URL.
fix #4564

Fix gift cards in Safari, fix preserving hash on redirect

---

src/misc/HtmlSanitizer.ts
test/tests/misc/HtmlSanitizerTest.ts

the regex allowing the tutatemplate: protocol
was only added to the sanitizeFragment config.
using sanitizeFragment for sanitizing knowledge
base entries would require us to insert the result manually into the DOM since mithril does not support trusting fragments and we don't want to serialize
to a string and then trust.
so we add the regex to the sanitizeHtml config as well
fix #5640

fix sanitizeHtml removing tutatemplate: links

---

src/api/worker/crypto/CryptoFacade.ts

There's no need to log the whole entity.

Improve message of SessionKeyNotFoundError

---

src/calendar/view/eventeditor/AttendeeListEditor.ts
src/calendar/view/eventeditor/CalendarEventEditView.ts

we can just show the attendee list editor in a readonly mode. being able to collapse the attendee list is useful even if you're not able to modify guests
fix #5691

fix not showing all attendees in a single event editor

---

src/calendar/date/eventeditor/CalendarEventWhoModel.ts
src/calendar/view/eventeditor/CalendarEventEditView.ts
test/tests/calendar/eventeditor/CalendarEventWhoModelTest.ts

as much as possible, the whole series should always be in the same calendar
fix #5692

fix allowing to change the calendar on a single instance

---

src/calendar/view/eventpopup/CalendarEventPopupViewModel.ts
src/calendar/view/eventpopup/EventPreviewView.ts
src/mail/view/EventBanner.ts

free users can import invites manually and then
try to use the response feature from the popup.
the resulting UpgradeRequiredError was not caught.
fix #5694
fix 54947127118faf09f41bb4eea42500e3612029ed

fix uncaught error when responding to imported invites

---

buildSrc/bump-version.js
buildSrc/postinstall.js
packages/tutanota-test-utils/package.json
src/calendar/date/eventeditor/CalendarEventModel.ts
src/mail/model/MailUtils.ts
test/tests/mail/SendMailModelTest.ts

for now, we're just putting the default sender in front. to make it more clear, we could pass it around separately, but that would make a fair amount of the logic around handling organizers/attendees more complicated.
fix #5665
fix 54947127118faf09f41bb4eea42500e3612029ed

fix not using the default sender as a default organizer

---

src/api/worker/facades/lazy/CalendarFacade.ts
src/calendar/export/CalendarImporter.ts
src/calendar/export/CalendarImporterDialog.ts
test/tests/api/worker/facades/CalendarFacadeTest.ts
test/tests/calendar/CalendarImporterTest.ts

we're now grouping events by uid before checking if they
should be created or not.
the first event of a group without a recurrenceId
is the designated progenitor (the rest is dropped
as duplicate). if it has a repeat rule and we
encounter altered instances in that group,
their recurrenceIds are added as excluded instances
on the progenitor.
this does not handle updating existing progenitors
when new altered instances are imported or adding
existing altered instances on newly imported
progenitors
fix #5708
fix ed27db58b2735268d70a6119ed1deeb27e8a8919

fix altered instances not being excluded on import

---

src/gui/base/ListUtils.ts

that shortcut conflicts with the chrome tab switcher and was not intended to be enabled for the web app.
fix #5652

disable ctrl + shift + A for select all in browsers

---

app-ios/tutanota.xcodeproj/project.pbxproj

It turns out we need iOS 15 in order for our way of handling MIME types to work.

Deprecate iOS 14

---

src/gui/ThemeController.ts
src/settings/whitelabel/CustomColorsEditorViewModel.ts

One issue was missing load of theme preference on init so settings did show the resolved theme id which came from native.
Another issue was not reloading the theme when there was a theme passed in the URL. Because of that we did not get a correctly resolved theme on the first start.
fix #5831
fix #5832

Fix applying and displaying system theme

---

src/misc/HtmlSanitizer.ts

the check is useless because URL.protocol includes the colon.
We have other safeguards against unsafe links in the native parts of our apps and obviously the browsers, so it's not a serious issue.
thanks to @Sjord

fix wrong protocol comparison

---

src/api/worker/facades/LoginFacade.ts
src/desktop/net/ProtocolProxy.ts

After switching to a new API we started returning 503 for network errors which is treated in a special way by the app.
Using response.error() is closer to how the app would behave without a protocol handler.
close #5866
close #5868

[desktop] Make ProtocolProxy return network errors

---

app-ios/argon2/phc-winner-argon2
app-ios/fastlane/Fastfile
app-ios/tutanota.xcodeproj/project.pbxproj
app-ios/tutanota.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
app-ios/tutanota/Info.plist
app-ios/tutanota/Sources/Crypto/phc-winner-argon2

Turns out that it's very annoying to create shared libraries as a separate target, as while it works great locally, there are issues with building releases with Jenkins (as seen with the past three builds.
Let's just not do that.

Remove argon2 target; merge into tutanota target

---

app-ios/tutanota/Sources/Crypto/Argon2.swift
app-ios/tutanota/Sources/tutanota-Bridging-Header.h

Seems we can't just do 'import argon2' anymore

Add argon2 to the bridging header

---

src/mail/export/Exporter.ts
test/tests/mail/export/ExporterTest.ts

that's the rule according to
https://www.rfc-editor.org/rfc/rfc5322#section-2.1
fix #5553
fix 1ad04f1368e11c6139d513ca609f59764293f7fd

fix inconsistent line endings in eml exports

---

app-ios/tutanota/Sources/Crypto/ValueEncryption.swift

It seems there was a misunderstanding of how the decrypt base64 function worked.
Fixes #5928

[iOS] Fix ValueEncryption converting back to base64 before parsing

---

src/api/worker/crypto/CryptoFacade.ts
src/api/worker/crypto/InstanceMapper.ts
src/api/worker/rest/EntityRestClient.ts

We never set ownerEncSessionKey on a cached instance so we would be missing an ownerEncSessionKey on Mail instance (either temporarily until the update or persistently if the cache is out of sync). Because of that we could not decrypt MailDetailsBlob in some cases.

Fix encryption errors for MailDetails tutadb#1633

---

src/misc/SubscriptionDialogs.ts
src/subscription/UpgradeSubscriptionWizard.ts

CustomerInfo is moved between lists on upgrade/downgrade and we might try to load it at the old location.
It seems like it was not necessary to load CustomerInfo anyway.
fix #5949

Fix error on loading CustomerInfo after upgrade

---

packages/tutanota-crypto/lib/misc/CryptoError.ts
src/api/common/utils/Utils.ts
src/misc/credentials/NativeCredentialsEncryption.ts

We did not expect encryption errors from fetching the credentials key before because we didn't check HMAC in those cases. Now that we do check it more consistently the errors show up sooner and must be handled properly.
fix #5916

Fix handling corrupted credentials key

---

src/desktop/sse/DesktopSseClient.ts
test/tests/desktop/sse/DesktopSseClientTest.ts
test/tests/testInNode.ts

we moved from plain strings to actual URLs in the build process which added slashes at the end of the result. the client still used plain strings to construct the notification URLs and had duplicated slashes because of that
fix #6010

fix wrong push notification urls

---

src/login/PostLoginActions.ts
src/misc/ClientDetector.ts

We no longer wish to support web browsers that have WebAssembly disabled as we need to use C libraries for some things now.
tutadb#1630

Drop support for browsers that do not have WebAssembly

---

src/api/worker/rest/EntityRestClient.ts
src/calendar/model/CalendarModel.ts
test/tests/api/worker/rest/EntityRestClientMock.ts
test/tests/calendar/CalendarModelTest.ts

0cf654d06 changed how we handle missing session key when decrypting instances which is handled like a programming error now. This broke the logic for the CalendarModel where we have a temporary solution for not having a proper key: we are supposed to always pass the key provider for instances that are encrypted together with Mail but in this case we don't have a reference to mail yet so we can't do that.
We removed the handling for the missing session key because it shouldn't result in silent errors on the client and this way we can actually handle it when we need it like in the case above with calendar updates.
fix #6021

Fix processing calendar event updates when MailDetails is enabled

---

src/api/worker/rest/RestClient.ts

concatenation this is prone to failure because of missing/duplicated slashes. we're building a URL anyway, so we might as well use the dedicated setter for path.

don't use string concatenation in RestClient.ts to build urls

---

src/app.ts

When in legacy domain and with some token or hash parameter, the redirect doesn't pass the parameters to the new website signup URL.
This commit adds the hash parameters to the redirect URL.
#5637

fix legacy domain hash parameters redirect

---

src/api/worker/facades/lazy/ConfigurationDatabase.ts
src/api/worker/search/DbFacade.ts

our indexedDb implementation is not very clear and the original error points to some timing or error handling problem in the initialization or migration sequence.
this patch stops these errors from becoming user-visible by ignoring them.
if the indexDB is available after all, the user can still add the rule later, if it is not, indexing will likely be disabled at some later point.
#5915

fix missing object store causing uncaught error reports

---

packages/tutanota-crypto/lib/hashes/Sha1.ts
packages/tutanota-crypto/lib/hashes/Sha256.ts
packages/tutanota-crypto/lib/hashes/Sha512.ts
packages/tutanota-crypto/lib/internal/sjcl.js
packages/tutanota-crypto/test/Sha256Test.ts

We've been passing the whole underlying buffer of Uint8Array to toBits() which works for most cases but can break if Uint8Array points only to the part of the underlying buffer. This is easy to run it with node's Buffer.from() which allocates a big chunk of data at once so it's underlying buffer will in many cases bigger than the byteLength.

Do not use the whole buffer for sjcl toBits()

---

src/subscription/BuyOptionBox.ts

When the current language uses more than two lines of text after the price on select plan page, the select plan button overlaps the monthly and yearly buttons.
Changing the container to flex-column and removing it's fixed height plus adding margin-top auto to the select plan button solves the issue.
fix #5552

fix overlap of select plan button with the monthly and yearly buttons

---

src/login/LoginView.ts

When the loginForm promise is resolved, the url
arg loginWith is read and stored in the mailAddress Stream. The loginForm promise is only resolved
in the oncreate function of the loginForm.
Since the oncreate function is not called again
when switching from saved accounts to create a new account, the promise won't be resolved again.
Moving the promise.resolve() to the onupdate
function solves the issue.
fix #5810

fix loginForm is not prefilled with address

---

src/contacts/view/ContactListRecipientView.ts
src/contacts/view/ContactListView.ts
src/mail/view/MailListView.ts
src/misc/ListModel.ts
src/search/view/SearchListView.ts
test/tests/misc/ListModelTest.ts

When the user is on mobile or more specific on a viewport that uses the single column layout and visualises an email, when back to mail list and long press to select another different email, the first one keeps selected.
This commit changes the behavior of the emails lists and contacts lists, discarding the previous selected email if in single column layout. On bigger viewports that uses two or more columns, the behavior stays the same.
fix #5696

fix multiple emails are selected when using long press

---

src/gui/AttachmentBubble.ts

When the email has to attachments on mobile and the two attachments are placed side by side in the email view, when opens the action bubble for the right one the bubble overflow to the right clipping part of its content.
This commit verifies if the bubble will overflow the screen and inverts the side of it, instead to open to the right, it will open to the left side of screen.
fix #5919

fix file attachment bubble out of screen

---

app-android/app/src/main/AndroidManifest.xml

Starting on API 33, Google stopped granting the SCHEDULE_EXACT_ALARM automatically when installing the app, making necessary to ask for user's permission before scheduling alarms.
This commit limits the SCHEDULE_EXACT_ALARM permission to API 32 and introduces the USE_EXACT_ALARM permission that is granted when installing the app.
fix #6045

Update Alarm Permission on Android

---

src/contacts/view/ContactView.ts
src/mail/editor/MailEditor.ts
src/mail/view/MailViewer.ts
src/search/view/SearchView.ts

It seems like it happens when users trigger the contact editor too early, probably because their security key is sending keyboard input.
fix #5959

Fix uncaught programming error, check for contact list id

---

src/api/worker/search/MailIndexer.ts

As the search is looking for draftMails it should use the mailDetailsDraft into the comparison and not the mailDetails.
fix #6051

change from mailDetails to mailDetailsDraft

---

app-android/app/src/main/AndroidManifest.xml

As Google will probably take a deeper look at this permission request, we decided to postpone it to the next release.
#6059
#6045

Rollback Android Alarm permission

---

src/subscription/FeatureListProvider.ts

Previously it would fail on any error because .catch() block didn't return anything. It was possible because the type inference was failing for the helper function.
close tutadb#1661

Fix handling errors when fetching feature list

---

buildSrc/buildWebapp.js
src/login/LoginViewModel.ts
src/serviceworker/sw.ts

We implemented immediate takeover for the old domain so that the users who initiate credential migration won't be stuck with the client which doesn't support it.
close #6074

Prevent having outdated client during credential migration

---

src/api/worker/search/Indexer.ts

typeof null === "object" so our check was itself trying to access the field that was not there.
Now we use optional chaining and only check the fields typees directly.
fix #6046

Fix iOS IndexedDB workaround

---

buildSrc/LaunchHtml.js
src/gui/main-styles.ts
src/subscription/BuyOptionBox.ts
src/subscription/SubscriptionSelector.ts
src/subscription/UpgradeSubscriptionWizard.ts
src/subscription/giftcards/PurchaseGiftCardDialog.ts

This commit separated the price from the details, now they're built separately and now the pick a plan screen uses grid to build the columns and rows, giving more flexibility to the box-size according to the amount of text
fix #6087

change plans to use grid and separate the price from the details

---

src/subscription/UpgradeSubscriptionPage.ts

Stops users from bypassing the business & age check boxes when signing up for a free account.
Closes #5169.

Fix pressing enter bypassing the `confirmFreeSubscription` dialog

---

src/gui/dialogs/ProgressDialog.ts
src/gui/main-styles.ts
src/mail/export/Exporter.ts
src/mail/view/MailViewerToolbar.ts

When exporting mails no progress is informed to the user, just a blocking dialog asking to wait.
Now it show a progress bar and informs the user how many emails have been prepared and how many emails are going to be exported.
Co-Authors: @ganthern @rezbyte 
close #5546

Show progress bar when exporting emails

---

src/calendar/date/eventeditor/CalendarEventModel.ts
src/misc/SimpleTextViewModel.ts

These fields will not be rendered as HTML, so we don't need to use any sort of HTML sanitization for input.
Fixes #5897

Don't run calendar location/title through HTML sanitization - #5897

---

package-lock.json
package.json
src/desktop/net/ProtocolProxy.ts

[desktop] Fix making excessive handshakes

---

src/gui/main-styles.ts

increased the z-index of link tooltips
to a bigger number. The link tooltip should be
probably above everything else when displayed.
fix #6124

fix link-tt z-index too low

---

app-ios/fastlane/metadata/default/marketing_url.txt
app-ios/fastlane/metadata/default/privacy_url.txt
app-ios/fastlane/metadata/default/support_url.txt

fastlane was flagging the old URLs as unreachable
even though there's a redirect now.

Update fastlane config

---

src/mail/export/Exporter.ts

This fixes the day name being always the day in the date field in exported eml files. 
Closes #5282.

Fix the day name being wrong when exporting an email as a `.eml`

---

src/calendar/date/eventeditor/CalendarEventModel.ts
src/calendar/view/eventeditor/CalendarEventEditDialog.ts
src/misc/TranslationKey.ts
src/translations/de.ts
src/translations/de_sie.ts
src/translations/en.ts

When the user tries to update an event that was deleted, they receive just an error.
Now, the app handles the NotFoundError and shows a message to the user informing that the event doesn't exist anymore.
fix #3388

Fix updating deleted event show error

---

src/gui/base/Icon.ts

Stops tooltips from overflowing if they exceed the bounds of the viewport by shifting them left.
Closes #6162.

Fix folder name tooltip on mail viewer header overflowing the screen

---

src/gui/base/Checkbox.ts
src/gui/main-styles.ts

Greys out the checkbox by reducing its opacity & setting the cursor to default. Also included is a small typo fix.
Closes #3133.

Fix checkbox not indicating if disabled

---

src/gui/DesktopToolbars.ts
src/mail/view/ConversationViewer.ts

Divs that should not be printed need
the noprint css class assigned.
Printing the desktop toolbar results in
a small grey vertical line. And printing
the footer results in an extra empty page.
fix #6119
fix #6120

fix that too many divs are being printed

---

src/contacts/view/ContactView.ts
src/mail/view/MailView.ts
src/search/view/SearchView.ts

In keyboards that doesn't have the del key, sometimes the Backspace key is named as DEL. eg Some Apple Keyboards
This adds Backspace as a new shortcut to delete emails/contacts, the behavior is the same from the DEL button.
closes #4563

Fix DEL shortcut doesn't work in web app

---

src/login/PostLoginActions.ts

When the user is with the desktop app closed and try to send a file through email the Tuta client doesn't attach the file to the email.
This commit removes the temp folder cleanup at the startup when running the desktop app, since we might have multiple instances running and using the temp folder.
fix #5850

Fix MAPI does not attach files unless already logged in

---

src/mail/view/MailViewerHeader.ts

This allows you to select everything inside the mail viewer header & thus copy the sender and recipient names.
Closes #5748.

Fix sender and recipient names in mail view being unselectable

---

src/login/LoginViewModel.ts

we will proceed with the login as normal, just without persisting the credentials.
this is similar to how we would handle denied keychain access, for example.
#3853
close #6213

catch CancelledError during credentials store

---

src/calendar/view/eventeditor/CalendarEventEditDialog.ts
src/login/LoginViewModel.ts

The if statement to show the error message was just checking for EventSaveResult.NotFound === true, what is always true. Changed to result === EventSaveResult.NotFound.
fix #6207

fix event not found message even with existing events

---

src/calendar/view/eventeditor/CalendarEventEditDialog.ts
src/gui/base/Checkbox.ts
src/login/LoginViewModel.ts

The invisible checkbox used for keyboard input becomes visible when screen readers are used on mobile. This commit ensures the position of the invisible checkbox is the same as the visible checkbox.
Closes #6215.

Fix invisible checkbox being out of line with visible checkbox

---

src/calendar/view/eventeditor/CalendarEventEditDialog.ts
src/gui/PinchZoom.ts
src/gui/base/Checkbox.ts
src/login/LoginViewModel.ts

When the user selects a text in the MailBody while on MailView on iOS the text is unselected as soon as the user release the touch action.
This commit fix it by checking if it's a long press event, if true, we don't clear the selection.
fix #6209

Fix cannot select text on ios

---

src/calendar/view/eventeditor/CalendarEventEditDialog.ts
src/gui/PinchZoom.ts
src/gui/base/Checkbox.ts
src/login/LoginViewModel.ts
src/mail/view/MailFolderRow.ts

Removes code reintroduced when #6122 & #6191 was merged into master. The keyboard input must be handled directly as `onblur` is called every time a folder row is clicked due to the route change.
Closes #6225.

Fixed the more button in the folder rows disappearing on click

---

src/calendar/view/eventeditor/CalendarEventEditDialog.ts
src/gui/PinchZoom.ts
src/gui/base/Checkbox.ts
src/login/LoginViewModel.ts
src/mail/view/MailFolderRow.ts
src/mail/view/MailViewerViewModel.ts

making `isBlockingExternalImages` the default by also adding `this.contentBlockingStatus === ContentBlockingStatus.NoExternalContent` makes sure images are not displayed unless
after explicitly giving permission.
also see the discussion in https://github.com/tutao/tutanota/issues/6227#issuecomment-1834081434
fix #6227

fix that external images in draft editor are displayed without consent

---

src/api/worker/search/MailIndexer.ts
src/search/view/SearchViewModel.ts

fixes #6278
This fix only removes the duplicate invocation of indexMailboxes which already improves the performance for my case by factor 10.
Timings for initial indexing:
30 days, 74 mails, **7224 ms**
```
IndexerCore.ts:941 {"indexingTime":65.10000000335276,"storageTime":2390.100000000559,"preparingTime":4834.699999997392,"mailcount":74,"storedBytes":760928,"encryptionTime":449.8999999957159,"writeRequests":5148,"largestColumn":295,"words":5012,"indexedBytes":682158,"downloadingTime":4319.699999998324} total time:  7224.799999997951
```
Next 30 days:
30 days, 61 mails, **6554 ms**
```
IndexerCore.ts:941 {"indexingTime":58.20000000298023,"storageTime":1879.2999999998137,"preparingTime":4674.89999999851,"mailcount":61,"storedBytes":649648,"encryptionTime":391.39999999664724,"writeRequests" …
```

only invoke indexMailboxes once when extending or creating search index

---

src/api/worker/facades/lazy/MailFacade.ts
src/api/worker/search/MailIndexer.ts
src/mail/editor/MailEditor.ts
src/mail/view/MailViewerHeader.ts
src/mail/view/MailViewerViewModel.ts
src/search/view/SearchViewModel.ts

mail that has its details migrated already has its authStatus potentially set to null, which is bad for our check for authenticationStatus in several places. we need to check the mail details as well to not get false negatives.
There's several other places where mail.authStatus is checked directly that completely ignores the presence of mailDetails.
* no auth failure banners are shown for these

unable to store permanent content rules for maildetails mail

---

src/api/worker/facades/lazy/MailFacade.ts
src/api/worker/search/MailIndexer.ts
src/desktop/DesktopMain.ts
src/desktop/sse/SecretStorage.ts
src/desktop/tray/DesktopTray.ts
src/mail/editor/MailEditor.ts
src/mail/view/MailRow.ts
src/mail/view/MailViewerHeader.ts
src/mail/view/MailViewerViewModel.ts
src/misc/ClientConstants.ts
src/search/SearchBarOverlay.ts
src/search/view/SearchViewModel.ts

if no explicit backend is given, we default to trying gnome-libsecret since that was what we required before.
the code that keytar used to do its thing is virtually identical to what chromium is doing when using gnome-libsecret.
the preselection can still be overridden by adding any of the other `--password-store` switches.

pre-select gnome-libsecret safeStorage backend

---

src/api/worker/facades/lazy/MailFacade.ts
src/api/worker/search/MailIndexer.ts
src/desktop/DesktopMain.ts
src/desktop/sse/SecretStorage.ts
src/desktop/tray/DesktopTray.ts
src/mail/editor/MailEditor.ts
src/mail/model/InboxRuleHandler.ts
src/mail/view/MailRow.ts
src/mail/view/MailViewerHeader.ts
src/mail/view/MailViewerUtils.ts
src/mail/view/MailViewerViewModel.ts
src/misc/ClientConstants.ts
src/search/SearchBarOverlay.ts
src/search/view/SearchViewModel.ts
src/settings/SelectMailAddressForm.ts

the "report mail" and "show images" button can both be at the bottom of the mail action menu.
this moves the "destructive" actions (unsubscribe, show/hide images) further up so they're not at the bottom of the list of actions where the report mail action is when it is available.
close #6196

optimize ordering of more actions in mail viewer

---

src/api/worker/facades/lazy/MailFacade.ts
src/api/worker/search/MailIndexer.ts
src/desktop/DesktopMain.ts
src/desktop/sse/SecretStorage.ts
src/desktop/tray/DesktopTray.ts
src/mail/editor/MailEditor.ts
src/mail/model/InboxRuleHandler.ts
src/mail/view/MailRow.ts
src/mail/view/MailViewerHeader.ts
src/mail/view/MailViewerUtils.ts
src/mail/view/MailViewerViewModel.ts
src/misc/ClientConstants.ts
src/search/SearchBarOverlay.ts
src/search/view/SearchViewModel.ts
src/settings/SelectMailAddressForm.ts
src/templates/view/TemplatePopup.ts

When the user opens the template popup while writing an email and close the popup without selecting a template, the selected text is replaced by an empty string.
This commit verifies if the text isn't empty before changing it, so we prevent the text replacement by nothing and also keep the behavior of focusing the editor after closing the popup.
fix #3263

fix text is deleted after closing email template popup

---

src/api/worker/facades/lazy/MailFacade.ts
src/api/worker/search/MailIndexer.ts
src/desktop/DesktopMain.ts
src/desktop/ElectronUpdater.ts
src/desktop/sse/SecretStorage.ts
src/desktop/tray/DesktopTray.ts
src/gui/base/Icon.ts
src/mail/editor/MailEditor.ts
src/mail/model/InboxRuleHandler.ts
src/mail/view/MailRow.ts
src/mail/view/MailViewerHeader.ts
src/mail/view/MailViewerUtils.ts
src/mail/view/MailViewerViewModel.ts
src/misc/ClientConstants.ts
src/search/SearchBarOverlay.ts
src/search/view/SearchViewModel.ts
src/settings/SelectMailAddressForm.ts
src/templates/view/TemplatePopup.ts
test/tests/desktop/ElectronUpdaterTest.ts

When the update fails 5 times, the ElectronUpdater has its listeners removed, the user receives a notification informing that the software will try to update later and if the user tries to update again, they receive an error message.
Since there's no more listeners, and we don't want a massive check for updates on our servers, the user doesn't receive the error anymore, just the checkUpdate promise as is resolved as false.
fix #6140

Fix error when update failed 5 times

---

src/calendar/view/CalendarView.ts

Before the changes on Agenda View we always wanted to create a new event using Today as the event's date.
Now, as the Agenda can display events for a selected date, the action of creating a new event while on Agenda View respects the selected date.
fix #6294

Fix adding an event in agenda view does not respect selected day

---

src/calendar/view/CalendarView.ts
src/gui/base/Icon.ts

Fix edit/more button is not clickable for push identifiers
The problem is related to the property onmouseenter added to the icon.
onmouseenter is triggered every time that the mouse moves inside the
container, because it was redrawn and the mouse is already on it.
It was triggering the tooltip and redrawing the component repeatedly.
fix #6293

Fix edit/more button is not clickable for push identifiers

---

src/api/worker/WorkerLocator.ts
src/api/worker/facades/lazy/BlobFacade.ts
src/calendar/view/CalendarView.ts
test/tests/api/worker/facades/BlobFacadeTest.ts

When the user is on day/week view and press the android back key it is redirected to month view, even if it never visited it.
This commit removes the handleBackPress from Calendar header, as it doesn't have to deal with it anymore since we want the same behavior as we have for month view.
fix #6280

Fix back navigation in Calendar working incorrectly for day/week view

---

packages/tutanota-utils/lib/StringUtils.ts
src/api/worker/WorkerLocator.ts
src/api/worker/facades/lazy/BlobFacade.ts
src/calendar/export/CalendarExporter.ts
src/calendar/export/CalendarParser.ts
src/calendar/view/CalendarView.ts
src/misc/parsing/ParserCombinator.ts
test/tests/api/worker/facades/BlobFacadeTest.ts
test/tests/calendar/CalendarImporterTest.ts

* str.replace(pat, rep) only replaces the first instance if pat is a string
* our str.replaceAll method of escaping the control chars is order-dependent. slashes must be done first to prevent double-escaping.
fix #4685
fix f8dd6c9cacf1ad3f5a31baf2629e25c0e4c7b2f0
re-test 
https://github.com/tutao/tutanota/issues/4685
https://github.com/tutao/tutanota/issues/3507
https://github.com/tutao/tutanota/issues/2164

fix incomplete string escape during calendar export

---

src/calendar/view/MultiDayCalendarView.ts
src/gui/base/IconSegmentControl.ts

Added missing card styles to Day/Week view and fixed missing labels
Related to #6253
See https://github.com/tutao/tutanota/issues/6253#issuecomment-1857540423

Added missing card styles to Day/Week view and fixed missing labels

---

src/contacts/view/ContactView.ts
src/misc/ListModel.ts

When the user multi-select any quantity of contacts at the ContactView and after swiping/pressing back two times it doesn't return to MailList view.
This commit makes sure to just handle the back actions and clear the selection if there's any contact selected, otherwise do the default app handling for back swipe/press.
fix #6181

Fix back swipe doesn't return to mail tab after multi-selecting contacts

---

app-android/app/src/main/java/de/tutao/tutanota/AndroidNativeCryptoFacade.kt
app-android/app/src/main/java/de/tutao/tutanota/generated_ipc/KyberEncapsulation.kt
app-android/app/src/main/java/de/tutao/tutanota/generated_ipc/KyberKeyPair.kt
app-android/app/src/main/java/de/tutao/tutanota/generated_ipc/KyberPrivateKey.kt
app-android/app/src/main/java/de/tutao/tutanota/generated_ipc/KyberPublicKey.kt

The compiler removes unused functions, but it does not know that they are to be accessed with JNI, so we must annotate these classes/methods with Keep to prevent them from being optimized out.
tutadb#1736

Declare methods with Keep to avoid them being optimized out

---

src/calendar/view/CalendarMobileHeader.ts

Some mobile devices have large displays, such as tablets, and thus will need to show buttons here.
Closes #6337

Display day/view buttons on mobile calendar layout at all resolutions

---

src/mail/view/MailViewerViewModel.ts

A draft was tried to be loaded as a blob in the phishing check. Disabled the phishing check for drafts since this is not needed.

Fix error on loading old draft, closes #6370

---

packages/tutanota-utils/lib/DateUtils.ts
src/api/worker/search/SearchFacade.ts
src/calendar/date/CalendarEventsRepository.ts
src/calendar/view/CalendarViewModel.ts
src/misc/ListModel.ts
src/search/SearchBar.ts
src/search/model/SearchModel.ts
src/search/model/SearchUtils.ts
src/search/view/SearchView.ts
src/search/view/SearchViewModel.ts

[fix search view missing some updates to the search URL](https://github.com/tutao/tutanota/commit/9a4184716546837ae81248ebb9404efca9c2cec8)
the list that is recreated when the URL changes also calls
updateSearchUrl which then overrides later state changes from the search
bar. re-ordering some operations that happen when clearing the search
bar or routing from quicksearch fixes that.
also cancel the current search when leaving the search view or changing
the search bar content.

Fix calendar search

---

src/gui/base/Overlay.ts
src/gui/main-styles.ts

This prevents all overlays including the minimized editor overlay from being printed when they are visible on screen.
Closes #3598.

Fix overlays being printed

---

app-android/app/src/main/AndroidManifest.xml

This will help system processes & other apps on Android devices correctly categorize the Tuta Mail app.
Close #4119.

Set app category to "Social" in Android manifest

---

src/calendar/view/CalendarAgendaView.ts
src/calendar/view/CalendarTimeIndicator.ts
src/calendar/view/CalendarView.ts
src/gui/base/ViewColumn.ts

Add an option in time indicator's attributes to make the circle not clip to the left, so it can be visible in certain views where overflow-x is not possible.
RE: https://github.com/tutao/tutanota/issues/6284#issuecomment-1893823223

Fix circle agenda view

---

src/calendar/view/CalendarAgendaView.ts
src/gui/ScopedRouter.ts
src/gui/base/PageView.ts
src/search/SearchBar.ts

Fix that vertical scrolling does not work on 1/2 column layouts, and that there is no horizontal scrolling bar, either.
Also remove a styling workaround to fix an issue with scrollbars, as this also fixes the vertical scrollbar randomly appearing.
Fixes #6402 and #6326

Fix agenda view scrolling on different layouts

---

src/calendar/date/CalendarEventsRepository.ts

This solves the error "The Object can not be cloned" that has being thrown on iOS while opening the calendar.
Seems to be related to freezeMap and updateEventMap functions. Need further investigations.
Without this patch:

Fix The object can not be cloned on iOS

---

src/calendar/view/CalendarView.ts

These were still prefixed as _<name> instead of private.
Also remove the scheduler as it was leftover from a WIP commit that was changed later.
Also remove one usage of an unnecessary ts-ignore in CalendarView.

Fix visibility of CalendarView methods; small cleanup

---

src/api/worker/WorkerLocator.ts
src/api/worker/offline/OfflineStorage.ts
src/api/worker/search/Indexer.ts
src/settings/MailSettingsViewer.ts
test/tests/api/worker/search/IndexerTest.ts

There are multiple bugs that all caused this.
1. There was a loop where Indexer.disableMailIndexing() would call init() which would re-initialize mail indexing again. We moved enabling mail indexing out of init() as it was mixing up responsibilities.  We could make init() return whether it is a new database but instead  we rely on isNewOfflineDb which should work the same way.
2. OfflineStorage.init() was not checking for the last update correctly which made all the places that check for isNewOfflineDb work incorrectly.
3. MailSettingsViewer was still passing a reason string in place of a user id which made it impossible to disable search index. We've removed the parameter as it is redundant and inconsistent.
fix #6412

Fix being unable to disable mail search index in apps

---

src/gui/base/Dialog.ts
src/gui/dialogs/ShortcutDialog.ts

This changes the default focus of the `Dialog` to search for & focus a scrollable dialog container if it cannot find any inputs to focus. 
Note this also affects the logs dialog on the login page (the one that appears one you press the version text). Personally, I think this is correct behaviour.
Closes #3190.

Fix the 'Keyboard shortcuts' being unscrollable with keyboard

---

src/api/worker/facades/lazy/GroupManagementFacade.ts
src/templates/TemplateGroupUtils.ts

Seems that the problem have already been fixed, but this commit implements the changes suggested in the issue.
Also, fixes a bug that the contactAdmin_msg was displayed even when the user was the global admin or user was allowed to create a template. This wasn't preventing real allowed users from creating templates.
close #6205

Fix creating a template list causes SessionKeyNotFoundError

---

src/misc/ListModel.ts
src/search/view/SearchViewModel.ts

When the user search for emails and another client do some update that
affects the current results, the affected emails where gone from the
list and the search needs to be done again.
This happens due the fact that the **MOVE** operation consists on the
combination of the DELETE and CREATE operations. So, when the client
receives the DELETE action, the email is removed from the list but not 
re-added when the CREATE action is received.
This commit handles the MOVE operation by checking if it really is a
MOVE operation (the updates contain a CREATE and DELETE for same id) and
then handle to update the current states to match the new listId.
fix #1732

Fix mails disappear from search view when moved

---

src/api/common/EntityTypes.ts
src/api/main/MainLocator.ts
src/api/worker/WorkerLocator.ts
src/api/worker/crypto/CryptoFacade.ts
src/api/worker/crypto/OwnerEncSessionKeysUpdateQueue.ts
src/api/worker/facades/lazy/BlobFacade.ts
src/api/worker/search/IndexUtils.ts
src/mail/editor/MailEditor.ts
src/mail/export/Bundler.ts
src/mail/export/Exporter.ts
src/mail/view/MailListView.ts
src/mail/view/MailViewerToolbar.ts
src/mail/view/MailViewerViewModel.ts
test/tests/api/worker/crypto/CryptoFacadeTest.ts
test/tests/mail/export/BundlerTest.ts
test/tests/mail/view/MailViewerViewModelTest.ts

https://github.com/tutao/tutanota/issues/6275
We assumed that _ownerEncSessionKey is written for a File
when we download it. This is not always the case as the
UpdateSessionKeysService might not have been invoked or
the invocation might have failed.

enforce updating _ownerEncSessionKey for Files if needed

---

app-android/app/src/main/java/de/tutao/tutanota/Contact.kt

On Android we are limited to 500 operations in one batch. Since we need to create a whole contact at once, this commit changes when the batch is applied to right after setting up all operations related to that contact.
fix #6483

Fix too many contact provider operations

---

app-android/app/src/main/java/de/tutao/tutanota/AndroidMobileSystemFacade.kt
app-android/app/src/main/java/de/tutao/tutanota/Contact.kt
app-android/app/src/main/java/de/tutao/tutanota/MainActivity.kt
app-android/app/src/main/java/de/tutao/tutanota/generated_ipc/MobileSystemFacade.kt
app-android/app/src/main/java/de/tutao/tutanota/generated_ipc/MobileSystemFacadeReceiveDispatcher.kt
app-ios/tutanota/Sources/Contacts/StructuredContactTypes.swift
app-ios/tutanota/Sources/GeneratedIpc/MobileSystemFacade.swift
app-ios/tutanota/Sources/GeneratedIpc/MobileSystemFacadeReceiveDispatcher.swift
app-ios/tutanota/Sources/IosMobileSystemFacade.swift
ipc-schema/facades/MobileSystemFacade.json
src/api/common/utils/ErrorUtils.ts
src/contacts/model/NativeContactsSyncManager.ts
src/misc/TranslationKey.ts
src/native/common/generatedipc/MobileSystemFacade.ts
src/native/common/generatedipc/MobileSystemFacadeSendDispatcher.ts
src/settings/ContactsSettingsViewer.ts
src/translations/de.ts
src/translations/de_sie.ts
src/translations/en.ts

When the user tries to enable contact synchronization the app crashes without error message. The reason was a missing Phone type that was added now. 
Insert address when creating contacts on Android and doesn't enable change synchronization permission dropdown to enabled if no permission were granted. Also handle errors of missing contact permissions and displays a message about it.
fix #6494
fix #6500 
close #6492

Fix addresses are not synchronized and sync permission

---

src/api/common/utils/EntityUpdateUtils.ts
src/search/view/SearchViewModel.ts

Previously we would skip the delete part of the moving mail when we try to simulate the update. This lead to issues where folder filter does not match the displayed email.
Now we check for valid destination when optimizing for move batches.
fix #6495

Fix not removing mail results from search on move

---

src/desktop/DesktopMain.ts
src/desktop/db/DesktopSqlCipher.ts

Previously when the database initialization failed (e.g. due to mismatching key) we would not close it but would try to simply delete it. Windows was disallowing it due to the file lock and the app would get stuck with a database that is not opened nor can be deleted.
Now we make sure to close the database if initialization fails. Additionally, we proceed with closing the database if vacuuming fails during the normal database closing so it doesn't prevent us from closing the database. This is not needed to fix the issue at hand but hopefully improves the reliability
fix #5063

[desktop] Fix not closing offline DB before deleting it

---

src/api/common/TutanotaConstants.ts
src/api/entities/sys/ModelInfo.ts
src/api/entities/sys/Services.ts
src/api/entities/sys/TypeModels.js
src/api/entities/sys/TypeRefs.ts
src/api/main/MainLocator.ts
src/api/worker/WorkerLocator.ts
src/api/worker/facades/LoginFacade.ts
src/api/worker/facades/UserFacade.ts
src/api/worker/facades/lazy/MailFacade.ts
src/api/worker/facades/lazy/UserManagementFacade.ts
src/login/recover/RecoverLoginDialog.ts
src/misc/credentials/CredentialsProvider.ts
src/settings/login/ChangePasswordDialogs.ts
test/tests/api/worker/facades/LoginFacadeTest.ts
test/tests/misc/credentials/CredentialsProviderTest.ts

The current modern KDF is Argon2id, but the migration can be reused for future KDFs.
This includes
- when creating a new session
- when resuming a session
Also migrate locally stored credentials.
tutadb#1655

Migrate to Argon2id on login

---

src/gui/main-styles.ts
src/subscription/PaymentMethodInput.ts

After converting PayPal icon to svg we failed to add explicit size for it so it had no size.
fix #6559

Fix PayPal logo size

---

src/misc/TranslationKey.ts
src/settings/mailaddress/AddAliasDialog.ts
src/settings/mailaddress/MailAddressTable.ts
src/settings/mailaddress/MailAddressTableModel.ts
src/translations/de.ts
src/translations/de_sie.ts
src/translations/en.ts

It is not true that legacy plans can have unlimited custom domains. Make it not display anything here to prevent confusion.
Fixes #6540

Don't show incorrect mail address info on legacy plans

---

src/api/common/Env.ts
src/calendar/gui/eventeditor-view/CalendarEventEditDialog.ts
src/contacts/ContactEditor.ts
src/contacts/view/CalendarViewerActions.ts
src/contacts/view/ContactViewerActions.ts
src/gui/base/ListUtils.ts
src/gui/base/TextField.ts
src/gui/dialogs/ShortcutDialog.ts
src/mail/editor/MailEditor.ts
src/misc/KeyManager.ts
src/misc/NavShortcuts.ts
src/native/main/WebDesktopFacade.ts
src/settings/EditOutOfOfficeNotificationDialog.ts
src/templates/view/TemplateSearchBar.ts

Apple devices have this swapped, so we need to register it swapped. For example, CTRL-S on Linux is equivalent to CMD-S on macOS (for saving a draft).
Also fix KeyManager's private fields, since those have not been properly marked as private, yet.
Fixes #6503

Swap ctrl/meta on macOS/iOS

---

src/calendar/gui/CalendarGuiUtils.ts
src/gui/base/Color.ts
test/tests/gui/ColorTest.ts

It doesn't make sense to error here and make the entire app unusable, so we just fallback to a blue color.
Fixes #6515

Fallback to blue if an invalid color is passed

---

src/search/view/SearchViewModel.ts

Updating the loading status of the list model updates the state, so in some cases the new search type is being considered but the old state is still around.
fix #6497

Reset list selected items and if mail is actually there

---

src/calendar/view/CalendarView.ts
src/calendar/view/CalendarViewModel.ts
src/calendar/view/EventDragHandler.ts
src/calendar/view/MultiDayCalendarView.ts
test/tests/calendar/EventDragHandlerTest.ts

Moving the cursor outside of the calendar view cancels the drag event.
Also do not allow dragging all-day events in the mobile view, as this does not work properly with the mobile header.
Fixes #6513

Fix dragging all-day events

---

src/contacts/ContactImporter.ts

When user receives a vCard as attachment an import option is displayed inside the attachment bubble, allowing the user to preview and import the users contained inside that vCard.
The app handles both vCard mime types, text/vcard and text/x-vcard
close [#6469](https://github.com/tutao/tutanota/issues/6469)

Import vCard from Attachment and from Native

---

src/contacts/view/ContactView.ts

Call selectNone on the list model to clear the selection after deleting a selection of contacts.
Fixes #6623

Reset selection in contact list view when deleting selected contents

---

src/calendar/view/CalendarMobileHeader.ts

This should be newEvent_action; createEvent_label is used as a placeholder for when the event name is empty in the edit event dialog.
Fixes #6626

Fix wrong label on new event button tooltip

---

src/mail/view/MinimizedMailEditorOverlay.ts

This puts the overlay back into the bottom right corner.
Closes #6622.

Fix the minimized mail editor overlay being too high

---

src/calendar/date/CalendarEventsRepository.ts
src/calendar/date/CalendarUtils.ts
test/tests/calendar/CalendarUtilsTest.ts

Took out some code that was no longer useful. Long events are now always
taken out when updated, the new event will automatically be filled in.
close #6491
close #6444

Events are removed immediately when deleting single or changing rules

---

src/settings/AboutDialog.ts

This commit makes the Version Number, License and Company Name able to be copied
fix #6605

Makes version number copiable from about Dialog

---

src/search/SearchBar.ts

The users were able to trigger an empty search result even without accepting to enable the search index. Now, even if the user tries to bypass the dialog, the SearchBar will not return any result
fix #2689

Fix SearchBar returning no results even with not enabled index

---

src/subscription/Captcha.ts
test/tests/Suite.ts
test/tests/subscription/SignupFormTest.ts

Fix Captcha matching hours 25-29 and allows it to match times that will never be correct (but can be checked locally).
Add missing SignupFormTest to the test suite.
Fixes #6316

Fix client-side captcha verification; fix SignupFormTest

---

src/calendar/view/MultiDayCalendarView.ts

The ideal solution in my eyes is to rewrite the calendar header so that the header and body for the day are in one column flex. Using flex is better than constantly calculating the sizes of elements ourselves both in code simplicity and performance.
Until then, this quick workaround seems to do the trick.
Closes #6521.

Fix the all day events in the calendar being misaligned on desktop

---

src/api/common/TutanotaConstants.ts
src/api/common/mail/CommonMailUtils.ts
src/mail/model/MailUtils.ts
src/mail/view/CollapsedMailView.ts
src/mail/view/MailViewerHeader.ts
src/mail/view/MailViewerViewModel.ts
test/tests/api/common/mail/CommonMailUtilsTest.ts

15713f1 changed to how we detect and display system notifications. Since tuta-crypt we send all system notifications from the system group address. It was attempting then to replace the sender with reply-to address.
This cannot work because system notifications are sent with MailDetails now, and we do not know authStatus nor replyTos until we load MailDetails.
This commit simplifies the handling by not attempting to replace the sender but by hiding it for all system notification mails. Now there will be more cases when they are hidden then before but it should have no effect since sender of system notification emails is irrelevant and replyTos will be used to write a reply.
fix #6708
Please review carefully. Please try legacy announcements/invoice emails/tutao team emails and MailDetails …

Fix an issue with system notification emails

---

src/contacts/model/NativeContactsSyncManager.ts

This commit fixes the problem that was preventing users from fully disable the contact sync. Now when the settings are changed, they're reflected into deviceConfig.
fix #6742

Fix can't disable contact sync

---

buildSrc/bump-version.js

By default, npm tries to install the dependencies after running `npm version`. This has lead to issues where npm would try to find a version of a module that doesn't exist yet or no longer exist.
We have disabled this behavior since we don't want to have individual complete node_modules for each package anyway, each package's node_modules should contain only what's necessary. That's why we've been deleting them manually before.
With --workspaces-update false npm skips the step

Fix bump-version script

---

.github/workflows/release.yml
.github/workflows/swift-test.yml
.github/workflows/test.yml

This changes the `paths` attribute to follow the style used in GitHub Action's docs. This PR also applies the security practices used in the Swift CI to the rest of the workflows. The hardening should help mitigate any attacks from compromised actions. I also updated the actions.
Closes #6754.

Fix the Swift CI running without iOS changes and harden the other workflows

---

app-ios/tutanota.xcodeproj/project.pbxproj
app-ios/tutanota/Sources/Contacts/IosMobileContactsFacade.swift
app-ios/tutanota/Sources/Contacts/StructuredContactTypes.swift
app-ios/tutanota/Sources/Utils/MurMurHash.swift

The original contact hashing used to check contact changes was based on Swift's implementation of Hashable that unfortunately is granted to be the same just during the program execution, leading to different hashes every app startup.
This commit replaces the use of Hashble by an implementation of MurmurHash, leading to stable hashes across multiples app startup.
fix #6776

Fix iOS contact hashing

---

src/calendar/gui/eventeditor-view/RepeatRuleEditor.ts
src/calendar/gui/pickers/DatePicker.ts
src/calendar/gui/pickers/TimePicker.ts
src/gui/AriaUtils.ts
src/gui/base/TextField.ts
src/misc/KeyManager.ts

This adds keyboard controls based of the material & Gnome date pickers controls in order to fix the tab indexing of the event editor. This also includes a fix for the highlight circle appearing in padding days. The flow style names in `TimePicker` were also removed as a byproduct.
Closes #6656.

Add keyboard controls to the date picker

---

src/calendar/model/CalendarModel.ts
src/calendar/view/CalendarViewModel.ts
test/tests/calendar/CalendarViewModelTest.ts

Users were able to move any events belonging to any calendar that they participate. This commit adds a verification if they are allowed to move an event before starting the drag event, preventing it if they aren't.
fix https://github.com/tutao/tutanota/issues/6735

Fix Non-editable events are draggable on Calendar View

---

src/calendar/export/CalendarParser.ts
src/misc/parsing/ParserCombinator.ts
test/tests/calendar/CalendarParserTest.ts

Adds events when importing event if alarm is not properly parsed
fix #6753

Changed parseDuration to parse all duration combinations

---

src/gui/base/NotificationOverlay.ts
src/gui/main-styles.ts

This commit sets the notification width to "fit-content" preventing the notification from disappearing while resizing the screen.
Tested with report error and autoresponder notification
fix #6430

Fix notification resize incorrectly

---

src/gui/editor/Editor.ts
src/gui/editor/HtmlEditor.ts

Turns out this breaks navigation and templates.
Fixes #6759

Do not create an emspace whenever tab is pressed

---

src/calendar/gui/day-selector/DaySelector.ts
src/gui/base/Carousel.ts

This fixes the issues with pressing a date going to the previous month and the wrong week being shown etc. The issue I linked also mentions wanting to return to previous views on back events which I am not sure whether we want to.
Closes #6784.
Closes #6734.

Fix the calendar date picker showing the wrong month/week on Chromium

---

src/calendar/gui/CalendarGuiUtils.ts
src/calendar/gui/day-selector/DaySelector.ts
src/calendar/view/CalendarMonthView.ts

This adds mouse wheel controls as suggested by the issue to the `DaySelector`.
Closes #1719.

Fix not being able to scroll calendar without gestures in mobile layout

---

src/app.ts

We do not show the 404 page on the webapp correctly if paths that did not exist include more than one slash.
e.g. `/test/test`.

fix 404 page not shown for paths with more than one slash

---

src/calendar/gui/pickers/TimePicker.ts
src/gui/main-styles.ts

This fixes the display but the dialog still displays in the wrong time format. A custom time picker for mobile will be created later, see #6765.
Closes #6339.

Fix the time picker displaying the wrong time format on mobile

---

src/api/main/MainLocator.ts
src/calendar/model/CalendarModel.ts
src/calendar/view/CalendarViewModel.ts
src/misc/DeviceConfig.ts
test/tests/calendar/CalendarViewModelTest.ts

After #6736 the theme was being called too early because of a chain of calls from CalendarModel -> CalendarUtils -> CalendarGuiUtils -> ... -> theme -> DeviceConfig throwing an error inside deviceConfig.
This commit moves the function canFullyEditEvent to CalendarViewModel making sure that all the GUI stuff have been already loaded.
fix #6795

Fix window is not defined when starting the desktop app

---

src/settings/mailaddress/AddAliasDialog.ts

This was the boolean expression devised by wec's truth table.
Closes #6808.

Fix not being able to add a custom domain when the domain limit is maxed

---

src/api/common/TutanotaConstants.ts

SecondFactorType.webauthn refers to the actual U2F setting in the client
Fixes tutanota-next#39

Remove SecondFactorTypeNames

---

src/gui/editor/Editor.ts

This reverts commit f0d6f2c28a50ac1ec70636e3efb1952980dca0f1.
Squire triggers some DOM modifications in getCursorPosition() and that causes it to skip firing `input` event in `_docWasChanged()`, probably because there are multiple DOM mutations that are done in the same event loop and MutatationObserver is only invoked once for them.
fix #6831

Fix paste not triggering `input` events in Editor

---

src/calendar/view/CalendarEventBubble.ts
src/gui/main-styles.ts

I also experimented with a CSS flow based `CalendarEventBubble` to simplify the code but that is still too difficult because of the absolute positioning and sizing used in `CalendarDayEventsView`.
Closes #6582.

Fix the name of events overflowing onto the time

---

app-ios/tutanota/Sources/Contacts/IosMobileContactsFacade.swift

Avoid `_$!XXXXX!$_` names by using CNLabeledValue.localizedString to localize contact labels before importing them.
Fixes #6799

[ios] Localize custom labels when doing contact import

---

app-ios/tutanota/Sources/Contacts/IosMobileContactsFacade.swift
app-ios/tutanota/Sources/Contacts/StructuredContactTypes.swift

We've been taking notes into account for hashing but we cannot read or write notes from native so it would mismatch every time.
We can add it back once we can access notes field.
fix #6827
Co-authored-by wrd <wrd@tutao.de>

[ios] Fix trying to updates contacts with notes on every sync

---

src/gui/base/Dropdown.ts
src/mail/view/MailGuiUtils.ts

Label is a human-readable accessibility description, and it might include parts that we don't want to filter by.
We opted into preferring text to label because that's what users are more likely to see. It is not perfect as in some cases (e.g. folder names) we display something that we don't want to filter by (folder indentation level with dots) but it is less surprising. A proper fix would be to introduce another value/function for filtering.
#5353

Fix dropdown filtering by wrong field

---

schemas/sys.json
src/api/entities/sys/ModelInfo.ts
src/api/entities/sys/Services.ts
src/api/entities/sys/TypeModels.js
src/api/entities/sys/TypeRefs.ts
src/api/entities/tutanota/ModelInfo.ts
src/api/entities/tutanota/Services.ts
src/api/entities/tutanota/TypeModels.js
src/api/entities/tutanota/TypeRefs.ts
src/api/worker/offline/OfflineStorageMigrator.ts
src/api/worker/offline/migrations/sys-v94.ts
src/api/worker/offline/migrations/sys-v96.ts
src/api/worker/offline/migrations/sys-v97.ts
src/misc/SubscriptionDialogs.ts
src/subscription/BuyDialog.ts
src/subscription/SubscriptionViewer.ts

As of 2020 the canceledPremiumAccount boolean value has always been set to false therefore this value is no longer needed, and we can remove it. Additionally, this commit includes model changes for the new TranslationService and removes the following unused services and types.
* PREMIUM_FEATURE_SERVICE
* PREMIUM_FEATURE_DATA
* PREMIUM_FEATURE_RETURN
* MIGRATE_TO_V18_SERVICE
* DEFAULT_SYSTEM_MIGRATE_DATA
* REGISTRATION_CONFIG_SERVICE
* REGISTRATION_CONFIG_RETURN
* SHARE_SERVICE
* SHARE_DATA

remove canceledPremiumAccount flag from customer type (#6883)

---

src/desktop/ApplicationWindow.ts
src/desktop/DesktopMain.ts
src/desktop/DesktopWindowManager.ts
test/tests/desktop/ApplicationWindowTest.ts

This commit fixes the dictionaries being downloaded too late causing electron to use the default fallback download url.

Fix dictionaries being downloaded too late

---

src/contacts/view/ContactView.ts
src/gui/base/BaseSearchBar.ts
src/mail/view/MailView.ts
src/search/SearchBar.ts

This is a temporary mitigation until we switch to using the offline db key instead of the user group key for the indexer.
Related to #6305.

Show the search bar as disabled when offline in contact and mail views

---

src/api/common/TutanotaConstants.ts
src/api/common/mail/CommonMailUtils.ts
src/api/entities/tutanota/ModelInfo.ts
src/api/entities/tutanota/TypeModels.js
src/api/entities/tutanota/TypeRefs.ts
src/api/worker/crypto/CryptoFacade.ts
src/api/worker/facades/lazy/MailFacade.ts
src/api/worker/offline/OfflineStorageMigrator.ts
src/api/worker/offline/migrations/tutanota-v71.ts
src/mail/model/MailUtils.ts
src/mail/view/MailViewerHeader.ts
test/tests/api/common/mail/CommonMailUtilsTest.ts
test/tests/api/worker/crypto/CryptoFacadeTest.ts
test/tests/api/worker/facades/MailFacadeTest.ts

To show the pq padlock symbol for the sender we introduced another enum value for the encryptionAuthStatus on Mail instances which is only set for the sent mail. It is only set in case the mail is confidential and all recipients support the TutaCrypt protocol.
see tutadb1788

Show pq padlock symbol for sent mail, tutadb 1788

---

package-lock.json
package.json

Existing local repos: run `rm -rf node_modules/better-sqlite3 && npm install && rm -r test/native-cache` for the changes to take effect.

Update better-sqlite3 commit for browser test crash fix

---

src/api/worker/facades/LoginFacade.ts
test/tests/api/worker/facades/LoginFacadeTest.ts

#6935
When doing a login with offline data we initialize the user facade from offline cache. In case another client changed the kdf type (argon2 migration) we need to update the user facade as soon as we go online to unlock the user group key correctly.

fix login with offline data after argon2 migration by a different client. 

---

src/api/common/TutanotaConstants.ts
src/api/worker/facades/LoginFacade.ts
test/tests/api/worker/facades/LoginFacadeTest.ts

We disable argon2 migration to prevent that client with offline support prior to 229.240513.0 have unexpected errors

disable argon2 migration

---

src/RootView.ts
src/contacts/view/ContactListRecipientView.ts
src/contacts/view/ContactRow.ts
src/gui/SelectableRowContainer.ts
src/gui/base/List.ts
src/gui/base/ViewColumn.ts
src/gui/nav/ViewSlider.ts

There is still a possible issue where the tab order and the selection via the arrow keys do not align. If you tab to the third row then press down for instance, the forth row will not be selected.
I am not sure whether to fix this as the arrow keys and tab do slightly different things. The arrow keys focus and open a row while the tab just focuses a row.
Closes #5361.

Fix keyboard navigation in the single-column mail view

---

app-ios/tutanota/Sources/Contacts/IosMobileContactsFacade.swift

This is to improve debugging errors with predicates.

[ios] Wrap ContactStore.enumateContacts with ContactStoreError

---

src/mail/view/MailViewerViewModel.ts

linkify interacted badly with the sanitizer making some emails display as empty
close #6930

Removes linkify pass when displaying email

---

src/api/worker/invoicegen/InvoiceTexts.ts
src/api/worker/invoicegen/PdfInvoiceGenerator.ts
test/tests/api/worker/invoicegen/PdfInvoiceGeneratorTest.ts

Expanded the text that is shown when a VatID number should be displayed.
Also split invoice translation key into two to prevent overflow.
Close #6947

Fix VatID number not shown + text overflow on PDF

---

buildSrc/DevBuild.js
package-lock.json
package.json
packages/tuta-wasm-loader/lib/WasmHandler.ts
packages/tuta-wasm-loader/lib/index.ts

This commit adds the resolving of wasm files also available to calls from the Node part, reading the file and returning the exports object.

Handle wasm loading from Node process

---

src/calendar/gui/eventeditor-view/CalendarEventEditView.ts

This commit gets the modulus of the parsed integer, preventing any non-positive value from being added as a valid reminder time.
fix #6951

Prevent negative reminder time

---

src/api/common/Env.ts
src/api/common/TutanotaConstants.ts
src/login/LoginForm.ts
src/misc/WhitelabelCustomizations.ts

This commit removes the check for the DisableSavePassword feature since it isn't included anymore in our client and can be safely removed.
fix #6863

Fix whitelabel domains unable to store credentials

---

src/login/PostLoginActions.ts

This commit adds the whitelabel domain as the themeId for the whitelabel theme in case it doesn't have an Id.
Co-authored-by: and <and@tutao.de>
Fixes #7090

Fixes whitelabel themes being merged with default ones

---

src/login/CredentialRemovalHandler.ts
src/login/LoginViewModel.ts
test/tests/login/LoginViewModelTest.ts

Added minimum handling for the cases when secret storage is not avilable so that the users don't see the unexpected error dialog.
Also changed CredentialRemovalHandler to allow using encrypted credentials.
Fix #7077

[desktop] Handle DeviceStorageUnavailableError on login

---

src/gui/base/buttons/BaseButton.ts

Title causes the hover text, and aria-label should derive from title.
fix #7031

Use title instead of aria-label in BaseButton

---

app-android/app/src/main/java/de/tutao/tutanota/MainActivity.kt

fix #7035
example:
```html
<table background="radial-gradient(circle, rgba(255,242,0,1) 0%,rgba(255,203,3,1) 75%)" </table>
```
browser interprets background as relative URL and we crash when we try to load the resource

Move getting asset path into try/catch statement in MainActivity

---

src/calendar/gui/eventpopup/CalendarEventPopup.ts

My old enemy, JavaScript's dynamic binding strikes again.
Closes #7107.

Fix the delete event popup not closing

---

src/calendar/gui/day-selector/DaySelectorPopup.ts

Fix both arrow buttons in the Day Selector Popup going to the previous month

---

.github/workflows/kotlin-test.yml

This commit implements the Android Lint and Tests into the pipeline to check if everything is ok at least with the written unit tests.
Closes #6678

Add Android lint & test to GitHub CI

---

tuta-sdk/rust/Cargo.lock
tuta-sdk/rust/Cargo.toml
tuta-sdk/rust/src/crypto/crypto_facade.rs
tuta-sdk/rust/src/crypto/mod.rs
tuta-sdk/rust/src/crypto_entity_client.rs
tuta-sdk/rust/src/element_value.rs
tuta-sdk/rust/src/entities/entity_facade.rs
tuta-sdk/rust/src/entities/mod.rs
tuta-sdk/rust/src/entity_client.rs
tuta-sdk/rust/src/instance_mapper.rs
tuta-sdk/rust/src/lib.rs
tuta-sdk/rust/src/metamodel.rs
tuta-sdk/rust/src/util/entity_test_utils.rs
tuta-sdk/rust/src/util/mod.rs

This PR introduces 'CryptoEntityClient' a wrapper around `EntityClient` that utilizes `CryptoFacade` to provide automatic encryption/decryption to entity operations. Only the entity downloading functionality has been implemented as per the issue.
Closes #6955.

[SDK] Encrypted entity client with downloading

---

buildSrc/DesktopBuilder.js
buildSrc/DevBuild.js
buildSrc/buildUtils.js
buildSrc/bump-version.js
buildSrc/electron-package-json-template.js
buildSrc/env.js
buildSrc/fetchDictionaries.js
buildSrc/getNativeLibrary.js
buildSrc/graph.js
buildSrc/nativeLibraryProvider.js
buildSrc/publish.js
buildSrc/tsconfig.json
buildSrc/updateLibs.js
packages/tuta-wasm-loader/lib/index.ts

It isn't invoked automatically anywhere but the editors should pick it up and it can also be run manually.
It also fixes few little issues, e.g. getPrebuiltNativeModuleForWindows was getting called with the right arguments.

[build] Add type checking to buildSrc

---

src/calendar-app/calendar/view/CalendarView.ts
src/common/gui/FolderColumnView.ts

This commit prevents the redraw event from being fired when the sidebar is scrolled. The redraw isn't needed since we change the dom directly through target.
Co-authored-by: André Dias <and@tutao.de>
Fixes #7179

[Calendar] Fixes calendar sidebar scrolling performance issue

---

src/common/api/main/MainLocator.ts
src/common/misc/TranslationKey.ts
src/common/native/main/SystemPermissionHandler.ts
src/common/native/main/wizard/SetupWizard.ts
src/common/native/main/wizard/setupwizardpages/SetupContactsPage.ts
src/common/native/main/wizard/setupwizardpages/SetupNotificationsPage.ts
src/mail-app/translations/de.ts
src/mail-app/translations/de_sie.ts
src/mail-app/translations/en.ts

This commit adds the contacts permission page instead of the contacts
import and sync when using the Calendar app. The permission is needed
to suggest contacts when creating an event and inviting guests.
Co-authored-by: André Dias <and@tutao.de>
Fixes https://github.com/tutao/tutanota/issues/7150

[Calendar] Contacts permission inside Onboarding Wizard

---

tuta-sdk/rust/Cargo.lock
tuta-sdk/rust/Cargo.toml
tuta-sdk/rust/src/lib.rs
tuta-sdk/rust/src/logging.rs

[sdk] Add log, oslog, and android_log
Use the log crate by rust-lang for logging.
Use android_log for Android.
Use oslog for iOS.
Use simple_log for stdout.
Closes #7151

[sdk] Add log, oslog, and android_log

---

app-android/app/build.gradle
app-android/app/src/main/AndroidManifest.xml
app-android/app/src/main/java/de/tutao/tutanota/AndroidFileFacade.kt
app-android/app/src/main/java/de/tutao/tutanota/AndroidNativeCryptoFacade.kt
app-android/app/src/main/java/de/tutao/tutanota/AndroidThemeFacade.kt
app-android/app/src/main/java/de/tutao/tutanota/LifecycleJobService.kt
app-android/app/src/main/java/de/tutao/tutanota/MainActivity.kt
app-android/app/src/main/java/de/tutao/tutanota/ModelTypes.kt
app-android/app/src/main/java/de/tutao/tutanota/Utils.kt
app-android/app/src/main/java/de/tutao/tutanota/credentials/AndroidNativeCredentialsFacade.kt
app-android/app/src/main/java/de/tutao/tutanota/credentials/CredentialsDao.kt
app-android/app/src/main/java/de/tutao/tutanota/data/AlarmInfoDao.kt
app-android/app/src/main/java/de/tutao/tutanota/data/UserInfoDao.kt
app-android/app/src/main/java/de/tutao/tutanota/push/LocalNotificationsFacade.kt
app-android/app/src/main/java/de/tutao/tutanota/push/NetworkObserver.kt
app-android/app/src/main/java/de/tutao/tutanota/push/PushNotificationService.kt
app-android/app/src/main/java/de/tutao/tutanota/push/SseStorage.kt
app-android/app/src/test/java/de/tutao/tutanota/AndroidNativeCredentialFacadeTest.kt
app-android/build.gradle
tuta-sdk/android/build.gradle
tuta-sdk/android/sdk/build.gradle.kts

Close https://github.com/tutao/private-issues/issues/207

Update Android SDK target to 14

---

src/misc/credentials/CredentialsProvider.ts
test/tests/misc/credentials/CredentialsProviderTest.ts

This will result in the login form being consistent regardless of what order users were added/logged in.
Closes #7295

Sort result of getInternalCredentialsInfos

---

src/common/search/view/SearchRouter.ts
src/mail-app/search/model/SearchUtils.ts
src/mail-app/search/view/SearchView.ts
src/mail-app/search/view/SearchViewModel.ts

Fix double-clicking on a search category logging out the desktop client

---

src/mail-app/contacts/view/ContactView.ts
src/mail-app/contacts/view/ContactViewModel.ts

This PR makes the show contact option open the contacts view with the relevant contact selected. It opens the details view on single column view. There is also a commit which removes `targetContactId` because we never set it to anything other than `null`.
Closes #7256.

Fix show contact not displaying the contact

---

app-android/app/src/main/java/de/tutao/tutanota/push/LocalNotificationsFacade.kt
tuta-sdk/rust/sdk/src/crypto_entity_client.rs
tuta-sdk/rust/sdk/src/entities/accounting.rs
tuta-sdk/rust/sdk/src/entities/base.rs
tuta-sdk/rust/sdk/src/entities/entity_facade.rs
tuta-sdk/rust/sdk/src/entities/gossip.rs
tuta-sdk/rust/sdk/src/entities/mod.rs
tuta-sdk/rust/sdk/src/entities/monitor.rs
tuta-sdk/rust/sdk/src/entities/storage.rs
tuta-sdk/rust/sdk/src/entities/sys.rs
tuta-sdk/rust/sdk/src/entities/tutanota.rs
tuta-sdk/rust/sdk/src/entities/usage.rs
tuta-sdk/rust/sdk/src/instance_mapper.rs
tuta-sdk/rust/sdk/src/json_serializer.rs
tuta-sdk/rust/sdk/src/login/login_facade.rs
tuta-sdk/rust/sdk/src/type_models/monitor.json
tuta-sdk/rust/sdk/src/type_models/sys.json
tuta-sdk/rust/sdk/src/type_models/tutanota.json
tuta-sdk/rust/sdk/src/util/entity_test_utils.rs
tuta-sdk/rust/sdk/test_data/email_response_attachments.json

Fix invalid value attachments

---

app-ios/TutanotaNotificationExtension/Info.plist
tuta-sdk/android/sdk/build.gradle.kts

- [iOS] Fix missing `CFBundleDisplayName` in TutanotaNotificationExtension 
- [Android] Fix `ReleaseTest` targets not building Rust part

[iOS/Android] Fix build issues

---

src/common/api/main/PageContextLoginListener.ts

We have added a migration to add `encryptedPassphraseKey` and we've been erroneously calling `getDecryptedCredentialsByUserId()` before any credentials have been stored.
Now we first make sure that the credentials are there and then we try to fetch and decrypt them.
fix #7330

Fix key error after the first login

---

src/mail-app/contacts/view/ContactView.ts
src/mail-app/contacts/view/ContactViewModel.ts
src/mail-app/mail/view/MailViewer.ts

This is another spin on solving #7256.
This reverts 5be83674 and 26dfa0f5 as they introduced some issues with initialization, namely `initOnce` could run multiple times.
In this commit we try to acknowledge that existing URL pattern is not sufficient to distinguish between the cases as we might have selection without focus.
Instead, we introduce an explicit argument to focus the item details.
We considered synchronizing the column focus state using this argument in all cases but this would entail a larger refactoring.

Fix contact selection issues

---

src/common/subscription/PriceUtils.ts
src/common/subscription/UpgradeConfirmSubscriptionPage.ts
src/common/subscription/UpgradeSubscriptionPage.ts
src/common/subscription/UpgradeSubscriptionWizard.ts

This fixes the currency symbol being included and the decimal separator in the call to the Braintree card verification causing it to fail.
It is not possible to have `getSubscriptionPriceWithCurrency` return without currency formatting because the return of `getPlanPrices` cannot be changed as `StoreKit` can only return the price in the local currency.
Closes #7370.

Fix the credit card verification

---

src/common/api/worker/facades/KeyRotationFacade.ts
src/common/subscription/DeleteAccountDialog.ts
test/tests/api/worker/facades/KeyRotationFacadeTest.ts

* get to the last dialog for confirming the account deletion from the settings 
* check that it's asking for the password for confirmation, not "please enter a new password" in the password fields' help text

fix delete account dialog asking for a new password

---

src/common/api/worker/facades/LoginFacade.ts

We need to initialize the kdfVersion and the phassphrase when resuming a session in order to successfully migrate the kdf and be able to rotate group keys.
#tutadb1835

always initialize kdfVersion and passphrase when resuming session

---

ci/Ios.Jenkinsfile
ci/Publish-CalendarMobileArtifacts.Jenkinsfile
ci/jenkins-lib/util.groovy

This commit adds a new jenkins file responsible for publishing the Calendar mobile artifacts to each app store on the public release track.
We also move the runFastLane function to util.groovy since it's being used on multiple files.

[CI] Add Jenkins publish calendar mobile artifacts

---

src/common/gui/ThemeController.ts
src/common/gui/builtinThemes.ts
src/common/gui/theme.ts
src/common/login/LoginView.ts
src/common/misc/TranslationKey.ts
src/common/native/main/wizard/setupwizardpages/SetupThemePage.ts
src/common/settings/AppearanceSettingsViewer.ts
src/mail-app/translations/de.ts
src/mail-app/translations/de_sie.ts
src/mail-app/translations/en.ts
test/tests/gui/ThemeControllerTest.ts
test/tests/settings/whitelabel/CustomColorEditorTest.ts

Adds two new colors to Mail and Calendar app and removes the blue theme, replacing it by the new Blue theme using Calendar Colors. Also adapts how the themes are displayed, Light and Dark can be Light Blue/Red and Dark Blue/Red this will depend on which app the user is running.
- Mail App:
- Light
- Dark
- Light Blue
- Dark Blue
- Calendar App:
- Light
- Dark
- Light Red
- Dark Red

Adds new App colors

---

src/common/api/worker/offline/migrations/tutanota-v75.ts
src/common/api/worker/rest/DefaultEntityRestCache.ts

We exclude the audit log entries from the offline cache in order to fix unexpected error after doing the admin group key rotation. #tutadb1855
The admin group with a new key pair is updated in the same batch and as the audit log entry for this update is written. We cannot yet decrypt the audit log with new key at this point.
The simple fix is to exclude it from the offline cache. That way it will only be decrypted later when the new key is available.

Exclude AuditLogEntries from offline cache

---

src/common/api/worker/offline/migrations/tutanota-v74.ts

We need to delete all CalendarEvents since we changed the format for storing customIds (CalendarEvents use customIds) in the offline database. All entities with customIds, that are stored in the offline database (e.g. CalendarEvent, MailSetEntry), are from now on stored in the offline database using a **base64Ext** encoded id string.

fix CalendarEvents offline storage migration for TutanotaModeV74

---

src/common/api/worker/offline/migrations/tutanota-v74.ts
src/common/api/worker/offline/migrations/tutanota-v75.ts

when logging in, the app assumes that the
UserSettingsGroupRoot is cached if the UserGroupInfo is cached.
Deleting UserGroupInfos as well makes sure that we fall back to the sync login to redownload the changed entities

fix offline migrations for tutanota 75

---

src/common/api/worker/facades/LoginFacade.ts
src/common/misc/credentials/CredentialsProvider.ts
src/common/settings/login/ChangePasswordDialogs.ts
test/tests/misc/credentials/CredentialsProviderTest.ts

After we've added passphraseKey to credentials we forgot to update it in stored credentials on password change.
This commit changes it in a way that both encryptedPassword and encryptedPassphraseKey are updated at the same time.
Fix #7462

Fix credentials being invalid after changing the password

---

buildSrc/esbuildUtils.js

After changing the app structure we didn't fix the esbuild plugin that marks all translations as external.
Now we fixed the filter and also made it more generic.

[build] Fix huge debug builds caused by translations

---

app-android/app/src/main/AndroidManifest.xml
app-android/app/src/main/java/de/tutao/tutanota/AndroidMobileContactsFacade.kt
app-android/app/src/main/java/de/tutao/tutanota/StubSyncService.kt
app-android/app/src/main/res/xml/syncadapter.xml

Certain contact apps require the account to be syncable. In order to do this, we implement a stubbed sync service and adapter which does nothing and ask Android not to call it. Preexisting installations of the app will need to turn contact synchronization off and on again to receive this fix.
Closes #6568.

Fix synchronized contacts not appearing in some contact apps

---

buildSrc/getNativeLibrary.js

There was a duplicate short option '-e' which became an error after commander update. the duplicate one was not used.

[build] Fix arguments to getNativeLibrary

---

src/common/api/worker/EventQueue.ts

MailSetEntry which points to same mail but from
different folder will still have the same instanceListElementId. Having them in move-able types means they are treated as same ( even though they point to same mail from different folder ) which is not correct

Remove MailSetEntry from MovableTypes List in EventQueue

---

src/common/api/worker/facades/lazy/MailFacade.ts
src/common/api/worker/search/SearchFacade.ts
src/common/mailFunctionality/MailModel.ts
src/mail-app/mail/view/ConversationViewModel.ts
src/mail-app/mail/view/MailViewModel.ts

We noticed that we receive more reports about NotFoundErrors by our users since the last release. All of them where caused by moved mails that we tried to download when processing entity events.
Test notes:

fix 404s for moved mails

---

src/common/api/worker/facades/lazy/CalendarFacade.ts

Before making the REST request to update a calendar event we assign some technical attributes like _id and _ownerEncSessionKey to the new/updated event. The assignment of the _ownerKeyVersion was missing wich is required if we have another version of the group key. It is suspicious that we have to do this assignement at all because before editing the event we clone the existing entity and all attributes should have been assigned to the new one already. It should probably also not the responsibility of the updateCalendarEvent function to assign these attributes. This commit just fixes this issue itself so the user does not get the error but we should review the clone and update mechanism.
fixes #7533

Assign correct ownerKeyVersion when updating calendar event

---

src/common/api/worker/offline/OfflineStorage.ts
src/common/api/worker/rest/CacheStorageProxy.ts
src/common/api/worker/rest/DefaultEntityRestCache.ts
src/common/api/worker/rest/EphemeralCacheStorage.ts
src/common/api/worker/search/SearchFacade.ts
test/tests/api/worker/offline/OfflineStorageTest.ts

to avoid excessive entity updates and inconsistent offline storage, we don't send entity updates for each mail set migrated mail. instead we detect the mail set migration for each folder and drop its whole mail list from the offline cache.
we could fix up the database when we receive the changed folder, but that would involve re-doing the migration locally and will lead to very long entity event handling that might get interrupted, breaking the offline database anyway.

Improve mail set migration performance

---

src/common/api/common/utils/EntityUtils.ts

safari respects the standards and gives us Invalid Date / NaN with our noncompliant date string. using an ISO date should fix the random issues we saw because of that.

fix invalid default offline cutoff date

---

.github/workflows/test.yml
buildSrc/DevBuild.js
buildSrc/buildWebapp.js

After splitting the worker into two, we forgot to set the correct path for the built worker to worker-bootstrap. Now it gets the correct location  depending on which app is being built.
It also adds a new test to the github pipeline to ensure that both apps can be built using the rollup and respect the import rules.

Fix build scripts

---

src/common/gui/builtinThemes.ts
src/common/gui/theme.ts
src/common/settings/AboutDialog.ts

Brings back the brand logo to desktop and webapp and also changes the logo color on about dialog, now it's colored with our red shades just on red light theme.
Fixes #7569

Fixes the logo on desktop and non-red themes

---

tuta-sdk/rust/sdk/src/custom_id.rs
tuta-sdk/rust/sdk/src/date.rs
tuta-sdk/rust/sdk/src/generated_id.rs
tuta-sdk/rust/sdk/src/instance_mapper.rs
tuta-sdk/rust/sdk/src/util/mod.rs

On Swift, SystemTime will have precision loss due to uniffi internally converting to a floating point number + dividing the number by one billion to get nanoseconds. This leads to dates being off by 1 lower due to conversion back to milliseconds being slightly low and thus rounding down.
For now, we just use u64 so it stays an integer in all implementations.
Fixes #7581

[sdk] Use u64 instead of SystemTime for DateTime

---

src/common/gui/base/Dropdown.ts
src/common/gui/main-styles.ts

In some languages like German or Russian the external content dropdown text doesn't fit and so it gets cutoff with ellipsis. This commit fixes that by shifting the dropdown as needed so the entire text is displayed. When fitting the entire text on screen isn't possible, the dropdown spans the whole width and text is cutoff.
Fixes: #7458

Fix text cutoff in external content dropdown

---

src/common/gui/base/Dropdown.ts

The issue is a result of a miscalculation of the dropdown.style.right Introduced in PR #7624 
Fixes: #7636

Fixes dropdown appearing on far right of viewport

---

src/common/desktop/net/ProtocolProxy.ts

we still get too many requests from the desktop client when it is rebuilding the search index. Undicis http2 support should have matured enough for us to enable it to see if it is stable enough.
All of this should work without major hickups on linux, mac and windows:

[desktop] allow http2 in undici config

---

tuta-sdk/rust/sdk/src/crypto_entity_client.rs
tuta-sdk/rust/sdk/src/entities/entity_facade.rs
tuta-sdk/rust/sdk/src/lib.rs

we have some tests that require us to use a mix of mocks and real implementations. once we have a real integration test setup, we could move back to using `automock` on the struct because the tests that require this are technically not unit tests.

[tutasdk] make `EntityFacade` a trait.

---

src/common/settings/mailaddress/MailAddressTable.ts

Alleviates user confusion when trying to edit alias.name after setting it to empty string.
Reverts #4783
Fix #7254

Revert "Prefill name in sender name dialog if nothing was set"

---

buildSrc/RollupConfig.js
src/calendar-app/calendar/gui/eventpopup/CalendarContactPopup.ts
src/calendar-app/calendar/gui/eventpopup/CalendarContactPreviewViewModel.ts
src/calendar-app/calendar/gui/eventpopup/ContactPreviewView.ts
src/calendar-app/calendar/gui/eventpopup/EventPreviewView.ts
src/calendar-app/calendar/search/view/CalendarSearchView.ts
src/calendar-app/calendar/view/CalendarAgendaView.ts
src/calendar-app/calendar/view/CalendarView.ts
src/calendar-app/calendar/view/CalendarViewModel.ts
src/calendar-app/calendar/view/EventDetailsView.ts
src/calendar-app/calendarLocator.ts
src/common/api/main/CommonLocator.ts
src/common/calendar/date/CalendarEventsRepository.ts
src/common/calendar/date/CalendarUtils.ts
src/common/gui/base/GuiUtils.ts
src/common/gui/base/buttons/BannerButton.ts
src/common/misc/TranslationKey.ts
src/mail-app/contacts/view/ContactCardViewer.ts
src/mail-app/contacts/view/ContactViewer.ts
src/mail-app/mailLocator.ts
src/mail-app/search/view/SearchView.ts
src/mail-app/translations/de.ts
src/mail-app/translations/de_sie.ts
src/mail-app/translations/en.ts
test/tests/calendar/CalendarViewModelTest.ts

This commit makes birthday events preview show contact info as a pop-up with pre-defined actions such as send email and call phone number.
Closes #7672

[Calendar] Birthdays preview shows contact information

---

src/common/gui/builtinThemes.ts

[a11y] Make dark theme accent colors AA-accessible

---

src/common/misc/LanguageViewModel.ts
src/mail-app/mail/signature/Signature.ts

The default email signature should have a clickable link so users don't have to copy and paste the link into the browser. The link itself is added ass a parameter into the translation text. As we don't detect links in email content and make them clickable automatically, I decided to surround the replacement with an anchor tag. I also introduced a new link, that was requested by marketing.

Make default email signature clickable

---

src/common/api/worker/rest/DefaultEntityRestCache.ts
src/common/misc/LanguageViewModel.ts
src/mail-app/mail/signature/Signature.ts
test/tests/api/worker/rest/EntityRestCacheTest.ts

After rotating group keys we need to access the former group key for previously encrypted instances. Former group keys are stored on the GroupKey LET which use a customId. These instances are not cached by default. But with the recent modification to that cache that allows caching MailSetEntries GroupKey entites can also be cached. With this commit we enable the caching for this type.

allow caching of GroupKey entities

---

src/common/gui/base/TextField.ts
src/common/settings/SelectMailAddressForm.ts
src/mail-app/contacts/ContactAggregateEditor.ts
src/mail-app/contacts/ContactEditor.ts
src/mail-app/settings/AddInboxRuleDialog.ts
src/mail-app/settings/AddSpamRuleDialog.ts
src/mail-app/settings/TemplateEditor.ts
src/mail-app/settings/emaildomain/EnterDomainPage.ts

There are a few fields where we don't use input type="email" but shouldn't be capitalized. This includes some email fields, domain names, and social handles to name a few.
As such, mobile devices automatically capitalize these fields.
Close #7403

Disable auto-capitalization for lowercase only input fields

---

src/common/api/common/utils/UserUtils.ts
src/common/api/entities/sys/ModelInfo.ts
src/common/api/entities/sys/Services.ts
src/common/api/entities/sys/TypeModels.js
src/common/api/entities/sys/TypeRefs.ts
src/common/api/main/UserController.ts
src/common/api/worker/facades/lazy/GroupManagementFacade.ts
src/mail-app/app.ts
src/mail-app/mailLocator.ts
test/tests/api/worker/facades/GroupManagementFacadeTest.ts
tuta-sdk/rust/sdk/src/entities/sys.rs
tuta-sdk/rust/sdk/src/entities/tutanota.rs
tuta-sdk/rust/sdk/src/services/monitor.rs
tuta-sdk/rust/sdk/src/services/sys.rs
tuta-sdk/rust/sdk/src/services/tutanota.rs
tuta-sdk/rust/sdk/src/type_models/sys.json

In order to delete the local admin groups, we need to first re-assign their managed groups to the global admin.
tutadb#1878

Remove local admin groups

---

src/common/gui/ThemeController.ts

On iOS the app defaults to light theme on initial launch, even if the system theme is dark.
This is a result of iOS initialUrl not containing a theme param causing it to miss initial theme setting logic branch.
Close: #7045

Make theme default to system on initial launch on iOS

---

src/mail-app/mail/view/MailViewModel.ts
test/tests/Suite.ts
test/tests/mail/view/MailViewModelTest.ts

By mistake we executed the same condition twice:
firstMailReceivedTimestamp > secondReceivedTimeStamp & secondReceivedTimestamp < firstReceivedTimestamp
The above condition is apparently checking the same thing twice, and therefore, resulted in possibly random sort orders. This only happened in case of mailSet folders, and if sorting by `mail.receivedDate` is leading to a different sort order, than sorting by `mail.id`.

Fix sort order of mails with mailSet in MailViewModel

---

src/calendar-app/calendar/gui/day-selector/DaySelectorSidebar.ts

When navigating through the months in the SidebarDaySelector It doesn't highlight the day if It isn't the current selected date.

Fix Highlighted Day on Desktop view

---

src/calendar-app/calendar/gui/CalendarGuiUtils.ts
src/common/gui/base/Icon.ts

When hovering the Previous/Next Day IconButton in the Agenda view, the tooltip text displayed was incorrect, showing the text to navigate to the previous/next week instead of the day.
Also fixes an issue with hovering IconButtons and not displaying the tooltip.
Co-authored-by: André Dias <and@tutao.de>

7246 fix calendar nav tooltip

---

src/calendar-app/workerUtils/worker/CalendarWorkerLocator.ts
src/common/api/worker/facades/LoginFacade.ts
src/mail-app/workerUtils/worker/WorkerLocator.ts
test/tests/api/worker/facades/LoginFacadeTest.ts

fix the issue we had when trying to see the recover code after kdfMigration to argon 2. tutadb#1894

refresh user after kdf migration

---

src/common/gui/main-styles.ts
src/mail-app/mail/editor/MailEditor.ts
src/mail-app/mail/view/MailGuiUtils.ts
src/mail-app/mail/view/MailViewerViewModel.ts

Mail body text color in reply

---

src/mail-app/mail/view/MailViewerViewModel.ts

Issue caused by inline images not being replaced after a loadAll call (without notify) which sanitizes mail body.
This is due to the replaceInlineImages call being inside a loadCompleteNotification listener.
Fixed by calling loadAll *with* notify in reply. loadAll is also now only called when necessary.
Close #6523

Fix inline image being removed in mail viewer on reply

---

src/calendar-app/calendar/search/CalendarSearchBar.ts

Hide keyboard in calendar search after clicking Go Button in Mobile

---

src/common/gui/base/InputButton.ts
src/common/gui/base/SingleLineTextField.ts

This commit adds a button that has a label and when clicked/focused will render an input. 
Also makes the SingleLineTextField more complaint with accessibility by allowing it to receive an aria-label.

Input Button

---

src/common/support/FaqModel.ts

Issue caused by caching the initially selected language and not changing current language while switching language. Resolved by resetting lazyloaded when switching the system language.
close: #7335

Support entry language not change on switching language

---

app-ios/TutanotaShareExtension/ShareViewController.swift

"Calling this method has no effect." according to Apple docs. This was changed recently according to wayback machine.
https://developer.apple.com/documentation/uikit/uiapplication/1622961-openurl
Fixes #7944

Use UIApplication.open instead of UIApplication.openURL on share

---

src/calendar-app/calendar/gui/CalendarGuiUtils.ts
src/calendar-app/calendar/gui/RemindersEditor.ts
src/calendar-app/calendar/gui/eventeditor-model/CalendarEventWhoModel.ts
src/calendar-app/calendar/gui/eventeditor-view/AttendeeListEditor.ts
src/calendar-app/calendar/gui/eventeditor-view/CalendarEventEditDialog.ts
src/calendar-app/calendar/gui/eventeditor-view/CalendarEventEditView.ts
src/calendar-app/calendar/gui/eventeditor-view/EventTimeEditor.ts
src/calendar-app/calendar/gui/eventeditor-view/RepeatRuleEditor.ts
src/calendar-app/calendar/gui/pickers/GuestPicker.ts
src/calendar-app/calendar/gui/pickers/TimePicker.ts
src/common/contactsFunctionality/ContactUtils.ts
src/common/gui/MailRecipientsTextField.ts
src/common/gui/PasswordInput.ts
src/common/gui/base/Dropdown.ts
src/common/gui/base/RadioGroup.ts
src/common/gui/base/Select.ts
src/common/gui/base/SingleLineTextField.ts
src/common/gui/editor/Editor.ts
src/common/gui/editor/HtmlEditor.ts
src/common/gui/main-styles.ts

Implements the Guest Pages and the GuestPicker, allowing to invite guests when creating a new event.
Also fixes the Reminder selector not correctly handling the custom option due event loop race conditions.

Implements Guests Page

---

src/common/calendar/import/ImportExportUtils.ts
src/mail-app/translations/de.ts
src/mail-app/translations/de_sie.ts
src/mail-app/translations/en.ts

This commit change the URL validation removing the support for HTTP unsecure protocol.

Fix external calendar URLs validation

---

src/common/gui/base/Dropdown.ts

The inner dropdown container was overflowing the outer one instead of scrolling because its height was not restricted. This could be reproduced on a screen that's not tall enough e.g. small mobile screen or landscape orientation of the phone.
Now we set the height to the one of the parent to always have correct height.
Close #7937

Fix dropdown not scrolling when there's not enough vertical space

---

src/common/gui/main-styles.ts

very long Url in mobile app showing in small text which is not readable. Resolved by breaking overflow text in url to multiple lines which will make link readable to user.
close: #7972

Show long Url properly in mobile view.

---

app-ios/TutanotaSharedFramework/Contacts/ContactStoreError.swift
app-ios/TutanotaSharedFramework/Keychain/KeychainManager.swift
app-ios/TutanotaSharedFramework/Offline/IosSqlCipherFade.swift
app-ios/TutanotaSharedFramework/Utils/CancelledError.swift
app-ios/TutanotaSharedFramework/Utils/PermissionError.swift
app-ios/TutanotaSharedFramework/Utils/TUTErrorFactory.m
src/common/api/common/utils/ErrorUtils.ts

Some errors names contain tutanota package when it should have been tutashared. Caught because the incorrect CredentialAuthenticationException name was causing the error banner to show on Authentication cancelled due the error not being handled correctly.
Close #7977 

Correct error names in ErrorNameToType map

---

src/common/desktop/files/DesktopFileFacade.ts
test/tests/desktop/files/DesktopFileFacadeTest.ts

* test uploading attachment on desktop win, linux, mac.

[desktop] fix not sending Content-Length header in native file upload

---

app-android/.run/app-debug-emulator.run.xml
tuta-sdk/rust/sdk/src/crypto/crypto_facade.rs
tuta-sdk/rust/sdk/src/crypto_entity_client.rs
tuta-sdk/rust/sdk/src/entities/entity_facade.rs
tuta-sdk/rust/sdk/src/entity_client.rs
tuta-sdk/rust/sdk/src/instance_mapper.rs
tuta-sdk/rust/sdk/src/json_serializer.rs
tuta-sdk/rust/sdk/src/services/service_executor.rs
tuta-sdk/rust/sdk/src/util/test_utils.rs

#tutadb1913
We did not set the owner key version properly on an instance when decrypting it. This was fine for owner key version 0 which is the default fallback but it does not work after a key rotation. We now set this properly, so that we can preview the mail without loading it from the server again when opening the app by tapping the notification.

fix opening mail preview from notification on mobile after key rotation

---

src/common/misc/TranslationKey.ts
src/common/settings/UserViewer.ts
src/mail-app/translations/de.ts
src/mail-app/translations/de_sie.ts
src/mail-app/translations/en.ts

When adding a new admin and an admin key rotation is pending we inform the admin that he must wait the rotation to finish first.
tutadb#1905

Prevent adding new admin when rotating admin group

---

src/common/ratings/InAppRatingUtils.ts

importing the file directly breaks builds that depend on tutanota-3 the bundlers are configured to resolve the actual file to use

fix luxon import in InAppRatingUtils.ts

---

src/mail-app/mail/view/MailViewerViewModel.ts

Issue caused by inline images not being replaced after a loadAll call (without notify) which sanitizes mail body.
This is due to the replaceInlineImages call being inside a loadCompleteNotification listener.
Fixed by calling loadAll *with* notify in reply. loadAll is also now only called when necessary.
Related to #6523
Fix #8003

Fix inline image being removed in mail viewer on forward

---

src/common/api/common/TutanotaConstants.ts

We enable the argon2 migration for every user that is still using bycrypt to derive the password key. During the login process we derive a new password key from the existing password and encrypt the user group key with it. This step is a requirement for upgrading to quantum safe key material.
see  #tutadb1896

Enable argon2 migration

---

app-ios/fastlane/Fastfile
buildSrc/createReleaseDraft.js
ci/Android.Jenkinsfile
ci/Desktop.Jenkinsfile
ci/Ios.Jenkinsfile
ci/Publish-CalendarMobileArtifacts.Jenkinsfile
ci/Publish-MailAndroidArtifacts.Jenkinsfile
ci/Publish-MailDesktopArtifacts.Jenkinsfile
ci/Publish-MailiOSArtifacts.Jenkinsfile
ci/Publish-WebappArtifacts.Jenkinsfile
ci/Release.Jenkinsfile
ci/Webapp.Jenkinsfile
ci/jenkins-lib/desktop-artifacts-map.groovy
ci/jenkins-lib/util.groovy

Close https://github.com/tutao/tutanota/issues/6830
Close https://github.com/tutao/tutanota/issues/7985
Close https://github.com/tutao/tutanota/issues/7986

Reorganize build/release pipelines

---

src/calendar-app/calendar/gui/CalendarGuiUtils.ts
src/calendar-app/calendar/gui/EditCalendarDialog.ts
src/calendar-app/calendar/view/CalendarView.ts

This commit re-implements the generateRandomColor function and adds a random default color for new external calendars.
fix #8121

Fix missing color for external calendars

---

ci/Ios.Jenkinsfile
ci/IosRenewCerts.Jenkinsfile

Set emscripten cache location explicitly.
Only run renew certs on the intel mac until the new one is ready.

[ci] Fix iOS jobs

---

src/common/gui/SidebarSection.ts

Removed extra spacing (margin bottom) between sidebar heading and AddItem button
close #8112

Remove extra spacing between items in Menu bar.

---

ci/Publish-MailAndroidArtifacts.Jenkinsfile

Allow publish android release notes stage to be ran independently

---

src/common/subscription/SubscriptionSelector.ts

Yearly Prices on iOS must be displayed as full price according to Apple's subscription policies, so this commit reverts the changes made for Cyber Monday and displays the full price when booking a new subscription

Fixes iOS yearly full price being displayed as per month

---

src/common/api/worker/offline/OfflineStorage.ts
src/common/api/worker/rest/CustomCacheHandler.ts
src/common/api/worker/rest/DefaultEntityRestCache.ts
test/tests/api/worker/rest/EntityRestCacheTest.ts

Notification process on mobile does insert Mail instances into offline db in order to show the mail preview as quickly as possible when the user clicks on notification. In most cases it happens before login, and it happens independently of entity update processing.
EntityRestCache does only download new list element instances when they are within the cached range. In most cases new mails are within the cached range as mail indexer caches mail bag ranges during initial indexing. However, if the mail bag size has been reached there will be a new mail bag with mail list that is not cached by the client (there is no range stored for this new list).
EventQueue optimizes event updates. If CREATE event is followed by an UPDATE event they will be folded into a single CREATE event.
In a situation …

Fix outdated mails from notification

---

src/common/gui/base/ViewColumn.ts

While setting ViewColumn's `aria-hidden` to `true` when not visible works for mobile screen readers. The ViewColumn can still be tabbed into. To make sure the ViewColumn is ignored, we use `inert` instead.
Close #7054

Fix ViewColumn still tabbable when off-screen in single-column layout

---

packages/tuta-wasm-loader/lib/WasmHandler.ts
src/common/api/worker/facades/lazy/BlobFacade.ts
src/common/api/worker/facades/lazy/MailExportFacade.ts
src/common/api/worker/rest/EntityRestClient.ts
src/mail-app/native/main/MailExportController.ts
src/mail-app/workerUtils/worker/WorkerLocator.ts
test/tests/api/worker/facades/BlobFacadeTest.ts
test/tests/api/worker/facades/MailExportFacadeTest.ts
test/tests/api/worker/rest/EntityRestClientTest.ts
test/tests/native/main/MailExportControllerTest.ts

Get server information and round-robin calls to servers when exporting

---

src/mail-app/mail/view/CollapsedMailView.ts
src/mail-app/mail/view/MailViewerHeader.ts

The issue was caused by the more button having a parent element with a `role="button"` resulting in the more button having a role of "presentation".
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/button_role#all_descendants_are_presentational
To fix this, click handling was moved to a more button's sibling element (mail sender text).
Close #8183

Fix cannot focus mail more button on mobile screen readers

---

test/tests/api/worker/facades/MailExportFacadeTest.ts
test/tests/native/main/MailExportControllerTest.ts

We stopped using baseUrl when getting attachment data, as we have exact servers the blobs are stored on to retrieve from.

Fix export facade tests

---

src/mail-app/mail/view/MailView.ts

The issue is being able to open labels dropdown even if there are no labels.
Resolved by only showing dropdown if there are any labels found.
close #8141

Fix being able to open Labels dropdown even if there are no labels

---

src/common/api/worker/crypto/CryptoFacade.ts

fixes a bug introduced with a6d6d26d1a04a244fd2d238495b362118032aa89 the bug most likely is not triggered

set the ownerGroup on unmapped instances in client-side migrations

---

src/mail-app/search/SearchBar.ts

On chrome, clicking the "New email" button causes the search input to be autofilled with the user's email. This happens even with autocomplete set to "off", and with the button having a type of "button"
Wrapping the search input in a form isolates it from unrelated buttons and fixes the issue.
Close #8236

Fix autocomplete search field with user email on chrome

---

src/calendar-app/calendar/model/CalendarModel.ts

After login a client might try to process group events but the entity related to these events might have already been deleted by another client which raise an exception. In our case the client loses its group membership (shared calendar has been deleted) and try to load members of this deleted shared calendar. This commit handles errors happening while initializing the calendar model.
Co-authored-by: bedhub
fix #8254
tutadb#1942

Fix not authorized error after login

---

src/common/subscription/UpgradeConfirmSubscriptionPage.ts
src/common/subscription/UpgradeSubscriptionWizard.ts

After subscription to a paid account and using PayPal, the SignupWizard would logout the user before showing the CongratulationPage which cause some backgorund actions to fail and raise exceptions (no user found, no user group key required for initialization of the db). This commit removes this unecessary logout and resolve a bunch of error related to this race condition.
Co-authored-by: bedhub
tutadb#1805

Fix unexpected error during signup for paid account

---

packages/node-mimimi/src/importer.rs
packages/node-mimimi/src/importer/file_reader.rs
packages/node-mimimi/src/importer/filename_producer.rs
packages/node-mimimi/src/importer/importable_mail/extend_mail_parser.rs
packages/node-mimimi/src/importer/importable_mail/plain_text_to_html_converter.rs
tuta-sdk/rust/sdk/src/id/id_tuple.rs

Our Jenkins CI is still using rust version 1.78 to compile certain artifacts. This commits ensures that the project is compatible with rust version 1.78.

fix minor issues with rust version 1.78

---

src/calendar-app/calendar/gui/eventeditor-model/CalendarEventWhenModel.ts
src/common/api/common/utils/CommonCalendarUtils.ts

Fixed the issue by allowing users to change the end date back to the same date as the initial date.
Closes #7723

Fix all-day events spanning two days when created at the end of the day

---

src/mail-app/mail/view/MailViewerHeader.ts

Because the sender's name is used as a fold mail button. An empty sender name results in an element with a height of zero, making it impossible to click to fold mails.
VoiceOver also does not focus the fold mail button when the sender name is empty.
Close https://github.com/tutao/tutanota/issues/8266
Close https://github.com/tutao/tutanota/issues/8309

Use invisible address as displayed sender when sender name is empty

---

src/mail-app/mail/view/MailViewer.ts

It was happening due to align property which will cause mailbody height to be incorrect. Solved by removing the deprecated align property.
close: #8271

Fix some mail bodies cutoff on Mobile

---

src/common/misc/DateParser.ts

Adds a validation to mark short year/month dates as invalid. The only validation that we were doing was if Date(str) is valid, which is but not valid as intended to be. e.g. 00-07 would be interpreted as 07/1900 by JS Date instead of 07/2000 as expected.
Closes #8051

Rejects invalid short dates

---

src/calendar-app/calendar/gui/eventpopup/CalendarEventPopup.ts
src/calendar-app/calendar/gui/eventpopup/CalendarEventPreviewViewModel.ts
src/common/api/common/utils/CommonCalendarUtils.ts
src/common/calendar/date/CalendarUtils.ts
src/common/misc/SanitizedTextViewModel.ts
test/tests/calendar/CalendarUtilsTest.ts

Fixed Outlook event invite descriptions to preserve links after sanitization by applying the prepareCalendarDescription function
Closes #7814

Fix outlook event invite description with links

---

src/mail-app/contacts/view/ContactView.ts

Between 1140px and 1200px width there's a mix of desktop header and two-column layout. Caused by minWidth using first_col_max_width.
Close #6850

Fix contact view invalid layout width

---

src/mail-app/mail/view/MailViewModel.ts

After importing mails on the desktop client, those mails are not visible immediately on other devices with offline storage. This is due to the optimization of EntityEvents (CREATE + UPDATE = CREATE). Previously, the mails were only downloaded on ImportMailState UPDATE events in the MailViewModel, which are never processed on the devices not making the import. This led to a corrupted state where the imported mails are never downloaded to the device. This fix ensures that the mails are downloaded and the offline storage is updated properly.

fix ImportMailState CREATE event not downloading imported mails

---

src/mail-app/workerUtils/index/MailIndexer.ts

After importing mails on the desktop client, those mails were not indexed properly due to missing of the CREATE entity event. This is due to the optimization of EntityEvents (CREATE + UPDATE = CREATE). Previously, the mails were only indexed on ImportMailState UPDATE events in the MailIndexer, This led to a corrupted state where the imported mails are never indexed properly and required the deletion of the offline cache. This fix ensures that the mails are indexed properly.

fix ImportMailState CREATE event not updating the search indexer

---

src/calendar-app/calendar/model/CalendarModel.ts

we're seeing some external calendars that change UIDs every day, so it's causing a lot of request on login. the fact that it's done by the calendarModel without any concurrency control also leads to users getting IP banned; the client fires all the delete requests in parallel which gives the connection pooling no chance to kick in because by the time the first TLS handshake is done, all requests are in flight already
awaiting each delete request makes the whole process take more time and more likely to be interrupted. we will have to rethink external calendar sync to improve this.
this is probably annoying to test because of the debounce for calendar sync. it's probably best to set up a shared calendar on some other services and change them manually.
It needs to be tested on desktop, ios …

don't delete outdated external calendar events in parallel

---

src/calendar-app/calendarLocator.ts
src/common/api/main/LoginController.ts
src/common/api/main/UserController.ts
src/common/api/worker/rest/DefaultEntityRestCache.ts
src/mail-app/mailLocator.ts
test/tests/api/worker/rest/EntityRestCacheTest.ts

In some cases LoginFacade does succeed with the partial login, but some login actions fail on the page side, e.g. loading of `TutanotaProperties`. This leads to an inconsistent state where the worker is in the logged in state while the page context is not.
We solve the issue by catching the errors during page context init and resetting the state on both sides.
In the future we could make the process more robust by loading all the necessary parts in `LoginFacade` or making some parts lazy-loaded.
Fix #5537

Fix login issues

---

src/common/desktop/export/DesktopExportFacade.ts
src/mail-app/mail/export/Exporter.ts
src/mail-app/mail/export/emlUtils.ts
src/mail-app/mail/view/MailListView.ts
test/tests/desktop/export/DesktopExportFacadeTest.ts

Exporting two mails that have the same subject and sent date will result in the second file overwriting the first one. This is because the exported file name has the following structure: {YYYY-MM-DD-HHhMMmSSs}-{subject}.{exportMode}.
Adding the mailId to the file name solves the issue.
Close #8402

Change exported mail file name to include mailId

---

src/common/api/worker/facades/lazy/MailExportFacade.ts
src/common/api/worker/rest/EntityRestClient.ts
test/tests/api/worker/facades/MailExportFacadeTest.ts
test/tests/api/worker/rest/EntityRestClientTest.ts

This is to prevent suspending subsequent requests when export gets a 429 HTTP response.
Close #8408

Set suspension behavior to throw for all export related requests

---

src/mail-app/mail/view/MailViewer.ts

This particular error is thrown when resizing inside a ResizeObserver which can cause an infinite loop in some cases (not our case).
Moving the resize inside a requestAnimationFrame (and making sure to cancel pending requests) resolves the issue.
close: #8417

Fix ResizeObserver loop completed with undelivered notifications.

---

src/mail-app/settings/MailExportSettings.ts

Resolved by adding padding between Mailbox selection dropdown and "Export" button which align same as Import design
close: #8431

Fix Padding between Export button and Mailbox dropdown

---

tuta-sdk/rust/Cargo.lock
tuta-sdk/rust/Cargo.toml

fixes build problems with android
tutadb#1963

update pqcrypto-internals to 0.2.8

---

src/common/gui/PinchZoom.ts
src/common/gui/main-styles.ts
src/mail-app/mail/view/MailViewer.ts

- Break preformatted text on mobile.
- Wrap unbreakable long lines of text when scaling exceeds a certain threshold (scaling might still be applied on top, if necessary).

Fix over-scaling mail body on mobile

---

src/mail-app/mail/view/MailViewerViewModel.ts

fix mail view update race condition when opening mails from notification while offline and then going back online
#tutadb1966

fix mail view update race condition when opening mails from notification

---

buildSrc/DevBuild.js
buildSrc/postinstall.js
libs/webassembly/Makefile_liboqs
libs/webassembly/remove-fprintf.patch
packages/tutanota-crypto/lib/encryption/Liboqs/Kyber.ts
packages/tutanota-crypto/lib/encryption/Liboqs/tuta_kem.c
packages/tutanota-crypto/lib/encryption/Liboqs/tuta_kem.h
packages/tutanota-crypto/lib/index.ts
src/common/api/worker/facades/KyberFacade.ts
test/tests/api/worker/crypto/CompatibilityTest.ts

kyber will be dropped with the next release
we need to apply our hack to turn ml-kem into kyber for backward compatibility. this requires some extra kdf and hash step to bind the key to the ciphertext.
we do not want to pull additional dependencies in typescript and liboqs already comes with shake and sha3, so we just do this in C.
we apply a patch to remove fprintf calls from the compiledd liboqs code to not depend on stdio for wasm build
#tutadb1956

update liboqs to version 0.12.0 and use ml-kem instead of kyber

---

src/calendar-app/calendar/gui/eventpopup/CalendarEventPopup.ts
src/calendar-app/calendar/gui/eventpopup/CalendarEventPreviewViewModel.ts
src/calendar-app/calendar/gui/eventpopup/EventPreviewView.ts
src/calendar-app/calendar/model/CalendarModel.ts
src/calendar-app/calendar/view/CalendarView.ts
src/calendar-app/calendar/view/EventDetailsView.ts
src/common/calendar/date/CalendarUtils.ts

Add calendar info, color, name, and type, at event popup and event details (search and agenda view)
Changes icon alignment to always align to the top, except when the data displayed fits in a single line, in this case it's centered.
Closes #7209

Show which calendar the event belongs to at event preview

---

src/common/gui/main-styles.ts

Fixed home button background color in ios align to app background color
when the user is in darkmode theme
close #8426

Fix Home Button background color align the app background color

---

packages/tutanota-utils/lib/Utils.ts
src/common/gui/base/List.ts
src/mail-app/mail/view/MailViewer.ts

createResizeObserver returns a ResizeObserver that handles resize events in a `requestAnimationFrame`.
This is done to prevent `ResizeObserver loop completed with undelivered notifications` errors, which can happen when excessively resizing an observed element, resulting in resize events being deferred to the next render cycle.
Close #8517

Use createResizeObserver for ResizeObserver creation everywhere

---

src/calendar-app/calendar/model/CalendarModel.ts
src/calendar-app/calendar/view/CalendarView.ts
src/calendar-app/calendar/view/CalendarViewModel.ts

Adds a flag when subscribing to external calendars that locks the interface and prevents users from subscribing to the same calendar multiple times.
It also adds a queue to calendar sync and synchronizes it, preventing the same calendar from being synced in parallel.
Fixes #8446
Fixes #8447

Fixes External Calendars synchronization

---

src/calendar-app/calendar/gui/RemindersEditor.ts
src/calendar-app/calendar/gui/eventeditor-view/EventTimeEditor.ts
src/calendar-app/calendar/gui/eventeditor-view/RepeatRuleEditor.ts
src/calendar-app/calendar/gui/pickers/DatePicker.ts
src/calendar-app/calendar/gui/pickers/GuestPicker.ts
src/calendar-app/calendar/gui/pickers/TimePicker.ts
src/common/gui/base/InputButton.ts
src/common/gui/base/RadioGroup.ts
src/common/gui/base/Select.ts
src/common/gui/base/SingleLineTextField.ts
src/common/gui/main-styles.ts
src/common/misc/KeyManager.ts

Changes the Select to not use modals but instead a dive right before/after the dropdown trigger. This will increase the accessibility.

Fixes Select dropdown implementation

---

src/common/desktop/integration/DesktopIntegratorDarwin.ts

"zoom-changed" event only fires on pinch zoom on macOS and not when zooming using menu items or keyboard shortcuts.
To make sure zoom is handled similar to other platform, zoom menu items are replaced with custom ones that emit "zoom-changed" events when activated.
Close: #5441

Fix zoom factor persistence on macOS 

---

libs/squire-raw.mjs

Brings back old behaviour that was removed in #8341 when we switched away from using blockquotes for indentation. Which resulted in inline replies no longer being possible.
Close #8544

Remove indentation on Enter and Backspace in empty blockquote line

---

src/mail-app/mail/view/MailGuiUtils.ts
src/mail-app/mail/view/MailViewer.ts

- Fix broken moveMailsToSystemFolder
- Remap show mail source shortcut to Shift+I so it doesn't clash with the move to inbox shortcut.
Close https://github.com/tutao/tutanota/issues/8650
Close https://github.com/tutao/tutanota/issues/8573

Fix move mail using keyboard shortcuts

---

src/common/api/worker/facades/lazy/MailFacade.ts
src/mail-app/mail/model/MailModel.ts
src/mail-app/mail/view/MailGuiUtils.ts
src/mail-app/mail/view/MailListView.ts
src/mail-app/mail/view/MailView.ts
src/mail-app/mail/view/MailViewerHeader.ts
src/mail-app/search/view/SearchView.ts

When permanently deleting a conversation that has some of its mails in folders that aren't in trash/spam, only mails that are in the current folder which must be trash/spam are deleted.
This is done by passing the folder id to the DeleteMailService along with all the conversation mailIds.
Close #8658

Fix delete action for conversation to only delete mails in trash/spam

---

src/mail-app/search/view/SearchView.ts

The issue happened because we forcefully unwrapped conversationViewModel when only one mail is selected. This is wrong, when one email is selected via multiselect there won't be a conversationViewModel. ViewModel already has this logic so we shouldn't duplicate it in the view.

Fix entering multiselect in mail search

---

app-ios/TutanotaNotificationExtension/NotificationService.swift
app-ios/TutanotaSharedFramework/Notifications/SdkRestClient.swift

After URLSession refactoring we did not pass the headers that SDK passed to the RestClient to the actual HTTP request.
Additionally, change NotificationService so that the errors do not cause timeout and are logged.

[ios] Fix downloading mails for notifications

---

src/mail-app/mail/editor/MailEditorViewModel.ts

Currently, giving options to download and remove the attachment when the user is in Mail Editor. Changed that to open and remove. Instead of downloading attachment user can open the attachment and if the user still wants to download it is possible to save attachment from  the viewer mode.
close: #4371

Change attachment option from download to open in Mail Editor.

---

src/common/api/worker/facades/lazy/MailExportFacade.ts
src/common/api/worker/rest/EntityRestClient.ts
src/mail-app/native/main/MailExportController.ts
test/tests/api/worker/facades/MailExportFacadeTest.ts
test/tests/native/main/MailExportControllerTest.ts

Round-robin mail details calls when exporting

---

app-ios/TutanotaSharedFramework/Alarms/RepeatRule.swift

Imported events might contain invalid SETPOS rules that can crash the app.
fixes #8728

Fixes app crashes during alarm scheduling

---

src/calendar-app/calendar/gui/pickers/DatePicker.ts

When hitting Return key after extending search range while on free plan, the upgrade dialogue is shown twice.
This happens because input is handled in both the input field's `onkeydown` and in another event listener on the document that is meant to handle input when focus is shifted outside the DatePicker (like when clicking away for example). This is a problem because when the first dialogue appears it grabs focus and since it's outside the DatePicker, it triggers an additional handling of input.
To fix this, we add the event listeners to the main-view instead of the entire document, excluding the modal and overlay layers.
Close #8755

Fix duplicate upgrade dialogue to paid plan when in search view

---

src/calendar-app/calendar/gui/pickers/DatePicker.ts

The label had a higher z-index than that of the mobile date input which is supposed to cover the input field on mobile.
Giving the mobile date input a z-index of 1 fixes the issue.
Close #8765

Fix VisualDatePicker showing on mobile when tapping label

---

src/common/api/worker/facades/KeyRotationFacade.ts
src/common/api/worker/facades/UserFacade.ts
test/tests/api/worker/facades/KeyRotationFacadeTest.ts

Waitng for the event update to update the cache would cause a race condition where we encrypt with the old key after rotating, which is not allowed.
tutadb#2068

Put new userGroupKey in the KeyCache after successful rotation

---

app-ios/calendar-project.yml
app-ios/mail-project.yml
app-ios/tutanota/Info.plist
app-ios/tutanota/Sources/AppDelegate.swift
app-ios/tutanota/Sources/Utils/Mailto.swift
app-ios/tutanota/Sources/ViewController.swift
app-ios/tutanotaTests/MailToTest.swift

"mailto" URL scheme is missing in info.plist which is required to set Tuta asdefault app on iOS.
Fixed by adding "mailto" URL scheme in CFBundleURLSchemes member of the CFBundleURLTypes.

Default mail app on iOS

---

src/common/api/common/TutanotaConstants.ts
src/common/desktop/ApplicationWindow.ts
test/tests/desktop/ApplicationWindowTest.ts

Added keyboard shortcuts (Ctrl + + and ctrl + -) for zooming in and out on Linux and Windows. This was already working on Mac.
Close: #8749

Implement keyboard shortcut for zoomin and zoomout

---

app-android/calendar/build.gradle.kts
app-android/calendar/src/main/java/de/tutao/calendar/MainActivity.kt

SDK 35 brought some changes on how apps behave related to screen size. This commit rolls back the targetSdk to 34, the latest working version.

[Android] Fixes keyboard hiding fields

---

libs/purify.js
package-lock.json
package.json
src/mail-app/mail/view/MailListView.ts
src/mail-app/mail/view/MailView.ts
src/mail-app/mail/view/MailViewModel.ts

Introduced in c65f0f22
When viewing a conversation with conversation thread enabled but with mail list grouping disabled, mail actions apply to the entire conversation without exclusions (sent mails are supposed to be excluded from move operations when acting on conversations). This occurs because the entire conversation was used as actionable mails regardless of whether list grouping was enabled or not.
Sent mails not being excluded from move operations was due to `excludeMailSet` (passed to the server to exclude mails in a specific folder from the being moved) being `null` when mail list grouping is disabled.
To fix this, we use `getStickyMails` which would return the primary mail or the conversation mails being viewed depending on whether mail grouping is enabled or not.
Close #8886

Fix mail actions act on entire conversation with list grouping disabled

---

libs/purify.js
package-lock.json
package.json
src/mail-app/mail/view/MailListView.ts
src/mail-app/mail/view/MailView.ts
src/mail-app/mail/view/MailViewModel.ts

Introduced in c65f0f22
Moving selected mails in a list was broken due to a small refactor in `MailView`'s `moveMailsFromFolder`. The refactor changed when selected mails are captured from before the `onSelected` action to after it. Because the onSelected action is selectNone on mobile, we end up capturing 0 mails for the move. 
Reverting the refactor fixes this by capturing the selected mails before showing the folder selection dropdown.
Fix #8891

Fix move selected mails from folder not working on mobile

---

src/mail-app/settings/MailSettingsViewer.ts

Since there is not a separate db for searching when offline storage is available, having the "Search mailbox" option does not make sense, since search is always enabled.
The option remains for web version.
Close: #8834

Only show 'search mailbox' in settingsView for browser

---

tuta-sdk/rust/make_ios.sh

If we don't do this, then we may randomly run into linking errors due to missing symbols (e.g. ___chkstk_darwin), as it will try to link with 10.0, instead.

[sdk] Set IPHONEOS_DEPLOYMENT_TARGET for make_ios.sh

---

src/mail-app/workerUtils/index/MailIndexer.ts
test/tests/api/worker/search/MailIndexerTest.ts

MailIndexer does not check if the email is in range before putting it 
into index. Fixed by checking the received date of email, if the 
received email date is less than the current Index date, then putting to
the index otherwise not adding.
Close #8897

Check if the email is in range before putting it into index.

---

src/common/misc/TranslationKey.ts
src/mail-app/mail/view/MailGuiUtils.ts

Use a generic permanent deletion confirmation text since permanent deletion is also possible from the Spam folder.
Close #8936

Fix wrong perma delete confirmation text when deleting from Spam

---

packages/node-mimimi/src/importer.rs
packages/node-mimimi/src/importer/importable_mail.rs
packages/node-mimimi/tests/resources/testmail/brokendate.eml

The message parser returns -1 if it can't parse the Date: header. Converting this with `n as u64` leads to an underflow and subsequently to a panic because of the multiplication necessary to convert to milliseconds.
We'll now use safe methods to default to 1970-01-01T00:00:00.000 if the date is unusable.
fix #8766

[mimimi] fix invalid dates breaking the importer

---

app-android/calendar/src/main/java/de/tutao/calendar/widget/Agenda.kt
app-android/calendar/src/main/java/de/tutao/calendar/widget/WidgetReceiver.kt
app-android/calendar/src/main/java/de/tutao/calendar/widget/data/CacheDateDao.kt
app-android/calendar/src/main/java/de/tutao/calendar/widget/data/CalendarEventDao.kt
app-android/calendar/src/main/java/de/tutao/calendar/widget/data/CalendarEventListDao.kt
app-android/calendar/src/main/java/de/tutao/calendar/widget/data/LastSyncDao.kt
app-android/calendar/src/main/java/de/tutao/calendar/widget/data/UIEvent.kt
app-android/calendar/src/main/java/de/tutao/calendar/widget/data/WidgetDataRepository.kt
app-android/calendar/src/main/java/de/tutao/calendar/widget/data/WidgetRepository.kt
app-android/calendar/src/main/java/de/tutao/calendar/widget/data/WidgetWorkerRepository.kt
app-android/calendar/src/main/java/de/tutao/calendar/widget/model/WidgetUIViewModel.kt
tuta-sdk/rust/sdk/Cargo.toml
tuta-sdk/rust/sdk/src/date/calendar_facade.rs

This commit chances how the cache is stored on the device. Instead of only living in memory, it encrypts a minimal version of the events and keep them in the Preferences DataStore so it can survive to phone restarts and other events that might purge widget's memory.

[Android] Fixes the Widget Cache

---

Cargo.lock
app-android/calendar/src/main/java/de/tutao/calendar/widget/Agenda.kt
app-android/calendar/src/main/java/de/tutao/calendar/widget/WidgetReceiver.kt
app-android/calendar/src/main/java/de/tutao/calendar/widget/data/CacheDateDao.kt
app-android/calendar/src/main/java/de/tutao/calendar/widget/data/CalendarEventDao.kt
app-android/calendar/src/main/java/de/tutao/calendar/widget/data/CalendarEventListDao.kt
app-android/calendar/src/main/java/de/tutao/calendar/widget/data/LastSyncDao.kt
app-android/calendar/src/main/java/de/tutao/calendar/widget/data/UIEvent.kt
app-android/calendar/src/main/java/de/tutao/calendar/widget/data/WidgetDataRepository.kt
app-android/calendar/src/main/java/de/tutao/calendar/widget/data/WidgetRepository.kt
app-android/calendar/src/main/java/de/tutao/calendar/widget/data/WidgetWorkerRepository.kt
app-android/calendar/src/main/java/de/tutao/calendar/widget/model/WidgetUIViewModel.kt
tuta-sdk/rust/sdk/Cargo.toml
tuta-sdk/rust/sdk/src/date/calendar_facade.rs
tuta-sdk/rust/sdk/src/date/event_facade.rs

When generating event instances, the SDK was not aware of timezone changes. This PR adds a calculation to fix the timezone when there are DST changes during an event series.
Co-authored-by: André Dias <and@tutao.de>

[SDK] Fixes timezone during event generation

---

app-android/app/src/main/java/de/tutao/tutanota/push/MailNotificationActionReceiver.kt

Mail notification does not disappear after clicking "Delete" or "Mark Read"
Fixed by filtering manually notification in "dismiss notification"  because cancel might not be quick enough.
Close #8905

[Android] Mail notification does not disappear after cancelling

---

src/common/api/common/Logger.ts

While we never use console.debug ourselves, a lot of browser extensions unconditionally expect this to be present and (understandably) do not check to see if it's there or not before calling it.
Closes #8809

Add console.debug to replaceNativeLogger

---

src/mail-app/mail/view/MailView.ts

Add a shortcut (ctrl-shift-N) to allow the user to create a new folder without having to click on anything to open the dialog.
Since a user may have access to more than one mail group, we can disambiguate this by checking what folder they are looking at (if any) and use this folder's owner group.
close #8922

Add keyboard shortcut to create new folder

---

src/calendar-app/calendar/search/model/CalendarSearchModel.ts
src/calendar-app/calendar/view/CalendarViewModel.ts
src/common/calendar/date/CalendarEventsRepository.ts
src/mail-app/search/model/SearchModel.ts

We currently don't fetch the new memberships when the user joins/leaves a shared calendar.
This commit changes the logic of loadMonthsIfNeeded and starts listening for GroupMember entity events updates, so when a GroupMember is added or removed, the calendar related to that membership is also added or removed.

Handle GroupMember changes when loading calendars

---

src/RootView.ts
src/common/gui/base/Checkbox.ts
src/common/gui/base/Modal.ts
src/common/gui/base/Overlay.ts

Reverts commit d94873bc12a4d75ab64d6129e04d8c2f8ac18986 and makes overlays inert only when behind an open modal.
Close #8767

Trap focus in modals when using screen readers

---

src/common/api/worker/facades/lazy/KeyVerificationFacade.ts
src/common/settings/keymanagement/KeyManagementSettingsViewer.ts
test/tests/api/worker/facades/KeyVerificationFacadeTest.ts

We only display manually verified identity keys, and ignore TOFU source of truth
Co-authored-by: vis <vis@tutao.de>
tutadb#2116

Only displays manually verified identity keys

---

buildSrc/bump-version.js

When bumping version we ran into an issue with base64ct that got updated to version 1.8.0 which requires Rust 1.85. Rather than pinning dependencies, we decided to change bump-version to only update tuta-sdk and node-mimimi for now. Though we probably should revisit the matter at a later point.

Change bump-version to only update tuta-sdk and node-mimimi

---

src/common/api/worker/facades/PublicKeyProvider.ts

ultimately this resulted in authentication failed status for tuta crypt messages

fix version null check when loading public encryption keys 

---

src/mail-app/mail/view/MailViewModel.ts

Mails are sorted by received date in the MailListModel, but the encoded date in the mailId is the date the mails were created in the server. Therefore, the current stop condition using the mailId is not sufficient to find out whether we have already loaded mails older than the mail we're looking for. Fixed by limiting the pages to load, if the targeted mail is within the pagelimit it will loadAndSelect otherwise loading stop after the page limit.
Close: #8305

Fix Imported mails cannot be selected

---

src/mail-app/mail/editor/MailEditor.ts
src/mail-app/mail/view/MailViewerViewModel.ts

Replying to a long email thread causes lag issues on some mobile devices. This happens because each reply introduces another level of nesting.
This change collapses replies that are 2+ levels deep by default in the MailEditor. The thread can be expanded using a quote expander button.
Close #617

Collapse the quoted reply by default when replying to a mail thread

---

src/mail-app/mail/model/ConversationListModel.ts
test/tests/mail/model/ConversationListModelTest.ts

We are not relying on the list model to do this, since we might have older mails get selected. In this case, we were already calling onSingleSelection, but not in the case where it was the latest mail of a conversation. We should unconditionally call this.
Closes #9208

loadAndSelect in ConversationListModel should call onSingleSelection

---

libs/sqlcipher-android/README-android-sqlcipher.md
libs/sqlcipher-android/build-sqlcipher-android.sh

Caused by a bug in OpenSSL:
https://github.com/openssl/openssl/commit/b7f6519229a6002f944626ab3db216175dd0f142
The code for AES was reading from invalid place in memory instead of static memory region.
Bump OpenSSL used in sqlcipher-android to 3.5.1.
Fix #9224

[android] Fix crash on armeabi-v7a

---

app-ios/tutanota/Sources/Contacts/IosMobileContactsFacade.swift
app-ios/tutanota/Sources/Contacts/UserContactMapping.swift

Contacts created outside of the mail app were being duplicated everytime contacts are synced.
This happens because `nativeContactWithoutSourceId` were being inserted repeatedly instead of just updating the contact mappings.
Close #8981

[ios] Fix duplicates when syncing contacts created natively

---

app-android/app/build.gradle
app-android/app/src/main/res/values-night-v35/styles.xml
app-android/app/src/main/res/values-v35/styles.xml
app-android/calendar/build.gradle.kts
app-android/calendar/src/main/res/values-night-v35/styles.xml
app-android/calendar/src/main/res/values-v35/styles.xml

Upgrade targetingSDK version to latest version(stable version is 35)
One of the major feature in SDK35 is EdgeToEdgeEnforcement which means 
the app fills the whole screen (it no longer leaves some margins for the
bottom Android buttons for example)
For now, this change can be disabled by adding 
"windowOptOutEdgeToEdgeEnforcement" option in the themes.xml file, but 
this option is temporary and need to be remove in the future.
Close #9287

9287 upgrade android

---

src/calendar-app/calendar/gui/eventpopup/CalendarEventPopup.ts
src/calendar-app/calendar/gui/eventpopup/CalendarEventPreviewViewModel.ts
src/calendar-app/calendar/view/CalendarMonthView.ts
src/calendar-app/calendar/view/CalendarView.ts
src/calendar-app/calendar/view/CalendarViewModel.ts
src/calendar-app/calendar/view/EventDetailsView.ts
src/calendar-app/calendar/view/EventDragHandler.ts
src/calendar-app/calendar/view/MultiDayCalendarView.ts
src/common/misc/TranslationKey.ts
src/mail-app/translations/de.ts
src/mail-app/translations/de_sie.ts
src/mail-app/translations/en.ts

Now users can duplicate events by dragging and dropping it holding the CTRL key, clicking the Duplicate button during preview or pressing CTRL+D when previewing it

Adds the option to duplicate an event

---

tuta-sdk/rust/sdk/src/key_cache.rs
tuta-sdk/rust/sdk/src/key_loader_facade.rs
tuta-sdk/rust/sdk/src/lib.rs
tuta-sdk/rust/sdk/src/login/login_facade.rs
tuta-sdk/rust/sdk/src/user_facade.rs
tuta-sdk/rust/sdk/src/user_facade_factory.rs
tuta-sdk/rust/sdk/src/util/test_utils.rs

This pull request introduces enhancements to the `KeyCache` architecture, adding cache to former group key, integrates a `UserFacadeFactory` for improved user facade creation, and expands testing utilities for key retrieval operations.
- **Refactored `KeyCache` structure**: Replaced `current_group_keys` with `group_keys` to support multiple key versions per group and added `latest_group_key_version` for tracking the latest version.
- **New methods in `KeyCache`**: Added `get_group_key_for_version` to retrieve specific key versions and updated `put_group_key` to manage multiple versions and update `latest_group_key_version`.
- **Introduced `UserFacadeFactory`**: Created a factory class to encapsulate the creation of `UserFacade` instances, simplifying dependency management by injecting …

[SDK] Cache former key

---

src/common/desktop/DesktopWindowManager.ts

Saving the config so close to close easily results in it being empty
Fixes: #7021

Do not try to save bounds on window close

---

buildSrc/DevBuild.js
make.js
src/common/api/worker/offline/OfflineStorageMigrator.ts
test/tests/api/worker/offline/OfflineStorageMigratorTest.ts

There was a missing check that migrations bring the version to the latest one.
In addition, we were checking the version against non-populated metadata which worked accidentally on the first run because `undefined < 1 === true`.

Make sure the offline storage version is consistent with migrations

---

app-android/app/src/main/java/de/tutao/tutanota/AndroidFileFacade.kt
app-android/calendar/src/main/java/de/tutao/calendar/AndroidFileFacade.kt
app-ios/calendar/Sources/Files/IosFileFacade.swift
app-ios/tutanota/Sources/Files/IosFileFacade.swift
src/calendar-app/calendar/gui/eventeditor-model/CalendarNotificationModel.ts
src/calendar-app/calendar/gui/eventeditor-view/CalendarEventEditDialog.ts
src/common/api/worker/facades/lazy/MailFacade.ts

When adding a guest to an event that already had guests, creating the calendar invitation draft on mobile could throw an exception.
The issue occurred because each draft email attached an .ics file by creating a temp file, uploading it, and then deleting it. Multiple drafts ran in parallel, causing two drafts to attempt deleting the same file — the second one always failing.
This commit fixes the problem by deferring file deletion until after the promise completes and ensuring these operations run sequentially (invite, cancellation and update of an event).
Closes #9323

Fix adding multiple guests to existing event on mobile

---

src/mail-app/mail/view/MailListView.ts

MailListView would leak the DOM elements for the list items on every layout change.
There were two causes:
- `onbeforeremove()` is only getting when the node loses its parent which never happens in our case because `MailListView` always renders the same list wrapper. Instead, we should have been using `onremove()` which is always called when the node is removed from the DOM
- the second issue is that the event handlers were created on every render. Every render the attrs for the wrapper vnode would get updated and callback would get replaced with a new one that's also referencing the new event handler. The reference to the old event handler would get lost and never removed
We fixed it by replacing `onbeforeremove()` with `onremove()` and by making sure that the event handlers are stable …

[desktop] Fix memory leak when resizing the window

---

make.js
src/common/desktop/CommandExecutor.ts
src/common/desktop/DesktopMain.ts
src/common/desktop/export/DesktopExportFacade.ts
src/common/desktop/files/DesktopFileFacade.ts
test/tests/desktop/files/DesktopFileFacadeTest.ts

Electron uses xdg-open to open files. On GNOME it will try to use gio open which reads user configs from a few files. To detect those config files it uses `XDG_CURRENT_DESKTOP` env variable.
Electron overwrites `XDG_CURRENT_DESKTOP` to enable some compatibility functions in Chromium. This breaks gio because it can't locate the config files for default apps. It can be reproduced on Ubuntu with GNOME. There is a fix in Electron to restore the env for opening files, but it doesn't work.
We worked around that by invoking xdg-open directly with correct env.
Additionally, we fixed opening the directories having the same issue and getting stuck by using showItemInFolder instead. This also has an additional benefit of highlighting the file in the file manager.
Close #9696

[desktop] Fix opening files & directories on Linux

---

src/mail-app/mail/model/MailModel.ts
src/mail-app/mail/view/MailGuiUtils.ts
src/mail-app/mail/view/MailView.ts
src/mail-app/mail/view/MailViewerUtils.ts
src/mail-app/mail/view/MailViewerViewModel.ts
src/mail-app/search/view/SearchView.ts

Fix marking conversation as spam only moves primaryMail to spam.
Close #9687
Fix marking mail as phishing doesn't update mail's phishing status.
Close #9700

Fix mark mails as spam/phishing

---

app-ios/AgendaWidgetExtension/Data/WidgetModel.swift
tuta-sdk/rust/sdk/src/date/event_facade.rs

Previously, events were grouped by calendar and sorted by time within each group by the SDK.
Now events are no longer grouped by calendar. Instead, all events are merged into a single list and sorted together by start time.
---
Previously, the SDK was incorrectly adding one week to past events, causing them to be included in the wrong week.
Now events in the past are allowed to be generated without modification. Events occurring before the N=0 event are now filtered out afterward.

Fixes sorting on iOS Widget & SDK event generation 

---

src/calendar-app/calendar/model/CalendarModel.ts
src/calendar-app/calendarLocator.ts
src/common/misc/GroupColors.ts
src/common/misc/TranslationKey.ts
src/mail-app/gui/date/EventBannerImpl.ts
src/mail-app/mail/view/MailViewerHeader.ts
src/mail-app/mailLocator.ts
src/mail-app/translations/de.ts
src/mail-app/translations/de_sie.ts
src/mail-app/translations/en.ts
test/tests/calendar/CalendarModelTest.ts

When receiving an event invitation, users may have more than just one conflicting event, but we show only one inside the time overview.
This commit adds an expandable panel to the event banner, allowing users to expand it by clicking in the warning info and quickly see which events, along the already displayed one, are conflicting with the invitation.
Closes #9726

Adds conflicting events information to Event Banner

---

src/mail-app/mail/view/ConversationViewer.ts

Caused by the shortcut being enabled when the `MailViewerViewModel` is `null`, which happens because `!viewModel()?.isDraftMail()` is true when the mail is not draft but also when the viewModel is null.
The same is true for the replyAll and forward shortcuts.
Close #9736

Fix failed AssertNotNull when reply shortcut is triggered to quickly
