src/api/common/utils/CommonCalendarUtils.ts, src/api/main/MainLocator.ts, src/api/main/RecipientsModel.ts, src/calendar/date/CalendarEventViewModel.ts, src/calendar/date/CalendarInvites.ts, src/calendar/date/CalendarUpdateDistributor.ts, src/calendar/model/CalendarModel.ts, src/calendar/view/CalendarEventEditDialog.ts, src/calendar/view/EventPreviewView.ts, src/contacts/model/ContactModel.ts, src/gui/MailRecipientsTextField.ts, src/mail/editor/SendMailModel.ts, src/misc/Formatter.ts, src/misc/RecipientsSearchModel.ts, src/misc/parsing/MailAddressParser.ts, src/sharing/view/GroupSharingDialog.ts, test/tests/calendar/CalendarModelTest.ts
=> Calendarupdate notfound 4964

src/api/common/error/ImportError.ts, src/api/worker/facades/lazy/CalendarFacade.ts
=> Log errors in calendar facade

src/app.ts, src/mail/view/ConversationViewModel.ts, src/mail/view/MailViewerViewModel.ts
close #5189
this is not 100% clean but it's good enough to not drown out real entity leaks until we fix the underlying problem with the listeners.
=> fix Entity leak warning

src/search/view/MultiSearchViewer.ts
=> fix action buttons don't work on mobile in the search view

src/mail/editor/MailEditor.ts, src/mail/editor/MailEditorViewModel.ts
we assumed that we're always getting data files, but now we can get file refs.
now mapping them to data files before inserting into the editor
fix #5157
fix c3529794f87c859b4b308007cc8d69c351398d34
=> [desktop] fix not being able to add inline images

src/mail/view/ConversationViewModel.ts
=> load mail bodies during conversation load retry

app-android/app/build.gradle, app-android/app/src/main/java/de/tutao/tutanota/AndroidFileFacade.kt, app-android/app/src/main/java/de/tutao/tutanota/generated_ipc/FileFacade.kt, app-android/app/src/main/java/de/tutao/tutanota/generated_ipc/FileFacadeReceiveDispatcher.kt, app-ios/tutanota/Info.plist, app-ios/tutanota/Sources/Files/IosFileFacade.swift, app-ios/tutanota/Sources/GeneratedIpc/FileFacade.swift, app-ios/tutanota/Sources/GeneratedIpc/FileFacadeReceiveDispatcher.swift, ipc-schema/facades/FileFacade.json, package-lock.json, package.json, packages/licc/package.json, packages/tutanota-crypto/package.json, packages/tutanota-test-utils/package.json, packages/tutanota-usagetests/package.json, packages/tutanota-utils/package.json, src/desktop/ApplicationWindow.ts, src/desktop/DesktopFileFacade.ts, src/mail/editor/MailEditor.ts, src/mail/editor/MailEditorViewModel.ts, src/mail/view/ConversationViewModel.ts, src/native/common/FileApp.ts, src/native/common/generatedipc/FileFacade.ts, src/native/common/generatedipc/FileFacadeReceiveDispatcher.ts
* downgrade electron 22 because of connection problems
* remove leftover logs
* file extension filter for inline images
* make attachment button work in apps again
* svg inline images on desktop
=> fixing dev bugs

src/mail/editor/SendMailModel.ts
we changed all mail address comparisons to be case-insensitive in the case of the recipientsFilter this was implemented in a mutating way for performance reasons
on mail that contains a mixed-case sender this leads to us changing a final field on the mail when trying to update the reply flag which is illegal
we now filter the array without changing its contents
fix #5212
=> fix recipientsFilter changing the recipients' mail addresses

schemas/accounting.json, src/api/entities/accounting/ModelInfo.ts, src/api/entities/accounting/TypeModels.js, src/api/entities/accounting/TypeRefs.ts, src/api/worker/offline/OfflineStorageMigrator.ts, src/api/worker/offline/migrations/accounting-v5.ts, src/subscription/PaymentViewer.ts
See server side issue tutadb#1373
=> improve balance calculation

src/login/contactform/ContactFormRequestDialog.ts, src/login/recover/RecoverLoginDialog.ts, src/settings/AddUserDialog.ts, src/settings/PasswordForm.ts, src/settings/login/ChangePasswordDialogs.ts, src/subscription/SignupForm.ts
* confirm password on all password changes that are not reversible without credentials (admins can just try again)
* show reveal toggle on all password fields
close #5185
=> make password confirm text field visible by default

src/api/worker/WorkerLocator.ts, src/api/worker/facades/lazy/CalendarFacade.ts, src/misc/TranslationKey.ts, src/translations/de.ts, src/translations/de_sie.ts, src/translations/en.ts, test/tests/api/worker/facades/CalendarFacadeTest.ts
close https://github.com/tutao/tutanota/issues/4915
close https://github.com/tutao/tutanota/issues/4457
=> Notify user about too many alarms

libs/mithril.js, src/misc/ClientDetector.ts
=> Fix rendering failing silently

src/settings/mailaddress/MailAddressTable.ts
Custom aliases can be only deleted, there is no option to explicitly activate them again. -> delete confirmation dialog
Tutanota aliases can be activated -> no confirmation dialog is shown, and they can be deactivated -> deactivate confirmation dialog
The bug was introduced here: 797c6e75a99d0a4b4b1de3903995e661ea630acd
fix #5042
=> fix wrong message for activating an alias

app-android/app/build.gradle, app-android/app/src/main/java/de/tutao/tutanota/MainActivity.kt, app-android/app/src/main/res/values-v26/styles.xml, app-android/app/src/main/res/values/styles.xml
Use SplashScreen API
close #3719
=> Use SplashScreen API

src/gui/Header.ts, src/mail/view/ConversationViewer.ts, src/mail/view/MailView.ts
Display mail subject in header on mobile
close #5251
=> Display mail subject in header on mobile

src/mail/view/CollapsedMailView.ts, src/mail/view/MailViewerHeader.ts
Prevent unwanted text wrapping on the date
fix #5250
=> Prevent unwanted text wrapping on the date

ci/Android.Jenkinsfile, ci/Desktop.Jenkinsfile, ci/Ios.Jenkinsfile, ci/Release.Jenkinsfile
it's set through the global jenkins configuration now
=> [ci] remove NODE_PATH from jenkinsfiles

package-lock.json, package.json
includes a fix for uncatchable net errors
during differential downloads
fix #5338
=> update electron-updater to 6.0.4

src/api/common/TutanotaConstants.ts, src/calendar/date/CalendarInvites.ts, src/calendar/view/CalendarEventPopup.ts, src/gui/AttachmentBubble.ts, src/gui/animation/Animations.ts, src/gui/base/Button.ts, src/gui/base/Dropdown.ts, src/gui/base/Modal.ts, src/gui/main-styles.ts, src/login/contactform/ContactFormRequestDialog.ts, src/mail/editor/MailEditor.ts, src/mail/editor/MailEditorViewModel.ts, src/mail/view/AttachmentBubble.ts, src/mail/view/MailViewerHeader.ts, src/misc/Formatter.ts
=> improve attachment bubbles

src/gui/nav/DrawerMenu.ts, src/gui/nav/NavFunctions.ts, src/support/SupportDialog.ts
contact option at the end of the results is now only shown for premium users
fix #5368
=> show FAQ option in help menu for free users

src/contacts/ContactEditor.ts
=> fix not being able to create contacts from mail view

src/api/worker/facades/lazy/CalendarFacade.ts, src/api/worker/rest/EntityRestClient.ts, test/tests/api/worker/facades/CalendarFacadeTest.ts
=> directly throw any offline errors from setupMultiple

src/gui/editor/Editor.ts
squire 2.0 removed the isPaste argument from the sanitizeToDomFragment function.
since sanitizeToDomFragment is called before squire's willPaste event is fired, we can't have our sanitization strategy depend on the willPaste event.
we therefore add our own paste handler to the dom element squire uses and set a flag once we detect a paste and reset it when squire next fires the "input" event.
* user pastes
* "paste" event on dom sets flag
* sanitizeToDomFragment is called by squire and we inject the flag
* "input" event on squire resets flag.
fix #5384
fix 0dd3cd40dbd7260e5c6272f605fe9d8d55d72eb7
=> fix mail editor loading external content on all replies

src/gui/main-styles.ts
=> Have correct background color when dragging mail

src/contacts/view/ContactListView.ts, src/gui/main-styles.ts, src/mail/view/MailRow.ts, src/settings/KnowledgeBaseListView.ts, src/settings/TemplateListView.ts, src/settings/UserListView.ts, src/settings/groups/GroupListView.ts
=> Fix styles of some of the list row

src/gui/base/CounterBadge.ts, src/gui/base/IconButton.ts, src/gui/base/NavButton.ts, src/mail/view/MailFolderRow.ts, src/mail/view/MailFoldersView.ts
adds folder edit button on hover and tab, and add folder on bottom
close #5298
=> Simple folder edit

src/gui/base/List.ts
=> Prevent incorrect select after moving mails

src/mail/view/ConversationViewer.ts, src/mail/view/MailViewer.ts, src/mail/view/MailViewerHeader.ts
=> Better apply safe inset to mail view

libs/squire-raw.mjs, package-lock.json, package.json
=> update squire to 2.0.3

src/mail/view/MailFoldersView.ts
=> add button row is tabbable and a true button

src/mail/view/MailFolderRow.ts
=> menu button does not show for folder row on mobile

src/mail/view/CollapsedMailView.ts
=> Add ability to tab to and open collapsed mails with keyboard

src/misc/RouteChange.ts
=> add error catch for dead object

src/gui/MobileHeader.ts
=> Fix double progress bar in 2 column layout

src/api/common/TutanotaConstants.ts, src/misc/TranslationKey.ts, src/subscription/SwitchSubscriptionDialog.ts, src/translations/de.ts, src/translations/de_sie.ts, src/translations/en.ts
Give information to the user to resolve any issue with switching.
tutadb#1479
=> Handle precondition failed errors when switching plans

src/subscription/SubscriptionSelector.ts
=> Fix signup showing text about switching plans

src/subscription/SubscriptionUtils.ts
Better inform how the user can fix upgrading in some cases.
tutadb#1488
=> Add PreconditionFailedPaymentMsg cases

src/desktop/DesktopMain.ts, src/desktop/config/ConfigFile.ts, src/desktop/config/DesktopConfig.ts, test/tests/Suite.ts, test/tests/desktop/config/ConfigFileTest.ts, test/tests/desktop/config/DesktopConfigTest.ts
=> Make DesktopConfigTest and update DesktopConfig

src/gui/FolderColumnView.ts, src/gui/main-styles.ts
=> Fix background color for the drawer menu

src/settings/TemplateDetailsViewer.ts, src/settings/TemplateListView.ts
this also fixes links not opening in the browser or a new tab
fix #5484
=> sanitize templates before displaying them

src/contacts/view/ContactListView.ts, src/gui/base/NewList.ts, src/mail/view/MailListView.ts, src/misc/ListModel.ts, src/search/view/SearchListView.ts
=> Fix inclusive/exclusive multiselect behavior for list items

package-lock.json, package.json
=> Electron 25.2.0

schemas/sys.json, src/api/entities/sys/ModelInfo.ts, src/api/entities/sys/TypeModels.js, src/api/entities/sys/TypeRefs.ts, src/api/worker/offline/OfflineStorageMigrator.ts, src/api/worker/offline/migrations/sys-v88.ts, src/misc/TranslationKey.ts, src/translations/de.ts, src/translations/de_sie.ts, src/translations/en.ts
=> model changes for basic promotion support

src/misc/ListModel.ts, test/tests/misc/ListModelTest.ts
=> Keyboard control issue 5579

src/misc/ListModel.ts, test/tests/misc/ListModelTest.ts
=> Fix issue with ctrl click not selecting mail

src/gui/base/List.ts, src/gui/base/ListSwipeHandler.ts, src/subscription/BuyOptionBox.ts, src/subscription/SubscriptionSelector.ts, src/subscription/giftcards/PurchaseGiftCardDialog.ts
fix https://github.com/tutao/tutanota/issues/5598
fix https://github.com/tutao/tutanota/issues/5603
=> Scrollbar fixes

src/gui/base/BaseSearchBar.ts, src/search/SearchBar.ts
=> focus search bar when using keyboard shortcut

src/contacts/view/ContactListView.ts, src/gui/base/List.ts, src/mail/view/MailListView.ts, src/search/view/SearchListView.ts, src/settings/KnowledgeBaseListView.ts, src/settings/TemplateListView.ts, src/settings/UserListView.ts, src/settings/contactform/ContactFormListView.ts, src/settings/groups/GroupListView.ts
=> List selection fixes (again)

src/templates/view/TemplateExpander.ts
=> Fix links in template popup

packages/tutanota-utils/lib/ArrayUtils.ts, src/misc/ListModel.ts, test/tests/misc/ListModelTest.ts
=> Fix updating list item with custom sort

src/gui/base/List.ts
=> Handle missing ResizeObserver

src/desktop/DesktopWindowManager.ts, src/desktop/ElectronExportTypes.ts
Event.sender is not set anymore nor do we need it.
fix #5630
=> [desktop]  Fix uncaught error or resizing

app-android/app/build.gradle, app-android/app/src/main/java/de/tutao/tutanota/AndroidFileFacade.kt, app-android/app/src/main/java/de/tutao/tutanota/MainActivity.kt, app-android/app/src/main/java/de/tutao/tutanota/NetworkUtils.kt, app-android/app/src/main/java/de/tutao/tutanota/TLS13SocketFactory.java, app-android/app/src/main/java/de/tutao/tutanota/Utils.kt, app-android/app/src/main/java/de/tutao/tutanota/push/PushNotificationService.kt, app-android/app/src/main/java/de/tutao/tutanota/push/SseClient.kt, app-android/app/src/main/java/de/tutao/tutanota/push/TutanotaNotificationsHandler.kt
Tests to be run with a device < Android 10 and with a device >= Android 10
=> tls1.3 support for android < 10

src/api/common/TutanotaConstants.ts, src/api/main/UserController.ts, src/api/worker/facades/LoginFacade.ts, src/api/worker/facades/lazy/CustomerFacade.ts, src/api/worker/facades/lazy/UserManagementFacade.ts, src/subscription/BuyDialog.ts, src/subscription/SubscriptionUtils.ts, src/subscription/SubscriptionViewer.ts, src/subscription/SwitchSubscriptionDialog.ts, src/subscription/UpgradeConfirmSubscriptionPage.ts, test/tests/api/worker/facades/LoginFacadeTest.ts, test/tests/calendar/CalendarTestUtils.ts, test/tests/calendar/eventeditor/CalendarEventModelTest.ts, test/tests/calendar/eventeditor/CalendarEventWhoModelTest.ts, test/tests/subscription/SwitchSubscriptionDialogModelTest.ts
Because that is what it actually means.
tutadb#1543
=> Rename AccountType.PREMIUM to AccountType.PAID

src/templates/TemplateGroupUtils.ts
=> Do not try to GET from UpgradePriceService until we know we need it

src/settings/mailaddress/MailAddressTable.ts, src/settings/mailaddress/MailAddressTableModel.ts
Handle reactivating aliases.
Also only show plans that will give the user more aliases.
tutadb#1476
=> Improve handling of alias limits

src/calendar/date/eventeditor/CalendarEventModel.ts, src/calendar/view/eventeditor/CalendarEventEditView.ts
moved the condition into a method so the intent is a bit more clear
fix #5690
=> fix showing the wrong readonly message for single edit operations

src/calendar/date/CalendarUtils.ts, src/calendar/model/CalendarModel.ts
=> fix events not being recreated when they become long/short

src/calendar/view/CalendarViewModel.ts
we changed the CalendarModel to only re-create the event when it's really necessary, but we relied on the ID change in the CalendarView entity update handler for some unnecessary cases.
fix #5725
=> fix CalendarView not properly removing events that lost days

src/calendar/date/eventeditor/CalendarEventModel.ts, src/calendar/view/eventeditor/CalendarEventEditView.ts, src/calendar/view/eventeditor/RepeatRuleEditor.ts
=> fix repeat rule being editable in situations where it should not

app-android/app/build.gradle, app-ios/tutanota/Info.plist, package-lock.json, package.json, packages/licc/package.json, packages/otest/package.json, packages/tutanota-crypto/package.json, packages/tutanota-test-utils/package.json, packages/tutanota-usagetests/package.json, packages/tutanota-utils/package.json, src/mail/view/MailView.ts
fix ada22cf214a8633195f2391f72a59335bf8e56ab
fix #5745
=> fix wrong column focus in mailview

src/calendar/date/eventeditor/CalendarEventWhenModel.ts, src/calendar/export/CalendarParser.ts, test/tests/calendar/CalendarParserTest.ts, test/tests/calendar/eventeditor/CalendarEventWhenModelTest.ts
Also fixes duplicate exclusions on the event
fix #5750
=> Fix recurrence-id not being parsed in correct zone

src/api/entities/tutanota/ModelInfo.ts, src/api/worker/EventBusClient.ts, src/api/worker/EventBusEventCoordinator.ts, src/api/worker/facades/lazy/MailFacade.ts, test/tests/api/worker/facades/MailFacadeTest.ts
=> model changes for user spam reports

app-android/app/build.gradle, app-android/app/src/main/AndroidManifest.xml, app-android/app/src/main/java/de/tutao/tutanota/MainActivity.kt, app-android/app/src/main/java/de/tutao/tutanota/Utils.kt, app-android/app/src/main/java/de/tutao/tutanota/push/AndroidNativePushFacade.kt, app-android/app/src/main/java/de/tutao/tutanota/push/LocalNotificationsFacade.kt, app-android/app/src/main/java/de/tutao/tutanota/push/PushNotificationService.kt
=> target android api v33

libs/squire-raw.mjs, src/RootView.ts, src/api/common/TutanotaConstants.ts, src/api/main/EntropyCollector.ts, src/gui/SearchInPageOverlay.ts, src/gui/base/BubbleTextField.ts, src/gui/base/Dialog.ts, src/gui/base/List.ts, src/gui/base/NavButton.ts, src/gui/date/DatePicker.ts, src/gui/date/TimePicker.ts, src/gui/editor/Editor.ts, src/mail/editor/MailEditor.ts, src/mail/view/CollapsedMailView.ts, src/mail/view/MailViewerHeader.ts, src/misc/KeyManager.ts, src/search/SearchBar.ts, src/templates/view/TemplateExpander.ts, src/templates/view/TemplatePopup.ts, src/templates/view/TemplateShortcutListener.ts, test/tests/api/main/EntropyCollectorTest.ts
=> Keyboard events remove depricated 4221

app-android/app/src/main/java/de/tutao/tutanota/MainActivity.kt
we have been saving the webView state in onSaveInstanceState, which puts the current history stack into the bundle. Our history entries can be quite big because they contain the favicon and encoded custom theme and custom logo.
even on non-whitelabel accounts it could get big by just having a lot of entries.
we're never restoring this state, so it should be fine to just not save it and prevent the resulting crashes from bundles > 1MB.
also fix some warnings
fix #5529
=> [android] fix excessive bundle size when putting app in background

src/sharing/model/GroupSharingModel.ts, src/sharing/view/GroupSharingDialog.ts
=> Close sharing dialog if removing self from group

src/contacts/view/ContactListViewModel.ts
=> Load contact list from url

src/contacts/ContactListEditor.ts, src/contacts/view/ContactView.ts, src/gui/MailRecipientsTextField.ts, src/gui/base/BubbleTextField.ts, src/misc/TranslationKey.ts, src/translations/de.ts, src/translations/de_sie.ts, src/translations/en.ts, test/tests/contacts/ContactListEditorTest.ts
=> improve the contact list edit dialog, help text and translations

src/api/common/TutanotaConstants.ts, src/api/worker/offline/migrations/sys-v90.ts
We didn't migrate User in v89, so we need to migrate it in v90.
tutadb#1600
=> Add missing kdfVersion migration

src/api/main/EntropyCollector.ts, src/misc/KeyManager.ts
=> Check for key and handle instead of throwing error

src/gui/SearchInPageOverlay.ts, src/gui/base/BubbleTextField.ts, src/gui/base/TextField.ts, src/gui/date/DatePicker.ts, src/gui/date/TimePicker.ts, src/mail/view/MailListView.ts, src/search/SearchBar.ts, src/subscription/BuyOptionBox.ts, src/templates/view/TemplateSearchBar.ts
=> Update key press checking in more places

app-android/app/src/main/java/de/tutao/tutanota/MainActivity.kt, src/api/worker/offline/OfflineStorage.ts
We've noticed that loading worker-search bundle sometimes takes ~5 sec. Opening and reading of asset actually took no time.
Cause seems to be safebrowsing, which is not needed because we are loading only our own resources and we don't want to send info to Google anyway.
fix #5830
=> [android] Fix lag when logging in

buildSrc/RollupConfig.js, buildSrc/updateLibs.js, libs/winreg.mjs
=> vendor winreg

app-ios/tutanota/Sources/ViewController.swift
=> [ios] Fix reacting to system theme changes

src/gui/PinchZoom.ts, src/gui/main-styles.ts, src/mail/view/MailViewer.ts
=> PinchZoom for Android and iOS

src/contacts/view/ContactView.ts, src/sharing/view/GroupSharingDialog.ts
=> Fix error thrown when non-admin user get notAuthorized exception

src/gui/base/BubbleTextField.ts
=> Fix undefined error, check for key existing correctly

src/api/worker/facades/lazy/MailFacade.ts, test/tests/api/worker/facades/MailFacadeTest.ts
Verify that the mime type is correctly formatted so that it will not be rejected when sent.
tutadb#831
=> Validate that mime types are validly formatted when sent

packages/tutanota-usagetests/README.md, packages/tutanota-usagetests/lib/model/UsageTest.ts, packages/tutanota-usagetests/test/Suite.ts, src/api/common/TutanotaConstants.ts, src/api/main/MainLocator.ts, src/api/worker/facades/LoginFacade.ts, src/api/worker/facades/lazy/CustomerFacade.ts, src/api/worker/facades/lazy/MailFacade.ts, src/api/worker/facades/lazy/UserManagementFacade.ts, src/login/contactform/ContactFormRequestDialog.ts, src/login/recover/RecoverLoginDialog.ts, src/mail/editor/SendMailModel.ts, src/misc/ErrorReporter.ts, src/misc/KdfPicker.ts, src/misc/UsageTestModel.ts, src/settings/AddUserDialog.ts, src/settings/ImportUsersViewer.ts, src/settings/login/ChangePasswordDialogs.ts, src/subscription/SignupForm.ts, test/tests/mail/SendMailModelTest.ts
=> Rollout new kdf: argon2id

src/gui/PinchZoom.ts, src/gui/main-styles.ts, src/mail/view/MailGuiUtils.ts, src/mail/view/MailViewer.ts, src/misc/HtmlSanitizer.ts, test/tests/misc/HtmlSanitizerTest.ts
close #1997
fix #5913 
fix #5871
=> Pinch to zoom for emails

src/api/common/TutanotaConstants.ts, src/api/main/UserController.ts, src/app.ts, src/login/PostLoginActions.ts, src/login/PostLoginUtils.ts, test/tests/Suite.ts, test/tests/login/PostLoginUtilsTest.ts
close #5710
Still needs a translation update after the German translations are updated but otherwise is ready to be reviewed.
=> Implement new behavior for upgrade reminder

src/api/worker/WorkerLocator.ts, src/api/worker/facades/lazy/CalendarFacade.ts, src/api/worker/facades/lazy/GroupManagementFacade.ts, src/contacts/view/ContactListViewModel.ts
=> Add reload for user when adding contact list

src/sharing/GroupGuiUtils.ts
=> fix sender and calendar being swapped in the calendar invitation mail

src/calendar/view/CalendarViewModel.ts
we changed addDaysForEventInstance to only worry about the month it was called for and ignore the rest of the event that may extend to the next month, but did not adapt CalendarViewModel._addOrUpdateEvent to also add short events to the month where they end.
in cases where we
* receive an entity event update for a short event that starts in the current month but ends in the next
* the month view displays a complete week that is part of the next month at the bottom (to fill the 6x7 grid)
we would therefore not display that events end.
fix #5896
fix #5839
=> fix short events not being displayed sometimes in the 6th week row

app-ios/tutanota.xcodeproj/project.pbxproj, app-ios/tutanota/Sources/CustomSchemeHandlers.swift, app-ios/tutanota/Sources/Utils/UnfairLock.swift
There are two issues which should be fixed now:
- possibly calling methods on task that was cancelled
- accessing dictionary without thread safety
fix #5955
=> [ios] Fix crash in ApiSchemeHandler

app-android/app/src/main/java/de/tutao/tutanota/alarms/AlarmNotificationsManager.kt
=> [android] Guard against malformed alarms

src/calendar/model/CalendarModel.ts, test/tests/calendar/CalendarModelTest.ts
We need to wait for ownerEncSessionKey to be set, as it may not be immediately set when the update is triggered, and we lack a back reference to the Mail to get the bucket key for the file of the Calendar event.
tutadb#1644
=> Wait until ownerEncSessionKey is set before processing calendar event updates

src/api/common/EntityClient.ts, src/api/main/MainLocator.ts, src/api/worker/WorkerLocator.ts, src/api/worker/crypto/CryptoFacade.ts, src/api/worker/facades/lazy/GroupManagementFacade.ts, src/api/worker/facades/lazy/MailFacade.ts, src/api/worker/rest/DefaultEntityRestCache.ts, src/api/worker/rest/EntityRestClient.ts, src/api/worker/search/Indexer.ts, src/api/worker/search/MailIndexer.ts, src/mail/export/Bundler.ts, src/mail/export/Exporter.ts, src/mail/model/InboxRuleHandler.ts, src/mail/model/MailUtils.ts, src/mail/view/MailListView.ts, src/mail/view/MailViewerToolbar.ts, src/mail/view/MailViewerUtils.ts, src/mail/view/MailViewerViewModel.ts, test/tests/api/worker/search/IndexerTest.ts, test/tests/api/worker/search/MailIndexerTest.ts, test/tests/mail/InboxRuleHandlerTest.ts, test/tests/mail/export/BundlerTest.ts
server issue 1657
Test on any account:
Test on an account with mail details enabled:
Test on an account with mail details disabled (legacy):
=> Fix decrypt file

src/api/common/TutanotaConstants.ts, src/settings/mailaddress/MailAddressesUtils.ts, src/subscription/SignupForm.ts
Test Notes: check if the forbidden domain is shown in the dropdown
=> Remove domain that should not be available yet

src/misc/2fa/SecondFactorAuthDialog.ts, src/misc/2fa/SecondFactorAuthView.ts, src/misc/2fa/webauthn/WebauthnClient.ts
=> 2fa fixes small

app-ios/TutanotaShareExtension/ShareViewController.swift, app-ios/tutanota/Sources/Files/BlobUtil.swift, app-ios/tutanota/Sources/Files/FileUtils.swift, app-ios/tutanota/Sources/Files/IosFileFacade.swift, app-ios/tutanota/Sources/Sharing/SharingStorage.swift
Throw error instead of crashing when not able to handle file
close #5209
=> [ios] Zip file when attaching if it is secretly a directory

src/api/common/utils/CommonCalendarUtils.ts, src/calendar/view/CalendarView.ts
=> Events still display when adding event in day view

src/misc/KeyManager.ts
=> Check if KeyboardEvent is in a composition event

src/search/view/SearchViewModel.ts
sometimes, the search result display list passes an ID to fetch() that is not actually contained in the search result list. possible causes:
1. that mail was moved while the search was active, but not applied yet
2. the search query changed and the whole result list is invalidated before the display list was notified
both cases are not serious errors and can be fixed by re-searching. this commit changes the logic to load from the newest ID in the results that is older than or equal to the requested load start instead of requiring an exact match, which should give plausible results at least in case 1.
fix #5340
=> fix error when search list loads from ID not contained in results

src/login/LoginViewModel.ts
=> change migration time

packages/tutanota-utils/lib/ArrayUtils.ts, src/api/common/TutanotaConstants.ts, src/gui/base/WizardDialog.ts, src/misc/TranslationKey.ts, src/settings/AddUserDialog.ts, src/settings/SelectMailAddressForm.ts, src/settings/SettingsView.ts, src/settings/emaildomain/AddEmailAddressesPage.ts, src/settings/emaildomain/EnterDomainPage.ts, src/settings/emaildomain/VerifyDnsRecordsPage.ts, src/settings/emaildomain/VerifyOwnershipPage.ts, src/settings/groups/AddGroupDialog.ts, src/settings/mailaddress/AddAliasDialog.ts, src/settings/mailaddress/MailAddressTable.ts, src/settings/mailaddress/MailAddressTableModel.ts, src/settings/mailaddress/MailAddressesUtils.ts, src/subscription/InvoiceAndPaymentDataPage.ts, src/subscription/SignupForm.ts, src/subscription/SignupPage.ts, src/subscription/UpgradeConfirmSubscriptionPage.ts, src/subscription/UpgradeCongratulationsPage.ts, src/subscription/UpgradeSubscriptionPage.ts, src/subscription/UpgradeSubscriptionWizard.ts, src/subscription/giftcards/RedeemGiftCardWizard.ts, src/translations/de.ts, src/translations/de_sie.ts, src/translations/en.ts
close #5961
Hide paid email domains for iOS
tutadb merge request 521
=> Add tuta.com as email address domain

src/misc/Formatter.ts
=> Better check for yesterday when adding label to mail

src/calendar/view/eventeditor/AttendeeListEditor.ts
=> Check if user is admin before asking about plan upgrade in calendar

src/api/worker/search/Indexer.ts, test/tests/api/worker/search/IndexerTest.ts
=> Ios indexer bug 6046

src/login/PostLoginActions.ts
fix #6065
fix 55fb3dc8963e6be7b6602e8895e46e43c924c558
=> fix second factor filter in post login actions not doing anything

src/api/common/TutanotaConstants.ts
=> Remove signup for new domain

src/api/common/TutanotaConstants.ts, src/subscription/UpgradeSubscriptionPage.ts
=> Prevent user from signing up with free tuta.com address

src/api/common/TutanotaConstants.ts, src/settings/AddUserDialog.ts, src/subscription/UpgradeSubscriptionPage.ts
=> Remove check for first party domain when upgrading subscription

app-android/app/src/main/java/de/tutao/tutanota/AndroidThemeFacade.kt, app-android/app/src/main/java/de/tutao/tutanota/MainActivity.kt, app-android/app/src/main/java/de/tutao/tutanota/Utils.kt
=> [android] Remove deprecated PreferenceManager

src/mail/view/MailListView.ts
When inside a subfolder of Archive, the action of swipe to inbox moves the email to the main Archive folder.
This commit changes the verification of email destiny by checking if the selected folder is a subfolder of Archive during the render config.
fix #6086
=> Fix swipe to inbox when inside a subfolder of Archive

src/gui/PinchZoom.ts, src/mail/view/MailViewer.ts
fix #6038
fix #6037 
fix #6013
=> Pinch zoom orientation issue 6038

buildSrc/RollupConfig.js, buildSrc/updateLibs.js, libs/undici.mjs
fix 803bbf05b06c321659e518d56c02e27bc9935fa1
close #6150
#6053
=> vendor undici 5.27.2

src/api/worker/search/DbFacade.ts
It seems like Safari still has odd behavior around transactions and microtasks. We suspect that the issue occurred because of an additional async/await. We rolled back createTransaction() to the previous state.
Fix #6146
=> Fix IndexedDB transaction timing out on iOS

src/mail/model/MailUtils.ts, src/mail/view/MailListView.ts
=> Update where archive_label is used

src/search/view/SearchView.ts, src/search/view/SearchViewModel.ts
=> Remove check that resulted in reloading with empty search results

src/misc/SubscriptionDialogs.ts, src/templates/TemplateGroupUtils.ts
=> Check if user is Global Admin before getting available plans

src/api/worker/facades/lazy/MailFacade.ts, src/api/worker/search/MailIndexer.ts, src/desktop/DesktopMain.ts, src/desktop/tray/DesktopTray.ts, src/mail/editor/MailEditor.ts, src/mail/view/MailViewerHeader.ts, src/mail/view/MailViewerViewModel.ts, src/search/view/SearchViewModel.ts
This fixes the tray icon still appearing when 'run in background' is disabled. It also fixes the tray icon not being added or removed when the setting is changed.
Closes #2173.
=> Fix tray icon still being displayed when it's disabled in the settings

src/api/worker/facades/lazy/MailFacade.ts, src/api/worker/search/MailIndexer.ts, src/desktop/DesktopMain.ts, src/desktop/tray/DesktopTray.ts, src/mail/editor/MailEditor.ts, src/mail/view/MailRow.ts, src/mail/view/MailViewerHeader.ts, src/mail/view/MailViewerViewModel.ts, src/misc/ClientConstants.ts, src/search/SearchBarOverlay.ts, src/search/view/SearchViewModel.ts
This adds the team badge to the translation system & changes it's text to 'Tuta Team' in English & German.
Closes #6246.
=> Fix team badge text still being 'Tutanota Team'

src/api/worker/facades/lazy/MailFacade.ts, src/api/worker/search/MailIndexer.ts, src/desktop/DesktopMain.ts, src/desktop/sse/SecretStorage.ts, src/desktop/tray/DesktopTray.ts, src/mail/editor/MailEditor.ts, src/mail/model/InboxRuleHandler.ts, src/mail/view/MailRow.ts, src/mail/view/MailViewerHeader.ts, src/mail/view/MailViewerViewModel.ts, src/misc/ClientConstants.ts, src/search/SearchBarOverlay.ts, src/search/view/SearchViewModel.ts
fix b29a7b319a92a614c18462a63b8697bf36f05f79
close #6267
=> fix inbox rules treating legacy and maildetails mail bcc differently

src/api/worker/facades/lazy/MailFacade.ts, src/api/worker/search/MailIndexer.ts, src/desktop/DesktopMain.ts, src/desktop/sse/SecretStorage.ts, src/desktop/tray/DesktopTray.ts, src/mail/editor/MailEditor.ts, src/mail/model/InboxRuleHandler.ts, src/mail/view/MailRow.ts, src/mail/view/MailViewerHeader.ts, src/mail/view/MailViewerViewModel.ts, src/misc/ClientConstants.ts, src/search/SearchBarOverlay.ts, src/search/view/SearchViewModel.ts, src/settings/SelectMailAddressForm.ts
object identity comparison instead of string comparison caused the validation to be restarted on each update call
fix 434bf2bb6c9ef0100f7e577cdefea825b2a360a9
close #6222
=> fix eternal email validation in SelectMailAddressForm

src/api/worker/WorkerLocator.ts, src/api/worker/facades/lazy/BlobFacade.ts, test/tests/api/worker/facades/BlobFacadeTest.ts
=> retry to load session key in case instance is out of sync

src/gui/base/Checkbox.ts, src/gui/base/GuiUtils.ts, src/gui/main-styles.ts, src/misc/HtmlSanitizer.ts, src/subscription/SignupForm.ts, src/subscription/giftcards/GiftCardUtils.ts
=> Fix checkbox being misplaced when paired with a long label

src/api/worker/WorkerLocator.ts, src/api/worker/facades/lazy/BlobFacade.ts
There is no cache in the admin client...
=> fix admin client

src/mail/view/MailViewerHeader.ts, src/mail/view/MailViewerViewModel.ts
=> fix authentication banner rendering

src/calendar/view/CalendarAgendaItemView.ts, src/calendar/view/CalendarAgendaView.ts, src/calendar/view/CalendarDayEventsView.ts, src/calendar/view/CalendarMonthView.ts, src/calendar/view/CalendarView.ts, src/calendar/view/CalendarViewModel.ts, src/calendar/view/MultiDayCalendarView.ts, src/gui/base/PageView.ts
=> Scroll to current time when looking at current day

src/api/worker/crypto/CryptoFacade.ts, src/api/worker/facades/lazy/MailFacade.ts
We also get rid of some redundant re-encryptions by just returning the re-encrypted instanceSessionKeys already.
tutadb#1747
=> Stop tryint to use MailSessionKey as BucketKey

src/calendar/view/CalendarAgendaView.ts
Fixes [this comment](https://github.com/tutao/tutanota/issues/6285#issuecomment-1894053611).
=> Fix the agenda view not scrolling to the current time on today

src/calendar/view/CalendarAgendaView.ts
Fixes [this comment](https://github.com/tutao/tutanota/issues/6326#issuecomment-1895774319).
=> Fix a horizontal scrollbar appearing in the agenda view

src/calendar/view/CalendarAgendaView.ts, src/calendar/view/CalendarMonthView.ts, src/calendar/view/MultiDayCalendarView.ts, src/gui/base/PageView.ts
=> Handle swipe gesture in the agenda view event list 

src/api/main/MainLocator.ts, src/contacts/model/ContactModel.ts, src/login/CredentialRemovalHandler.ts, src/login/LoginViewModel.ts, src/misc/DeviceConfig.ts, src/misc/TranslationKey.ts, src/settings/ContactsSettingsViewer.ts, src/settings/MailSettingsViewer.ts, src/settings/SettingsView.ts, src/translations/de.ts, src/translations/de_sie.ts, src/translations/en.ts, test/tests/login/LoginViewModelTest.ts, test/tests/misc/DeviceConfigTest.ts
Added the contacts section to the settings view and moved the creation
of new contacts when sending an email from the Email section to Contacts
section. 
Also now, when the user deletes their credentials from the app,
their previous synchronized Tuta contacts are removed from phones'
contact book.
close #6374
=> Manage Tuta Contacts synchronization

libs/squire-raw.mjs
This fixes the issue in our local copy of squire, we should also submit a PR to the squire repository.
Closes #6220.
=> Fix the editor not switching to RTL when replying

src/calendar/date/CalendarEventsRepository.ts, src/calendar/view/CalendarViewModel.ts
=> Fix not seeing some calendar event updates in calendar

src/calendar/gui/eventeditor-view/CalendarEventEditView.ts, src/calendar/gui/pickers/DatePicker.ts
=> Disable mobile date input when it cannot be edited

src/calendar/gui/eventpopup/EventPreviewView.ts, src/gui/base/ExternalLink.ts, src/gui/base/GuiUtils.ts, src/login/LoginView.ts, src/login/recover/TakeOverDeletedAddressDialog.ts, src/mail/view/MailViewerUtils.ts, src/misc/2fa/SecondFactorAuthView.ts, src/misc/LanguageViewModel.ts, src/misc/news/MoreInfoLink.ts, src/misc/news/items/PinBiometricsNews.ts, src/misc/news/items/ReferralLinkViewer.ts, src/misc/passwords/PasswordGeneratorDialog.ts, src/settings/AboutDialog.ts, src/settings/DesktopSettingsViewer.ts, src/settings/emaildomain/VerifyDnsRecordsPage.ts, src/settings/groups/AddGroupDialog.ts, src/settings/login/LoginSettingsViewer.ts, src/settings/login/RecoverCodeDialog.ts, src/settings/login/secondfactor/SecondFactorsEditForm.ts, src/subscription/SignupForm.ts
=> Fix links not being keyboard accessible

app-android/app/src/main/java/de/tutao/tutanota/AesKeyLength.kt, app-android/app/src/main/java/de/tutao/tutanota/AndroidNativeCryptoFacade.kt, app-ios/tutanota/Sources/Crypto/AES.swift, packages/tutanota-crypto/lib/encryption/Aes.ts, packages/tutanota-crypto/lib/encryption/KeyEncryption.ts, packages/tutanota-crypto/lib/index.ts, packages/tutanota-crypto/test/AesTest.ts, packages/tutanota-crypto/test/KeyEncryptionTest.ts, src/api/worker/crypto/CryptoFacade.ts, src/api/worker/crypto/InstanceMapper.ts, src/api/worker/facades/LoginFacade.ts, src/api/worker/facades/PQFacade.ts, src/api/worker/facades/lazy/ConfigurationDatabase.ts, src/api/worker/search/IndexUtils.ts, src/api/worker/search/Indexer.ts, src/api/worker/search/IndexerCore.ts, src/api/worker/search/SuggestionFacade.ts, src/desktop/CryptoFns.ts, src/desktop/DesktopKeyStoreFacade.ts, src/desktop/DesktopNativeCryptoFacade.ts, src/desktop/credentials/DesktopNativeCredentialsFacade.ts, src/desktop/sse/DesktopAlarmStorage.ts, test/tests/TestUtils.ts, test/tests/api/worker/search/IndexUtilsTest.ts, test/tests/api/worker/search/IndexerCoreTest.ts, test/tests/desktop/DesktopCryptoFacadeTest.ts, test/tests/desktop/DesktopKeyStoreFacadeTest.ts, test/tests/desktop/config/DesktopConfigTest.ts, test/tests/desktop/sse/DesktopAlarmStorageTest.ts
There are a number of exceptions because of legacy data.
=> Enforce MACs for AES-256-CBC

app-android/app/src/main/java/de/tutao/tutanota/MainActivity.kt, app-ios/tutanota/Sources/CustomSchemeHandlers.swift
=> fix invoice pdf download for android and ios app

buildSrc/bump-version.js
=> adapt bump-version.js to new version number scheme

buildSrc/packageBuilderFunctions.js
- Do not rely on shell to glob anymore so it should be more portable
- Do single tsc invocation with all packages
- Take list of runtime packages from tsconfig instead of duplicating it in the script
=> Improve package building functions

src/gui/base/Overlay.ts
=> Make overlay close action singleUse

libs/squire-raw.mjs, package-lock.json, package.json
=> Update Squire to 2.2.7

src/contacts/view/ContactView.ts, src/contacts/view/ContactViewerActions.ts, src/search/view/SearchView.ts
Adding the onConfirm function to deleteContacts in ContactView.ts is in line with how mails handle this need
in promptAndDeleteMails
fix #6507
=> Add selectNone when deleting contacts

src/contacts/ContactEditor.ts, src/gui/base/BubbleTextField.ts, src/gui/base/Dialog.ts, src/gui/base/TextField.ts, src/gui/editor/Editor.ts, src/login/recover/RecoverLoginDialog.ts, src/login/recover/TakeOverDeletedAddressDialog.ts, src/settings/IdentifierListViewer.ts, src/settings/UserViewer.ts, src/settings/groups/GroupDetailsView.ts, src/settings/mailaddress/MailAddressTable.ts, src/settings/whitelabel/WhitelabelImprintAndPrivacySettings.ts, src/settings/whitelabel/WhitelabelRegistrationSettings.ts, src/subscription/DeleteAccountDialog.ts
This hints devices such as phones what keyboard type to use.
Fixes #6097
=> Fix url/email input types not being used for some fields

src/login/LoginViewModel.ts, src/login/MigratingCredentialsBanner.ts, test/tests/login/LoginViewModelTest.ts
Prevent it from showing on whitelabel in addition to apps.
Fixes #6496
=> Don't show MigratingCredentialsBanner outside of main webapp page

.github/workflows/swift-test.yml, .github/workflows/test.yml
They are already run before merging
=> [ci] Do not run checks again on master

libs/squire-raw.mjs
=> Remove check in squire that prevented pasting multi-line text

.github/workflows/test.yml
This will allow to run on PRs from forks
=> [ci] Run test only on PR updates

app-android/gradle/wrapper/gradle-wrapper.properties
=> [android, build] Update gradle wrapper to 8.5

src/misc/TranslationKey.ts, src/settings/GlobalSettingsViewer.ts, src/translations/de.ts, src/translations/de_sie.ts, src/translations/en.ts
=> Fix a label in global settings clipping on mobile

app-android/app/src/main/java/de/tutao/tutanota/MainActivity.kt
This commit flags an intent that has already been handled by the app as handled, avoiding that when the user opens the app an intent re-deliver causes auto login.
fix #6322
=> Fix Android unwanted auto login

src/calendar/gui/eventeditor-model/CalendarEventModel.ts, src/calendar/gui/eventeditor-view/CalendarEventEditView.ts
=> Fix being unable to change the calendar for accepted events

src/settings/mailaddress/AddAliasDialog.ts, src/settings/mailaddress/MailAddressTableModel.ts, src/subscription/SubscriptionSelector.ts
=> Better info dialogs around adding email addresses

libs/squire-raw.mjs, src/gui/editor/Editor.ts, src/gui/editor/HtmlEditor.ts
Fix the workaround for fixing ctrl-shift-z so that tab is still recognized correctly for list indentation.
Fixes #6661
=> Fix tabbing not working properly

app-android/app/src/main/java/de/tutao/tutanota/push/LocalNotificationsFacade.kt, app-android/app/src/main/res/drawable/ic_alarm.xml, app-android/app/src/main/res/drawable/ic_sync.xml
=> Add new Icons to Reminders and Notification Service

src/gui/base/RecipientButton.ts
=> Fix click on recipientButton

libs/better-sqlite3.mjs, libs/cborg.js, libs/electron-updater.mjs, libs/purify.js, libs/undici.mjs, libs/winreg.mjs, package-lock.json, package.json
=> Dompurify 3.0.10

src/gui/base/RadioSelector.ts, src/gui/dialogs/SelectCredentialsEncryptionModeDialog.ts, src/gui/dialogs/setupwizardpages/SetupLockPage.ts
=> Credential selector fixes

src/login/PostLoginActions.ts
=> Fix permission for notifications being asked too early

src/contacts/model/NativeContactsSyncManager.ts
=> Fix iOS empty notes overwriting Tuta notes

app-android/app/src/main/java/de/tutao/tutanota/generated_ipc/MobileContactsFacade.kt, app-android/app/src/main/java/de/tutao/tutanota/generated_ipc/MobileContactsFacadeReceiveDispatcher.kt, app-ios/tutanota/Sources/Contacts/IosMobileContactsFacade.swift, app-ios/tutanota/Sources/GeneratedIpc/MobileContactsFacade.swift, app-ios/tutanota/Sources/GeneratedIpc/MobileContactsFacadeReceiveDispatcher.swift, ipc-schema/facades/MobileContactsFacade.json, src/contacts/ContactImporter.ts, src/native/common/generatedipc/MobileContactsFacade.ts
=> Fix import contacts on iOS

src/contacts/model/ContactModel.ts, src/search/SearchBar.ts, src/search/model/SearchUtils.ts, src/search/view/SearchView.ts, src/search/view/SearchViewModel.ts
=> Save restriction states of different search types

src/gui/editor/Editor.ts
=> Fix the Mail Editor not scrolling to the cursor when entering out of view

package-lock.json, package.json, src/desktop/net/ProtocolProxy.ts
fix https://github.com/tutao/tutanota/issues/6641
=> Desktop bugfixes

src/gui/base/Dialog.ts
=> Fix the keyboard shortcuts dialog becoming unopenable on back press

src/calendar/gui/CalendarGuiUtils.ts, src/calendar/gui/day-selector/DaySelector.ts, src/calendar/gui/day-selector/DaySelectorSidebar.ts, src/calendar/view/CalendarDesktopToolbar.ts, src/calendar/view/CalendarMonthView.ts, src/calendar/view/CalendarView.ts, src/calendar/view/MultiDayCalendarView.ts, src/gui/FolderColumnView.ts, src/gui/main-styles.ts, src/gui/size.ts, src/misc/LanguageViewModel.ts
=> Fix calendar issues

src/RootView.ts, src/gui/AriaUtils.ts, src/gui/base/Dropdown.ts, src/gui/base/buttons/BaseButton.ts, src/gui/base/buttons/RowButton.ts, src/mail/view/MailFoldersView.ts, src/mail/view/MailGuiUtils.ts, src/misc/TranslationKey.ts, src/translations/de.ts, src/translations/de_sie.ts, src/translations/en.ts
=> Fix the `DropDown`'s navigation and it's filter including cosmetic periods

app-ios/tutanota.xcodeproj/project.pbxproj, app-ios/tutanota/Sources/Contacts/ContactStoreError.swift, app-ios/tutanota/Sources/Contacts/IosMobileContactsFacade.swift, app-ios/tutanota/Sources/Remote/RemoteBridge.swift, src/api/common/error/ContactStoreError.ts, src/api/common/utils/ErrorUtils.ts, src/contacts/model/NativeContactsSyncManager.ts
=> Catch unknown errors during contact sync

src/api/main/MainLocator.ts, src/app.ts, src/contacts/ContactImporter.ts, src/contacts/view/ContactView.ts, src/gui/dialogs/SetupWizard.ts, src/gui/dialogs/setupwizardpages/SetupContactsPage.ts, src/gui/dialogs/setupwizardpages/SetupNotificationsPage.ts, src/login/PostLoginActions.ts, src/mail/view/MailView.ts, src/misc/TranslationKey.ts, src/native/main/SystemPermissionHandler.ts, src/settings/ContactsSettingsViewer.ts, src/settings/SettingsView.ts, src/translations/de.ts, src/translations/de_sie.ts, src/translations/en.ts
Ask for permission instead of throwing error when importing contacts
fix #6797
=> Ask for permission instead of throwing error when importing contacts

app-ios/tutanota/Sources/Keychain/IosNativeCredentialsFacade.swift, src/gui/dialogs/SelectCredentialsEncryptionModeDialog.ts, src/gui/dialogs/setupwizardpages/SetupLockPage.ts
=> [ios] Ask for permission when encrypting with biometrics

src/mail/view/MailGuiUtils.ts
=> Fix accessibility description for move mails dropdown

src/api/worker/offline/OfflineStorage.ts, src/api/worker/rest/DefaultEntityRestCache.ts, test/tests/api/worker/rest/EntityRestCacheTest.ts
=> reload cached legacy mails from server on load

src/gui/nav/DrawerMenu.ts
=> Fix the news button being displayed for external users 

src/mail/view/MailFoldersView.ts
This stops the more button on the folder rows from being created to avoid external users being able to 'create' unusable folders.
Closes #5457.
=> Fix the 'Add folder' button displaying for external users

src/contacts/ContactImporter.ts
=> Fix the import device contacts dialog showing the wrong title

src/api/worker/facades/lazy/MailFacade.ts
=> set the correct (default) kdf type when creating new external users

src/api/common/TutanotaConstants.ts, src/api/main/MainLocator.ts, src/api/worker/facades/LoginFacade.ts, test/tests/api/worker/facades/LoginFacadeTest.ts
=> enable argon2 migration

src/api/worker/facades/lazy/ContactFacade.ts, src/contacts/ContactImporter.ts, src/contacts/view/ImportAsVCard.ts, src/gui/SelectAllCheckbox.ts
=> Add the ability to choose specific contacts when importing contacts

src/settings/mailaddress/AddAliasDialog.ts
=> Change adding email addresses to always show custom domain first

src/gui/base/Icon.ts
Wrap folder name if needed, change off screen calculation
close #6302
=> Fix folder name tooltip display issues

ci/Android.Jenkinsfile, ci/Desktop.Jenkinsfile, ci/Ios.Jenkinsfile, ci/Webapp.Jenkinsfile
Co-authored-by: mup <mup@tutao.de>
=> Add Emscripten setup to jenkins files

ci/Android.Jenkinsfile, ci/Desktop.Jenkinsfile, ci/Ios.Jenkinsfile, ci/Webapp.Jenkinsfile
Co-authored-by: wrd <wrd@tutao.de>
=> Fix the emscripten script permission on jenkins

src/contacts/ContactImporter.ts, src/contacts/view/ContactListRecipientView.ts, src/contacts/view/ContactListView.ts, src/contacts/view/ContactRow.ts
=> Fix contact rows not showing their multi-select checkboxes

app-ios/TutanotaSharedFramework/Keychain/IosNativeCredentialsFacade.swift, app-ios/TutanotaSharedFramework/Notifications/NotificationStorage.swift, app-ios/TutanotaSharedTests/CredentialsFacadeTest.swift, app-ios/tutanota/Sources/AppDelegate.swift
Fix https://github.com/tutao/tutanota/issues/7014
=> Fix migrating data on iOS

src/login/LoginForm.ts
=> Do not trigger show password button when using enter to log in

app-ios/TutanotaSharedFramework/Credentials/CredentialsDatabase.swift, src/desktop/db/DesktopCredentialsStorage.ts
=> Change `INSERT` to `INSERT OR REPLACE` for storing credentials

src/gui/base/ViewColumn.ts, src/gui/nav/ViewSlider.ts
This reverts commit 77215b63.
Closes #7050.
=> Fix a blank screen appearing when swiping back

tuta-sdk/rust/Cargo.lock, tuta-sdk/rust/Cargo.toml, tuta-sdk/rust/src/crypto/compatibility_test_utils.rs, tuta-sdk/rust/src/crypto/ecc.rs, tuta-sdk/rust/src/crypto/kyber.rs, tuta-sdk/rust/src/crypto/mod.rs, tuta-sdk/rust/src/crypto/rsa.rs, tuta-sdk/rust/src/util/mod.rs
Stacks on top of #7025
Closes #6954
=> Add asymmetric primitives

src/api/worker/EventBusEventCoordinator.ts, test/tests/api/worker/EventBusEventCoordinatorTest.ts
Should not try to rotate keys if we are an external user.
tutadb#1817
=> Fix external mailbox login

tuta-sdk/rust/src/entities/accounting.rs, tuta-sdk/rust/src/entities/base.rs, tuta-sdk/rust/src/entities/monitor.rs, tuta-sdk/rust/src/entities/storage.rs, tuta-sdk/rust/src/entities/sys.rs, tuta-sdk/rust/src/entities/tutanota.rs, tuta-sdk/rust/src/entities/usage.rs, tuta-sdk/rust/src/entity_client.rs, tuta-sdk/rust/src/instance_mapper.rs, tuta-sdk/rust/src/lib.rs, tuta-sdk/rust/src/mail_facade.rs, tuta-sdk/rust/src/type_models/sys.json, tuta-sdk/rust/src/typed_entity_client.rs, tuta-sdk/rust/src/user_facade.rs
=> [SDK] download and convert into well-typed entities

src/calendar/view/CalendarDayEventsView.ts, src/calendar/view/CalendarEventBubble.ts, src/calendar/view/CalendarMonthView.ts, src/calendar/view/CalendarView.ts, src/calendar/view/MultiDayCalendarView.ts
=> Fix calendar keyboard navigation bugs

app-android/app/src/main/res/mipmap-anydpi-v26/ic_logo.xml, app-android/app/src/main/res/mipmap-anydpi-v26/ic_logo_dark.xml, app-android/app/src/main/res/mipmap-anydpi-v26/ic_logo_round.xml
=> re-add support for monochrome android launcher icons

src/termination/TerminationForm.ts
=> Fix TerminationForm.ts inputs.

src/desktop/sse/SseClient.ts
=> [desktop] Fix invalid state error in SseClient

src/calendar/view/CalendarMobileHeader.ts
=> Fix previous and forward day/week/month navigation buttons for single column view

src/subscription/SwitchSubscriptionDialog.ts
These cases were removed by 0461d52074707880eb7ea493c506e87e3814bfed. So I just copied them back.
Closes #6998.
=> Fix an error occurring when downgrading with a contact list

buildSrc/winsigner.cjs
This reverts commit c95f2fc0432ea5550d5395be986eb5f99d3b9eaa.
=> Revert "[build] Fix singing Windows client"

src/calendar/view/CalendarEventBubble.ts
=> Fix truncated events titles with more than 3 lines of length

src/api/worker/offline/migrations/sys-v102.ts
Purge Group and UserGroupRoot from offline database.
tutadb#1814
=> Introduce SystemModelV102

src/api/worker/facades/KeyLoaderFacade.ts
=> Remove special handling for case that former group key list is not set

.github/workflows/kotlin-test.yml, src/calendar/view/CalendarEventBubble.ts, src/calendar/view/CalendarView.ts
=> New events created from the left sife 'New Event Button' has its starting time set to next half/full hour

buildSrc/DevBuild.js, buildSrc/buildWebapp.js, libs/webassembly/Makefile_liboqs, packages/tuta-wasm-loader/lib/WasmHandler.ts, packages/tuta-wasm-loader/lib/index.ts, test/TestBuilder.js
=> Wasm build optimization

src/api/main/MainLocator.ts, src/api/worker/EventBusEventCoordinator.ts, src/api/worker/WorkerImpl.ts, src/api/worker/WorkerLocator.ts, src/api/worker/facades/KeyLoaderFacade.ts, src/api/worker/facades/lazy/CacheManagementFacade.ts, src/api/worker/facades/lazy/GroupManagementFacade.ts, src/api/worker/rest/DefaultEntityRestCache.ts, test/tests/api/worker/EventBusEventCoordinatorTest.ts, test/tests/api/worker/facades/KeyLoaderFacadeTest.ts
=> Robust key loading

libs/purify.js, package-lock.json, package.json
=> Update DOMPurify to 3.1.6

src/calendar-app/calendar/view/CalendarMonthView.ts, src/common/gui/main-styles.ts
=> 7168 clicking the week number opens the week view

tuta-sdk/rust/src/crypto/crypto_facade.rs, tuta-sdk/rust/src/util/test_utils.rs
No more writing 40 lines to make a single Mail.
=> [sdk] Add create_test_entity

tuta-sdk/rust/src/crypto/crypto_facade.rs, tuta-sdk/rust/src/crypto/key.rs, tuta-sdk/rust/src/crypto/kyber.rs, tuta-sdk/rust/src/crypto/mod.rs, tuta-sdk/rust/src/entities/mod.rs, tuta-sdk/rust/src/entities/tutanota.rs, tuta-sdk/rust/src/entity_client.rs, tuta-sdk/rust/src/generated_id.rs, tuta-sdk/rust/src/key_cache.rs, tuta-sdk/rust/src/key_loader_facade.rs, tuta-sdk/rust/src/lib.rs, tuta-sdk/rust/src/login/credentials.rs, tuta-sdk/rust/src/login/login_facade.rs, tuta-sdk/rust/src/login/mod.rs, tuta-sdk/rust/src/mail_facade.rs, tuta-sdk/rust/src/typed_entity_client.rs, tuta-sdk/rust/src/user_facade.rs, tuta-sdk/rust/src/util/mod.rs
=> [SDK] Session resume with existing credentials

src/calendar-app/calendar/view/CalendarDayEventsView.ts
=> Set new event from mouse click on Day and Week view according to its position inside the tile

src/calendar-app/calendar/gui/CalendarGuiUtils.ts, src/calendar-app/calendar/gui/eventpopup/EventPreviewView.ts, src/calendar-app/calendar/view/CalendarAgendaItemView.ts, src/calendar-app/calendar/view/CalendarDayEventsView.ts, src/calendar-app/calendar/view/ContinuingCalendarEventBubble.ts, src/common/misc/TranslationKey.ts, src/mail-app/translations/de.ts, src/mail-app/translations/de_sie.ts, src/mail-app/translations/en.ts, src/mail-app/translations/pt_br.ts
=> 7164 add no title text for calendar events

src/calendar-app/calendarLocator.ts, src/common/native/main/WebMobileFacade.ts, src/mail-app/mailLocator.ts
=> [Calendar] close Calendar app instead of 404 with back action

buildSrc/bump-version.js
This commit fixes the android versionCode bumping
=> Fixes bump-version script

schemas/sys.json, src/common/api/entities/sys/ModelInfo.ts, src/common/api/entities/sys/TypeModels.js, src/common/api/entities/sys/TypeRefs.ts, src/common/api/worker/facades/KeyRotationFacade.ts, src/common/api/worker/offline/OfflineStorageMigrator.ts, src/common/api/worker/offline/migrations/sys-v106.ts, test/tests/api/worker/facades/KeyRotationFacadeTest.ts, tuta-sdk/rust/src/type_models/sys.json
Customer and team group key rotation tutadb#1820
Key rotation error handling tutadb#1824
=> Team and customer group key rotations and error handling

buildSrc/RollupConfig.js, src/common/login/PostLoginActions.ts, src/common/misc/TranslationKey.ts, src/common/misc/news/NewsList.ts, src/common/misc/news/items/RichNotificationsNews.ts, src/common/native/main/NativePushServiceApp.ts, src/common/native/main/wizard/SetupWizard.ts, src/common/native/main/wizard/setupwizardpages/SetupContactsPage.ts, src/common/native/main/wizard/setupwizardpages/SetupNotificationsPage.ts, src/common/settings/NotificationPermissionsDialog.ts, src/common/settings/SettingsBannerButton.ts, src/mail-app/mailLocator.ts, src/mail-app/settings/NotificationContentSelector.ts, src/mail-app/translations/de.ts, src/mail-app/translations/de_sie.ts, src/mail-app/translations/en.ts
close #7292
A bit barebones for now and also tests will fail because there's no German translation (yet)
=> Rich notifications news item

app-android/calendar/proguard-rules.pro, app-android/calendar/src/main/cpp/CMakeLists.txt, app-android/calendar/src/main/java/de/tutao/calendar/MainActivity.kt
Fixes the proguard rule that was not keeping the ipc, leading Calendar App to crash due to not finding Kyber functions.
Fixes #7339
Fixes #7341
Fixes #7342
=> Fixes proguard-rules.pro to keep calendar ipc

app-ios/fastlane/Fastfile, ci/Ios-Calendar.Jenkinsfile
Adds the Jenkins file to build the iOS app, store the artifacts at the artifact repo and push the test version to Testflight.
=> [CI] Adds Jenkins calendar iOS build script

src/calendar-app/gui/CalendarBottomNav.ts
Search points to the right direction again
=> 7327 Search in the bottom nav bar returns you to the login screen

src/common/misc/news/items/RichNotificationsNews.ts
We don't want it to show on desktop.
Fixes #7392
=> Only show rich notifications news item if on app

src/common/api/main/PageContextLoginListener.ts, src/common/api/worker/facades/LoginFacade.ts, test/tests/api/worker/search/IndexerTest.ts
Include databaseKey in CacheInfo so we don't need to get it again.
Fixes #7372
=> Fix app password being displayed three times

src/common/api/worker/facades/KeyRotationFacade.ts, test/tests/api/worker/facades/KeyRotationFacadeTest.ts
=> Only catch LockedErrors and throw anything else

src/common/login/PostLoginActions.ts
moved showSetupWizardIfNeeded from partialloginsuccess to fullloginsuccess
closes #7396
=> 7396 Onboarding wizard is shown during paid signup

app-ios/project.yml
=> Fix the plan prices not loading

tuta-sdk/rust/sdk/src/crypto/crypto_facade.rs, tuta-sdk/rust/sdk/src/element_value.rs, tuta-sdk/rust/sdk/src/instance_mapper.rs, tuta-sdk/rust/sdk/src/util/entity_test_utils.rs
(branched from master but should go into `dev-mail` after it's rebased on master, the only commit here is `[sdk] Improve deserialization errors, optimize deserialization`)
=> [sdk] Deserialization improvements

app-ios/TutanotaSharedFramework/Notifications/NotificationStorage.swift
=> [ios] Fix default notification pref

app-ios/tutanota/Sources/CustomSchemeHandlers.swift
=> [ios] Fix crash on downloading invoices

app-ios/TutanotaSharedFramework/TutanotaSharedFramework.md, doc/notifications.md
Fix typo issue at
+ doc/notifications.md
+ app-ios/TutanotaSharedFramework/TutanotaSharedFramework.md
=> Fix typo issue at

buildSrc/RustGenerator.js
please merge together with the same branch in next
=> [build] Move RustGenerator to main repo

app-android/app/src/androidTest/java/de/tutao/tutanota/EncryptionCompatTest.kt, app-android/app/src/main/java/de/tutao/tutanota/MainActivity.kt, app-android/calendar/src/main/java/de/tutao/calendar/MainActivity.kt
It doesn't exist anymore...
Fixes a crash
=> [android] Do not load libtutanota

src/common/api/worker/facades/KeyLoaderFacade.ts, src/common/api/worker/facades/KeyRotationFacade.ts
=> Fix group reinvitations when rotating keys

src/common/api/worker/facades/KeyRotationFacade.ts
When encrypting asymmetrically for recipients from another customer, we pass in a list of recipients for whom we already could not find a public key, and if that list is not empty, no encryption will take place because we just want to collect the recipients we cannot find. In the case of rotation, though, we need the encryption to take place, so we always pass in an empty list, and we handle the recipients without public keys separately with a different list.
tutadb#1839
=> Fix group members being kicked out when rotating keys

src/calendar-app/calendar/gui/CalendarGuiUtils.ts, src/calendar-app/calendar/view/CalendarDesktopToolbar.ts, src/calendar-app/calendar/view/CalendarMobileHeader.ts, src/calendar-app/calendar/view/CalendarMonthView.ts, src/calendar-app/calendar/view/CalendarView.ts, src/calendar-app/calendar/view/MultiDayCalendarView.ts, src/common/api/common/utils/CommonCalendarUtils.ts, src/common/gui/MobileHeader.ts, src/common/misc/DeviceConfig.ts, src/common/native/main/WebMobileFacade.ts
use back button to return to monthView
adds back button to agenda view if opened from month view
closes #7215 
closes #7207
=> 7215 back button

app-android/calendar/src/main/AndroidManifest.xml, app-android/calendar/src/main/java/de/tutao/calendar/MainActivity.kt, app-ios/calendar/Info.plist, app-ios/calendar/Sources/AppDelegate.swift, app-ios/calendar/Sources/Webauthn/IosWebauthnFacade.swift, src/braintree.html, src/common/subscription/InvoiceAndPaymentDataPage.ts
This commit changes the schema url used to redirect actions to the calendar app, such as during 2fa and credit card payment process.
=> PI 219 New app schema for calendar app

src/common/misc/TranslationKey.ts, src/common/settings/UserViewer.ts, src/mail-app/translations/de.ts, src/mail-app/translations/de_sie.ts, src/mail-app/translations/en.ts
=> handle error when the user has a pending user group key rotation

tuta-sdk/rust/sdk/src/crypto/crypto_facade.rs
It is unnecessary to do as it's only needed for updating owner enc session key and it does not work with key rotation as we don't implement range requests yet.
=> [sdk] Do not load instance owner owner sym key

src/common/misc/LazySearchBar.ts
import the right SearchBar based on app type
=> import the right SearchBar based on app type

src/common/api/common/TutanotaConstants.ts, src/common/api/worker/facades/KeyRotationFacade.ts, test/tests/api/worker/facades/KeyRotationFacadeTest.ts
=> Add support for multi-user, single-admin key rotations

app-android/calendar/src/main/java/de/tutao/calendar/webauthn/AndroidWebauthnFacade.kt
Updates calendar Webauthn callback intent url when registering a new U2F key.
=> [Calendar] Updates Webauthn callback url

app-android/app/src/main/AndroidManifest.xml, app-android/app/src/main/java/de/tutao/tutanota/AndroidMobileContactsFacade.kt, app-android/app/src/main/java/de/tutao/tutanota/StubSyncService.kt, app-android/app/src/main/res/xml/syncadapter.xml, src/common/subscription/FeatureListProvider.ts
We cannot offer this as a feature to iOS users due to limitations with iOS subscriptions.
Closes #7195
=> [ios] Prevent family option from being shown under features

src/common/api/worker/EventBusClient.ts, test/tests/api/worker/EventBusClientTest.ts
We might receive entityEventUpdates for types that are unknown to the client and therefore want to exclude these types from being processed. Therefore, we now remove unknown types that are not in tutanotaTypes from the eventBatch.
=> filter for unknown types in EventBusClient

app-ios/calendar-project.yml, app-ios/calendar/calendar.entitlements, app-ios/calendar/calendarDebug Development.entitlements, app-ios/calendar/calendarDebug Staging.entitlements, app-ios/calendar/calendarRelease Development.entitlements, app-ios/calendar/calendarRelease Staging.entitlements, app-ios/fastlane/Fastfile, ci/Ios-Calendar.Jenkinsfile, ci/IosRenewCalendarCerts.Jenkinsfile, ci/Publish-CalendarMobileArtifacts.Jenkinsfile
Fixes calendar spec;
Adds a new lane in Fastfile to only publish calendar app after unstash;
Creates new lanes for renewing only calendar certs;
Moves Calendar related lanes closer;
Fixes publish artifacts jenkins job.
=> [Calendar] [CI] [iOS] Fix calendar CI

src/common/api/common/EntityFunctions.ts, src/common/api/worker/offline/OfflineStorage.ts, src/common/api/worker/offline/StandardMigrations.ts, src/common/api/worker/offline/migrations/sys-v96.ts, src/common/api/worker/offline/migrations/tutanota-v69.ts, src/common/api/worker/offline/migrations/tutanota-v75.ts, test/tests/api/worker/offline/OfflineStorageMigrationsTest.ts
=> Offline type ref

src/calendar-app/calendar/search/CalendarSearchBar.ts, src/calendar-app/calendar/search/view/CalendarSearchView.ts
=> Calendar search bar ui changes

src/calendar-app/calendar/search/view/CalendarSearchView.ts, src/common/gui/nav/ViewSlider.ts
=> make drawer menu optional and disable it in the CalendarSearchView

src/calendar-app/calendar/model/CalendarModel.ts, src/calendar-app/calendar/settings/NotificationSettingsViewer.ts, src/calendar-app/calendarLocator.ts, src/common/native/main/NativePushServiceApp.ts, src/mail-app/mailLocator.ts, src/mail-app/settings/NotificationSettingsViewer.ts, test/tests/calendar/CalendarModelTest.ts
Adds checks to prevent alarm scheduling when a push identifier is disabled.
=> Completely deactivate push identifiers when disabled

src/calendar-app/calendar/settings/CalendarSettingsView.ts, src/calendar-app/calendar/view/CalendarMobileHeader.ts, src/common/gui/BackgroundColumnLayout.ts, src/common/gui/BaseMobileHeader.ts, src/common/gui/main-styles.ts
Adapts the new settings to work with two and three column layouts. Also fixes an old and small bug on calendar view where the menu icon was shown even on three columns layout.
=> Adapts the new settings page to bigger layouts

src/mail-app/search/SearchBar.ts
Check if is app before automatically focus on the SearchBar.ts
=> Fixes search bar autofocus

src/calendar-app/calendar/settings/CalendarSettingsView.ts
Removes the header from tablet view and fixes the titles on inner settings pages.
=> Fixes the settings page

src/calendar-app/calendar/settings/NotificationSettingsViewer.ts
This commit fixes calendar alarm scheduling when re-enabling the push identifier by calling reRegister right after re-enabling the identifier.
=> Fixes alarm re-schedule

android.js, app-android/calendar/build.gradle.kts, ci/Android-Calendar.Jenkinsfile, ci/Publish-CalendarMobileArtifacts.Jenkinsfile
Replaces the apk build process by a bundle build process since PlayStore doesn't accept APKs anymore for new apps.
=> Fixes android build to use bundle instead of apk

libs/winreg.mjs, package-lock.json, package.json
Downgrades winreg to 1.2.4 from 1.2.5 as new version doesn't work with whitespaces in values
Fixes #7609
=> [desktop] Fix run on startup on windows

android.js, app-android/calendar/build.gradle.kts, ci/Android-Calendar.Jenkinsfile, ci/Publish-CalendarMobileArtifacts.Jenkinsfile
generate apk through jenkins job
=> Pi222 calendar apk

src/common/api/worker/EventQueue.ts, test/tests/api/worker/search/EventQueueTest.ts
=> fix event processing same id different type

src/common/desktop/net/ProtocolProxy.ts
This reverts commit fbeea00bd4d3144eb275d92dffb7ec32ec24efb8.
=> Revert "[desktop] allow http2 in undici config"

android.js
=> removed aab file from apk bundle

src/common/mailFunctionality/MailboxModel.ts, src/mail-app/mail/model/InboxRuleHandler.ts, src/mail-app/mail/model/MailModel.ts, src/mail-app/mail/model/MailUtils.ts, src/mail-app/mail/view/ConversationViewModel.ts, src/mail-app/mail/view/EditFolderDialog.ts, src/mail-app/mail/view/MailFoldersView.ts, src/mail-app/mail/view/MailGuiUtils.ts, src/mail-app/mail/view/MailListView.ts, src/mail-app/mail/view/MailView.ts, src/mail-app/mail/view/MailViewModel.ts, src/mail-app/mail/view/MailViewerViewModel.ts, src/mail-app/mailLocator.ts, src/mail-app/native/main/OpenMailboxHandler.ts, src/mail-app/search/view/SearchView.ts, src/mail-app/search/view/SearchViewModel.ts, src/mail-app/settings/AddInboxRuleDialog.ts, src/mail-app/settings/MailSettingsViewer.ts, test/tests/calendar/CalendarInvitesTest.ts, test/tests/calendar/CalendarTestUtils.ts, test/tests/calendar/eventeditor/CalendarEventModelTest.ts, test/tests/mail/SendMailModelTest.ts
=> Fix folders not being updated

src/mail-app/contacts/view/ContactView.ts, src/mail-app/contacts/view/ImportAsVCard.ts
=> import vcard for mobile app

src/common/login/LoginView.ts, src/common/login/LoginViewModel.ts, src/common/misc/TranslationKey.ts, src/mail-app/translations/de.ts, src/mail-app/translations/de_sie.ts, src/mail-app/translations/en.ts, test/tests/login/LoginViewModelTest.ts
=> Deleting credential offline

src/common/settings/login/RecoverCodeDialog.ts
=> 5944 recovery code with space

src/calendar-app/calendar/search/view/CalendarSearchView.ts, src/common/gui/main-styles.ts, src/mail-app/search/view/SearchView.ts
=> Align the filter fields in the search view

app-android/app/src/androidTest/java/de/tutao/tutanota/MigrationTest.kt, app-android/app/src/main/AndroidManifest.xml, app-android/app/src/main/java/de/tutao/tutanota/MainActivity.kt, app-android/app/src/main/java/de/tutao/tutanota/push/Credentials.kt, app-android/app/src/main/java/de/tutao/tutanota/push/LocalNotificationsFacade.kt, app-android/app/src/main/java/de/tutao/tutanota/push/MailNotificationActionReceiver.kt, app-android/app/src/main/java/de/tutao/tutanota/push/TutanotaNotificationsHandler.kt, app-android/calendar/src/androidTest/java/de/tutao/calendar/EncryptionCompatTest.kt, app-android/calendar/src/androidTest/java/de/tutao/calendar/MigrationTest.kt, app-ios/TutanotaNotificationExtension/NotificationService.swift, app-ios/TutanotaSharedFramework/Notifications/NotificationActions.swift, app-ios/TutanotaSharedFramework/Notifications/SdkRestClient.swift, app-ios/tutanota/Sources/AppDelegate.swift, src/common/api/worker/offline/OfflineStorageMigrator.ts, src/common/api/worker/offline/migrations/sys-v112.ts, src/common/api/worker/offline/migrations/tutanota-v76.ts, tuta-sdk/rust/sdk/src/entity_client.rs, tuta-sdk/rust/sdk/src/json_serializer.rs, tuta-sdk/rust/sdk/src/services/service_executor.rs
=> Add actions on notifications

src/common/api/common/TutanotaConstants.ts, src/common/api/worker/EventBusClient.ts, src/common/api/worker/facades/LoginFacade.ts, src/common/api/worker/facades/lazy/GroupManagementFacade.ts, src/mail-app/workerUtils/worker/WorkerLocator.ts, test/tests/api/worker/facades/GroupManagementFacadeTest.ts, test/tests/api/worker/facades/LoginFacadeTest.ts
Finally migrate all users to Argon2.
Fix race condition that is triggered upon multi-user account key rotation.
=> Argon2 migration and race condition fix

src/calendar-app/calendar/search/view/CalendarSearchViewModel.ts, src/mail-app/search/view/SearchViewModel.ts
=> Add time validator to the calendar search, all warnings show

src/calendar-app/calendar/gui/pickers/DatePicker.ts
=> Check if date is a new date before overwriting inputText in DatePicker

src/calendar-app/calendar/gui/eventpopup/ContactPreviewView.ts, src/common/calendar/date/CalendarEventsRepository.ts
=> Fix null error while sorting birthdays on load

src/calendar-app/calendar/gui/pickers/DatePicker.ts
=> Update previous date when datepicker date is updated

src/common/api/common/TutanotaConstants.ts, src/common/misc/AppStorePaymentPicker.ts, src/common/subscription/PaymentViewer.ts, src/common/subscription/SubscriptionViewer.ts, src/common/subscription/UpgradeConfirmSubscriptionPage.ts, src/common/subscription/UpgradeSubscriptionWizard.ts
=> Remove usage test check for AppStore Payment

src/common/gui/base/Card.ts, src/common/gui/main-styles.ts
=> Created generic card component

buildSrc/RustGenerator.js, tuta-sdk/rust/sdk/src/util/test_utils.rs
=> fix CompressedString in RustGenerator.js

buildSrc/LaunchHtml.js
=> Update the SEO tags of the client

src/mail-app/settings/emaildomain/DnsRecordTable.ts
=> Dns record custom domain setup show full value

src/mail-app/search/SearchBar.ts
=> Hide Keyboard after clicking return button in mobile

src/common/misc/KeyManager.ts
=> Fix keyboard navigation inside dialogs stuck at disabled elements

src/common/gui/AriaUtils.ts, src/common/gui/base/Switch.ts, src/common/gui/main-styles.ts
=> Toggle button

src/mail-app/mail/view/MailRow.ts
=> Add more vertical padding to list view labels

src/mail-app/mail/model/MailUtils.ts, src/mail-app/mail/view/MailViewerToolbar.ts, src/mail-app/mail/view/MobileMailMultiselectionActionBar.ts
=> Add check to see mails are in the same mailbox when showing label action

tuta-sdk/rust/Cargo.lock, tuta-sdk/rust/sdk/Cargo.toml
https://github.com/rustpq/pqcrypto/issues/68
=> [sdk] Fix compiling for iOS by pinning pqcrypto-internals

src/calendar-app/calendarLocator.ts, src/common/misc/RecipientsSearchModel.ts, src/common/native/main/MobileContactSuggestionProvider.ts, src/mail-app/mailLocator.ts
Solved by only asking for permission once.
close: #6805
=> Prevent asking for Contact Permission repeatedly

app-android/app/src/main/java/de/tutao/tutanota/AndroidThemeFacade.kt
=> Match status Bar color with app theme in android

app-android/app/build.gradle, app-android/app/src/debugDist/res/values/strings.xml, app-android/app/src/main/AndroidManifest.xml, app-android/app/src/main/java/de/tutao/tutanota/AndroidMobileContactsFacade.kt, app-android/app/src/main/res/values/strings.xml, app-android/app/src/main/res/xml/account_authenticator.xml, app-android/app/src/main/res/xml/authenticator.xml, app-android/app/src/main/res/xml/contacts.xml, app-android/app/src/main/res/xml/syncadapter.xml, app-android/tutashared/src/main/java/de/tutao/tutashared/credentials/AccountAuthenticatorService.kt, app-android/tutashared/src/main/java/de/tutao/tutashared/credentials/AccountManagerAuthenticator.kt
=> Make Contacts app recognize tuta account

app-ios/tutanota/Sources/Files/FileChooser.swift
Crash caused by an uncaught exception due to popover requiring position information on iPad only but not on iPhone.
Close #7914
=> Fix app crashing when adding attachments on iPad

src/mail-app/contacts/view/ImportAsVCard.ts
=> Show Native File Picker as a file only picker for vcf import

src/common/gui/base/buttons/RowButton.ts
=> Prevent screen reader from reading dropdown options twice

src/calendar-app/calendar/gui/eventeditor-view/CalendarEventEditView.ts, src/calendar-app/calendar/gui/eventeditor-view/EventTimeEditor.ts, src/calendar-app/calendar/gui/pickers/DatePicker.ts, src/calendar-app/calendar/gui/pickers/TimePicker.ts, src/common/gui/base/InputButton.ts, src/common/gui/base/Select.ts, src/common/gui/base/SingleLineTextField.ts, src/common/gui/base/TextField.ts, src/common/gui/base/buttons/OutlineButton.ts, src/common/gui/main-styles.ts, src/common/misc/TranslationKey.ts, src/mail-app/translations/de.ts, src/mail-app/translations/de_sie.ts, src/mail-app/translations/en.ts
Modifies the existing Time Picker to use the new components. 
Also adapts the DatePicker to support both variants (old and new).
Both components where adapted to be accessible on mobile devices and desktop when using keyboard navigation.
=> Adds time section to new event editor

src/common/api/worker/facades/lazy/CalendarFacade.ts
Fixes short events that are cut off in the next month due to the random shift by generating them until their end date instead of the load range.
=> Fix Events being cut in the next month

src/common/api/worker/crypto/AsymmetricCryptoFacade.ts, src/common/api/worker/crypto/CryptoFacade.ts, src/common/api/worker/facades/KeyRotationFacade.ts, test/tests/api/worker/crypto/AsymmetricCryptoFacadeTest.ts, tuta-sdk/rust/sdk/src/blobs/blob_access_token_facade.rs, tuta-sdk/rust/sdk/src/crypto.rs, tuta-sdk/rust/sdk/src/crypto/asymmetric_crypto_facade.rs, tuta-sdk/rust/sdk/src/crypto/crypto_facade.rs, tuta-sdk/rust/sdk/src/crypto/key.rs, tuta-sdk/rust/sdk/src/crypto/rsa.rs, tuta-sdk/rust/sdk/src/crypto/tuta_crypt.rs, tuta-sdk/rust/sdk/src/custom_id.rs, tuta-sdk/rust/sdk/src/entity_client.rs, tuta-sdk/rust/sdk/src/instance_mapper.rs, tuta-sdk/rust/sdk/src/key_cache.rs, tuta-sdk/rust/sdk/src/key_loader_facade.rs, tuta-sdk/rust/sdk/src/lib.rs, tuta-sdk/rust/sdk/src/mail_facade.rs, tuta-sdk/rust/sdk/src/services/test_services.rs, tuta-sdk/rust/sdk/src/tutanota_constants.rs, tuta-sdk/rust/sdk/src/typed_entity_client.rs, tuta-sdk/rust/sdk/src/user_facade.rs, tuta-sdk/rust/sdk/src/util/test_utils.rs
=> 1876 asymmetric crypto rust

src/common/misc/TranslationKey.ts, src/mail-app/mail/view/MailView.ts, src/mail-app/translations/de.ts, src/mail-app/translations/de_sie.ts, src/mail-app/translations/en.ts
=> Add confirmation dialog before deleting label

app-android/app/src/main/java/de/tutao/tutanota/push/SseClient.kt, app-android/app/src/main/java/de/tutao/tutanota/push/TutanotaNotificationsHandler.kt, app-android/app/src/main/java/de/tutao/tutanota/push/api.kt, app-android/calendar/src/main/java/de/tutao/calendar/push/SseClient.kt, app-android/calendar/src/main/java/de/tutao/calendar/push/TutanotaNotificationsHandler.kt, app-android/calendar/src/main/java/de/tutao/calendar/push/api.kt, app-android/tutashared/build.gradle.kts, app-android/tutashared/src/main/java/de/tutao/tutashared/NetworkUtils.kt, src/common/native/main/NativePushServiceApp.ts
=> [android] Fix invalid version number in notifications

desktop.js, packages/tutanota-crypto/lib/internal/crypto-jsbn-2012-08-09_1.js, packages/tutanota-crypto/lib/internal/sjcl.js, src/common/api/common/utils/FileUtils.ts, src/common/calendar/date/Time.ts, src/common/subscription/giftcards/GiftCardMessageEditorField.ts, webapp.js
See:
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substring#differences_between_substring_and_slice
=> Replace deprecated `substr()`

src/common/gui/base/Color.ts, src/common/subscription/Captcha.ts
In dark theme captcha is showing in white background with some white
space, resolved by using css filters
close: #7981
=> Captcha in dark view

src/mail-app/mail/view/LabelsPopup.ts, src/mail-app/mail/view/MailViewerHeader.ts, src/mail-app/mail/view/MailViewerToolbar.ts
=> Restrict labels name to one line in dropdown

src/mail-app/contacts/view/ContactView.ts
=> Show More option on mobile sidebar in contacts

src/common/gui/AriaUtils.ts, src/mail-app/mail/view/LabelsPopup.ts
=> Fix label checkboxes not being recognized by screen readers

src/common/api/worker/offline/OfflineStorageMigrator.ts, src/common/api/worker/offline/migrations/offline2.ts, src/common/api/worker/offline/migrations/tutanota-v77.ts
Co-authored-by: bir <bir@tutao.de>
Close #8022
=> Fix TutanotaProperties migration in tutanota-v77

src/mail-app/mail/model/MailModel.ts
=> Group mails by listId before applying labels

src/common/api/main/LoginController.ts, src/common/api/main/UserController.ts, src/mail-app/app.ts
Reload Customer and on full login to always have up-to-date customizations
Close #8029
=> Fix outdated customer customizations

src/common/api/common/EntityClient.ts, src/mail-app/app.ts
=> Double check TutanotaProperties before adding default label

doc/HACKING.md
On the HACKING.md file, several links to source code files are broken. This commit fixes those links.
=> [docs] Update broken links to files

src/mail-app/mail/view/MailView.ts
Keyboard shortcut for Labels added in key "L"
=> 8007 keyboard shortcut for labels

src/common/gui/base/Dropdown.ts, src/common/gui/main-styles.ts, src/mail-app/mail/view/LabelsPopup.ts
=> Close dropdown without selecting an option with keyboard

packages/tutanota-crypto/lib/misc/Constants.ts, src/common/api/entities/sys/Services.ts, src/common/api/entities/sys/TypeModels.js, src/common/api/entities/sys/TypeRefs.ts, src/common/api/worker/facades/KeyRotationFacade.ts, test/tests/api/worker/facades/KeyRotationFacadeTest.ts, tuta-sdk/rust/sdk/src/entities/generated/sys.rs, tuta-sdk/rust/sdk/src/services/generated/sys.rs, tuta-sdk/rust/sdk/src/type_models/sys.json
=> Handle multiple admin group key rotation

tuta-sdk/rust/sdk/src/blobs/blob_facade.rs
blob/file data chunking did handle empty data properly. This commit introduces a wrapper around the .chunks method which returns a single empty chunk in the empty data case.
=> allow empty blob data in blob_facade.rs

src/common/api/common/EntityClient.ts, src/common/api/entities/sys/ModelInfo.ts, src/common/api/entities/sys/Services.ts, src/common/api/entities/sys/TypeModels.js, src/common/api/entities/sys/TypeRefs.ts, src/common/api/worker/facades/LoginFacade.ts, src/common/api/worker/rest/DefaultEntityRestCache.ts, src/common/api/worker/rest/EntityRestClient.ts, src/common/misc/passwords/PasswordRequestDialog.ts, src/common/settings/UserViewer.ts, src/common/settings/login/LoginSettingsViewer.ts, src/common/settings/login/secondfactor/SecondFactorEditDialog.ts, src/common/settings/login/secondfactor/SecondFactorEditModel.ts, src/common/settings/login/secondfactor/SecondFactorsEditForm.ts, test/tests/settings/login/secondfactor/SecondFactorEditModelTest.ts, tuta-sdk/rust/sdk/src/entities/generated/sys.rs, tuta-sdk/rust/sdk/src/services/generated/sys.rs, tuta-sdk/rust/sdk/src/type_models/sys.json
Add SystemModel 115
Close #5986
=> Password check before adding or deleting SecondFactorAuthentication

src/mail-app/mail/view/MailViewModel.ts
Add a marker so that we can abort view changes early if state changes, such as if a different mail/folder view was requested while the current one was loading.
This can happen if you change folders during entity updates. You can end up having both changes fight over which view, and this can result in repeated view switching, as a previous call will end up overriding a later call.
There are a few ways to improve this. Mailbox model, for example, could just be fully loaded, and then much of it wouldn't have to be async...
Closes #8031
=> Fix concurrency issues with MailViewModel

src/mail-app/settings/MailSettingsViewer.ts
=> Only show Mail Export Settings UI on desktop

src/common/gui/base/Modal.ts
=> Fix focus not returned to callingElement on modal close

src/RootView.ts
=> Fix overlay should be inert when modal is open

app-android/app/src/main/AndroidManifest.xml, app-android/app/src/main/java/de/tutao/tutanota/MainActivity.kt, app-android/app/src/main/java/de/tutao/tutanota/push/BootBroadcastReceiver.kt, app-android/app/src/main/java/de/tutao/tutanota/push/PushNotificationService.kt, app-android/calendar/src/main/AndroidManifest.xml, app-android/calendar/src/main/java/de/tutao/calendar/MainActivity.kt, app-android/calendar/src/main/java/de/tutao/calendar/push/BootBroadcastReceiver.kt, app-android/calendar/src/main/java/de/tutao/calendar/push/PushNotificationService.kt
Foreground notification was not used in most cases and doesn't seem to make a difference when battery optimizations are disabled, but it complicates publishing to Google Play.
Close #8206
=> [android] Remove foreground notification

src/common/subscription/giftcards/RedeemGiftCardWizard.ts
=> Fix tuta.com domain not allowed for gift card signups

.github/workflows/test.yml
We compile mimimi now which takes longer.
=> [ci] Run browser tests without sandbox

ipc-schema/facades/NativeMailImportFacade.json, packages/node-mimimi/src/importer_api.rs, packages/node-mimimi/src/logging/console.rs, packages/node-mimimi/src/logging/logger.rs, src/common/desktop/DesktopMain.ts, src/common/desktop/DesktopWindowManager.ts, src/common/desktop/ipc/RemoteBridge.ts, src/common/desktop/mailimport/DesktopMailImportFacade.ts, src/common/native/common/generatedipc/DesktopGlobalDispatcher.ts, src/common/native/common/generatedipc/NativeMailImportFacade.ts, src/common/native/common/generatedipc/NativeMailImportFacadeReceiveDispatcher.ts, src/common/native/common/generatedipc/NativeMailImportFacadeSendDispatcher.ts, src/mail-app/mail/import/MailImporter.ts
* improve user experience when import is disabled server-side
* make the desktop main process quit when requested
=> Desktop import fixes

packages/tutanota-crypto/lib/misc/Constants.ts, schemas/sys.json, src/calendar-app/workerUtils/worker/CalendarWorkerLocator.ts, src/common/api/entities/sys/TypeModels.js, src/common/api/entities/sys/TypeRefs.ts, src/common/api/worker/facades/KeyAuthenticationFacade.ts, src/common/api/worker/facades/KeyLoaderFacade.ts, src/common/api/worker/facades/KeyRotationFacade.ts, src/common/api/worker/facades/lazy/GroupManagementFacade.ts, src/mail-app/workerUtils/worker/WorkerLocator.ts, test/tests/api/worker/facades/GroupManagementFacadeTest.ts, test/tests/api/worker/facades/KeyRotationFacadeTest.ts, tuta-sdk/rust/sdk/src/crypto/asymmetric_crypto_facade.rs, tuta-sdk/rust/sdk/src/entities/generated/sys.rs, tuta-sdk/rust/sdk/src/type_models/sys.json, tuta-sdk/rust/sdk/src/util/test_utils.rs
=> Authenticate new user group key as admin

src/common/gui/base/colorPicker/ColorPickerView.ts
=> Fix Hue Slider goes out of bounds on mobile

src/common/gui/base/TextField.ts
=> Close folder edit dialog by pressing Esc

src/common/api/worker/facades/KeyAuthenticationFacade.ts, src/common/api/worker/facades/KeyCache.ts, src/common/api/worker/facades/KeyRotationFacade.ts, src/common/api/worker/facades/LoginFacade.ts, src/common/api/worker/facades/UserFacade.ts, src/common/api/worker/facades/lazy/GroupManagementFacade.ts, test/tests/api/worker/facades/GroupManagementFacadeTest.ts, test/tests/api/worker/facades/KeyRotationFacadeTest.ts, test/tests/api/worker/facades/UserFacadeTest.ts
Co-authored-by: bedhub
tutadb#1925
=> Update keynames according to new convention

ci/containers/README.md, ci/containers/fdroid-build.dockerfile, ci/containers/fdroid-build.sh
=> Add Dockerfile for local F-Droid builds

packages/node-mimimi/src/importer.rs, schemas/tutanota.json, src/common/api/entities/tutanota/Services.ts, src/common/api/entities/tutanota/TypeModels.js, src/common/api/entities/tutanota/TypeRefs.ts, tuta-sdk/rust/sdk/src/entities/generated/tutanota.rs, tuta-sdk/rust/sdk/src/services/generated/tutanota.rs, tuta-sdk/rust/sdk/src/type_models/tutanota.json
The TutanotaModelV80 includes now both, the change for the (Advanced)CalendarRepeatRule, 
and the changes for the email import (ImportMailState).
=> re-generate types for TutanotaModelV80

src/mail-app/mail/view/LabelsPopup.ts
=> Fix LabelsPopup "Apply" button label does not use translation

packages/node-mimimi/Cargo.lock, schemas/sys.json, src/common/api/entities/sys/TypeModels.js, src/common/api/entities/sys/TypeRefs.ts, src/common/api/worker/facades/KeyAuthenticationFacade.ts, src/common/api/worker/facades/KeyRotationFacade.ts, src/common/api/worker/facades/lazy/GroupManagementFacade.ts, test/tests/api/worker/facades/GroupManagementFacadeTest.ts, test/tests/api/worker/facades/KeyRotationFacadeTest.ts, tuta-sdk/rust/sdk/src/crypto/asymmetric_crypto_facade.rs, tuta-sdk/rust/sdk/src/entities/generated/sys.rs, tuta-sdk/rust/sdk/src/type_models/sys.json, tuta-sdk/rust/sdk/src/util/test_utils.rs
=> Use HMAC to authenticate rotated keys

src/common/gui/RenderLoginInfoLinks.ts, src/common/misc/ErrorReporter.ts, src/common/misc/TranslationKey.ts, src/common/misc/passwords/PasswordGeneratorDialog.ts, src/common/settings/AboutDialog.ts, src/mail-app/translations/de.ts, src/mail-app/translations/de_sie.ts, src/mail-app/translations/en.ts
=> 8295 translation missing

src/common/misc/KeyManager.ts, src/common/settings/PasswordForm.ts, src/common/subscription/SignupForm.ts
=> voiceover in "Terms and Agreement"

src/common/gui/base/Checkbox.ts, src/common/gui/base/InfoIcon.ts, src/common/gui/base/TextField.ts, src/common/misc/KeyManager.ts, src/common/misc/TranslationKey.ts, src/common/settings/login/RecoverCodeDialog.ts, src/common/subscription/BuyOptionBox.ts, src/common/subscription/UpgradeCongratulationsPage.ts, src/mail-app/translations/de.ts, src/mail-app/translations/de_sie.ts, src/mail-app/translations/en.ts
close #3623 
Co-authored by: ivk <ivk@tutao.de>
=> Screenreader reading information multiple times in signup

app-android/tutashared/src/main/java/de/tutao/tutashared/offline/AndroidSqlCipherFacade.kt
Co-authored-by: bir <bir@tutao.de>
Close #8049
=> Add busy timeout for sqlite db on android

buildSrc/LaunchHtml.js
=> Include Desktop in title tag check

ci/Release.Jenkinsfile
Remove generateReleaseNotes checkbox and generate notes automatically when publishing to production.
Close #8279
=> [ci] Auto generate release notes when publishing to prod

src/common/login/CredentialRemovalHandler.ts
This commit adds minimal handling for the case when the device key is corrupted in some way, and we try to remove the local SSE data.
This does not address the issue that the local data will still be unusable, this needs to be addressed in a more general way separately.
Close #8280
=> Handle keychain errors when removing credentials

src/calendar-app/calendar/view/CalendarMonthView.ts
=> Fix arrow at the end of an allday event that spans to the next week

packages/node-mimimi/src/importer/file_reader.rs, packages/node-mimimi/src/importer/messages.rs, packages/node-mimimi/src/importer_api.rs, src/common/desktop/mailimport/DesktopMailImportFacade.ts, src/mail-app/mail/import/MailImporter.ts
- remove unused errors
- pause progress estimation on other windows of the same mailbox
=> small import improvements

package-lock.json, package.json
=> Update Electron to 34.0.1

src/common/gui/RenderLoginInfoLinks.ts, src/common/misc/ErrorReporter.ts, src/common/misc/passwords/PasswordGeneratorDialog.ts, src/common/settings/AboutDialog.ts
=> Add missing translation in client

app-android/tutashared/src/main/java/de/tutao/tutashared/offline/AndroidSqlCipherFacade.kt
Fixed by changing busy_timeout from 100 to 1000
close: #8382
=> Fix "SQLiteException issue in Android"

src/common/api/worker/facades/lazy/BlobFacade.ts, test/tests/api/worker/facades/BlobFacadeTest.ts
=> Handle empty blobs response

src/calendar-app/workerUtils/worker/CalendarWorkerLocator.ts, src/common/api/worker/facades/lazy/BlobFacade.ts, src/mail-app/workerUtils/worker/WorkerLocator.ts, test/tests/api/worker/facades/BlobFacadeTest.ts
=> 8401 export broken attachments

src/mail-app/settings/MailExportViewer.ts
=> Fix Web Mail Export Viewer appears on first render on desktop

libs/purify.js, package-lock.json, package.json
- Start writing a mail. 
- Before sending it replace the content using devtools with `<div><img src="nonono.png" onerror="console.log('XSS')" /></div>`
- Clear the console
- Open the received mail
- Show external images
- See that no CSP violations have been logged
=> Dompurify 3.2.4

src/mail-app/mail/model/MailListModel.ts
=> Fix MailListModel.getLabelsForMail throws assertNotNull error

src/common/api/entities/sys/TypeModels.js, src/common/api/entities/sys/TypeRefs.ts, src/common/api/worker/facades/KeyAuthenticationFacade.ts, src/common/api/worker/facades/KeyRotationFacade.ts, src/mail-app/workerUtils/index/BulkMailLoader.ts, test/tests/api/worker/facades/KeyRotationFacadeTest.ts, tuta-sdk/rust/sdk/src/entities/generated/sys.rs, tuta-sdk/rust/sdk/src/type_models/sys.json
=> change pubKeyMac to type KEY_MAC

tuta-sdk/android/sdk/build.gradle.kts
This commit updates SDK gradle file adding the correct target folder for the SDK according to the new workspace changes.
=> Fixes Android SDK

app-android/tutashared/src/main/java/de/tutao/tutashared/offline/AndroidSqlCipherFacade.kt
=> 8536 android sql databaselock

ci/Ios-Calendar.Jenkinsfile
=> Remove calendar iOS test stage

ci/Android-Calendar.Jenkinsfile, ci/Android.Jenkinsfile
Changed SqlCipher version from 4.5.0 to 4.6.0 in jenkin jobs
=> [Android] SqlCipher jenkin job change for Release

src/common/api/worker/facades/KeyRotationFacade.ts
=> Do not send group key updates to deactivated members

src/common/gui/main-styles.ts
=> Fix cropped mobile bottom action bar on iOS

src/mail-app/mail/model/MailModel.ts, src/mail-app/mail/view/ExternalLoginView.ts, src/mail-app/mail/view/MailView.ts, src/mail-app/mail/view/MailViewerHeader.ts, src/mail-app/mail/view/MailViewerViewModel.ts, src/mail-app/search/view/SearchView.ts
=> Fix inconsistencies for external users

src/mail-app/mail/model/MailModel.ts, src/mail-app/mail/view/ConversationViewModel.ts, src/mail-app/mail/view/ExternalLoginView.ts, src/mail-app/mail/view/MailView.ts, src/mail-app/mail/view/MailViewModel.ts, src/mail-app/mail/view/MailViewerHeader.ts, src/mail-app/mail/view/MailViewerViewModel.ts, src/mail-app/search/view/SearchView.ts, test/tests/mail/view/ConversationViewModelTest.ts
=> Disable conversation view for external users

src/common/api/common/CommonMailUtils.ts, src/mail-app/mail/view/MailGuiUtils.ts, src/mail-app/mail/view/MailListView.ts, src/mail-app/mail/view/MailViewer.ts
=> Fix swipe left does not permanently delete when in spam folder

src/mail-app/mail/view/MobileMailMultiselectionActionBar.ts
=> Fix multiselect label dropdown not taking full width

src/mail-app/mail/view/MailView.ts
=> Fix show partially selected labels in conversation

src/mail-app/mail/view/MobileMailActionBar.ts
=> Fix reply all icon used for reply action in MobileMailActionBar

app-ios/TutanotaSharedFramework/Sql/sqlite3.h
Updated iOS sqlcipher to version 3.46.1
close #8555
=> 8555 update ios sqlcipher

src/calendar-app/calendar/gui/pickers/DatePicker.ts
=> Fix Search Indexing started before confirming date in iOS

src/common/misc/ListModel.ts, test/tests/misc/ListModelTest.ts
The source of the problem is inconsistent state of selected items in ListModel. ListModel has an issue with keeping track of selection with ListAutoSelectBehavior.NEWER. When there isn't a newer item it will fall back to selecting the first item from the list which might be the item that we are removing, which means that there will be an item in the selected list that is not in the overall items list (or more specifically not in the filtered items list) which is a violation of the contract. Because of that mismatch we would still try to populate the selected items with conversation data even though we don't have it anymore.
We fixed the issue by fixing the issue in ListModel itself. First we remove the item from the list and only then we try to find candidate for selection.
This also …
=> Fix unwrapped null in getLatestMailForConversation()

app-android/app/src/main/java/de/tutao/tutanota/push/LocalNotificationsFacade.kt
Opening an email from a notification list always opens the mail for the most recent notification instead of the selected one. This happens because we were using the `abs(1 + address.hashCode())` as the request code for the open mail PendingIntent, which will result in having the same request code for all email notifications per address
Fixed by generating a unique request code for every intentOpenMail.
Close #8333
=> [Android] Fix opening email notification opens latest mail for alias

src/calendar-app/calendar/gui/eventpopup/CalendarEventPreviewViewModel.ts, src/calendar-app/calendar/gui/eventpopup/EventPreviewView.ts
=> Remove a thrown error when there is no calendar and instead return null

app-android/calendar/src/main/java/de/tutao/calendar/widget/Agenda.kt, app-android/calendar/src/main/java/de/tutao/calendar/widget/WidgetReceiver.kt, app-android/calendar/src/main/java/de/tutao/calendar/widget/data/WidgetRepository.kt, app-android/calendar/src/main/java/de/tutao/calendar/widget/data/WidgetStateDefinition.kt, app-android/calendar/src/main/java/de/tutao/calendar/widget/model/WidgetUIViewModel.kt, tuta-sdk/rust/sdk/src/date/calendar_facade.rs
=> Fixes Widget removal purgin DataStore

src/mail-app/contacts/view/ContactView.ts, src/mail-app/mail/view/MailView.ts, src/mail-app/search/view/SearchView.ts
=> 8844 delete dialog when nothing selected

src/calendar-app/calendar/model/CalendarModel.ts, src/common/api/common/EntityClient.ts, src/common/api/common/utils/EntityUtils.ts, src/common/api/worker/facades/lazy/CalendarFacade.ts, src/common/api/worker/rest/AdminClientDummyEntityRestCache.ts, src/common/api/worker/rest/DefaultEntityRestCache.ts, src/common/api/worker/rest/EntityRestClient.ts, test/tests/api/worker/rest/EntityRestCacheTest.ts, test/tests/api/worker/rest/EntityRestClientMock.ts, test/tests/api/worker/rest/EntityRestClientTest.ts
Adds the function to batch delete calendar events and also changes the logic for external calendars, adding a retry mechanism and mass event deletion to increase processing speeds.
=> Adds batch delete to calendar events

src/mail-app/mail/model/MailUtils.ts, src/mail-app/search/view/SearchViewModel.ts, test/tests/api/common/mail/CommonMailUtilsTest.ts
Have SQLite search sort by date, then ID if dates are the same.
Close #8903
=> Have SearchViewModel sort by receivedDate for mails

src/common/api/entities/tutanota/Services.ts, src/common/api/entities/tutanota/TypeModels.js, src/common/api/entities/tutanota/TypeRefs.ts, src/common/api/worker/crypto/CryptoFacade.ts, src/common/api/worker/crypto/CryptoWrapper.ts, src/common/api/worker/facades/EntropyFacade.ts, src/common/api/worker/facades/LoginFacade.ts, src/common/api/worker/facades/lazy/BlobFacade.ts, src/common/api/worker/facades/lazy/ConfigurationDatabase.ts, src/common/api/worker/facades/lazy/CustomerFacade.ts, src/common/api/worker/facades/lazy/GiftCardFacade.ts, src/common/api/worker/facades/lazy/GroupManagementFacade.ts, src/common/api/worker/facades/lazy/MailFacade.ts, src/common/api/worker/facades/lazy/ShareFacade.ts, src/common/api/worker/facades/lazy/UserManagementFacade.ts, src/mail-app/settings/groups/AddGroupDialog.ts, src/mail-app/workerUtils/index/Indexer.ts, test/tests/api/worker/facades/GroupManagementFacadeTest.ts, test/tests/api/worker/facades/LoginFacadeTest.ts, tuta-sdk/rust/sdk/src/crypto/asymmetric_crypto_facade.rs, tuta-sdk/rust/sdk/src/crypto/key.rs, tuta-sdk/rust/sdk/src/entities/generated/tutanota.rs, tuta-sdk/rust/sdk/src/services/generated/tutanota.rs, tuta-sdk/rust/sdk/src/type_models/tutanota.json
=> create identity key for new shared mailboxes

src/calendar-app/workerUtils/worker/CalendarWorkerLocator.ts, src/common/api/worker/facades/lazy/CustomerFacade.ts, src/common/api/worker/facades/lazy/UserManagementFacade.ts, src/common/subscription/SwitchSubscriptionDialog.ts, src/common/subscription/UpgradeConfirmSubscriptionPage.ts, src/mail-app/workerUtils/worker/WorkerLocator.ts
We want to remove the system user groups "free", "premium", "starter", and "stream". These system groups are very large, but not meaningful/used anymore.
=> remove system users groups free and premium

src/calendar-app/workerUtils/worker/CalendarWorkerLocator.ts, src/common/api/common/TutanotaConstants.ts, src/common/api/entities/sys/Services.ts, src/common/api/entities/sys/TypeModels.js, src/common/api/entities/sys/TypeRefs.ts, src/common/api/worker/facades/LoginFacade.ts, src/common/api/worker/facades/RolloutFacade.ts, src/mail-app/workerUtils/worker/WorkerLocator.ts, test/tests/Suite.ts, test/tests/api/worker/facades/LoginFacadeTest.ts, test/tests/api/worker/facades/RolloutFacadeTest.ts, tuta-sdk/rust/sdk/src/entities/generated/sys.rs, tuta-sdk/rust/sdk/src/services/generated/sys.rs, tuta-sdk/rust/sdk/src/type_models/sys.json
=> Implement rollout framework

src/common/gui/base/Dropdown.ts
=> keep folder dropdown visible when keyboard pops up by rendering again

src/calendar-app/calendar/view/CalendarViewModel.ts
We improve the loading performance when scrolling quickly through the calendar by aborting intermediate network requests/offline db lookups as these are no longer relevant to the displayed month.
=> improve syncing time when scrolling quickly through months in calendar

src/common/gui/base/Label.ts, src/common/gui/base/List.ts, src/common/gui/base/ViewColumn.ts, src/mail-app/mail/view/CollapsedMailView.ts, src/mail-app/mail/view/LabelsPopup.ts, src/mail-app/mail/view/MailRow.ts, src/mail-app/mail/view/MailView.ts, src/mail-app/mail/view/MailViewerHeader.ts
Co-authored-by: wrd <wrd@tutao.de>
=> Add test ids for conversation actions UI tests

src/calendar-app/calendar/search/view/CalendarSearchViewModel.ts, src/calendar-app/calendar/view/CalendarViewModel.ts, src/common/calendar/date/CalendarEventsRepository.ts, src/mail-app/search/view/SearchViewModel.ts
Rewrites some minor functions and adds logs to check if something went wrong during event generation.
=> [iOS] Improves birthday events handling

src/calendar-app/workerUtils/worker/CalendarWorkerLocator.ts, src/common/api/worker/EventBusClient.ts, src/common/api/worker/EventBusEventCoordinator.ts, src/common/api/worker/facades/lazy/GroupManagementFacade.ts, src/mail-app/workerUtils/worker/WorkerLocator.ts, test/tests/api/worker/EventBusClientTest.ts, test/tests/api/worker/EventBusEventCoordinatorTest.ts, test/tests/api/worker/facades/GroupManagementFacadeTest.ts
=> Identity keys for existing shared mailboxes

src/calendar-app/workerUtils/worker/CalendarWorkerLocator.ts, src/common/api/worker/EventBusClient.ts, src/common/api/worker/EventBusEventCoordinator.ts, src/mail-app/workerUtils/worker/WorkerLocator.ts, test/tests/api/worker/EventBusClientTest.ts, test/tests/api/worker/EventBusEventCoordinatorTest.ts
=> Identity keys for existing users

app-ios/fastlane/Fastfile, src/common/calendar/date/CalendarEventsRepository.ts
- [Replaces console.table by console.info](https://github.com/tutao/tutanota/commit/defb1cda793390379e9d89e975f1e8e4ade867ae)
- [[iOS] Adds new profiles to Fastlane](https://github.com/tutao/tutanota/commit/64dd98cd7b61fd15e50dbd1e4660a6a35f43c584)
=> Fixes console.table error + Fastlane

ci/merge.groovy
Now that Jenkins has more than one executor for macOS, we must prevent the iOS tests to run in parallel since both write to the same temp folder which cause them to fail.
=> [ci] Run iOS tests sequentially

src/calendar-app/calendar/model/CalendarModel.ts
When deleting events that contains updates we must re-do all the iteration over duplicated events to get their original id to delete, and we also double the number of I/O operations since now we must delete and recreate instead of just update.
This commit removes the updated events from the deletion list and handle them in the classical way.
=> Changes external calendars sync flow to not delete updated events

packages/tutanota-utils/lib/ArrayUtils.ts, packages/tutanota-utils/lib/index.ts, packages/tutanota-utils/test/ArrayUtilsTest.ts, src/common/api/worker/facades/lazy/MailFacade.ts, src/common/api/worker/rest/EntityRestClient.ts, test/tests/api/worker/facades/MailFacadeTest.ts
=> Fix resolving session keys for attachments that were already decrypted

src/common/gui/builtinThemes.ts, src/common/gui/main-styles.ts
=> Change search text highlight color

src/mail-app/mail/model/MailModel.ts, src/mail-app/mailLocator.ts, test/tests/mail/MailModelTest.ts
=> Lazy load inboxRuleHandel to prevent null mailModel

src/calendar-app/calendar/view/CalendarView.ts, src/common/settings/AppearanceSettingsViewer.ts, src/common/sharing/view/ReceivedGroupInvitationDialog.ts, src/mail-app/contacts/view/ContactView.ts, src/mail-app/settings/SettingsView.ts
=> Catch LockedError when updating UserSettingsGroupRoot

src/calendar-app/workerUtils/worker/CalendarWorkerLocator.ts, src/common/api/main/PageContextLoginListener.ts, src/common/api/worker/facades/LoginFacade.ts, src/mail-app/contacts/view/ContactView.ts, src/mail-app/mail/model/ConversationListModel.ts, src/mail-app/mail/view/MailView.ts, src/mail-app/search/model/SearchOfflineRangePostLoginAction.ts, src/mail-app/workerUtils/index/IndexedDbIndexer.ts, src/mail-app/workerUtils/index/Indexer.ts, src/mail-app/workerUtils/index/OfflineStorageIndexer.ts, src/mail-app/workerUtils/worker/WorkerLocator.ts, test/tests/Suite.ts, test/tests/api/worker/facades/LoginFacadeTest.ts, test/tests/api/worker/search/IndexedDbIndexerTest.ts, test/tests/api/worker/search/OfflinestorageIndexerTest.ts, test/tests/mail/model/ConversationListModelTest.ts
=> Offline fixes

package-lock.json, package.json, test/tests/api/worker/search/OfflineStorageSearchFacadeTest.ts
This is to better support French.
Closes #9113
=> Split on apostrophes

src/calendar-app/calendar/model/CalendarModel.ts, test/tests/calendar/CalendarModelTest.ts
When performing a sync for an external calendar that has events with an organizer or attendees, CalendarModel#eventHasSameFields was not evaluating correctly. The deepEqual compare of organizer / attendees aggregates lead to comparing aggregateIds (_ids) and other technical fields that are not important when comparing the actual event data. This commit fixes the problem, by comparing stripped aggregates without the technical fields.
=> fix external calendar events with organizer/attendees leading to resync

src/common/api/worker/offline/OfflineStorage.ts, test/tests/api/worker/offline/OfflineStorageTest.ts
When migrating offline storage, `setCurrentOfflineSchemaVersion` is run after `migrate`. Because of this, migrating would fail with a "no such table: metadata" error if the migration purges storage, since purging drops the metadata table.
So instead of dropping the entire metadata table we only delete `metadata.lastUpdateTime`.
Close #9129
=> Delete `metadata.lastUpdateTime` when purging storage

src/common/api/worker/facades/KeyRotationFacade.ts, src/common/api/worker/facades/PublicEncryptionKeyProvider.ts, test/tests/api/worker/facades/KeyRotationFacadeTest.ts
=> Handle key verification errors when rotating shared groups

src/mail-app/mail/view/MailView.ts
=> Order labels alphabetically

src/common/gui/base/List.ts, src/mail-app/search/view/SearchListView.ts
List was using onSingleTogglingMultiselection from old attrs which acts on an old list state.
So we make sure list listeners always use the latest listModel.
Close: #9131
=> [Mobile] Fix press and hold not working in SearchView on first render

src/common/gui/Header.ts, src/mail-app/search/SearchBar.ts
=> Fix SearchBar doesn't span the entire available width on mobile

src/common/mailFunctionality/SendMailModel.ts, src/mail-app/mail/editor/MailEditor.ts, src/mail-app/mail/view/MailViewerUtils.ts, test/tests/mail/SendMailModelTest.ts
=> Fix uncaught conversation entry NotFoundError

src/common/api/main/RecipientsModel.ts, test/tests/misc/RecipientsModelTest.ts
Co-authored-by: hec <hec@tutao.de>
tuta#2242
=> reload verification state instead of overriding in mail editor

src/calendar-app/calendar/gui/CalendarGuiUtils.ts, src/calendar-app/calendar/gui/eventeditor-model/CalendarEventModel.ts, src/calendar-app/calendar/gui/eventeditor-model/CalendarEventModelStrategy.ts, src/calendar-app/calendar/gui/eventeditor-model/CalendarEventWhenModel.ts, src/calendar-app/calendar/gui/eventeditor-model/CalendarEventWhoModel.ts, src/calendar-app/calendar/gui/eventeditor-view/CalendarEventEditDialog.ts, src/calendar-app/calendar/gui/eventpopup/CalendarEventPopup.ts, src/calendar-app/calendar/gui/eventpopup/CalendarEventPreviewViewModel.ts, src/calendar-app/calendar/model/CalendarModel.ts, src/calendar-app/calendar/view/CalendarViewModel.ts, src/calendar-app/calendar/view/EventDetailsView.ts, src/calendar-app/calendar/view/EventDragHandler.ts, src/calendar-app/calendarLocator.ts, src/common/misc/TranslationKey.ts, src/mail-app/gui/date/EventBannerImpl.ts, src/mail-app/mailLocator.ts, src/mail-app/translations/de.ts, src/mail-app/translations/de_sie.ts, src/mail-app/translations/en.ts
=> 9303 partially edit delete event series

buildSrc/updateLibs.js, libs/purify.js
=> Change DomPurify source to mjs file

src/common/api/worker/offline/migrations/offline-v7.ts
=> Fix offline-7 migration failing on iOS

src/mail-app/mail/view/MailGuiUtils.ts, src/mail-app/mail/view/MailReportDialog.ts
=> Show undo move mail snackbar after the spam dialog is closed

src/mail-app/mail/view/MailFolderRow.ts, src/mail-app/mail/view/MailFoldersView.ts
=> 5428 open folder on icon click

src/common/api/common/TutanotaConstants.ts, src/common/gui/base/SnackBar.ts, src/mail-app/app.ts, src/mail-app/mail/view/ConversationViewer.ts, src/mail-app/mail/view/MailGuiUtils.ts, src/mail-app/mail/view/MailListView.ts, src/mail-app/mail/view/MailReportDialog.ts, src/mail-app/mail/view/MailView.ts, src/mail-app/mail/view/MailViewModel.ts, src/mail-app/mail/view/MailViewer.ts, src/mail-app/mail/view/MailViewerHeader.ts, src/mail-app/mail/view/MailViewerViewModel.ts, src/mail-app/mailLocator.ts, src/mail-app/search/view/SearchView.ts, src/mail-app/translations/de.ts, src/mail-app/translations/de_sie.ts, src/mail-app/translations/en.ts, test/tests/mail/view/MailViewerViewModelTest.ts
=> Undo move mail

src/mail-app/search/SearchBar.ts
QuickSearch now shows the most recent mails rather than the first 10 mails from the "From date"
close #9342
=> Show latest mails in quickSearch

src/common/gui/base/Dialog.ts
=> Use different message in Outdated Client dialog if user can defer update

src/mail-app/contacts/view/ContactView.ts
=> Show `Add contactList entries button` on two column layout

src/common/gui/ListColumnWrapper.ts, src/common/gui/base/List.ts, src/common/gui/base/ViewColumn.ts, src/common/gui/main-styles.ts, src/common/gui/nav/ViewSlider.ts, src/common/gui/size.ts, src/common/misc/DeviceConfig.ts, src/mail-app/mail/view/ConversationViewer.ts, src/mail-app/mail/view/MailListView.ts, src/mail-app/mail/view/MailView.ts, src/mail-app/search/view/SearchListView.ts, src/mail-app/search/view/SearchView.ts, test/tests/misc/DeviceConfigTest.ts
=> Add resize element on Mail List view column

src/mail-app/UndoModel.ts, src/mail-app/app.ts, src/mail-app/mail/view/MailGuiUtils.ts, src/mail-app/mail/view/MailListView.ts, src/mail-app/mail/view/MailView.ts, src/mail-app/mail/view/MailViewModel.ts, src/mail-app/mail/view/MailViewerHeader.ts, src/mail-app/mail/view/MailViewerViewModel.ts, src/mail-app/mailLocator.ts, src/mail-app/search/view/SearchView.ts, test/tests/mail/view/MailViewerViewModelTest.ts
=> Show undo when using trash action

src/calendar-app/calendar/gui/pickers/DatePickerDialog.ts
=> Remove Cancel button for from field in datePickerDialog

src/common/misc/HtmlSanitizer.ts
=> Do not try to highlight text if highlighted strings is empty

src/calendar-app/calendar/view/CalendarView.ts, src/common/contactsFunctionality/ContactModel.ts
=> Fix open event details when offline

src/common/desktop/DesktopWindowManager.ts
=> Fix window bounds reset on app launch

src/common/mailFunctionality/SendMailModel.ts, src/mail-app/mail/editor/MailEditor.ts, test/tests/mail/SendMailModelTest.ts
=> Fix draft conflict issues

src/common/file/FileControllerNative.ts
=> [desktop] Remove downloaded file names from logs

app-android/tutashared/src/main/java/de/tutao/tutashared/NetworkUtils.kt, app-ios/TutanotaNotificationExtension/NotificationService.swift, app-ios/TutanotaSharedFramework/Notifications/SdkRestClient.swift, tuta-sdk/rust/sdk/src/bindings/rest_client.rs, tuta-sdk/rust/sdk/src/rest_error.rs
=> Fix suspension handling, normalize headers in RestClient
